### ISSUE TITLE
Difficulty Triggering MSC's Aggressive Update Notifications

### ISSUE THREAD

**Issue by foigus** [munki/munki#1001]
I am trying to trigger the Aggressive Update Notifications in Munki and have done the following:

- Built and installed a Munki5dev branch version (5.0.1.4048) of Munki (to obtain the feature of preserving SUS Update Notification Tracking even if the SUS isn’t available)
- Manually edited UpdateNotificationTracking.plist to make an Apple update (Safari 13.1.1) last notify on 6/10 (19 days ago) and confirmed MSC reports the update has been pending for 19 days
- Deleted the LastNotifiedDate key from ManagedInstalls.plist via `sudo defaults delete /Library/Preferences/ManagedInstalls LastNotifiedDate`
- Ran `sudo managedsoftwareupdate --auto` and observed MSC launches to notify me of pending updates

Right now I am still able to quit MSC with a Cmd-Q and do not see the bulleted list of GUI “enhancements" detailed [here](https://github.com/munki/munki/wiki/aggressive-update-notifications-in-munki-5).  What am I missing to trigger the “difficult to ignore” behavior?

[AppleUpdates_plist.txt](https://github.com/munki/munki/files/4853148/AppleUpdates_plist.txt)
[UpdateNotificationTracking_plist.txt](https://github.com/munki/munki/files/4853149/UpdateNotificationTracking_plist.txt)

**Comment by gregneagle** [comment]
Why did you rename the files?

**Comment by gregneagle** [comment]
Does Safari13.1.1MojaveAuto require a restart? I'm thinking it doesn't...

**Comment by foigus** [comment]
1) I renamed the files because GitHub won't let me attach `.plist` files--it's not on their approved list of extensions
2) No, Safari updates do not require a restart--let me try with the Security Update

**Comment by foigus** [comment]
Ok, adding the Security Update triggered the GUI enhancements--it was like an eclipse.

**Comment by gregneagle** [comment]
So that seems like the behavior is what is expected -- the aggressive behavior is only for pending Apple updates that require a restart. Updates that don't require a restart can (eventually) be installed by Munki itself and so MSC doesn't try to aggressively get people to open System Preferences to install updates...

**Comment by gregneagle** [comment]
https://github.com/munki/munki/wiki/aggressive-update-notifications-in-munki-5

You might have a legitimate issue here, though.
We've seen that Apple updates that require a restart definitely trigger the super-aggressive mode.
I think Munki updates that have been pending a long time are supposed to trigger this mode as well.
So it's not unreasonable to expect aggressive notifications for Apple updates that _don't_ require a restart that have been pending a long time.
The logic gets complex, though, if there is a mix of Apple updates that require a restart and those that don't. Which type should Munki be more obnoxious about? The actual behavior is different for each type of update, so it can't do both at the same time...
