### ISSUE TITLE
Incomplete MSC Aggressive Notification

### ISSUE THREAD

**Issue by Zolotkey** [munki/munki#1002]
I have a 10.15.4 Client that is on 20 days of the pending 10.15.5 Update. The only aggressive behavior is the blocking of the "Skip these Updates" button. We can still quit/force quit, see the dock and other items.

Munki version is 5.0.0.4034 with default 14 days in the preferences.

Here is the log and plists.
[ManagedSoftwareUpdate.log](https://github.com/munki/munki/files/4853596/ManagedSoftwareUpdate.log)
[AppleUpdates.txt](https://github.com/munki/munki/files/4853598/AppleUpdates.txt)
[UpdateNotificationTracking.txt](https://github.com/munki/munki/files/4853599/UpdateNotificationTracking.txt)

**Comment by gregneagle** [comment]
It would be helpful to also have /Library/Preferences/com.apple.softwareupdate.plist, or at least the RecommendedUpdates from that file.

**Comment by Zolotkey** [comment]
Here is the whole file. :) 
[com.apple.softwareupdate.txt](https://github.com/munki/munki/files/4853653/com.apple.softwareupdate.txt)

**Comment by gregneagle** [comment]
With your test data I get the expected behavior:
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/700560/86163234-cf26bc00-bac4-11ea-89ad-1bfd22ad315a.png">

But _not_ when MSC.app is manually launched -- if I manually launch it I get the behavior you describe.

If `managedsoftwareupdate` launches it as part of a notification, I see the aggressive behavior. You can simulate that by doing `open munki://notify`

**Comment by Zolotkey** [comment]
The MSC.app opening on the 13th day, and then the 14+ day rolls around someone closes it and opens it again or just lets it sit. The more aggressive behavior is ignored until the next time munki closes and notify comes up. Would it be possible to have the already open move to the more aggressive notification? This machine has been just sitting locked for awhile. This is on its 20th day without the notify working until this issue was brought up.

**Comment by gregneagle** [comment]
You'd need to help me reproduce the issue. For me, if MSC.app is open manually, and then I simulate a notification with `open munki://notify`, MSC switches to the update view and enters "obnoxious" mode.

**Comment by gregneagle** [comment]
$ sudo cp ~/Downloads/com.apple.softwareupdate.txt /Library/Preferences/com.apple.SoftwareUpdate.plist
$ sudo cp ~/Downloads/UpdateNotificationTracking.txt /Library/Managed\ Installs/UpdateNotificationTracking.plist 
$ sudo cp ~/Downloads/AppleUpdates.txt /Library/Managed\ Installs/AppleUpdates.plist
$ defaults read /Library/Preferences/com.apple.SoftwareUpdate RecommendedUpdates
(
        {
        "Display Name" = "macOS Catalina 10.15.5 Update";
        "Display Version" = " ";
        Identifier = "macOS Catalina 10.15.5 Update";
        "Product Key" = "001-12341";
    }
)
$ open -a "Managed Software Center.app"

Opens in "normal mode":
<img width="1000" alt="Screen Shot 2020-06-30 at 11 53 21 AM" src="https://user-images.githubusercontent.com/700560/86166016-faaba580-bac8-11ea-90ed-afaee03c1318.png">

I can switch to other views:
<img width="1000" alt="Screen Shot 2020-06-30 at 11 54 04 AM" src="https://user-images.githubusercontent.com/700560/86166060-0a2aee80-bac9-11ea-98e8-422abd786885.png">

Now simulate a notification from managedsoftwareupdate:
$ open munki://notify

Switches to "Obnoxious mode" -- I must interact with the Install button.

<img width="1142" alt="Screen Shot 2020-06-30 at 11 54 24 AM" src="https://user-images.githubusercontent.com/700560/86166138-24fd6300-bac9-11ea-8371-95a0bc3c04d1.png">

**Comment by Zolotkey** [comment]
I do get that behavior if I do the `open munki://notify `. I wonder if because the user was at the screensaver/locked screen, the notify did not actually force the mode, so the next notify event it will enter the "Obnoxious mode"?

**Comment by Zolotkey** [comment]
So if you open MSC.app before it does its "Obnoxious mode" and you run `managedsoftwarecenter --auto` what the launchd munki supervisor does, it just sits in the background and does not try to notify you. When does the notify portion of MSC.app  kickoff automatically during a run?

**Comment by gregneagle** [comment]
Depends on the value of DaysBetweenNotifications, but normally managedsoftwareupdate won't notify more often than once per day.

**Comment by Zolotkey** [comment]
I have it set to 5. Is there a way I can mimic the 5 days is up?

**Comment by gregneagle** [comment]
Set LastNotifiedDate in /Library/Preferences/ManagedInstalls.plist appropriately.

Five days between notifications combined with aggressive notifications after 14 days seems like a non-ideal combination...

If UseNotificationCenterDays is at the default, it seems the sequence would be: Day 1: Notification Center notification. Day 6: MSC launch. Day 11: MSC launch. Day 16: MSC launch in obnoxious mode. Is that what you want/expect?

**Comment by Zolotkey** [comment]
I didn't expect that. I think we are going to tune the days to 2 days so we can turn the screws to update faster.

**Comment by gregneagle** [comment]
I did some more testing this evening with the specific scenario of MSC open, but moved mostly off-screen and to the background with an OS update pending. I found that a `managedsoftwareupdate --auto` run that triggered an update notification did _not_ recenter the updates window or start "obnoxious" mode as expected.

This change: https://github.com/munki/munki/commit/353d542974f369cf407b018f0ba8b2a5c8c77480 causes MSC to behave as expected and will be in a 5.0.1 release soon-ish. Please test if you are able.

**Comment by Zolotkey** [comment]
Testing today. Thank you.

**Comment by Zolotkey** [comment]
Upon coming back into the office today and looking at the testing machine, It did come to the front and center. While the Obnoxious mode did not happen. I can accept that behavior for coming back into the office. I will close this and deploy the new 5.0.1 when available.

**Comment by gregneagle** [comment]
Obnoxious mode may well have happened. But I’ve seen that if it sits there long enough, a background update check happens, and while displaying the status of that, the application comes out of obnoxious mode. After that completes, unless managedsoftwareupdate notifies for pending updates, the app remains in non-obnoxious mode.

**Comment by Zolotkey** [comment]
good to know. Thank you.
