### ISSUE TITLE
Big Sur breaks SoftwareRepoCACertificate function for untrusted CA's

### ISSUE THREAD

**Issue by jazz-o-mat** [munki/munki#1003]
```
Starting...
    Performing preflight tasks...
    CA cert path: /Library/Managed Installs/certs/ca.pem
    CA dir path:  None
    Adding CA cert /Library/Managed Installs/certs/ca.pem...
ERROR: Could not add CA cert /Library/Managed Installs/certs/ca.pem into System keychain: 1: SecTrustSettingsSetTrustSettings: The authorization was canceled by the user.
```

Big Sur presents a password screen and Munki will not run before the password has been entered or aborted.

We are using your puppet certificates for repo auth.

**Comment by gregneagle** [comment]
You certainly aren't using _my_ puppet certs! :-)

Yes: this is an Apple change in macOS 10.16. Certs can be added to the System keychain only interactively or via MDM.

There's not likely to be a _Munki_-specific solution to this issue, and you'll have to figure out how to work within Apple's new constraints or move away from using Puppet client certs.

If someone comes up with another solution, I'd be happy to consider it!

**Comment by jazz-o-mat** [comment]
hehe... you're right.

Does Munki have to use the system keychain or can Munki trust the ca cert itself?

**Comment by gregneagle** [comment]
Munki's http/https code is Apple's: NSURLSession and NSURLConnection. I don't know if it's possible to use alternate locations for CA certs. I don't use client certs myself, and so this is difficult for me to test, and there's little motivation for me to spend a lot of time on it since I don't use it.

I'd suggest posting on munki-dev and seeing if you can get some other people who use client certs to look into this with you.

Again: I'd be happy to consider any solution the community comes up with, but I cannot promise to do any work on this myself.

**Comment by jazz-o-mat** [comment]
My current workaround is not to use the ca.pem, then the connect seems to work anyway, because the webserver decides if the client cert is allowed or not.

Removing the ca.pem default in ManagedInstall.plist does not help, Munki searches and finds the ca.pem anyway.
If there is no ca.pem in the path he can't find it, but Munki doesn't seem to care.

By the way I noticed:
Our puppet root ca expired a few days ago and had to be replaced.
I noticed that when Munki tries to import the new cert it does not change in the system keychain. Same name, new expiration date, but in system keychain is only the old one. That is strange, but maybe a problem with security tool. ;)

**Comment by gregneagle** [comment]
Yes: this is an Apple change in macOS Big Sur. Certs can be added to the System keychain only interactively or via MDM.  Munki can’t do it with the `security` command any longer.

**Comment by jazz-o-mat** [comment]
This strange behavior is also at mojave and catalina.

**Comment by gregneagle** [comment]
I think people have figured out the workarounds (IE have your MDM install any trusted CA certs, or have your certs come from a chain already trusted by macOS), so closing this,
