### ISSUE TITLE
Upgrading from older Munki version to 5.1.x leaves old Python bits about

### ISSUE THREAD

**Issue by gregneagle** [munki/munki#1010]
```
# ls -al /usr/local/munki/Python.framework/Versions/
total 0
drwxr-xr-x   5 root  wheel  160 Aug  4 17:12 .
drwxr-xr-x   6 root  wheel  192 Aug  4 17:12 ..
drwxr-xr-x  10 root  wheel  320 Aug  3 15:25 3.7
drwxr-xr-x  11 root  wheel  352 Aug  4 17:12 3.8
lrwxr-xr-x   1 root  wheel    3 Aug  4 17:12 Current -> 3.8
```
```
# ls -al /usr/local/munki | grep python
lrwxr-xr-x   1 root  wheel     45 Aug  4 17:12 munki-python -> Python.framework/Versions/Current/bin/python3
lrwxr-xr-x   1 root  wheel     41 Aug  3 15:25 python -> Python.framework/Versions/3.7/bin/python3
```
The Python.framework/Versions/3.7 directory should be removed and the python symlink to Python.framework/Versions/3.7/bin/python3 should also be removed.
Suspect this is Apple installer behavior around versioned frameworks.

**Comment by grahamgilbert** [comment]
Looks like this could be solved pretty easily with a post install script on the python package - happy to take that on unless you were thinking of something more elaborate?

**Comment by gregneagle** [comment]
I agree that a postinstall script is a likely fix.

I'd like to understand _why_ this happens, though. It might be possible to prevent this behavior by tweaking the package Distribution file, for example.

With a postinstall script we'll have to remember to keep tweaking it as we move to Python 3.9, 3.10, etc...

**Comment by gregneagle** [comment]
This does seem to be an Apple installer behavior. I can replicate it with the Python.org packages. If I download and install the python-3.7.8 package, I see this:

```
$ ls -al /Library/Frameworks/Python.framework/Versions/
total 0
drwxrwxr-x   4 root  wheel  128 Aug  5 09:18 .
drwxr-xr-x   6 root  wheel  192 Aug  5 09:18 ..
drwxrwxr-x  11 root  admin  352 Aug  5 09:18 3.7
lrwxr-xr-x   1 root  wheel    3 Aug  5 09:18 Current -> 3.7
```
if I then download and install the Python 3.8.5 package, I see:
```
$ ls -al /Library/Frameworks/Python.framework/Versions/
total 0
drwxrwxr-x   5 root  wheel  160 Aug  5 09:21 .
drwxr-xr-x   6 root  wheel  192 Aug  5 09:21 ..
drwxrwxr-x  11 root  admin  352 Aug  5 09:18 3.7
drwxrwxr-x  11 root  admin  352 Aug  5 09:21 3.8
lrwxr-xr-x   1 root  wheel    3 Aug  5 09:21 Current -> 3.8
```
Even though there are no 3.7 files in the package:
```
$ pkgutil --payload-files ~/Downloads/python-3.8.5-macosx10.9.pkg | grep "/Versions/3.7"
```

**Comment by gregneagle** [comment]
I also wonder what happens when Python.framework/Versions/3.7 gets removed in the middle of a Munki run that is _using_ python3.7...

**Comment by gregneagle** [comment]
I poked around at the package this weekend. I have to believe the various bundle* tags in the PackageInfo XML influence this behavior, but could not find any documentation, and my experiments led nowhere.

So a postinstall script seems the way forward.

**Comment by gregneagle** [comment]
Addressed by the above referenced commit.
