### ISSUE TITLE
new-msc-design: Sidebar labels are truncated in some languages

### ISSUE THREAD

**Issue by gregneagle** [munki/munki#1019]
In non-English languages, the sidebar labels are sometimes truncated.

**Comment by gregneagle** [comment]
Example:
<img width="251" alt="image" src="https://user-images.githubusercontent.com/700560/92177743-ef8d3280-edf5-11ea-8869-29df8a2989dc.png">

**Comment by SteveKueng** [comment]
due to the fixed width of the sidebar the size of the fields is limited.
i could adjust it a bit and for most languages it looks good.

<img width="312" alt="Screenshot 2020-09-05 at 10 14 00" src="https://user-images.githubusercontent.com/5426904/92301087-d2c13e00-ef60-11ea-8ccd-ac7436cb07ca.png">
