### ISSUE TITLE
new-msc-design: layout issues on Big Sur

### ISSUE THREAD

**Issue by gregneagle** [munki/munki#1022]
![Image 9-4-20 at 8 07 AM](https://user-images.githubusercontent.com/700560/92254486-d0d67c80-ee85-11ea-81d8-176473c2fe18.jpg)

![Image 9-4-20 at 8 09 AM](https://user-images.githubusercontent.com/700560/92254554-ecda1e00-ee85-11ea-9bf4-ac29e86e16a3.jpg)

as seen in the screenshots, on Big Sur (Beta 5) the content view has a large border on the top and left.

**Comment by gregneagle** [comment]
New clue: it doesn't always do this. Sometimes when launched it lays out the view "normally". When it does this, the titlebar area is no longer draggable. I had it do the "wrong" layout a second time -- there were notification center notifications displayed, and the web view was pushed over enough to not be under those notifications. Once I dismissed the notifications, I could quit and relaunch MSC.app and the layout was "normal" again. 

I don't know how notification center notifications can interfere with an app's window layout, but it is looking like that is what is happening.

**Comment by gregneagle** [comment]
I can only reproduce it when waking from sleep or otherwise clearing a screen lock, if notification center notifications are displaying. I've now seen the behavior on Beta 5 and Beta 6.

**Comment by gregneagle** [comment]
I've now seen the behavior on beta 9. Once again, it happened when launching MSC.app shortly after waking the machine from sleep with notification center notifications displaying. The web view appears to "avoid" displaying under the displayed notifications.

**Comment by flammable** [comment]
I saw similar behavior on beta 9 - I ended up rebuilding my client customizations with the current templates (I hadn't touched them for a few years), and that improved things. Might have been a coincidence; I'll need to test more.

However, I'm also seeing our custom banner cut off at the right edge. Should it be shrinking, instead? The banner is the recommended 1158x200. I'm testing on a MacBook Pro (Retina, 13-inch, Early 2015), which explains why I'm only able to make MSC display two columns of icons instead of three.

Here's a screenshot:

<img width="1280" alt="Screen Shot 2020-10-12 at 1 48 49 PM" src="https://user-images.githubusercontent.com/8499030/95786657-056bfe00-0ca6-11eb-96f8-ec46c1f7d335.png">

**Comment by gregneagle** [comment]
> However, I'm also seeing our custom banner cut off at the right edge. Should it be shrinking, instead? The banner is the recommended 1158x200.

Which of course was the recommendation when the banner was the full-width of the window. With the new design, the width available for the banner is smaller.
Not sure if there's a perfect way to deal with the difference that isn't going to cause issues with some existing banners. The recommendation has always been to make sure the "important" parts of the image are on the left side of the image. Perhaps the recommendation will be to make sure your images look acceptable on both the previous design and the new design before rolling out Munki 5.2.

> I'm testing on a MacBook Pro (Retina, 13-inch, Early 2015), which explains why I'm only able to make MSC display two columns of icons instead of three.

Are you running it at a low display resolution? My 13" MBP (2016) with a resolution "like" 1440x900 has no issues displaying three columns, with the window at about 80% of the screen width:
<img width="1440" alt="Screen Shot 2020-10-12 at 1 44 04 PM" src="https://user-images.githubusercontent.com/700560/95788857-31c94f80-0c91-11eb-89b0-d9f8eabfe314.png">

**Comment by flammable** [comment]
That makes sense. I can pretty easily modify our custom banner for MSC to fit the new dimensions. When we move to Munki 5.2, we'll go all-in for everyone, so I'm not worried about maintaining both sets of customizations.

Big Sur on this laptop defaults to a resolution like 1280x800. A resolution like 1440x900 is available, too, but I suspect most of my users are still at Apple's default settings.

Also, I just reopened MSC, and was able to replicate the issue you observed again:

<img width="1280" alt="Screen Shot 2020-10-12 at 5 11 41 PM" src="https://user-images.githubusercontent.com/8499030/95790805-14ef4500-0cae-11eb-97f9-d7938bf25198.png">

The laptop was idle for almost the entire time from my last comment to this one. I'm not sure what caused the layout to change.

**Comment by gregneagle** [comment]
"Big Sur on this laptop defaults to a resolution like 1280x800. A resolution like 1440x900 is available, too, but I suspect most of my users are still at Apple's default settings." Huh. The default resolution on my (slightly) newer 13" MBP seems to be 1440x900 (in Catalina at least -- a non-Retina MBA that is my Big Sur tester also defaults to 1440x900 in Big Sur, but that's the "native" resolution).

<img width="668" alt="image" src="https://user-images.githubusercontent.com/700560/95791092-7820ad80-0c95-11eb-873a-f04418c3c7ed.png">

**Comment by gregneagle** [comment]
"When we move to Munki 5.2, we'll go all-in for everyone, so I'm not worried about maintaining both sets of customizations."

But you might find it easier to update your customized resources on the server prior to rolling out 5.2.

**Comment by gregneagle** [comment]
In any case, much of this discussion is not really related to the original issue we're tracking here, which is the mysterious shifting of the webview inside the MSC main window.

**Comment by flammable** [comment]
Ah yeah, I initially couldn't tell if the banner was a separate issue or not. I can submit a separate issue, if that'd be easier to track. At the very least, MSC will need new banners that fit the new dimensions, and [the documentation](https://github.com/munki/munki/wiki/Client-Customization) will need to be updated to match.

> But you might find it easier to update your customized resources on the server prior to rolling out 5.2.

Agreed. Shrinking the banner might be a good way to bridge the gap.

I don't understand Apple's reasoning (1440x900 looks great on this laptop), but here are the defaults:

<img width="780" alt="Screen Shot 2020-10-12 at 5 19 31 PM" src="https://user-images.githubusercontent.com/8499030/95791534-90052b00-0caf-11eb-96c6-c926c612f4d4.png">

**Comment by gregneagle** [comment]
> Agreed. Shrinking the banner might be a good way to bridge the gap.

Or just redoing them so the important stuff is within the leftmost 700px... I would not make them _smaller_ as that would make for weirdness on larger monitors.

**Comment by lifeunexpected** [comment]
I get this and its possible to recreate if you close MSC and then re-open it a few seconds later it could happen but it will also happen randomly when you open MSC after minutes or hours but sometimes it opens properly like excpected.

I first thought it was my custom design that caused it but then removed my custom theme and use the default and it still happens just like with my custom design.

I tried on a macbook pro 2018 with display both at scaled and more space and the same thing happens on both.

![InkedScreenshot 2020-10-15 at 12 31 40_LI](https://user-images.githubusercontent.com/36742392/96112572-21101800-0ee3-11eb-9814-7b1b834516bc.jpg)

**Comment by dev-yeet** [comment]
mine looks the same as above. 2019 16" MacBook Pro. 

This has happened to me for the past several betas including 11.0.1b1

![image](https://user-images.githubusercontent.com/3103719/98126946-25957400-1e84-11eb-9a6e-0bb039257423.png)

**Comment by jamesez** [comment]
I just spent 30 minutes trying to reproduce this in Xcode, so I could use the view hierarchy inspector, and could not.

Managed Software Center 5.3.0.4220 I can get it to glitch easily with a quick close and re-open.

Compiled against Xcode 12.1 (12A7403), I can't, no matter how I try, it get to reproduce.  Anyone want to double-check?

**Comment by gregneagle** [comment]
Sadly I built it with Xcode 12.1 on Big Sur 11.0.1 Beta 1 earlier this week and still encountered the problem.

**Comment by gregneagle** [comment]
![image](https://user-images.githubusercontent.com/700560/98429481-aeb2d380-205b-11eb-8fcf-f30b42a9734d.png)

**Comment by jamesez** [comment]
I was, finally, able to repro it in Xcode. My understanding is:

The view is being inserted at awakeFromNib, but when that runs, the layout is not finalized. The autoresizing mask is converted to a set of constraints, and when that happens, the constraints are (somewhat at random) injecting an offset that pin the web view to the smallest possible view size: 780x500.

These two constraints end up being added with a hard offset that generates that pinning behavior:

```    
    - 5 : <NSAutoresizingMaskLayoutConstraint:0x6000033c95e0 h=-&- v=-&- H:[Managed_Software_Center.MSCWebView:0x7f9390504080'Managed Software Center']-(309)-|   (active, names: '|':NSView:0x7f938d905ec0 )>
    - 7 : <NSAutoresizingMaskLayoutConstraint:0x6000033c9680 h=-&- v=-&- V:|-(353)-[Managed_Software_Center.MSCWebView:0x7f9390504080'Managed Software Center']   (active, names: '|':NSView:0x7f938d905ec0 )>
```

Instead of relying on converting auto layout masks to constraints, I just add them directly.

**Comment by gregneagle** [comment]
https://github.com/munki/munki/tree/msc-layout-test is another attempt at a fix...

**Comment by jamesez** [comment]
I've opened PR #1048 which uses a View Controller to host the WebView.

To be honest, just wrapping another View (as in your branch) is certainly more direct.

**Comment by jamesez** [comment]
I'd just go with the view-in-view, I can't get it to break either.

**Comment by gregneagle** [comment]
Definitely seems simpler overall, and adds no additional code. Thanks for your help!

**Comment by jamesez** [comment]
So many hours, such a simple fix. 😢

**Comment by gregneagle** [comment]
Your effort got us looking in the right place, though, so it was not wasted.

**Comment by gregneagle** [comment]
I've merged my fix into Munki5dev, but I'm going to leave this issue open for a bit until more people test.

**Comment by poundbangbash** [comment]
I just built and installed the latest Munki5dev branch code (installed MSC 5.3.0.4220 (4220)) and installed on 11.0.1 Beta (20B5022a).

After installing I opened the app and clicked around, all fine. I quit the app and immediately opened it again and saw the erroneous buffering on the top and right.  I'm able to reproduce it occasionally by quitting and re-opening the app after clicking around the app UI a bit. 

Prior to installing version 5.3.0.4220 (4220) I had used the latest Release 5.2b3 to get a baseline of error.  I was able to produce the issue in the same manner. Is there a chance of a cached state from the previous version?  I don't see anything in ~/Library/Saved Application State to remove.

<img width="1251" alt="Screen Shot 2020-11-07 at 3 49 36 PM" src="https://user-images.githubusercontent.com/1416288/98452049-71108200-2111-11eb-80b0-1f99d204c80c.png">

-Eric

**Comment by poundbangbash** [comment]
Even after clearing out ~/Library/Caches/com.googlecode.munki.ManagedSoftwareCenter I'm able to reproduce the issue.

**Comment by poundbangbash** [comment]
Interesting, I deleted the MSC app from /Applications and re-installed the .pkg generated from Munki5dev.
Now "About" shows `Version 5.3.0.482 (482)` and I _cannot_ reproduce the issue.  

It appears installing Managed Software Center over itself doesn't completely update..

-Eric

**Comment by gregneagle** [comment]
I bet if you look at /var/log/install.log you’ll see that installer is deciding not to install MSC.app because it thinks the version is lower. 

The version should _not_ be lower, and that’s an issue that needs to be addressed and fixed.

**Comment by poundbangbash** [comment]
Yep, precisely. I just ran thru an install scenario and watched the logs.
```2020-11-07 17:48:27-06 C02XM6BBJHD2 Installer[37560]: PackageKit: Skipping component "com.googlecode.munki.ManagedSoftwareCenter" (5.3.0-482.0.0-*) because the version 5.3.0-4220.0.0-* is already installed at /Applications/Managed Software Center.app.
```

So not to distract from this thread/issue. The new version of MSC looks to be behaving properly.

**Comment by gregneagle** [comment]
This might also have to do with exactly _how_ you built the app and package. If I build it with `./code/tools/make_munki_mpkg_from_git.sh -b Munki5dev` I get this:

<img width="856" alt="image" src="https://user-images.githubusercontent.com/700560/98453835-75896a80-2112-11eb-861d-f84b93f85205.png">

Note the app version if 5.3.0.4229.

The version is dynamically generated based on the number of git commits. If you were to, say, download the branch as a .zip and use `./code/tools/make_munki_mpkg.sh` the git history may not be there, leading to a lower version number like you report.

**Comment by gregneagle** [comment]
Considering this resolved.
