### ISSUE TITLE
Persistant MSC notification icon in Launchpad.app

### ISSUE THREAD

**Issue by neilrooney** [munki/munki#1026]
Experiencing an issue where the _Managed Software Centre_ is always showing a notification for everything which can be installed. There are no updates. Is there a way to hide this? Is it a bug? 

macOS 10.15.6
Managed Software Centre Version 5.2.0.4056 (4056)

<img width="208" alt="Screenshot 2020-09-21 at 16 13 40" src="https://user-images.githubusercontent.com/50698991/93778008-b6422880-fc25-11ea-8621-dfb2cd909908.png">

**Comment by gregneagle** [comment]
As the text you deleted when creating this issue suggested, this is not a support forum. Please post on the Munki-discuss list.
