### ISSUE TITLE
Running ./code/tools/make_munki_mpkg.sh for 5.1.0 results in a domain/default pair error when reading version.

### ISSUE THREAD

**Issue by carlashley** [munki/munki#1031]
When running the `./code/tools/make_munki_mpkg.sh` tool on the 5.1.0 release, the process exits with an error reading the version, however when `less /Volumes/redacted/work/git/github/others/munki/code/client/munkilib/version.plist` is run to verify the file is readable, the content of the file is accessible.

Running `defaults read /Volumes/redacted/work/git/github/others/munki/code/client/munkilib/version` also fails (also fails when adding `.plist` to complete the filename).

`/Volumes/<redacted>/work/git/github/others/munki` is the _root_ directory that the `./code/tools/make_munki_mpkg.sh` is run from.

Adding a quick and dirty echo of the `$MUNKIROOT` variable above the line where the `defaults` command is called to obtain the version results in this output:
```
DEBUG MUNKIROOTVAR
/Volumes/<redacted>/work/git/github/others/munki
```
From what I can see, the paths are correct, the file exists at the path but `defaults` will not read it.

Running `PlistBuddy` works.
```
[c@aurora]:munki # /usr/libexec/PlistBuddy -c 'print ":CFBundleShortVersionString"' /Volumes/redacted/work/git/github/others/munki/code/client/munkilib/version.plist 
5.1.0
```

Build is run on macOS 10.15.7.

```
[c@aurora]:munki # ./code/tools/make_munki_mpkg.sh 
2020-10-01 13:42:16.605 defaults[18971:160345] 
The domain/default pair of (/Volumes/redacted/work/git/github/others/munki/code/client/munkilib/version, CFBundleShortVersionString) does not exist
/Volumes/redacted/work/git/github/others/munki/code/client/munkilib/version is missing!
Perhaps /Volumes/redacted/work/git/github/others/munki does not contain the munki source?
```

Contents of directory:
```
[c@aurora]:munki # pwd
/Volumes/redacted/work/git/github/others/munki
[c@aurora]:munki # ls -lha
total 56
drwxr-xr-x  15 c  staff   510B  1 Oct 13:39 .
drwxr-xr-x  18 c  staff   612B  1 Oct 12:40 ..
drwxr-xr-x  12 c  staff   408B  1 Oct 12:30 .git
drwxr-xr-x   4 c  staff   136B  1 Oct 12:30 .github
-rw-r--r--   1 c  staff   220B  1 Oct 12:30 .gitignore
-rw-r--r--   1 c  staff   138B  1 Oct 12:30 .travis.yml
-rw-r--r--   1 c  staff   106B  1 Oct 12:30 CONTRIBUTING.md
-rw-r--r--   1 c  staff   531B  1 Oct 12:30 LICENSE.md
drwxr-xr-x   6 c  staff   204B  1 Oct 13:39 Python.framework
-rw-r--r--   1 c  staff   2.1K  1 Oct 12:30 README.md
-rwxr-xr-x   1 c  staff   3.2K  1 Oct 13:25 build.sh
drwxr-xr-x   6 c  staff   204B  1 Oct 12:30 code
-rw-r--r--   1 c  staff   264B  1 Oct 13:40 entitlements.plist
drwxr-xr-x   7 c  staff   238B  1 Oct 12:30 launchd
drwxr-xr-x   3 c  staff   102B  1 Oct 12:42 munki_builds
```

**Comment by gregneagle** [comment]
You are encountering Catalina privacy permissions issues.  Betting this works fine from, say, a directory in /Users/Shared.
