### ISSUE TITLE
CLA Link broken

### ISSUE THREAD

**Issue by thefuzzyjew** [munki/munki#1032]
The link appears to be broken in both the wiki and in CONTRIBUTING.md

![Screen Shot 2020-10-02 at 1 17 14 PM](https://user-images.githubusercontent.com/28544457/94956323-9de9cd80-04b1-11eb-9f5b-80e7a981afe2.png)

**Comment by gregneagle** [comment]
Confirmed. I cannot fix this myself, but have alerted the appropriate folk at WDAS.

**Comment by gregneagle** [comment]
Link updated.
(It's now https://media.disneyanimation.com/technology/opensource/CLAforWDP_8.8.18.pdf)
