### ISSUE TITLE
Dark Mode in MSC app

### ISSUE THREAD

**Issue by pytrisss** [munki/munki#1034]
Hi,

I'm trying to package the new stable munkitools for preparation of Big Sur and I noticed that it seems to ignore dark mode setting (MSC app version 5.2.0.4076).
If I load the older dev version I tested before it works fine (5.2.0.4071).

edit: This is on Big Sur latest dev beta.

<img width="1112" alt="Screenshot 2020-10-06 at 15 16 02" src="https://user-images.githubusercontent.com/20901065/95206407-f50bdd00-07e6-11eb-9169-0ed26cf7325b.png">

**Comment by gregneagle** [comment]
The title bar/toolbar of MSC.app doesn't look like that on any release of Munki, so I have to assume you've made some modifications. Here's MSC 5.2.0.4076 (from the Munki 5.1 release) on Big Sur Beta 9 with dark mode:

![image](https://user-images.githubusercontent.com/700560/95220620-82314080-07ab-11eb-80b0-0741c7820aa2.png)

MSC.app is unchanged in Munki 5.1.1. So how did you get to this result?

**Comment by pytrisss** [comment]
That's what I would like to know. 
I'm using custom site_default.zip, but I removed it from the server to be sure it isn't screwing with anything. (It essentialy just changes the banner anyway)

I uploaded an earlier screenshot with the custom banner still there by mistake but the toolbar is not custom, it's part of the trouble. 

What I'm doing is
`git clone https://github.com/munki/munki`
`./code/tools/make_munki_mpkg.sh`
I then take the app from the package and try to run it. 

If you think it's something on my end I will try it on a clean system on thursday.
Just can't get my head around it.

**Comment by gregneagle** [comment]
Is the behavior different when you use the package here?
https://github.com/munki/munki/releases/tag/v5.1.1

If so, I'd want to know more about your build environment. The package for the official release was built on macOS 10.15.6 with Xcode 11.5, though I'd expect macOS 10.15.7 and Xcode 11.7 would be fine, too.

If you are building under Xcode 12 on Big Sur, that might cause enough differences to explain the behavior you are seeing. If so, for now I'd suggest either using the official releases, or building with Xcode 11.x.

**Comment by pytrisss** [comment]
Yes, that works just fine. I completely forgot I was building now on xcode beta.
Thank you!

**Comment by gregneagle** [comment]
So there will probably be changes needed to get things to build properly on Xcode 12 -- I'm not in a position now to work on that specifically.
