### ISSUE TITLE
Feature Request: Ability to select and copy text in MSC.app product descriptions

### ISSUE THREAD

**Issue by shoopdawoop** [munki/munki#1036]
Let users copy descriptions or URLs that are not a hyperlinks, because why not? :D

**Comment by gregneagle** [comment]
I'm sure this is doable, but I'd like it done in such a way that preserves the "illusion" that this is a Mac app and not a web page. IOW, I'd like to avoid selections that look like this:
<img width="950" alt="image" src="https://user-images.githubusercontent.com/700560/96283677-6a1ea580-0f91-11eb-96bb-0912056e6daf.png">

**Comment by shoopdawoop** [comment]
Ah, I remember trying to figure this out myself but failing miserably.

This seems to work well. Thank you!

Cmd-A:

<img width="720" alt="webkit-user-select-text" src="https://github.com/munki/munki/assets/6615875/c23691ab-05dc-4912-924b-788116c34d38">

**Comment by gregneagle** [comment]
Shipped in Munki 6.3.4.
