### ISSUE TITLE
new-msc-design: Back button not visible in Developer view

### ISSUE THREAD

**Issue by shoopdawoop** [munki/munki#1039]
Not necessarily a bug but a minor inconsistency that was not an issue in the previous versions, a design choice (or flaw perhaps) that might have to be reconsidered?

In Product view a back button navigation element is shown in the upper left corner.

![munkitools_app-5 3 0 4192-backbutton](https://user-images.githubusercontent.com/6615875/96149631-d655c680-0f09-11eb-944d-8a21a5a518b9.PNG)

The back button navigation element is **not visible** in Developer view (e.g. all Products by Google, Inc.).
Instead, the custom banner is shown here now (with which the navigation element would interfere in the current layout).
A Cmd-LeftArrow still works.

**Comment by gregneagle** [comment]
I think this is more just task of defining the rules as to when that back button should be visible. In the old design it was visible all the time so it was easy!

Right now it only appears in "detail" views.

It could appear in more views; we just need to decide on the rules. Are you willing to give it some thought and write up a proposed set of rules?

**Comment by shoopdawoop** [comment]
I think it could be as simple as "visible at all times, except when the banner is shown", which imo should only be shown on the main page or perhaps on all main navigation element pages (i.e. Software, Categories, My Items, Updates), not anywhere further down the hierarchy.

**Comment by gregneagle** [comment]
Addressed here: https://github.com/munki/munki/commit/2e555b84607e04f78b5afeacbfc67eb54b61e7ac

**Comment by shoopdawoop** [comment]
One little thing still: on devices with smaller screens, e.g. on a MacBook Air (2013) at 1440 x 900, the banner now sits partly on top of the back arrow element when you switch through the categories menu right below the banner.

![macOS 11 0 1 RC2 + Munki 5 2 BETA 4](https://user-images.githubusercontent.com/6615875/98849564-b5728980-2453-11eb-8b73-c40b901664dc.PNG)

Could be fixed by cutting the banner off a bit more on the right side.

I consider this a cosmetic issue at this point, but I thought I'd mention it.

**Comment by gregneagle** [comment]
I don't think it has anything to do with screen/display size:

<img width="328" alt="image" src="https://user-images.githubusercontent.com/700560/98850310-6ef83d00-2409-11eb-90ec-ef9093747c0e.png">

Odd that in your screenshot the button appears to be _under_ the image; for me the button is always on top (as it must be because the webview is _under_ the button).

I don't at present plan to do anything about it.

**Comment by gregneagle** [comment]
Ah: visually different in Big Sur:

![image](https://user-images.githubusercontent.com/700560/98850643-ed54df00-2409-11eb-8f61-5deadd561abd.png)

My previous comment and screenshot was from Catalina. I suspect the button is "transparent"-ish in Big Sur.

**Comment by gregneagle** [comment]
If we zoom in when the image is lighter, we can see that is the case:

![image](https://user-images.githubusercontent.com/700560/98850812-2c833000-240a-11eb-98db-5614c290a5c7.png)

**Comment by shoopdawoop** [comment]
Sorry, I should have mentioned I was testing on "macOS 11.0.1 RC2 + Munki 5.2 Beta 4" (that was actually the filename of the screenshots, I forgot they get renamed when uploaded).

Right, the image I was using is just very black at that position, the button does sit on top of it.

When extending the window width though (way beyond the screen size in case of a 1440 x 900 screen), the banner image moves further to the right as well and eventually sets the back button free. But the banner image also increases in width until it's shown in full. Before that it gets cut off. So I suppose the issue could be solved by cutting off a little more aggressively at small window widths.
