### ISSUE TITLE
Xcode 12 / Big Sur build issues

### ISSUE THREAD

**Issue by gregneagle** [munki/munki#1040]
Various issues when building under Xcode 12 under Big Sur.

Right now: don't do that.

**Comment by securitygeneration** [comment]
I'm assuming you mean stuff like this when running `make_munki_mpkg.sh` on BS with the latest Xcode 12.2 command line tools (but not the full xcode)? 🙃 

`Building Managed Software Update.xcodeproj...
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`

**Comment by gregneagle** [comment]
Actually, no. I mean that with _Xcode 12.x_ on Big Sur, the GUI apps don't build properly.

The Xcode 12 command line tools failure sounds like a _different_ Apple bug/change.

The command-line tools have never been officially supported or recommended when building the Munki tools:
https://github.com/munki/munki/wiki/Building-Munki-packages#requirements

**Comment by gregneagle** [comment]
Current Munki5dev branch seems to build OK under Xcode 12.1 and Big Sur, so closing this.
