### ISSUE TITLE
Add EmulateProfileSupport to https://github.com/munki/munki/wiki/Preferences?

### ISSUE THREAD

**Issue by apizz** [munki/munki#1043]
Info for `EmulateProfileSupport` on https://github.com/munki/munki/wiki/Configuration-Profile-Emulation is not reflected as a supported preference on https://github.com/munki/munki/wiki/Preferences.  I can make the change, but didn't want to include if this was not officially supported.

**Comment by gregneagle** [comment]
It hasn't been released yet. I'd rather keep all the 5.2-specific documentation together as it evolves. Assuming that feature stays, after 5.2 is released we can update other places in the wiki if needed.

**Comment by apizz** [comment]
Got it, thanks

**Comment by gregneagle** [comment]
Added.
