### ISSUE TITLE
1024 munki certificates are not accepted by Apache 2.4.

### ISSUE THREAD

**Issue by oculos** [munki/munki#1045]
I migrated our munki server to another host running Apache 2.4.X. I didn't get the munki certificates to work:

```
[Fri Oct 30 19:22:42.480679 2020] [ssl:error] [pid 2531017:tid 139839605290752] [client 129.240.203.197:54770] AH02039: Certificate Verification: Error (66): EE certificate key too weak
```

I was following the guidelines [here](https://github.com/munki/munki/wiki/Using-Munki-With-SSL-Client-Certificates), but still it wasn't working.
I changed the bits of the cacert.pem at the openssl.cfg file to 4096, but it still wasn't working. 
After a long time, I found out that on the `addClient.sh` script, the key is still generated with 1024, and that's hard coded on the file. Maybe it should be configured as parameter, or read to match the one from the cacert?
I got it working after changing the value to 4096 on the abovementioned script.

**Comment by gregneagle** [comment]
The guide for setting up client ssl certs and client cert authentication hasn't been updated in a long time, so I'm not surprised that it no longer affects modern SSL/TLS standards.

Please feel free to add your notes to this documentation!

**Comment by oculos** [comment]
Great, will do so! :)
