### ISSUE TITLE
new-msc-design - Hyperlinks with target "_blank" in product descriptions do not open in a browser

### ISSUE THREAD

**Issue by homebysix** [munki/munki#1046]
## Issue description

Hyperlinks in product descriptions do not open in a browser, even when `target="_blank"` is specified.

## Steps to reproduce

1. Add a pkginfo to the Munki repo that contains a hyperlink with `target="_blank"` in the description, or set `InstallAppleSoftwareUpdates` to True on a Mac that requires a macOS update.
2. Observe the hyperlink appears in the MSC interface.
3. Click on the hyperlink and observe that the URL opens in MSC rather than in a browser, with no obvious way to get back to the product description page.

## Expected behavior

MSC should open hyperlinks with `target="_blank"` in the default browser, not in the MSC interface.

Additionally, hyperlinks in Apple software update descriptions should be opened in the default browser regardless of whether they specify `target="_blank"`.

## Screenshots

<img width="1236" alt="Screen Shot 2020-11-06 at 10 08 22 AM" src="https://user-images.githubusercontent.com/7801391/98406223-6e832f00-2022-11eb-9c2f-b5c93df37833.png">

<img width="1236" alt="Screen Shot 2020-11-06 at 10 08 26 AM" src="https://user-images.githubusercontent.com/7801391/98406231-7216b600-2022-11eb-94da-a1130fe0507b.png">

<img width="1236" alt="Screen Shot 2020-11-06 at 10 08 30 AM" src="https://user-images.githubusercontent.com/7801391/98406234-7511a680-2022-11eb-86c9-bded3464cf9b.png">

## Versions

- Munki 5.2 Beta 3
- Managed Software Center 5.3.0.4220 (4220)

**Comment by erikng** [comment]
I actually really like that the url is within MSC, especially for software updates.

Thanks,
Erik Gomez
________________________________

**Comment by homebysix** [comment]
If the page is displayed within MSC, I think it could benefit from a "back" button. There's precedent for this in the App Store, if you dig into an obscure corner of a product page like Version History:

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/7801391/98406854-8d35f580-2023-11eb-9458-05b6524c5e94.png">

My preference is still to display software update pages in browser, but I would feel less strongly if a "back" button existed.

For other links, I think the `target` should be respected. That way admins can choose whether to display pages in MSC or in browser.

**Comment by gregneagle** [comment]
I think we need to give more thought into the "rules" as to when the back navigation button is visible, as mentioned here: https://github.com/munki/munki/issues/1039

I think MSC.app in Munki 5.1 and earlier displays description HTML links inside MSC.app. I don't feel particularly strongly about any of this; I'd be perfectly happy with declaring that _all_ links will be displayed in the default browser in MSC.app 5.3.x...

In any case, can you double-check and verify/document the behavior of these same links with MSC.app 5.2.x and earlier? We can then discuss what the desired/"correct" behavior should be for MSC.app 5.3

**Comment by gregneagle** [comment]
I can't find any evidence that `target == '_blank'` has ever affected how MSC.app displays links anywhere other than when clicking on images in the "showcase":

https://github.com/munki/munki/blob/f1b5162841475a9486983faabff22504e14c06ae/code/apps/Managed%20Software%20Center/Managed%20Software%20Center/Resources/templates/showcase_template.html#L26

Is there documentation or observed behavior that would imply otherwise? IOW, is this actually a change in behavior?

I've changed the logic around the display of the navigate back button which might address part of your issue.

**Comment by gregneagle** [comment]
Given this: https://github.com/munki/munki/issues/1050
I'm seriously considering just changing the new MSC to open _all_ http/https links in the default browser. I do wonder what interesting integrations people have built this change might break...

**Comment by gregneagle** [comment]
@homebysix @erikng Reactions?

**Comment by erikng** [comment]
If it's a bug with WebKit, is what it is.

**Comment by gregneagle** [comment]
All http/https links now open in the user's default browser.
