### ISSUE TITLE
new-msc-design - Managed Software Center pkg version issue

### ISSUE THREAD

**Issue by poundbangbash** [munki/munki#1049]
Testing builds from the `Munki5dev` branch doesn't install MSC.app properly over the existing beta releases.
The MSC version in 5.2b3 is 5.3.0.4220 (4220).
The version of MSC installed with the Munki5dev pkg is 5.3.0.482 (482) so it doesn't install over the beta version even though it is newer code/build.

/var/log/install.log shows:

`2020-11-07 17:48:27-06 Installer[37560]: PackageKit: Skipping component "com.googlecode.munki.ManagedSoftwareCenter" (5.3.0-482.0.0-*) because the version 5.3.0-4220.0.0-* is already installed at /Applications/Managed Software Center.app.`

**Comment by gregneagle** [comment]
See https://github.com/munki/munki/issues/1022#issuecomment-723511276

If I build it with the git history in place, I get an app version of 5.3.0.4229.

How are you building it?

**Comment by poundbangbash** [comment]
I have the git repo cloned locally and run `./make_munki_mpkg.sh -r /Users/Shared/munki -o /Users/Shared -p` from within the repo/code/tools.

Flattening the pkg that is output, the Distribution shows the proper version:
```
<pkg-ref id="com.googlecode.munki.app" auth="Root" version="5.3.0.4227" installKBytes="28507">#munkitools_app.pkg</pkg-ref>
```
and looking in `/Users/Shared/munkitools/munkitools_app.pkg/PackageInfo` shows
```
<pkg-info format-version="2" install-location="/" identifier="com.googlecode.munki.app" version="5.3.0.4227"
```

But the bundle path shows a different version

```
<bundle path="./Applications/Managed Software Center.app/Contents/Resources/MunkiStatus.app" id="com.googlecode.munki.MunkiStatus" CFBundleShortVersionString="5.3.0.482" CFBundleVersion="482"/>
```

**Comment by gregneagle** [comment]
You’re showing the version of MunkiStatus. What is the version of MSC.app?

**Comment by poundbangbash** [comment]
Sorry, grabbed the wrong line but same version in /Users/Shared/munkitools/munkitools_app.pkg/PackageInfo

```
<bundle path="./Applications/Managed Software Center.app" id="com.googlecode.munki.ManagedSoftwareCenter" CFBundleShortVersionString="5.3.0.482" CFBundleVersion="482"/>
```

**Comment by gregneagle** [comment]
I can't reproduce this.
```
    <bundle path="./Applications/Managed Software Center.app" id="com.googlecode.munki.ManagedSoftwareCenter" CFBundleShortVersionString="5.3.0.4229" CFBundleVersion="4229"/>
```
Since your buildnumber part of the version is the "MAGIC_NUMBER" (https://github.com/munki/munki/blob/main/code/tools/make_munki_mpkg.sh#L17) it really feels like the git history is not there when you build. The build number is calculated as the number of git commits + the MAGIC_NUMBER (which I think is the number of SVN commits before the repo was moved from subversion to git.

**Comment by erikng** [comment]
Perhaps you are shallow cloning? I saw similar issues with the github actions.

**Comment by poundbangbash** [comment]
I had to look up what shallow cloning was. The repo was cloned with a standard `git clone https://github.com/munki/munki` and switching branches with `checkout`.

I’ll look at the packaging script later and see what it is pulling as a magic number here.

**Comment by poundbangbash** [comment]
I figured it out here.  It's either a rookie mistake using Xcode on my part or a dumb Apple bug or both.

I have two versions of Xcode from previous testing and had named one `Xcode 11.7.app`.  That is the one that was being used currently. When I tried to build the app in the Xcode GUI, I saw it wasn't pathing to the run-time Script that does the version math properly:

```
/Users/eholtam/Library/Developer/Xcode/DerivedData/Managed_Software_Center-eoncxnfijkaycnhkizttpmzeyiwx/Build/Intermediates.noindex/Managed Software Center.build/Debug/Managed Software Center.build/Script-C096D376251AA6C000977E34.sh: line 11: /Applications/Xcode: No such file or directory
```


After renaming `Xcode 11.7.app` to `Xcode11.7.app` and pointing `xcode-select -s /Applications/Xcode11.7.app` I'm getting a properly versioned application.

I assume the same error was happening when running the build script via CLI as I was seeing the script version everything properly, but the version read from the compiled apps was wrong:

```
Build variables

  munki core tools version: 5.2.0.4217
  LaunchAgents/LaunchDaemons version: 3.0.3265
  Apps package version: 5.3.0.4229
  Python package version: 3.8.5.4228

  metapackage version: 5.2.0.4229

  Bundle ID: com.googlecode.munki
  Munki source root: /Users/Shared/munki-git
  Output directory: /Users/Shared
  Include bootstrap pkg: NO
  Include config pkg: NO
  MDM-style package: NO

  Sign app with keychain cert: [cert]
  Sign package: NO

Building Managed Software Update.xcodeproj...
Managed Software Center.app version: 5.3.0.482
Building MunkiStatus.xcodeproj...
MunkiStatus.app version: 5.3.0.482
Building munki-notifier.xcodeproj...
munki-notifier.app version: 1.1.482
```

Now running with a "properly" named Xcode.app I get:

```
Build variables

  munki core tools version: 5.2.0.4217
  LaunchAgents/LaunchDaemons version: 3.0.3265
  Apps package version: 5.3.0.4227
  Python package version: 3.8.5.4228

  metapackage version: 5.2.0.4228

  Bundle ID: com.googlecode.munki
  Munki source root: /Users/Shared/munki
  Output directory: /Users/Shared
  Include bootstrap pkg: NO
  Include config pkg: NO
  MDM-style package: NO

  Sign app with keychain cert: [cert]
  Sign package: NO

Building Managed Software Update.xcodeproj...
Managed Software Center.app version: 5.3.0.4227
Building MunkiStatus.xcodeproj...
MunkiStatus.app version: 5.3.0.4192
Building munki-notifier.xcodeproj...
munki-notifier.app version: 1.1.4037
```
