### ISSUE TITLE
Logview is truncating lines in MSC 5.3.0.4229

### ISSUE THREAD

**Issue by MiqViq** [munki/munki#1052]
Logview is truncating lines in MSC 5.3.0.4229.
Only some amount of symbols are on the left side of the log view and then the line is clipped.
 
Tested on macOS 10.14.6 and macOS 10.15.7.

<img width="488" alt="msc_logview_truncates" src="https://user-images.githubusercontent.com/2473980/98814107-e770f500-242d-11eb-99e0-686b39aa01a2.png">

**Comment by rickheil** [comment]
Beat me to it - noticed that in my testing last night. 10.15.7 with b4 here as well.

**Comment by gregneagle** [comment]
Fixed here: https://github.com/munki/munki/commit/1b2451698a3e4a99adcae4a1fdc69c916553482a
