### ISSUE TITLE
EmulateProfileSupport not reflected in --show-config

### ISSUE THREAD

**Issue by anewhouse** [munki/munki#1054]
EmulateProfileSupport works great in 5.2, but when you run `sudo managedsoftwareupdate --show-config` it doesn't list that preference or the current setting.

**Comment by gregneagle** [comment]
Thank you. Remember, 5.2 is still in beta!

**Comment by gregneagle** [comment]
Addressed here: https://github.com/munki/munki/commit/72cdd10f47bf6ca060a86bbae0a2819679f641dc
