### ISSUE TITLE
Big Sur installer arguments

### ISSUE THREAD

**Issue by Bretterteig** [munki/munki#1055]
Encountering error `Error: --eraseinstall cannot be used in conjunction with --volume` with Munki 5.2 RC2 and the Big Sur installer. 
I am not sure if munki added the --volume flag or Big Sur added the restriction to use '--eraseinstall' and '--volume' together.
We use the --eraseinstall to repurpose/EOL devices. Would be awsome to continue using it.

**Comment by gregneagle** [comment]
Since this is not a workflow I use I’d recommend working on changes yourself, testing them, and creating a Pull Request. I cannot promise working on this issue myself would ever bubble to the top of my list.

**Comment by Bretterteig** [comment]
Sadly I am not well versed in python/programming . 

I found that '--volume' gets added in the osinstaller.py only if 
`pkgutils.MunkiLooseVersion(os_vers_to_install) < pkgutils.MunkiLooseVersion('10.12.4')`

Which leads me to believe that the version comparisons using MunkiLooseVersion is not working as intended with the new version.

**Comment by gregneagle** [comment]
Are your clients running Munki 5.1 or later? Earlier versions may indeed get the wrong os version from the Big Sur installer app.

Current versions of Munki don't have that issue:
```
>>> from munkilib.osinstaller import *
>>> get_os_version("/Volumes/Install macOS Big Sur/Install macOS Big Sur.app")
'11.0.1'
```

**Comment by Bretterteig** [comment]
I was running 5.2RC2. Somehow after running it multiple times (creating logs etc) it started working. Haven't changed a thing.
Consider it resolved as I cannot pinpoint it.
