### ISSUE TITLE
Arch Condition on Apple Silicon

### ISSUE THREAD

**Issue by nixtar** [munki/munki#1061]
Hello,

I have discovered that the "arch" condition is set to 'x86_64' on Apple Silicon when running under Rosetta.

Looking deeper I found this appears to either be a "bug" in python or is due to Rosetta.

munki-python running under Rosetta:
import os
os.uname()[4]
'x86_64' 

Python 2.7 that's bundled with the OS running natively:
import os
os.uname()[4]
'arm64'

I have worked around this for now by using the output of /usr/bin/arch however if native Apple Silicon Python 3.x isn't coming soon then possibly a hack to handle this is in order? Or possibly at least a note on the doco about the arch on the conditional item wiki?

**Comment by arubdesu** [comment]
I'd think this issue has less to do with munki than python.org themselves, here's a recent update about Universal support for macOS on ARM: https://twitter.com/RonaldOussoren/status/1326607707198132229

**Comment by gregneagle** [comment]
I don't have an Apple Silicon Mac with which to test.

Using `arch` as a replacement on Intel is problematic as at least in some cases it returns "i386" where `os.uname()[4]` returns "x86_64".

```
bash-3.2$ python -c "import os ; print os.uname()[4]"
x86_64
bash-3.2$ arch
i386
```

**Comment by nixtar** [comment]
Ahh interesting..

I guess if we are looking for a short term hack we could check if `arch`  is NOT 'arm64' and then use python os.uname()[4] for the more accurate result on Intel?

This is what I now have in a munki-fact script:
```python
from __future__ import absolute_import, print_function

import subprocess
import os


def fact():
    try:
        proc = subprocess.Popen(['/usr/bin/arch'],
                                stdout=subprocess.PIPE, stderr=subprocess.PIPE, text="UTF-8")
        stdout = proc.stdout.readline().rstrip()
    except (IOError, OSError):
        stdout = 'Unknown'

    if stdout == 'arm64':
        arch = stdout
    else:
        arch = os.uname()[4]

    return {'archex': arch}


if __name__ == '__main__':
    print(fact())
```

There may be more elegant ways to implement this.

I understand we are pretty much on pause until python 3.x universal2 binaries are available. I'm happy to continue with this ArchEx workaround, but others might get tripped up by this.

**Comment by nixtar** [comment]
Ahhh never mind!

Turns out that when `/usr/bin/arch` runs via python it also runs with Rosetta 2 and returns 'i386' on Apple Silicon devices. :(

I'll keep having a poke around and see if I can ID the arch from within Rosetta 2...
Open to suggestions 😊.

**Comment by nixtar** [comment]
Okay.. This is pretty hacky IMO but gets the job done for now.

The version property of os.uname() has some ARM identification in it..

Apple Silicon device via Rosetta:
os.uname()[3]
`'Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:10 PDT 2020; root:xnu-7195.50.7~2/RELEASE_ARM64_T8101'`

Intel device: ()
os.uname()[3]
'Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64'


```python
from __future__ import absolute_import, print_function

import os


def fact():
    
    version = os.uname()[3]

    if 'ARM64' in version:
        arch = 'arm64'
    else:
        arch = os.uname()[4]

    return {'archex': arch}


if __name__ == '__main__':
    print(fact())
```

**Comment by gregneagle** [comment]
Addressed for a future Munki release here: https://github.com/munki/munki/commit/7f736a4901397711e67cf6e9282be0194c59e9eb
