### ISSUE TITLE
Update needed in installationstate for startosinstall/Big Sur

### ISSUE THREAD

**Issue by Bretterteig** [munki/munki#1066]
With the change of Big Sur's version scheme there needs to be a small update in version comparisons/ installation status check. 

Something like

`if item_os_vers.split('.')[0] > 10:`
`   item_os_vers = item_os_vers.split('.')[0]`
`else:`
`   item_os_vers = '.'.join(item_os_vers.split('.')[0:2])`

in installationstate.py line 88

Not a contributor and very small change so posting an issue.

**Comment by gregneagle** [comment]
I believe this is addressed in this commit: https://github.com/munki/munki/commit/ae28a71550d5a4ba445f55e94acefe4de4874bf4, which is included in the Munki 5.2.1 release. Please test and confirm!
