### ISSUE TITLE
Rosetta 2 silent installation request

### ISSUE THREAD

**Issue by trevenag01** [munki/munki#1067]
When using Mosyle MDM to install Munki it doesn't install Rosetta 2 silently, would like to get this to install prior to munki running.

/usr/sbin/softwareupdate --install-rosetta --agree-to-license

**Comment by trevenag01** [comment]
Not sure if it is just the agree-to-license that is the issue

**Comment by poundbangbash** [comment]
As of the 5.2 release there is an option when using the build script to include installing Rosetta. See https://github.com/munki/munki/wiki/Building-Munki-packages and the tools usage notes. 

-Eric

**Comment by gregneagle** [comment]
https://github.com/munki/munki/blob/main/code/tools/pkgresources/Scripts_rosetta2/postinstall
