### ISSUE TITLE
BigSur Update 11.1 asks for password

### ISSUE THREAD

**Issue by trevenag01** [munki/munki#1068]
BigSur Update 11.1 asks for a password when updating through Managed Software Centre.

Won't complete until updated, have to hit cancel.

**Comment by gregneagle** [comment]
What version of Munki are you using? Recent versions of Munki direct the user to the Software Update prefs pane.

**Comment by trevenag01** [comment]
v5.3.0a5 it doesn't appear it is held with username/password request hidden.

**Comment by gregneagle** [comment]
Are you on Apple Silicon?  I have none to test but this seems to be a new Apple feature on that hardware. I suspect it means that Munki will not be able to help with even downloading Apple updates.

**Comment by trevenag01** [comment]
BigSur on m1 seems to prompt for admin username/password all software updates.  BigSur on intel seems fine.

**Comment by sphen13** [comment]
seems to me we could have munki check if running on arm and remove the -d flag from softwareupdate if so?

**Comment by gregneagle** [comment]
The changes will have to be more extensive than that. On Apple Silicon, if Apple makes no changes to `softwareupdate`’s behavior, Munki will not be able to download or install any Apple updates.

**Comment by trevenag01** [comment]
can we bypass this option for now?

**Comment by gregneagle** [comment]
Sure: configure Munki to not manage Apple updates on Apple Silicon Macs.

https://github.com/munki/munki/wiki/Apple-Software-Updates-With-Munki#details

**Comment by trevenag01** [comment]
I have the false setting in place but it still tries to connect.

Current Munki configuration:
                   AdditionalHttpHeaders: (
) [MANAGED] 
        AggressiveUpdateNotificationDays:    14 [/Library/Preferences/ManagedInstalls.plist] 
                AppleSoftwareUpdatesOnly: False [/Library/Preferences/ManagedInstalls.plist] 
                              CatalogURL:  None [not set] 
                   ClientCertificatePath:  None [not set] 
                        ClientIdentifier: u'SBCC_Staff' [MANAGED] 
                           ClientKeyPath:  None [not set] 

![image](https://user-images.githubusercontent.com/43830633/103588602-a7b21f80-4f3d-11eb-9c15-51bc0b23bd5d.png)

Feel a little stupid here, just checking I haven't missed anything here.

**Comment by gregneagle** [comment]
You've shown you have `AppleSoftwareUpdatesOnly` set to False; this preference, if true, causes Munki to _only_ manage Apple updates and not check for any Munki repo.

https://github.com/munki/munki/wiki/Apple-Software-Updates-With-Munki#using-the-munki-tools-only-to-install-apple-software-updates

You need to set `InstallAppleSoftwareUpdates` to False.

https://github.com/munki/munki/wiki/Apple-Software-Updates-With-Munki#details

**Comment by clreinki** [comment]
I have Munki bootstrapping when it comes down in the MDM enrollment profile.  This password issue on M1 Big Sur is causing it to endless loop and be unable to login or do anything.  I realize it's possible to just turn that off via the key mentioned above, however we have such a mix of device types it'd be easier if it was just hardcoded to disabled for M1.  If I wrote a pull request implementing this, would you merge it or would you prefer to make users use the InstallAppleSoftwareUpdates key?

**Comment by gregneagle** [comment]
Such a change is already in the Munki5dev and universal2 branches.

**Comment by gregneagle** [comment]
https://github.com/munki/munki/commit/bf0de6471384fe911b42c66378d1a4c360c20425

**Comment by clreinki** [comment]
Nice!  Looks like I need to rebuild my pkg!

**Comment by ofirgalcon** [comment]
I never had this issue. Is it specific to non-admin users?

**Comment by gregneagle** [comment]
Ask Apple for documentation on the full extent of the changes.

Remember that Munki runs as _root_, so admin/non-admin users don't come into play here.

My observation (which matches others): any run of `softwareupdate -da` or `softwareupdate -i <anything>` on Apple silicon results in a prompt for user credentials.

**Comment by gregneagle** [comment]
I'm closing this since the issue has been addressed in Munki 5.2.2 by disabling support for Apple software updates.
