### ISSUE TITLE
munkiimport --configure settings not saved in Big Sur

### ISSUE THREAD

**Issue by clreinki** [munki/munki#1071]
https://github.com/munki/munki/blob/2dda6b7783c0ec65e2e97cc3526c10eb63bf0bb3/code/client/munkilib/cliutils.py#L225

When running "munkiimport --configure" and filling in the appropriate values, it is expected that a preferences file be created at ~/Library/Preferences/com.googlecode.munki.munkiimport.plist.  This has worked prior to Big Sur.

Now after running it, the plist gets created but only the "default_catalog" key is set.  None of the others are saved.  I believe this is due to line 225 in cliutils.py which defines how preferences are saved based on macOS version.  Since Big Sur jumped major versions from 10 to 11, I think this line needs updated to fix the issue.

![Screenshot](https://user-images.githubusercontent.com/12813987/107696842-72a59500-6c80-11eb-923d-53d221c9d264.JPG)

**Comment by gregneagle** [comment]
Darwin version of Big Sur is 20, so that's not it.

```bash
$ uname -r
20.3.0
```

**Comment by gregneagle** [comment]
(that's a plus of using Darwin versions instead of the macOS "marketing" versions, they are a steadily-increasing integer.
OS X 10.6 was Darwin 10
OS X 10.7 was Darwin 11
OS X 10.8 was Darwin 12
...
macOS 10.15 is Darwin 19
macOS 11.0 is Darwin 20

So the issue must be elsewhere.

**Comment by gregneagle** [comment]
...and I cannot replicate this issue on macOS 11.2.1 running on Apple Silicon.

**Comment by gregneagle** [comment]
```bash
bash-3.2$ sw_vers
ProductName:	macOS
ProductVersion:	11.2
BuildVersion:	20D64
bash-3.2$ munkiimport --configure
Repo URL (example: afp://munki.example.com/repo): smb://foo/bar
pkginfo extension (Example: .plist): .pkginfo
pkginfo editor (examples: /usr/bin/vi or TextMate.app; leave empty to not open an editor after import): /usr/bin/vi
Default catalog to use (example: testing): testing
Repo access plugin (defaults to FileRepo): 
bash-3.2$ defaults read com.googlecode.munki.munkiimport
{
    "default_catalog" = testing;
    editor = "/usr/bin/vi";
    "pkginfo_extension" = ".pkginfo";
    plugin = "";
    "repo_url" = "smb://foo/bar";
}
```

**Comment by gregneagle** [comment]
Also reading it the other way: 
```bash
bash-3.2$ defaults read ~/Library/Preferences/com.googlecode.munki.munkiimport.plist 
{
    "default_catalog" = testing;
    editor = "/usr/bin/vi";
    "pkginfo_extension" = ".pkginfo";
    plugin = "";
    "repo_url" = "smb://foo/bar";
}
```

**Comment by clreinki** [comment]
Ha - of course, you're right Greg.  Darwin != macOS version, my mistake.

I've tested this on two machines, one intel-based Mac Mini running 11.2.1 and an M1 Macbook Air running 11.2 and can replicate on both, even after fresh reset.

**Comment by poundbangbash** [comment]
Are there PPPC allowances in play here? Greg, do you have Terminal or munkiimport allowed in Full Disk Access?

**Comment by gregneagle** [comment]
I am successful editing on Big Sur on Intel as well.

**Comment by clreinki** [comment]
I'll try resetting without joining to the MDM.  While it works on Catalina with the same MDM profiles, I'll try to isolate it to as clean of a macOS install as possible and update this issue with my results.

**Comment by gregneagle** [comment]
Yes, Terminal has Full Disk Access. I'm not convinced that is related to this issue, though, since user's Library/Preferences folder is not protected by PPPC/TCC.

**Comment by clreinki** [comment]
I gave Terminal full disk access and that did not help.  I also sent the MDM removal command to the device, all profiles are now gone but still no luck.  Full reset next but I'm still baffled why yours is working.

**Comment by clreinki** [comment]
Good news, bad news.

Good news - it's working after I reinstalled Munki 5.3 experimental from the github releases.
Bad news - I don't know why that fixed it.

The only difference is we push Munki with our MDM enrollment profile, which we package up with the make_munki_mpkg.sh script and sign with our developer certificate.  I realize that SHOULDN'T make a difference but I have no idea how else to explain it.

Regardless, Greg, if you want to close this issue since it's such a specific use case, I'm fine with that but also willing to keep investigating.

**Comment by gregneagle** [comment]
On your broken machines, where does the `/usr/local/munki/munki-python` symlink point?

**Comment by clreinki** [comment]
It points to "Python.framework/Versions/Current/bin/python3"

**Comment by gregneagle** [comment]
On your broken machines? Are you certain?
See https://groups.google.com/g/munki-dev/c/t2LYxjHAl-M/m/Q6Zdg01WAgAJ for why I ask.

**Comment by clreinki** [comment]
I am 100% certain - got the broken machine right in front of me.

**Comment by clreinki** [comment]
On the broken machine, munki-python --version outputs Python 3.8.5
On the now fixed machine, it outputs Python 3.9.1

**Comment by gregneagle** [comment]
Works here on:
```bash
$ sudo managedsoftwareupdate --version
5.2.1.4276
$ /usr/local/munki/munki-python -V
Python 3.8.5
```
and on an experimental Universal2 build on Apple Silicon.

**Comment by clreinki** [comment]
Final update - on a clean install of macOS (no MDM), I can install our mpkg manually and everything works fine.  However if that same mpkg is used in an MDM enrollment profile, I get the behavior mentioned above.  It doesn't make sense to me, but being such a strange and possibly MDM-specific (Mosyle) issue, I'm closing this.  Thanks all for the help!

**Comment by clreinki** [comment]
For what it's worth, rebuilding the mpkg on the universal2 branch fixed this issue.

**Comment by gregneagle** [comment]
Which is why I still think it is related to the pkg install issue with MDM mentioned here: https://groups.google.com/g/munki-dev/c/t2LYxjHAl-M/m/Q6Zdg01WAgAJ

**Comment by clreinki** [comment]
I think you're right because the old pkg has "python" and "no-python" subpackage, while the new one doesn't.  Either way, thanks for working with me on this.
