### ISSUE TITLE
Feature Request: add "only arm64" / "only intel" options to installation requirements

### ISSUE THREAD

**Issue by rlndkhlr** [munki/munki#1072]
HI there,

it would be really nice to have the Managed Software Centre only display packages suitable for the respective platform. Maybe through two keys - arm64 and intel - that are false by default (and would indicate a universal app) but can be set to true.... similar to min/max OS settings, and other installation requirements.

Use case: Some apps have added code to be universal (e.g. Chrome, Affinity apps, Alfred, ....), other developers provide an Intel and an Apple Silicon version of their apps (e.g. Slack, VLC, Brave Browser, ....). Having an environment with both Intel and Apple Silicon devices, I have two versions of an app in my repo. Currently, the MSC shows both versions in the software section, as well as the update section (even when one of the two is already installed).
I do not want to make the users a guess which app to install but rather only have the correct version available to them.

Going forward, probably something beneficial to most. Thank you. :)

**Comment by gregneagle** [comment]
It already supports that feature. Take a look in the wiki for the `supported_architectures` key.

**Comment by rlndkhlr** [comment]
So sorry, I completely missed that. Thank you! :)
