### ISSUE TITLE
MSC: Items vanish from My Items when removal is canceled

### ISSUE THREAD

**Issue by shoopdawoop** [munki/munki#1073]
I noticed this 'lil glitch in MSC (still present in v5.3.0.4287 on macOS 11.2.1) when removing an item in My Items but then hit Cancel (because maybe you got a warning that the app was still running), and although the item is still installed it will no longer be shown in My Items.

Quitting MSC does not correct this error, but the item still shows up as installed in Software and once you hit remove there, it will show up again in My Items.

I consider this a fringe case but when it happens it might be quite confusing to users.

**Comment by gregneagle** [comment]
Given the loose coupling between MSC.app, running as the current GUI user, and `managedsoftwareupdate`, running as root, it would be difficult to address this, and is probably not worth the effort.

When you click "Remove", MSC.app removes the item from the SelfServe manifests's managed_installs and adds it to the SelfServe manifests's managed_uninstalls. It then triggers a Munki run. It really has zero idea after that what actually happens. If the removal fails, the item should still be the SelfServe manifests's managed_uninstalls, but it will not appear in "My Items", which is really just the contents of the SelfServe manifests's managed_installs. There would be no mechanism to "put it back."

**Comment by shoopdawoop** [comment]
I see. Makes perfect sense to me to not do anything about this, so I'll close.

Thanks.
