### ISSUE TITLE
Feature request - add check to allow importing of matching software so long as supported_architectures have unshared values

### ISSUE THREAD

**Issue by apizz** [munki/munki#1076]
The question that has been brought up several times is how best to handle including two version of the same software - like Slack -, but which _does not_ have a universal app and instead has separate distributions for Intel and Apple Silicon (`arm64`).  As such, both distributions may have an app in a DMG with differing architectures.

The recommended strategy for this scenario is to leave the munki item `name` key the same and use the `supported_architectures` array to define either `x86_64` for Intel or `arm64` for Apple Silicon.  This is an excellent one, as a single munki software item can be named in manifests - `Slack` - and munki will do its thing to determine which software item to use based on the `supported_architectures`.

However, the challenge is that as of the current version it is not possible to have `munkiimport` import both items without indicating for the second software item that one already exists, despite the differing architectures.

There are 2 components that I believe need to be added to address this.

1. When processing an app, rather than a PKG, add a check to `munkiimport` to run `file` on the app's executable file. Automatically populate the collected architecture(s) and include those collected in a `supported_architectures` array as part of the import.
2. When processing an app, add a check to `munkiimport` such that _only_ when a possible match is found already in the repo compare the `supported_architectures`.  The only scenario that should cause an item to be imported where it normally would not would is if A) the matched software _has_ a non-empty `supported_architectures` array, B) the architecture of the new app is not empty and C) the architecture _does not exist_ in the existing item's `supported_architectures` array.

The important bit for the above additions is that the `supported_architectures` should only be compared when a possible match is found.

The addition of a message indicating the architecture would be helpful as well.

While I am far from a Python expert, running `file /Path/to/app.app/Contents/MacOS/BinaryFile | awk '{print $NF}'` will return either a single value - `x86_64` or `arm64` - while a universal app will return (currently) 3 with all but the first value being relevant.

```
~ > file /Volumes/VLC\ media\ player/VLC.app/Contents/MacOS/VLC                                                                     22:28:49
/Volumes/VLC media player/VLC.app/Contents/MacOS/VLC: Mach-O 64-bit executable arm64
~ > file /Applications/VLC.app/Contents/MacOS/VLC                                                                                   22:29:00
/Applications/VLC.app/Contents/MacOS/VLC: Mach-O 64-bit executable x86_64
~ > file /Applications/Alfred\ 4.app/Contents/MacOS/Alfred                                                                          22:29:28
/Applications/Alfred 4.app/Contents/MacOS/Alfred: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
/Applications/Alfred 4.app/Contents/MacOS/Alfred (for architecture x86_64):	Mach-O 64-bit executable x86_64
/Applications/Alfred 4.app/Contents/MacOS/Alfred (for architecture arm64):	Mach-O 64-bit executable arm64
~ > file /Applications/Alfred\ 4.app/Contents/MacOS/Alfred | awk '{print $NF}'                                                      22:30:07
arm64]
x86_64
arm64
~ > file /Applications/VLC.app/Contents/MacOS/VLC | awk '{print $NF}'                                                               22:36:15
x86_64
~ > file /Applications/iStat\ Menus.app/Contents/MacOS/iStat\ Menus | awk '{print $NF}'                                             22:36:47
[arm64]
x86_64
arm64
```

The benefit of this addition would be that admins would not have develop other logic or mechanisms to determine whether or not to forcibly import a munki item based on the its architecture.

**Comment by gregneagle** [comment]
This is more complex than you indicate.

Remember that most x86 software runs just fine on Apple silicon via Rosetta2. If munkiimport marked software that was x86-only with a supported_architecture array containing only x86_64, Munki would _not_ install it on Apple silicon Macs. In many cases, that's not the behavior you want.

I'm personally unlikely to spend any time working on any features around this -- it's pretty easily manually handled for those few products that have distinct Intel and Apple silicon installers, and this is likely to be a temporary situation in any case. If someone else wants to do the work, I'll be happy to review it.

**Comment by gregneagle** [comment]
I'm going to close this. munkiimport will allow you to import both Intel and Apple silicon versions of a piece of software, and autopkg has been updated to make this reasonably straightforward as well. No-one has proposed a concrete set of changes to address this any better in over a year, so I conclude that this issue, in practice, isn't a big deal.

**Comment by jelockwood** [comment]
@apizz @gregneagle 

FYI - I have a similar desire and yes Munki and AutoPkg have support for this and the following is the approach I will be using.

I have created two different AutoPkg recipes - one for the Intel version and one for the ARM version of Zoom. I add the respective architecture in the Munki recipe for each. I then plan to create a Munki condition script for the Intel version to check the users computer architecture and hence only make itself visible to the correct architecture computers. It should also be possible to add a check to see if Rosetta is installed as well and only offer the Intel version to those Macs with that although of course you can make that a payload free Munki install marked as a requirement.
