### ISSUE TITLE
Link to Contributor License Agreement broken

### ISSUE THREAD

**Issue by ryansumma** [munki/munki#1079]
https://disney-animation.s3.amazonaws.com/uploads/production/open_source_pdf/2/pdf/TestCLA-1.pdf

**Comment by gregneagle** [comment]
_Where_ is this broken? If I click the link on this page:

https://github.com/munki/munki/wiki/Contributing-to-Munki

It works as expected.

**Comment by gregneagle** [comment]
Closing due to lack of further communication.
