### ISSUE TITLE
VPP apps stop deploying after managed software centre executed

### ISSUE THREAD

**Issue by trevenag01** [munki/munki#1082]
Have i missed something very trivial before investigating further, but as soon as managed software centre is executed there after no more VPP apps are installing.

**Comment by gregneagle** [comment]
VPP apps would be installed by an MDM server. It would a really odd MDM bug if the execution of some random app like Managed Software Center affected the MDM server...

**Comment by MarcelRei** [comment]
I know that the MobileIron Client for example is build using munki. That did cause some issues for me at first, but I stayed with munki and disregarded the MobileIron Client to deploy software.

**Comment by gregneagle** [comment]
So if you are having issues with MobileIron installing VPP apps, I’d think that would be an issue you’d bring up with MobileIron support.

**Comment by gregneagle** [comment]
Closing.
