### ISSUE TITLE
Request the ability to hide the Sidebar in the MSC GUI

### ISSUE THREAD

**Issue by Lotusshaney** [munki/munki#1085]
Would i be possible to be able to hide the Sidebar in MSC GUI with a pref setting or if there are no optional_installs ?

The reason is I use Jamf to handle the software distribution with its Self Service application but Munki to do any updates.

I have had users get confused with MSC and look for software in there

**Comment by gregneagle** [comment]
Sure it might be possible. It’s not something I need, so I’m unlikely to work on it anytime soon.

**Comment by gregneagle** [comment]
Changes in Munki 5.5 should mostly address this issue.
