### ISSUE TITLE
Client certificates are not being read in BigSur 11.3

### ISSUE THREAD

**Issue by oculos** [munki/munki#1087]
Hi,

It seems that BigSur 11.3 broke the use of client certificate. We started to get the following error after an upgrade:

```
Starting...
    CA cert path: /Library/Managed Installs/certs/cacert.pem
    CA dir path:  None
    Adding CA cert /Library/Managed Installs/certs/cacert.pem...
ERROR: Could not add CA cert /Library/Managed Installs/certs/cacert.pem into System keychain: 1: Error reading file /Library/Managed Installs/certs/cacert.pem
    System.keychain updated.
    Adding client keychain to search path...
    ```

I've read on forums that people are also getting `“No required SSL certificate was sent”` on verbose mode.

Is there any fix in the horizon?

**Comment by gregneagle** [comment]
No fix on the horizon from _me_. I don't use client certs and have no easy way to set up an environment in which to use them/test them. That doesn't mean I will never ever look at or pay attention to this, but if you are hoping for a quick fix from me you will be disappointed.

If this is important to some Munki users I hope they'll find the development resources to dig in and discover the issue here and any potential workarounds.

**Comment by childrss** [comment]
Pat Szuta and I did some quick searching and found that the particular form of the security command munki is using to add the certificate has now been placed behind requiring user confirmation or MDM. 

https://www.reddit.com/r/macsysadmin/comments/n0q9d3/installing_ca_certs/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by oculos** [comment]
> No fix on the horizon from _me_. I don't use client certs and have no easy way to set up an environment in which to use them/test them. That doesn't mean I will never ever look at or pay attention to this, but if you are hoping for a quick fix from me you will be disappointed.
> 
> If this is important to some Munki users I hope they'll find the development resources to dig in and discover the issue here and any potential workarounds.

Hi Greg,

I see your point, but since the use of client certificates is a Munki feature, I found it only logical to open this issue. 
But still, it would be nice if a preference could be added to Munki so that it would skip trying to copy certs to the keychain and just assume they are there (or, better, that we could specify a given certificate from the keychain to be used).

**Comment by oculos** [comment]
> Pat Szuta and I did some quick searching and found that the particular form of the security command munki is using to add the certificate has now been placed behind requiring user confirmation or MDM.
> 
> https://www.reddit.com/r/macsysadmin/comments/n0q9d3/installing_ca_certs/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

Thanks! We do use MDM, but even when we add the CA certificate to the keychain, it seems to fail. How do you add the certificates manually (or via MDM) to the keychain so that Munki doesn't attempt to copy them?

**Comment by gregneagle** [comment]
Add them to the keychain via MDM and _don't_ put them in the place Munki copies them from.

**Comment by gregneagle** [comment]
But you are now talking about trusted CA certs that need to be in the System keychain. The original topic is "Client certificates are not being read in BigSur 11.3" which is a _different_ issue.

**Comment by oculos** [comment]
But shall the "UseClientCertificate" setting be set to False or True? And do the path settings for the certificates need to be unset?

**Comment by oculos** [comment]
> But you are now talking about trusted CA certs that need to be in the System keychain. The original topic is "Client certificates are not being read in BigSur 11.3" which is a _different_ issue.

Ok, I thought they were related. I suppose the CA can be installed on the System keychain via MDM as well, right?

**Comment by rrenstrom** [comment]
You may not even need the CA cert (even if you client cert is created with a self-signed CA), it's not required to use the client cert. 

The CA cert would only be necessary if you are using a self-signed cert for the *server* (using a server cert from a CA that macOS trusts by default solves that issue).

-rob

**Comment by rrenstrom** [comment]
btw, the new problem with client certs under macOS 11.3 is being discussed at 

https://groups.google.com/g/munki-dev/c/NnTkQeoM7Pk/m/r_rv_1PAEQAJ

**Comment by oculos** [comment]
> You may not even need the CA cert (even if you client cert is created with a self-signed CA), it's not required to use the client cert.
> 
> The CA cert would only be necessary if you are using a self-signed cert for the _server_ (using a server cert from a CA that macOS trusts by default solves that issue).
> 
> -rob

Yes, we are using a self-signed cert for the server, though I still get to download from it without the CA with curl.

**Comment by gregneagle** [comment]
No feedback on the changes in #1077 but these changes are now in the 5.5 release. I'm closing this as I believe they address the issue.
