### ISSUE TITLE
When software is selected for uninstallation but it is a dependency of other installed software, munki enters infinite update loop

### ISSUE THREAD

**Issue by waitbutY** [munki/munki#1092]
When I attempt to remove some software, I enter an infinite update loop.

Upon inspecting the logs, I see:

`WARNING: Will not attempt to remove X because some version of it is in the list of managed installs, or it is required by another managed install.`

There is no visual indicator in Munki that the uninstall is not possible, the Update tab will just attempt to update forever.

Removing the requested uninstall fixes the issue.

**Versions:**
- MacOS v11.3.1
- Munki v5.3.0.4258

**Comment by gregneagle** [comment]
Not sure this is easily addressable; one issue of course is there's nothing at all the end-user can do about this situation -- only the Munki admin can fix it. What would be your suggested approach?

**Comment by munneco** [comment]
Sorry to bring this up... Ran in a similar situation. I'm trying to uninstall a software (App A) that is a requirement for another software (App B).

When I install App B, App A is installed. The goal is that when I try to uninstall App A, App B is also removed. Is that possible at all?
