### ISSUE TITLE
Feature Request - munkiimport --optional-receipts to flag component packages as optional

### ISSUE THREAD

**Issue by carlashley** [munki/munki#1101]
When importing certain items into munki with `munkiimport`, there are scenarios where a package has other component packages that are "optional" as a result of either a choices XML value/arg, or are included in the package and only get installed if certain criteria are met.

Unless these are set to optional in the `pkginfo` after import, these optional packages can potentially lead to munki updates/installs looping.

Implementing a flag in `munkiimport` such as `--optional-receipts` that took package ID options in and for any matching package ID in discovered in the package, would set the `optional` boolean to false in the `receipts` array of the corresponding pkginfo file.

For example:
`munkiimport MicrosoftDefender.pkg --nointeractive --unattended_install --category=Security --developer=Microsoft --optional-receipts com.microsoft.package.Microsoft_AutoUpdate.app`

Would result in a `receipts` array that set the `optional` key to `true`.
```
        <key>receipts</key>
        <array>
                <dict>
                        <key>installed_size</key>
                        <integer>518528</integer>
                        <key>packageid</key>
                        <string>com.microsoft.wdav</string>
                        <key>version</key>
                        <string>101.32.69</string>
                </dict>
                <dict>
                        <key>installed_size</key>
                        <integer>15851</integer>
                        <key>optional</key>
                        <true/>
                        <key>packageid</key>
                        <string>com.microsoft.package.Microsoft_AutoUpdate.app</string>
                        <key>version</key>
                        <string>4.20.20020900</string>
                </dict>
        </array>
```

**Comment by gregneagle** [comment]
I have no plans to implement this. There are many things that can go into a pkginfo file that cannot be done directly with munkiimport or makepkginfo — editing the pkginfo file will always be the most flexible and robust mechanism for this sort of thing.

**Comment by gregneagle** [comment]
For more automated imports into Munki, Autopkg is probably a better route than attempting to cram more and more options into munkiimport/makepkginfo
