### ISSUE TITLE
Unwanted behavior with "Aggressive notifications" and full-screen application usage

### ISSUE THREAD

**Issue by gregneagle** [munki/munki#1108]
Munki 5's aggressive notifications that attempt to force the user to interact with Managed Software Center to install updates that have been pending a long time cause unwanted behavior in this scenario:

1) User is working with an app in "full screen mode" (which gives the app its own "Space")
2) Managed Software Center is open in another space
3) There are one or more updates pending long enough to trigger "Aggressive notifications) (default is over 14 days)
4) `managedsoftwareupdate` runs in the background and triggers munki-notifier to notify the user of pending updates.

Expected behavior:
OS switches to the Space containing Managed Software Center's window, and MSC.app does an "Aggressive notification".

Observed behavior:
OS remains in the Space containing the full-screen application. MSC.app does an aggressive notification, which blocks access/input to all other apps, disables the task switcher. etc. This results in a full-screen app one cannot interact with and no way to switch to MSC.app to trigger the updates it is trying to aggressively notify about.

**Comment by gregneagle** [comment]
I can reproduce this unwanted behavior consistently.

If I run `open munki://notify` the OS consistently switches to the space before MSC.app enters "obnoxious mode".
But if I instead run munki-notify, which uses NSWorkspace's openURL method to open the "munki://notify", the OS does _not_ switch to the Space containing MSC.app's window, and when MSC.app enters obnoxious mode, access to the current full-screen app is blocked.

One assumes that `open munki://notify` and using NSWorkspace's openURL method to open the same URL would behave the same, but this does not appear to be the case.

**Comment by fuzzylogiq** [comment]
I don't know if this is related, but I have experienced and looked into sporadic failures of MSC to launch if it's been rebranded with munki-rebrand and I find this in the unified log if i do `log stream --info --debug | grep munki` while clicking on the notification (which doesn't open MSC.app)

`2021-09-14 09:35:18.313145+0100 0x5098d5   Error       0x0                  1701   0    usernoted: [com.apple.unc:application] Failed to find appropriate application to launch for com.googlecode.munki.ManagedSoftwareCenter matching 4ECFB801-3134-4EDF-866A-B18DD9EB1107
2021-09-14 09:35:18.313202+0100 0x5098d5   Error       0x0                  1701   0    usernoted: [com.apple.unc:application] Failed to find app for  0.000000or response com.googlecode.munki.ManagedSoftwareCenter`

**Comment by fuzzylogiq** [comment]
I should also note that if I do `open munki://notify` MSC.app opens successfully

**Comment by TD5** [comment]
I've experienced this issue when an aggressive notification has left me locked-out. Once thing I realised though, is that my touch-bar shows the buttons from the window, so I can hit "cancel" on the touch bar, then switch back to the Managed Software Center's window and deal with the notification. It's still far from ideal, but it's a way to temporarily unblock yourself so you're not forced to do something more drastic like reboot.

**Comment by TD5** [comment]
Is anyone aware of any other mitigations for this issue?

**Comment by sahilkmr78** [comment]
+1, this happens constantly to me. When switching to a full-screen window I'm stuck with the notification that I can't interact with. I'm not even able to minimize my full-screen window to reach the notification.

**Comment by gregneagle** [comment]
I think I have this addressed here: https://github.com/munki/munki/commit/7ce973787b004e2d4bc680db70e0da281bd7fd93 with what seems to me to be a sort of hack. I first open/switch to MSC.app, sleep one second, then send it the "munki://notify" URL that (if the other conditions are right) will cause MSC.app to enter obnoxious mode.

**Comment by gregneagle** [comment]
(Essentially we're doing `open munki:// ; sleep 1 ; open munki://notify`)

**Comment by gregneagle** [comment]
I'm going to close this and re-open if we discover the fix doesn't completely address the issue.
