### ISSUE TITLE
Managed Software build 4362 reports as being v5.4 not v5.5?

### ISSUE THREAD

**Issue by jlayt** [munki/munki#1109]
After installing the munkitools-5.5.0.4362.pkg, the Managed Software app reports the version as 5.4.0.4362, i.e. the 5.5. build number but the 5.4 release number, which doesn't seem right? The command line tools report as being 5.5.0-4360, i.e. I guess the beta release build number?

This confuses AutoPkgr which always complains there is a Munki update pending. I've not noticed any other consequences as yet. If this is intended, I'll go complain to AutoPkgr instead.

Thanks!

**Comment by arubdesu** [comment]
Please don't complain when autopkgr is just a gui behind autopkg, and the creator of munki is one of the creators of not just autopkg but the recipe for munki. Please understand that the versioning is separate for the gui app and each of the ~6 other component pkgs when you expand the release version you see on GitHub. Please join us in the munki-discuss mailing list or the Mac admin slack munki or autopkg channels or feel free to explain the log entry you're seeing alongside the symptom you're having.

**Comment by gregneagle** [comment]
The versioning of the individual components is correct. I'm sorry it confuses AutoPkgr, but that's on the AutoPkgr's maintainers to solve (or not).

The Munki distribution package contains several component packages, each with their own version number. If a component didn't change, the version number may not change, either. Or one component might have big changes, and another might have only minor changes.

MSC.app's version number has never closely tracked the overall Munki release numbering. It's sheer coincidence that the MSC version is currently pretty close to the Munki release number.
