### ISSUE TITLE
When I use some special characters, it does work at all

### ISSUE THREAD

**Issue by NomalButHappy** [munki/munki#1110]
When I use the special characters "#" in the package name, it seems like the package name was cut down when I install the package. For example, the package named "asdf#aasdf.pkg", then when I use client to install it, the log print "nothing we know how to install in /Library/Managed Installs/Cache/asdf".
    Thank you for this software. It helps me a lot and hope you solve this problem as soon as possible

**Comment by gregneagle** [comment]
Remember that the Munki client retrieves its info and installers via http(s). So you must avoid any character that is illegal in a URL your filenames.

"#" is not generally considered an illegal URL character, but your Munki webserver may be treating it differently.

Given that Munki's been in use for over ten years with hundreds of thousands if not millions of clients, and no-one has reported this issue before, I have to think it has more to do with the configuration/operation of the webserver you are using.

I may be wrong here. If you can show a way to clearly reproduce this issue against a fairly generic Apache webserver, I'll be happy to look more deeply.

**Comment by gregneagle** [comment]
Of course the workaround for you right now is "don't put # in package filenames".

**Comment by gregneagle** [comment]
https://www.ietf.org/rfc/rfc1738.txt

```
   The character "#" is unsafe and should
   always be encoded because it is used in World Wide Web and in other
   systems to delimit a URL from a fragment/anchor identifier that might
   follow it.
```

If you really want "#" in your installer item names you may have to URL-encode that character in the `installer_item_location` in the item's pkginfo.  `foo#bar` becomes `foo%23bar`, for example.
