### ISSUE TITLE
Monterey upgrade fails on Apple Silicon due to new volume ownership requirement

### ISSUE THREAD

**Issue by miawri** [munki/munki#1114]
Upgrading to Monterey 12.0.1 using the munki startosinstall method fails with: -

Error: failed to authorize for installation. Provide a password with --stdinpass or --passprompt.
Error starting macOS install: startosinstall failed with return code 7

A volume owner's password is now needed to kick off the install as well.

Can the same mechanism that is used to get the current user's FileVault password for an AuthRestart be used here too?

Thanks

**Comment by 41john** [comment]
I'm surprised there is not more demand for this, deploying macOS updates via Munki is much better than via DEP in my experience. Would love to see this resolved if possible.

**Comment by gregneagle** [comment]
It would be nice to see this resolved. It would require someone to do work.

I have no need for the ability right now, as we have no Apple silicon Macs not running Monterey at present. I'll need the ability to upgrade from Monterey to macOS 13. So _I_ will be motivated to work on it this summer.

If someone else wants to work on it sooner, I can provide advice and direction.

I'm under the impression that some admins have had success using Graham Pugh's eraseinstall tool, which, despite the name, doesn't have to erase before it installs macOS.

**Comment by 41john** [comment]
> It would be nice to see this resolved. It would require someone to do work.
> 
> I have no need for the ability right now, as we have no Apple silicon Macs not running Monterey at present. I'll need the ability to upgrade from Monterey to macOS 13. So _I_ will be motivated to work on it this summer.
> 
> If someone else wants to work on it sooner, I can provide advice and direction.
> 
> I'm under the impression that some admins have had success using Graham Pugh's eraseinstall tool, which, despite the name, doesn't have to erase before it installs macOS.

I appreciate the followup Greg, as well as all the awesome work you in the mac admin community! I often watch Disney movies with my kids, and have a habit of watching for your name to pop up in the end credits.

I have about 60 M1 Macs currently in lab environments that need upgrading to Monterey. I don't think Graham Pugh's eraseinstall tool would help me that much as I believe it still needs user interaction. I will take a look at the project though and see if I feel comfortable adapting it to allow it to work in my environment. If I can post anything of use here I will do so.

**Comment by 41john** [comment]
I'm currently in the process of playing with my upgrade process on a test Mac running Bug Sur. I have taken Graham Pugh's eraseinstall tool with a few tiny edits to remove all the pop up messages, and instead supply in advance an admin account and password within the script.

I will likely then just create my own package for this and deploy via munki with a post install script to run the shell script as desired (including it running a tidy up to remove the script afterwards).

**Comment by gregneagle** [comment]
You might understand why that approach would not be generically acceptable. ("instead supply in advance an admin account and password within the script") If it works for you and you are comfortable with it, that's fine. But I cannot ship a solution like that to others.

**Comment by gregneagle** [comment]
See the Munki 6.0 beta, please!
