### ISSUE TITLE
Version/Naming conflict/confusion: munkitools-5.6.1.4394.pkg yields 5.5.1.4394 in about

### ISSUE THREAD

**Issue by marcalexanderschweitzer** [munki/munki#1119]
The code issues section is not a general help and troubleshooting forum.

https://github.com/munki/munki#get-help  
https://github.com/munki/munki/wiki#where-to-go-for-more-info-and-help  
https://github.com/munki/munki/wiki/Troubleshooting#still-stuck  

Please use the code issues section for reporting reproducible issues with the code or to propose/request new features.
But before you do, consider bringing up the topic for discussion on the munki-dev list: http://groups.google.com/group/munki-dev
<img width="233" alt="Screen Shot 2021-11-06 at 16 50 32" src="https://user-images.githubusercontent.com/33320175/140615755-312b43a7-54f5-4713-8609-3b394cccdcc3.png">

**Comment by gregneagle** [comment]
This is as expected. Please read the release notes.
