### ISSUE TITLE
munki-python: posix_spawn error

### ISSUE THREAD

**Issue by lfern01** [munki/munki#1122]
Hello! I'm new to munki and having some issues installing it on MacOS 11.6
- Installed the latest Version of munki (5.6.2)
- Installed the latest version of python (3.9.9)

Im currently stuck on running munkiimport --configure. I'm getting an error:
munki-python: posix_spawn: /usr/local/munki/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python: Undefined error: 0

Really appreciate the help!!! Thank you so much!

**Comment by gregneagle** [comment]
Munki ships with its own Python and be default uses that. What exactly did you do when you say you installed Python 3.9.9?

**Comment by lfern01** [comment]
thanks for getting back to me.
Initially, I installed munki without any modification to pyhon, unfortunately I get the same error after running "munkiimport". So I thought of upgrading the version of python (3.9.9) thinking it might fix the issue, but same result. :(

**Comment by gregneagle** [comment]
What happens if you type `munki-python` at a prompt?

**Comment by lfern01** [comment]
Same error:

administrator$ munki-python
munki-python: posix_spawn: /usr/local/munki/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python: Undefined error: 0

**Comment by gregneagle** [comment]
You have something installed that is blocking the execution of Munki's Python.

From MacAdmins Slack:

> Does anyone have experience of their organisation blocking the execution of Python scripts entirely? I’m finding my entire Munki system is now grinding to a halt because our antivirus (Cylance) has been set to block the execution of all Python. I’ve tried to explain my case to our security department but I wondered if anyone else has gone through a similar issue?

**Comment by gregneagle** [comment]
(and the line goes dead)

**Comment by lfern01** [comment]
Hello Greg, So sorry for the delay!! I really appreciate your help!!!
I reached out to our security team and verified that Cylance blocked python from running, we went ahead and exclude python. Sure enough, everything started working!!
You're the best!! thanks again!!!
