### ISSUE TITLE
Catch-22: Managed Software Update prevents user from quitting apps prior to attempting to install updates

### ISSUE THREAD

**Issue by amanda-mitchell** [munki/munki#1123]
# Prerequisites

* There are one or more updates pending long enough to trigger "Aggressive notifications"
* `managedsoftwareupdate` runs in the background and triggers munki-notifier to notify the user of pending updates.
* One or more applications that need to be updated are currently open

# Expected behavior

Managed Software Center provides the user a way to (gracefully!) quit the applications and install the updates.

# Actual behavior

Because Managed Software Center aggressively steals focus from the whole system, the only option is to attempt to install the updates, which will inevitably fail because the applications are open. After attempting to install the updates, focus is released so that the apps can be quit, but this is a frequent and unnecessary annoyance.

**Comment by gregneagle** [comment]
While testing something else, I was able to see this "in action". I'm not sure what should be done differently.

When _not_ in "aggressive mode", you might see something like this:
<img width="1000" alt="image" src="https://github.com/munki/munki/assets/700560/3beffcf9-3d5e-4894-a580-878085408bf6">
Chrome is open, and I click "Update". I see this:
<img width="1000" alt="image" src="https://github.com/munki/munki/assets/700560/9ce03dba-0d6c-4349-826e-e5d2802d7d0f">

I click OK, and then have to go quit Chrome to proceed.

If I'm in "Aggressive mode" the behavior after I click "Update" is _exactly the same_.

In both cases, the user has a chance to manually quit the running applications and try again.

What is your proposed change?

**Comment by gregneagle** [comment]
Is your proposed change actually not related to aggressive mode at all and more like this?
https://github.com/munki/munki/issues/1157

**Comment by gregneagle** [comment]
Closing this -- I don't see an actual problem here (perhaps I'm not understanding it), but there's no new info, so there's really nothing to act upon. Feel free to reopen if there's new info.
