### ISSUE TITLE
Dock icon notification badge says 1 update available but nothing listed

### ISSUE THREAD

**Issue by ixissupport** [munki/munki#1125]
Running on MacOS Monterey 12.0.1 - intel hardware.

The Managed Software Centre says no updates available in the UI.
The dockbar icon has 1 update notification badge stuck on it. No matter how many times I reboot.

The Managed Software Centre UI pops open every day to get in the way for no reason.

**Comment by arubdesu** [comment]
Hey @ixissupport, this is not a general support forum. Please follow the guidance on the wiki https://github.com/munki/munki/wiki#where-to-go-for-more-info-and-help

**Comment by ixissupport** [comment]
> Hey @ixissupport, this is not a general support forum. Please follow the guidance on the wiki https://github.com/munki/munki/wiki#where-to-go-for-more-info-and-help

I'm reporting a recurring bug, not requesting support.

**Comment by arubdesu** [comment]
Oh, pardon me. Have you looked at the log to confirm what 'bug' you're triggering with your configuration from your server with your packages? 😉

**Comment by ixissupport** [comment]
Just a lowly user who has no access to the server to see any logs.

**Comment by gregneagle** [comment]
I'd raise the issue to your local Munki admin.
There are local logs you may be able to access in /Library/Managed Installs/Logs/ManagedSoftwareUpdate.log*

I'm also curious about the output of `defaults read /Library/Preferences/ManagedInstalls PendingUpdateCount`
and `munki-python -c "import CoreFoundation ; print(CoreFoundation.CFPreferencesCopyAppValue('PendingUpdateCount', 'ManagedInstalls'))"`
and `munki-python -c "import CoreFoundation ; print(CoreFoundation.CFPreferencesAppValueIsForced('PendingUpdateCount', 'ManagedInstalls'))"`

**Comment by gregneagle** [comment]
I continue to suspect this is a local configuration problem. Without additional information from you there's no way to make any progress on this issue.

**Comment by ixissupport** [comment]
Munki admin didn't have a clue about the client cause.

I've updated the Managed Software Centre client and that fixed the dock notification icon and UI opening every day (is that the aggressive UI option I think I read about?).

I wrongly assumed the Managed Software Centre updating was automatic.

Managed Software Centre Version 5.5.1.4395 (4395) resolves this issue.

**Comment by gregneagle** [comment]
I wish you had provided the information I asked for. We'll leave this as a mystery. As for updating Munki/Managed Software Center, that is a task your local Munki admin should be handling for the machines he/she manages. Munki can indeed update itself.

**Comment by WarrenFaith** [comment]
Hi, I have the same issue. I get regular popup of the window and a never disappearing badge on the app icon.

I have run the commands you asked for earlier and this is the output:

> martin@mac ~ % defaults read /Library/Preferences/ManagedInstalls PendingUpdateCount
> 1
> martin@mac ~ % munki-python -c "import CoreFoundation ; print(CoreFoundation.CFPreferencesCopyAppValue('PendingUpdateCount', 'ManagedInstalls'))"
> 1
> martin@mac ~ % munki-python -c "import CoreFoundation ; print(CoreFoundation.CFPreferencesAppValueIsForced('PendingUpdateCount', 'ManagedInstalls'))"
> False

The app itself does not tell me about any software to update...

**Comment by WarrenFaith** [comment]
additional note: Seems my local admin does not really update the app, I am running Version 6.1.0.4543 (4543) here... I will ask them to update
