### ISSUE TITLE
Strange timestamp format in ManagedInstallReport.plist

### ISSUE THREAD

**Issue by kevaru** [munki/munki#1126]
I know this is not a support forum but since I was unable to reverse engineer the code that produces the timestamp in ManagedInstallReport.plist I think that this might be a bug. On some of our machines (10.15, then updated to BigSur, no change. Uninstalled/reinstalled munki tools, no change) the time format in the ManagedInstallReport.plist file after munki has run looks like this:

```
<key>Conditions</key>
	<dict>
        ...
        <key>date</key>
	<date>2030437302-06-07T24:60:-2147483648Z</date> 
        ...
```
But timestamps in Managedinstalls.plist from the same machine are as expected:

```
	<key>LastCheckDate</key>
	<date>2022-02-03T14:48:58Z</date>
```
The problem ist that this renders munkireport not operational on these machines as their scripts cannot read the ManagedInstallReport.plist file because of the date format. If this is the wrong place for this problem, I'd like to apologize. Please let me know where I should ask for help in this case.

Thanks
Kevin

**Comment by gregneagle** [comment]
Support forums are described here: https://github.com/munki/munki/wiki/Discussion-Group

Things in the conditions array can also be generated by scripts the admin (or the developers of MunkiReport) provide, so this could also be caused by non-Munki code.

https://github.com/munki/munki/blob/main/code/client/munkilib/info.py#L875-L877

**Comment by gregneagle** [comment]
I'd also like to point out that when you create a new issue, you see this:

> The code issues section is not a general help and troubleshooting forum.
> 
> https://github.com/munki/munki#get-help  
> https://github.com/munki/munki/wiki#where-to-go-for-more-info-and-help  
> https://github.com/munki/munki/wiki/Troubleshooting#still-stuck  
> 
> Please use the code issues section for reporting reproducible issues with the code or to propose/request new features.
> But before you do, consider bringing up the topic for discussion on the munki-dev list: http://groups.google.com/group/munki-dev
> 

How might it be made clearer to find the other help resources?

**Comment by kevaru** [comment]
Thank you very much for the quick reply. I noticed the messag but I thought this problem is munki code related as I do not get a consistent result on timestamps generated in files generated by munki. When I trigger a munki run via GUI Managed Software Center (same installer as on working machines) the ManagedInstallReport.plist file is replaced with a new version of the wired time stamp. That's what leads to my conclusion that munki code generates the time stamp.

Munkireport scripts do not write to ManagedInstallReport.plist. They parse it and search for information they need. The parsing fails due to the wrong time format. I can manually edit the timestamp in ManagedInstallReport.plist and then munkireport runs fine without changing anything. As soon as I do the next munki run, the Managedinstalls.plist gets overwritten with an unusable version.

Neither am I aware of any other script that would have an influence on ManagedInstallReport.plist

But I'll head over to the https://groups.google.com/g/munki-discuss then. 
Thanks again,
Kevin
