### ISSUE TITLE
postflight still using /usr/bin/python

### ISSUE THREAD

**Issue by stephanvanhienen** [munki/munki#1130]
When running managedsoftwareupdate it ends with warning :

Finishing...
    Performing postflight tasks...
WARNING: Error [Errno 2] No such file or directory: '/usr/local/munki/postflight' when attempting to run /usr/local/munki/postflight
Done.

head -n1 /usr/local/munki/postflight 
#!/usr/bin/python

Running the 5.6.3 release.

**Comment by miikkali** [comment]
I had the same error but for preflight. I tracked it down to an old version of a Munkireport module that still uses macOS system Python, which doesn't exist anymore on Monterey 12.3, so I just need to update that module. Might be worth checking if you use Munkireport.

On 31. Mar 2022, at 14:13, stephanvanhienen ***@***.******@***.***>> wrote:



When running managedsoftwareupdate it ends with warning :

Finishing...
Performing postflight tasks...
WARNING: Error [Errno 2] No such file or directory: '/usr/local/munki/postflight' when attempting to run /usr/local/munki/postflight
Done.

head -n1 /usr/local/munki/postflight
#!/usr/bin/python

Running the 5.6.3 release.

**Comment by stephanvanhienen** [comment]
Ah thnx, didn't think this would be munkireport. (which we are using)

**Comment by gregneagle** [comment]
Just for completeness: although Munki supports running a preflight and an postflight script, it does not ship with either. Any preflight or postflight script would be the responsibility of the local admin and/or other products being integrated with Munki.

**Comment by stephanvanhienen** [comment]
Yes thanks, after updating munkireports the warning is gone.

**Comment by jamie-selesti** [comment]
How did you update munkireports as I think I have the same issue
