### ISSUE TITLE
Munki fails to build when running Xcode 13.3 (PyObc 7.2)

### ISSUE THREAD

**Issue by carlashley** [munki/munki#1131]
I'm referencing https://github.com/gregneagle/relocatable-python/issues/25 as this seems to be the cause behind Munki build failing when building with Xcode 13.3 (at least on Apple Silicon, macOS 12.3.1) as an "FYI".
Bumping the `pyobjc` version requirement from `7.2` to `8.4.1` results in a successful munki build, but there's obviously no guarantee that this version of `pyobjc` will play nicely with current munki version (I'm going to be testing it for our internal build).

This is mostly an FYI for anyone else that bumps into this issue.
You can also build munki with the `pyobjc` version requirement of `7.2` using Xcode 13.2.1 (per Greg's reply to the referenced issue, and per some discussion in the munki channel in Macadmins Slack).

**Comment by gregneagle** [comment]
At some point Munki will have to be tested with newer versions of PyObjC and Python. That could be started by anyone — it doesn’t have to be me.

**Comment by gregneagle** [comment]
The Munki 5.7 Beta 1 release (git tag v5.7.0b1) and the current Munki5dev branch both build under Xcode 13.3.1 for me. PyObjC has been updated to version 8.5.  Testing the Munki tools against Python 3.10.4 and PyObjC 8.5 is a focus of the betas.
