### ISSUE TITLE
Make a Big Sur-styled icon

### ISSUE THREAD

**Issue by eivind-hovedkvarteret** [munki/munki#1132]
The Managed Software Center icon is starting to look dated, and should probably be updated to fit the Big Sur style.

If someone were to make an updated icon, would you use it?

**Comment by gregneagle** [comment]
Probably not. I’m not a fan of the Big Sur style.

**Comment by gregneagle** [comment]
There's certainly nothing stopping you from using any icon you like in your own deployment.
