### ISSUE TITLE
cliutil.py Python 3.9 namespacing bug

### ISSUE THREAD

**Issue by smaddock** [munki/munki#1134]
This issue pops up trying to use `manifestutil` with Python 3.9 on Linux.

Running `python2 /usr/local/munki/manifestutil` on Linux works as expected.
Running `python3 /usr/local/munki/manifestutil` returns:
> AttributeError: module 'plistlib' has no attribute 'readPlist'

which is [a documented change](https://docs.python.org/3.9/library/plistlib.html) in Python 3.9.

A [wrapper exists for this](https://github.com/munki/munki/blob/main/code/client/munkilib/wrappers.py#L47) which calls the correct `plistlib.loads`, and is [implemented in `get_version()`](https://github.com/munki/munki/blob/747f6e24393b15c5d4732bee63c2e6a61e1e7712/code/client/munkilib/cliutils.py#L113) however [the offending line in `pref()`](https://github.com/munki/munki/blob/747f6e24393b15c5d4732bee63c2e6a61e1e7712/code/client/munkilib/cliutils.py#L93) calls `plistlib.readPlist`, which forces it to load plistlib's function vs. the wrapper (thanks @nmcspadden !)

**Comment by gregneagle** [comment]
I believe I've addressed the issue here: https://github.com/munki/munki/commit/2d9b174ceb34e843ed46d1ff1781954ff95e9559

**Comment by gregneagle** [comment]
This change has also made it into 5.7.0b3, and will be in the final 5.7 release. I'm going to close this ticket. Please re-open if you discover any remaining issues.
