### ISSUE TITLE
Client cert crash with Munki 5.7.0b2 PyObjC 8.5 on Mojave 

### ISSUE THREAD

**Issue by rrenstrom** [munki/munki#1135]
This issue is a FYI for admins that use mTLS client certs for their Munki repo web server.

Munki 5.7.0 Beta 2 includes a new version of PyObjC, which has resurfaced this old issue #1115 of managedsoftwareupdate crashing when using a client cert on macOS Mojave 10.14.x (and perhaps earlier).

The beta runs fine on macOS Catalina and later (tested 10.15.7, 11.6.5, 12.3.1).

Last time we worked around the problem by reverting to PyObjC 7.2 in the Python framework in Munki 5.6.1. Apparently this problem still exists in the newer versions of PyObjC, and I'm not sure if we can work around it with any Munki code changes. Perhaps @np5 has some ideas since last time we looked at this?

Given that Apple no longer supports Mojave, the number of Macs affected by this issue may be small in most organizations. These could be frozen at Munki 5.6.4 until they are replaced/upgraded. Also in my limited testing, you can run Munki 5.7.0 with the earlier Python framework, so that may be another option for these cases (install Munki 5.7 without the newer Python framework component package).

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G9323

$ sudo managedsoftwareupdate -vvv
		...
		URLSession_task_didReceiveChallenge_completionHandler_
		Authentication challenge for Host: ... Realm: None AuthMethod: NSURLAuthenticationMethodServerTrust
		Allowing OS to handle authentication request
		URLSession_task_didReceiveChallenge_completionHandler_
		Authentication challenge for Host: ... Realm: None AuthMethod: NSURLAuthenticationMethodClientCertificate
		Client certificate required
		Accepted certificate-issuing authority: Common Name: ...
		Found matching identity
		Will attempt to authenticate
/usr/local/munki/munkilib/gurl.py:721: UninitializedDeallocWarning: leaking an uninitialized object of type NSURLCredential
	credential = NSURLCredential.alloc().initWithIdentity_certificates_persistence_(
2022-05-05 12:31:26.616 Python[19856:17909329] *** Terminating app due to uncaught exception 'OC_PythonException', reason: '<class 'ValueError'>: depythonifying 'pointer', got 'SecIdentityRef''
*** First throw call stack: 
(
	0   CoreFoundation                      0x00007fff4acd3035 __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff7553ba17 objc_exception_throw + 48
	2   _objc.cpython-310-darwin.so         0x00000001097a91fa PyObjCErr_ToObjCWithGILState + 90
	3   _objc.cpython-310-darwin.so         0x000000010978a890 method_stub + 6768
	4   libffi.dylib                        0x00007fff748b39ea ffi_closure_unix64_inner + 485
	5   libffi.dylib                        0x00007fff748b30ee ffi_closure_unix64 + 70
	6   Foundation                          0x00007fff4cebf954 -[NSBlockOperation main] + 68
	7   Foundation                          0x00007fff4ce9557d -[__NSOperationInternal _start:] + 685
	8   Foundation                          0x00007fff4cebf687 __NSOQSchedule_f + 227
	9   libdispatch.dylib                   0x00007fff76cbd5f8 _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x00007fff76cbe63d _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x00007fff76cc0de6 _dispatch_continuation_pop + 414
	12  libdispatch.dylib                   0x00007fff76cc04a3 _dispatch_async_redirect_invoke + 703
	13  libdispatch.dylib                   0x00007fff76ccc3bc _dispatch_root_queue_drain + 324
	14  libdispatch.dylib                   0x00007fff76cccb46 _dispatch_worker_thread2 + 90
	15  libsystem_pthread.dylib             0x00007fff76efe6b3 _pthread_wqthread + 583
	16  libsystem_pthread.dylib             0x00007fff76efe3fd start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
```

**Comment by gregneagle** [comment]
I think this time around I am unlikely to revert to PyObjC to 7.2 since you can't build that into the Python.framework with Xcode 11.3 or later (at least not without patching the source).

**Comment by gregneagle** [comment]
Have you tried (again) removing the "patch" as described here? 

> @np5 if the patch lines in gurl.py are no longer necessary (starting at line 76, # patch the credentialWithIdentity:certificates:persistence: signature), since that was addressed in PyObjC 7.3 issue 320, perhaps we should remove them (if it avoids this problem and potential future problems)?

**Comment by rrenstrom** [comment]
Still crashes with the "patch" lines removed in gurl.py

For the few 10.14 Macs in my fleet, I'm fine with leaving these at the older version of Munki 5.6.4, as a work-around, since these will be replaced soon.

To accomplish this, one can set 10.15 as the minimum_os_version in the pkginfo for the new munkitools 5.7 and later packages, so it doesn't deploy to macOS 10.14 and earlier. Or perhaps just set this in the munkitools_python pkginfo (from AutoPkg), to deploy 5.7 without the newer Python framework package.

**Comment by gregneagle** [comment]
can you please try this:
In gurl.py, line 721, replace
```python
credential = NSURLCredential.alloc().initWithIdentity_certificates_persistence_(
```
with
```python
credential = NSURLCredential.credentialWithIdentity_certificates_persistence_(
```

**Comment by gregneagle** [comment]
Next thing to try -- leave the previous change in place, then in gurl.py, lines 83-85:
Change:
```python
objc.registerMetaDataForSelector(
    b'NSURLCredential',
    b'credentialWithIdentity:certificates:persistence:',
    {'arguments': {
       2: {'null_accepted': False, 'type': b'@'},
       3: {'_template': True, 'type': b'@'},
       4: {'_template': True, 'type': b'Q'},
     },
     'classmethod': True,
     'hidden': False,
     'retval': {'_template': True, 'type': b"@"}}
)
```
to
```python
objc.registerMetaDataForSelector(
    b'NSURLCredential',
    b'credentialWithIdentity:certificates:persistence:',
    {'arguments': {
       2: {'null_accepted': False, 'type': b'@'},
     },
     'classmethod': True,
     'hidden': False,
     'retval': {'_template': True, 'type': b"@"}}
)
```

**Comment by gregneagle** [comment]
(note I made an edit to the above comment -- the "after" code is different)

**Comment by rrenstrom** [comment]
That patch worked!  Looks like you've solved it :-)  No longer crashing on macOS 10.14.6

I'll test on other macOS versions.

**Comment by gregneagle** [comment]
That's good news. Please test on 10.15, 11, and 12 if possible. And I'd like a copy of your gurl.py that you edited to make sure your changes are the same ones I think they are :-)

**Comment by gregneagle** [comment]
Credit entirely to @pudquick (AKA frogor) who seems to love digging into PyObjC issues...

**Comment by rrenstrom** [comment]
Here's the patched gurl.py

https://gist.github.com/rrenstrom/c1b7598a1f091efdfd7c0bd6c758b1bf

**Comment by rrenstrom** [comment]
tested on 10.15.7, 11.6.5.  I'll test Monterey later.

**Comment by gregneagle** [comment]
https://github.com/munki/munki/releases/tag/v5.7.0b3
