### ISSUE TITLE
Percentage progress should show in log during softwareupdate call

### ISSUE THREAD

**Issue by mtconleyuk** [munki/munki#1137]
If I execute softwareupdate from the command line (Monterey 12.3.1) and a download is required, a percentage progress is shown. This information does not appear in the ManagedSoftwareUpdate.log file when Munki calls softwareupdate. It would be helpful if it could do so — at least every 10% or so — to indicate that something is, in fact, happening.

**Comment by gregneagle** [comment]
_oh_: you mean Munki calling /usr/sbin/softwareupdate

Munki does show download percentage for that when it can parse that info out of /usr/sbin/softwareupdate output:

https://github.com/munki/munki/blob/main/code/client/munkilib/appleupdates/su_tool.py#L324-L333

I find that, especially recently, softwareupdate output has changed and Munki doesn't always parse that out.

If you have a concrete change to improve this, I'd be happy to test and implement it.

Given the general direction of softwareupdate support in Munki, I'm personally not motivated to spend a lot of time on this. (On Apple silicon, Munki neither attempts to download or install Apple software updates.)

**Comment by mtconleyuk** [comment]
Okay. If I get some spare time, I may take a look at it and see what would have to change, but that seems unlikely. Thanks for the feedback.
