### ISSUE TITLE
Issue updating software from Managed Software Centre App

### ISSUE THREAD

**Issue by renantea** [munki/munki#1147]
Cannot update packages/apps using Managed Software Centre application on MacOS Ventura Beta. It says "There is a configuration problem with the managed software installer. The process ended unexpectedly. Contact your systems administrator."

Workaround: updating apps from the command line works fine.

<img width="1289" alt="Screenshot 2022-07-07 at 12 24 35 PM" src="https://user-images.githubusercontent.com/2317737/177742052-94b5c4c2-a8fe-4104-b7c4-24fd82118851.png">

Platform: MacOS Ventura (V 13 Beta 22A5266r)
Mac: MacBook Air Intel (2018)
Managed Software Centre app version: 5.7.2.4439 (4439)

**Comment by gregneagle** [comment]
Not enough here to repro; I and others have been using Munki on Ventura betas with (largely) success. Please also re-test with the current Ventura beta.
