### ISSUE TITLE
Update Check Failed

### ISSUE THREAD

**Issue by jamie-selesti** [munki/munki#1148]
I'm pushing to install Managed Software Centre onto a Mac which has 12.4 (Monterey) 

I do that by running

```
curl https://munkibuilds.org/latest3.sh | sh
defaults write /Library/Preferences/ManagedInstalls SoftwareRepoURL "http://[mydomain]:8080/munki_repo"
defaults write /Library/Preferences/ManagedInstalls ClientIdentifier "Digital Marketing"
defaults write /Library/Preferences/ManagedInstalls InstallAppleSoftwareUpdates "true"
defaults write /Library/Preferences/ManagedInstalls SuppressUserNotification "true"
defaults write /Library/Preferences/ManagedInstalls FollowHTTPRedirects "all"
defaults write /Library/Preferences/ManagedInstalls InstallRequiresLogout "true"
defaults write /Library/Preferences/ManagedInstalls UnattendedAppleUpdates "true"

/bin/bash -c "$(curl -s --max-time 10 http://[mydomain]:8080/public/index.php?/install)"
defaults write /Library/Preferences/MunkiReport ReportItems -dict-add ard_model "/Library/Preferences/com.apple.RemoteDesktop.plist"
```

Managed Software Centre installs but when running it states Update Check Failed.

When running /usr/local/munki/managedsoftwareupdate it states

`/usr/local/munki/managedsoftwareupdate: bad interpreter: /usr/bin/python: no such file or directory
`

I have checked /usr/bin/ and it's correct there isn't a python file but there is a python3 file

AutoPKG 2.4.1
GIT 2.32.1
Munki admin 1.7.1

Everything works if I push to mac with OS 11.x it just stops working if I push to mac OS 12.x 

Any ideas?

**Comment by flammable** [comment]
It looks like you're installing an old, unofficial build of Munki from 2019. Try a [more recent, official version](https://github.com/munki/munki/releases) instead.

The error you're seeing seems to be related to the removal of Python 2 in macOS 12.3, so installing a newer version should revolve the issue you're seeing.

**Comment by gregneagle** [comment]
Nothing on https://munkibuilds.org is officially supported. Follow @flammable's advice.
