### ISSUE TITLE
Beta 6.0b1:  MSC progress bar present but no active progress during OS .app copy

### ISSUE THREAD

**Issue by poundbangbash** [munki/munki#1158]
In testing the `stage_os_install` option and I noticed when the OS Install.app is being copied to /Applications from the DMG there is a progress bar shown in MSC, but there is no progress being shown in the bar.  Activity monitor is showing 100s of MB/s being copied, but no indication in MSC of how long that should take.  After the copy finished the progress bar showed progress during the next phase of the task.

**Comment by gregneagle** [comment]
This is not easily addressable. `ditto` only gives us file-by-file progress info (not bytes/kbytes copied). The majority of the copy time is copying one single large file -- the SharedSupport.dmg.

Ideally, you make the item as unattended_install = True and the copy to /Applications happens in the background and the users don't have to worried about it.

**Comment by gregneagle** [comment]
BTW, this is the exact code that runs when Munki copies any items from a disk image. For years there was no real progress reporting at all -- just an indeterminate progress bar. The current implementation is still widely inaccurate, but the best we can do with the tools we have.

**Comment by gregneagle** [comment]
Closing as there's really nothing we can do about this.
