### ISSUE TITLE
Set `uninstallable` to True when using the `--uninstall_method` flag with the `--nopkg` flag

### ISSUE THREAD

**Issue by n8felton** [munki/munki#1160]
When using `makepkginfo` with the `--uninstall_method` flag and the `--nopkg` flag, it would be nice if the `uninstallable` key was set to true. 

This behavior can be seen when using the `--uninstall_method=uninstall_script` flag with a package, e.g.
```
% makepkginfo --uninstall_method=uninstall_script /Users/n8felton/Downloads/Nudge-1.1.9.81436.pkg
[snip]
	<key>uninstall_method</key>
	<string>uninstall_script</string>
	<key>uninstallable</key>
	<true/>
[/snip]
```

But when using `--uninstall_method=uninstall_script` with the `--nopkg` flag, the `uninstallable` key is not set
```
% makepkginfo --uninstall_method=uninstall_script --nopkg 
[snip]
	<key>uninstall_method</key>
	<string>uninstall_script</string>
[snip]
```

**Comment by gregneagle** [comment]
Looks the same as #950

**Comment by gregneagle** [comment]
Fixed here: https://github.com/munki/munki/commit/3b6aa2173da882d822ec5513db28305a3470d841
