### ISSUE TITLE
Minor Upgrade from 12.6.0 to 12.6.1 possible with Munki 6?

### ISSUE THREAD

**Issue by dannykorpan** [munki/munki#1164]
Hi,

according to the [wiki](https://github.com/munki/munki/wiki/Staging-macOS-Installers), it's not possible to run minor macOS upgrades with stage_os_installer introduced with Munki 6.
```This feature allows you to use Munki to assist with an upgrade from one "major" macOS release to a newer one. It is not supported for doing "minor" updates.```

Does that mean, that's not possible to use the new stage_os_installer to upgrade from macOS 12.6.0 to 12.6.1 or what does minor exactly means?

Thanks for your support and kind regards,
Danny

**Comment by gregneagle** [comment]
This really is a support Q and should be asked in the munki-discuss Google Group, as indicated when a new issue is opened here.

Short answer: it's not possible to use the new stage_os_installer to upgrade from macOS 12.6.0 to 12.6.1. This is Software Update's job to handle.
