### ISSUE TITLE
Munki distributed using Intune

### ISSUE THREAD

**Issue by hefty2212** [munki/munki#1168]
We are trying to use Intune to install Munki on our Macs.  It always fails with the following error:
Error code: 0x87D13BA2 One or more apps contain invalid bundleIDs.
We are using the following bundles:
org.python.python  3.10.4
com.googlecode.munki.ManagedSoftwareCenter    6.1.0.4528

Any help would be great

**Comment by gregneagle** [comment]
Please ask in the munki-discuss mailing list/Google Group.  http://groups.google.com/group/munki-discuss
