### ISSUE TITLE
Munki manifest pointing to download on CDN?

### ISSUE THREAD

**Issue by kai-h** [munki/munki#1169]
Is it possible to have Munki refer to a manifest on a privately hosted server, and in the pkginfo the link to the installer item to download the file from a CDN?

e.g. say I import Microsoft Office into my Munki server, but I'm distributing it to client workstations over the internet. Can I have the pkginfo point to the specific download on Microsoft's CDN instead of having to host it myself?

**Comment by gregneagle** [comment]
This is a better question for the munki-discuss Google Group/mailing list. GitHub issues are for reporting reproducible issues with the code.
