### ISSUE TITLE
6.3 beta crashes on macOS Mojave

### ISSUE THREAD

**Issue by rrenstrom** [munki/munki#1171]
Munki 6.3 beta 2 isn't working on a Mojave client, the managedsoftwareupate (munkishim) binary is crashing

```
sudo managedsoftwareupdate
dyld: Symbol not found: _OBJC_CLASS_$_NSConstantArray
		Referenced from: /usr/local/munki/managedsoftwareupdate (which was built for Mac OS X 11.0)
		Expected in: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
	in /usr/local/munki/managedsoftwareupdate
Abort trap: 6

```

Works if managedsoftwareupate.py is run directly instead of through shim

```
sudo /usr/local/munki/munki-python /usr/local/munki/.managedsoftwareupdate.py --version
6.3.0.4556
```

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G9323

**Comment by gregneagle** [comment]
Could you try this, replacing the managedsoftwareupate (munkishim) binary?
[managedsoftwareupdate.zip](https://github.com/munki/munki/files/11043796/managedsoftwareupdate.zip)

**Comment by gregneagle** [comment]
Here: [managedsoftwareupdate.zip](https://github.com/munki/munki/files/11044985/managedsoftwareupdate.zip)
