### ISSUE TITLE
Autoremove packages are removed unnecessarily before update

### ISSUE THREAD

**Issue by VitosX** [munki/munki#1172]
If a package (install.pkg) has `autoremove` key set to `true` in its' pkginfo file, and a newer version of this package is available for installation on a client, managedsoftwareupdate performs removal of the old package before installing the new one. It has no point.
Affects v6.2.1.4545.

**Comment by gregneagle** [comment]
Can you provide steps to reproduce this behavior?

**Comment by VitosX** [comment]
Sure.

1. Prepare two versions of some package. For example let's download _autopkg-2.7.1.pkg_ and _autopkg-2.7.2.pkg_ from [https://github.com/autopkg/autopkg/releases](https://github.com/autopkg/autopkg/releases).
2. Import _autopkg-2.7.1_ into repository using `munkiimport` 6.2.1.4545, all defaults (name: autopkg, catalog: testing)
3. Add _autopkg_ to _managed_installs_ in the test client manifest. Run `makecatalogs`.
4. Run `managedsoftwareupdate` on the test client and install autopkg.
5. Import _autopkg-2.7.2_ into repository. Add **autoremove** key and set it to true. Run `makecatalogs`.
6. Run `managedsoftwareupdate` on a test client.

The result:
```
Managed Software Update Tool
Copyright 2010-2023 The Munki Project
https://github.com/munki/munki

Starting...
Checking for available updates...
    Preventing idle sleep
    Downloading autopkg-2.7.2.pkg...
	0..20..40..60..80..100
    Verifying package integrity...
    Getting client resources...
    Allowing idle sleep

    The following items will be installed or upgraded:
        + autopkg-2.7.2
    The following items will be removed:
        - autopkg

Run managedsoftwareupdate --installonly to install the downloaded updates.
Finishing...
    Performing postflight tasks...
Done.
```

And `managedsoftwareupdate --installonly`
```
Managed Software Update Tool
Copyright 2010-2023 The Munki Project
https://github.com/munki/munki

Starting...
    Preventing idle sleep
Removing autopkg (1 of 1)...
    Gathering information on installed packages...
	0..20..40..60..80..100
	0..20..40..60..80..100
    Determining which filesystem items to remove...
    Removing 7268 filesystem items...
	0..20..40..60..80..100
    Removing receipt info...
	0..20..40..60..80..100
    Package removal complete.
Installing autopkg (1 of 1)...
   [ ... ]
    100.0 percent complete...
    The software was successfully installed.
    Allowing idle sleep
Finishing...
    Performing postflight tasks...
Done.

```

**Comment by gregneagle** [comment]
Can you explain what you are attempting to use `autoremove` for? It seems like you have a use-case scenario I'm not understanding.

**Comment by gregneagle** [comment]
I believe I've addressed the issue in the title here: https://github.com/munki/munki/commit/fafca468caada612df29005729a392f9c049f9ad.

This issue: https://github.com/munki/munki/issues/1172#issuecomment-1491697730 is related,  but separate.

**Comment by VitosX** [comment]
Thank you.

As for autoremove on an optional install... I guess it was just accidental discovery during troubleshooting this issue, as I clearly don't have a need for such scenario. I use autoremove for keeping tabs on licensed software (exactly as suggested) and for internal media sets / templates for Final Cut Pro video editing app, which can occupy a lot of disk space and should not be present on a workstation if not explicitly required in managed_installs.

So my main issue was with this unnecessary uninstall-before-update operation, when I uploaded a new version of some package marked with autoremove, which was not present before.

**Comment by gregneagle** [comment]
You can test my fix by copying the updated `munkilib/updatecheck/analyze.py` to `/usr/local/munki/munkilib/updatecheck/analyze.py on a test machine. Assuming it's OK, it will end up in a post 6.3.0 release.
