### ISSUE TITLE
Build numbering changed, or digit missing in latest release?

### ISSUE THREAD

**Issue by xndr** [munki/munki#1181]
Hi,
I noticed the latest release's build number was set to 482, when previously it had been in the 45xx range. Was this intentional or a typo?

Thanks

**Comment by natewalck** [comment]
The receipts look correct in the package itself and the package name looks right in the release page. Where do you see the build number as 482? 

<img width="427" alt="Screenshot 2023-07-06 at 20 33 15" src="https://github.com/munki/munki/assets/867868/77aeede0-7f17-4de4-9019-fd1ff487ece6">

**Comment by arubdesu** [comment]
I'm assuming this is the carry over from googlecode/svn's incrementing, but... dunno how it would break

**Comment by xndr** [comment]
In munki/code/tools/make_munki_mpkg.sh, MAGICNUMBER=482, and it used to match the build number before?

**Comment by natewalck** [comment]
That number never matched the build number since this moved to git. Check the git history for the history on that file specifically. 

It's the offset from when we switched from SVN to git so the build numbers in git would be at the correct number.

**Comment by xndr** [comment]
In the source tarball release for 6.3.1, MAGICNUMBER=4581, and in the source tarball for 6.3.2, MAGICNUMBER=482.
When I run make_munki_mpkg.sh for in both these releases, it gives me the file names munkitools-6.3.1.4581.pkg and munkitools-6.3.2.482.pkg

Ultimately, I suppose it doesn't really matter. I just thought it might have been a typo so I thought I'd raise the issue.

**Comment by gregneagle** [comment]
Are you doing a shallow git clone or no git clone and just downloading the zip file? In either case the "calculated" build number will be wrong.

https://github.com/munki/munki/wiki/Building-Munki-packages#procedure

Since you mention "In the source tarball release for 6.3.1" I'm guessing you aren't using a full git clone. Thus your odd/wrong build number.

**Comment by gregneagle** [comment]
No reposes, but I think my guess is right, so closing this.
