### ISSUE TITLE
Minor MSC UI issue - Removing app progress

### ISSUE THREAD

**Issue by poundbangbash** [munki/munki#1189]
Munki 6.3.3 installed
MSC 6.2.0.4576

Optional install of something that is a D&D install like Mozilla Firefox shows up in the My Items section with the opiton to Remove.
Clicking Remove and leaving the UI in the My Items sections shows progress of Removing with a progress spoke. 
Even after the logs show that the uninstall run is complete, and the application is removed from disk, the progress of Removing with the spoke spinning remains.

Steps to reproduce:
1) Using MSC, install a "copy from disk image" style app like Firefox.
2) Navigate to the My Items section in MSC
3) Click Remove button and let it process

Expected results:
The application would be deleted and the UI would refresh to indicate that item is no longer installed by disappearing from My Items.

Actual results:
The process of "Removing" with progress spokes remains even after the application has been uninstalled and the logs indicate the munki run is complete.  Navigating away from My Items and back does clear the item from the My Items UI.

![image](https://github.com/munki/munki/assets/1416288/5a910e70-0bbd-429a-ae94-bd73f4730579)

**Comment by gregneagle** [comment]
Does this happen _only_ in the My Items view? For example, does it happen in the Software view?

**Comment by gregneagle** [comment]
Answering my own Q, no, it does not happen in the Software view.

**Comment by gregneagle** [comment]
As auto-linked above, this issue is addressed here: https://github.com/munki/munki/commit/e92d5381096bba120fb1c6e65cfe378341c60b58

**Comment by gregneagle** [comment]
(Just for completeness, a similar and related issue occurred if you selected an item for install (from the Software view, for example) and then switched to the My Items view. The item would show as being downloaded and installed, but the "Installing" message and spinning gear would remain even after the item was installed: 
<img width="366" alt="image" src="https://github.com/munki/munki/assets/700560/de4c995d-fc0a-4311-bf4c-9f9f05965c72">

The change above addresses this issue as well.
