### ISSUE TITLE
Option to check for items to install only, 'dry run'

### ISSUE THREAD

**Issue by Melvin-P-NL** [munki/munki#1190]
It would be helpful for me if there was an option to only check for items that need to be installed, for the `managedsoftwareupdate` tool. I mean something like a dry run. Option `--checkonly` sounds like that, but it also downloads the needed packages and just skips installing them.

From a script that shows enrollment/deployment status to users, I would like to control a progress bar when performing a Munki background run. To make the status bar progressive for both downloads and installs, I need to know the number of items that need to be installed, before the actual run starts.

I currently read `/Library/Managed Installs/Logs/ManagedSoftwareUpdate.log` for lines starting with `Need to install`, to count the number of items. This technically works, but doesn't work out properly because it states this for each item and then already downloads it. So the number of items grows when downloading them.

Alternatively, I'm thinking about reading the local `manifest` folder. Could be a way to manage this, but it gives other difficulties, like conditions or overlapping items in included manifests.

**Comment by gregneagle** [comment]
managedsoftwareupdate checks for items that need to be installed or updated and downloads them as it goes. Items can have update_for items; if the primary item wasn't downloaded successfully, Munki won't bother trying to download the associated update_for items.
IOW, redesigning the check sequence to work without downloads would be a bit of work, and useful for very few things. I have no plans to do this work.

If what you want/need is something to display status while managedsoftwareupdate is doing its thing, you could just launch the MunkiStatus app, or use DEPNotify: https://gitlab.com/Mactroll/DEPNotify#-munki , or you could write something that receives the NSDistributedNotifications that managedsoftwareupdate posts: https://github.com/munki/munki/blob/main/code/client/munkilib/munkistatus.py and https://github.com/munki/munki/blob/main/code/apps/MunkiStatus/MunkiStatus/MunkiStatusViewController.swift#L158
