### ISSUE TITLE
Application failing to install 

### ISSUE THREAD

**Issue by siddhantmishra1305** [munki/munki#1202]
I see following error logged in install.log while trying to install a package via munki :

```
2024-01-24 14:44:54-05 MacBook-Pro shove[12079]: Error relinking file (primary): /Library/InstallerSandboxes/.PKInstallSandboxManager/30C4A3A1-D353-4DC2-9E0D-7D144233A02E.activeSandbox/Root/Library/Preferences/Logging/Subsystems/com.proofpoint.ecd.plist to /Library/Preferences/Logging/Subsystems/com.proofpoint.ecd.plist, error = 1
    srcPath = /Library/InstallerSandboxes/.PKInstallSandboxManager/30C4A3A1-D353-4DC2-9E0D-7D144233A02E.activeSandbox/Root/Library/Preferences/Logging/Subsystems/com.proofpoint.ecd.plist  
```

```
2024-01-24 14:53:13-05 MacBook-Pro installd[499]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=120 "An unexpected error occurred while moving files to the final destination." UserInfo={NSLocalizedDescription=An unexpected error occurred while moving files to the final destination., arguments=(
        "-f",
        "-s",
        "/Library/InstallerSandboxes/.PKInstallSandboxManager/97A37314-1EDF-4A75-B246-9194EE66689B.activeSandbox/Root",
        "/"
    ), NSUnderlyingError=0x137812af0 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}} {
        NSLocalizedDescription = "An unexpected error occurred while moving files to the final destination.";
        NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=1 \"Operation not permitted\"";
        arguments =     (
            "-f",
            "-s",
            "/Library/InstallerSandboxes/.PKInstallSandboxManager/97A37314-1EDF-4A75-B246-9194EE66689B.activeSandbox/Root",
            "/"
        );
    } 
```
[
![Munki - manual run for DelineaManagementAgent (1)](https://github.com/munki/munki/assets/47058179/e7259420-b6c6-4cdb-a9e5-264e15cb6c28)
](url)

Same package gets installed successfully using below command:
`sudo /usr/sbin/installer -verboseR -pkg <file> -target /`

I am seeing this issue in every 2 out of 10 devices which includes mostly Arm devices  and different OS versions(Monterey, Sonoma).

Any idea what could be wrong here ?

**Comment by arubdesu** [comment]
Hey there, please don't post support questions as an issue, you're encouraged instead to post a question to [munki-discuss](https://groups.google.com/group/munki-discuss), or use the resources mentioned in the README and elsewhere in the wiki. That being said you may have an issue relating to allowing permissions for munki that became more prevalent as of macOS Ventura, as described [here](https://groups.google.com/g/munki-dev/c/hFy4y4g4okc/m/g-geEBooBAAJ)
But you're also only seeing this intermittently, which means you should compare the working and non-working conditions (assuming it's reproducible) and try to find commonalities. You can also come discuss the issue in [MacAdmins Slack](https://macadmins.org).
