### ISSUE TITLE
TLS Certificat für https://munkibuilds.org/ is not correct

### ISSUE THREAD

**Issue by Chris53897** [munki/munki#1206]
There is a SSL_ERROR_BAD_CERT_DOMAIN for https://munkibuilds.org/

Certificat says something about `medicolegalsociety.sg`.

**Comment by arubdesu** [comment]
Pardon, where are you seeing references to munkibuilds.org?

**Comment by gregneagle** [comment]
That page is terribly out of date, and references to munkibuilds.org need to be removed.

**Comment by gregneagle** [comment]
OK, page updated, and among other updates, reference to munkibuilds.org removed.

**Comment by Chris53897** [comment]
thanks @gregneagle
