### ISSUE TITLE
When importing bundle packages in macOS 14.4 RestartAction is set incorrectly

### ISSUE THREAD

**Issue by vmiller** [munki/munki#1208]
macOS 14.4 has added a deprecation warning when installing bundle packages.  Adobe admin console packages are an example of this.

When using munkiimport to import a package like this on a macOS 14.4 system the RestartAction key gets set to the text of the deprecation warning : 

```
<key>RestartAction</key>
<string>installer: [DEPRECATION WARNING] -- Legacy Installer Package
installer: This package will be incompatible with a future version of macOS. Contact the developer for support.
None</string>
```

I've reproduced this with munki 6.4.2.4634 and 6.5.0.4652

**Comment by vmiller** [comment]
```
vaughn@test-air Build % installer -query 'RestartAction' -pkg InDesignCC_Install.pkg
installer: [DEPRECATION WARNING] -- Legacy Installer Package
installer: This package will be incompatible with a future version of macOS. Contact the developer for support.
None
vaughn@test-air Build % 
```

**Comment by gregneagle** [comment]
Addressed here: https://github.com/munki/munki/commit/29fd72a80cf7f40f41b250fd64191597e4e3d949
Thank you, Apple devs, for not using STDERR for your new deprecation warning.

**Comment by gregneagle** [comment]
Munki 6.5 has been released and includes the fix for this.
