### ISSUE TITLE
Feature Request - preference for controlling MSC Status.app window blur when in login window

### ISSUE THREAD

**Issue by MiqViq** [munki/munki#1225]
I would prefer that admin could choose if the MSC Status is blurring the view when it appears over login window.
I am using another utility view over login window which loses it's usefulness when MunkiStatus blurs the view.

There  should be a preference in ManagedInstalls.plist to control it.
Preference key could be something like DoNotBlurAtLoginWindow -bool true

**Comment by gregneagle** [comment]
Previously Munki displayed translucent windows with reduced alpha behind the status window. Did these not interfere with your other "utility view"? I'm not that interested in Yet Another Preference, though if someone else did the work I might be persuaded. I think it might be better to just figure out the issue (if it didn't occur with the translucent windows) and fix it. I suspect this has more to do with window _levels_, and the new blur windows are being displayed at a higher level. This could almost certainly be changed.

**Comment by gregneagle** [comment]
Was hoping you might provide additional information about this other "utility view" so we could see if the issue was reproducible and addressable without adding Yet Another Preference that might trigger other issues (if the blurred background windows don't exist, there's nothing stopping a user from just logging in in the middle of a Munki update at the loginwindow)

**Comment by gregneagle** [comment]
Changes here: https://github.com/munki/munki/commit/f0efc69780be1d732168c9ec12b55763013ac079 cause the window levels of the backdrop (blur), status, and log windows to be the same levels they were before the switch from reduced alpha to blur. If your other "utility view" was not affected before the switch to blurring, it should not be after this change.

**Comment by gregneagle** [comment]
Still waiting for feedback here.

**Comment by gregneagle** [comment]
Closing due to lack of feedback. Please reopen if needed.

**Comment by MiqViq** [comment]
Hi Greg,

Here is an attached image of the last Munki version that has the preferred behaviour:
<img width="1563" height="1365" alt="Image" src="https://github.com/user-attachments/assets/f7f38b63-1c36-404a-bbb6-eea516569881" />

There is a blocking, mostly transparent overlay but you can still see what is in the background, like that utility window (of my own code) that we would like to be seen when MSC runs at loginwindow.
Later versions of Munki are using overlay so blurred that there is no visibility under that.

So, if there was a preference to like select the blur amount of that overlay when at loginwindow, it may be easiest to code?

-MiqViq

**Comment by gregneagle** [comment]
Thank you for the additional detail.

How _often_ is MunkiStatus installing things at the loginwindow, and how often is it important to be able to read that information _while_ Munki is actively installing updates?
