### ISSUE TITLE
MunkiTools Cannot be updated

### ISSUE THREAD

**Issue by deXx84** [munki/munki#1226]
Hi, 
I can't update the Munkitools?
The MAC server I am using is up to date.
The only strange thing is that the update function was already working before.
![grafik](https://github.com/user-attachments/assets/fb3d5949-1fea-4840-9cd4-d6ac8df1f50b)

**Comment by arubdesu** [comment]
Your screenshot is of [Autopkgr](https://github.com/lindegroup/autopkgr/wiki), which is not related to the munki project, would you mind looking to see if the help you need is available from that project? This is a bug tracker for issues with munkitools from a development perspective, you can also look at the resources in the ReadMe.md https://github.com/munki/munki#get-help
