### ISSUE TITLE
Aggressive Notification while in fullscreen prevents interaction

### ISSUE THREAD

**Issue by BrandonNolet** [munki/munki#1229]
This is not a duplicate of #1123 nor is it a dupe of #1108

Problem: When the Munki application is already running in any fashion, and the screen that it's on is in full-screen application mode with another application, the desktop does not change to the one that contains Munki. This prevents the user from interacting with anything, even changing desktops to focus on the Munki app. 

Expected behaviour: Munki forces a desktop change to focus on the Munki application.

Steps to reproduce:
1. Install an old version of one of your managed apps.
2. Run Munki and make sure that it sees that there's an out of date app.
3. `sudo chown <username> /Library/Managed\ Installs/UpdateNotificationTracking.plist`
4. In the file in step 3, modify the managed_installs key corresponding your app to have the date set to a month behind the current date, then save. 
5. Run `sudo defaults delete /Library/Preferences/ManagedInstalls LastNotifiedDate`
6. Make sure Munki is still open.
7. On the same screen that has Munki open, open your terminal in full screen.
8. Run `sudo managedsoftwareupdate -a`
9. Observe that without closing your terminal, you cannot access Munki to dismiss the aggressive notification

Running macOS 14.7 and Munki 6.6.2.4699 according to `sudo managedsoftwareupdate -v`.

**Comment by gregneagle** [comment]
Thank you: reproduced.
Does the issue occur if Managed Software Center is not open? If not, this suggests a clunky workaround would be to quit and relaunch MSC.app when notifying. The downside here is that's pretty awful looking if Managed Software Center is currently the frontmost app where the user might be currently interacting with it.

**Comment by gregneagle** [comment]
Tested and the issue doesn't occur if MSC.app is not open. munki-notifier/MSC.app doesn't do anything special to switch back to the space that contains MSC.app; macOS does that automatically. I guess we need to investigate if there's some Spaces API to ensure we're on the right space.

**Comment by BrandonNolet** [comment]
No I can confirm the issue does not occur when the MSC.app is not open. 

A workaround could be to have it kill the MSC.app whenever it's about to pop up an aggressive notification. Unless there's something that connects the running of the MSC.app and in-progress installations of managed software?

**Comment by gregneagle** [comment]
Looks like we have a fix here: https://github.com/munki/munki/pull/1230

**Comment by BrandonNolet** [comment]
Fantastic! I'll see if I can compile and test

**Comment by BrandonNolet** [comment]
What kind of ETA should I expect for a new release?

**Comment by gregneagle** [comment]
I'm hoping I'll be able to do a release this week.

**Comment by gregneagle** [comment]
https://github.com/munki/munki/releases/tag/v6.6.3
