### ISSUE TITLE
Update Munki Tools doesnt working

### ISSUE THREAD

**Issue by deXx84** [munki/munki#1233]
Hello Community,
I have the following problem: munki tools cannot be updated, not even after a new installation.
I even tried to get the update via the terminal, but unfortunately it didn't work that way either.

The Program downloads something, but then the error appears 
"Couldn't communicate with a helper application"

![grafik](https://github.com/user-attachments/assets/9aa762a8-18c6-484a-9c15-4fc4ca73b4ca)
![grafik](https://github.com/user-attachments/assets/b59944b8-95be-4321-a659-1420d4ff2972)

The account I use is the local admin account

**Comment by gregneagle** [comment]
Your screenshot appears to be of Autopkgr, a tool that is not developed or supported by the Munki developers.

You should look for similar issues here: https://github.com/lindegroup/autopkgr/issues?q=is%3Aissue

If you don't find a similar issue and/or solution, create an issue _there_.
