### ISSUE TITLE
When removing items, update_for items that apply to more than one installed item can be erroneously removed

### ISSUE THREAD

**Issue by natewalck** [munki/munki#253]
_From [gregnea...@mac.com](https://code.google.com/u/108281479280137864473/) on July 01, 2013 09:24:25_

What steps will reproduce the problem? 1. Mark "baz" as an update for "foo" and "bar".
2. Install  "foo" and "bar" on a machine.
3. Remove "bar" from the machine. What is the expected output? What do you see instead? Expected: "baz" is left alone, as it is an update_for "foo", which remains installed.
Instead: "baz" is removed. Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/munki/issues/detail?id=253_

**Comment by rmanly** [comment]
This is no longer the case and has not been the case for quite some time. I think at least as long as I've been using munki 2.

This should be closed.
