### ISSUE TITLE
makepkginfo doesn't use --displayname option with --apple-update

### ISSUE THREAD

**Issue by natewalck** [munki/munki#255]
_From [hjuutila...@mac.com](https://code.google.com/u/104810762682981732871/) on July 23, 2013 23:26:41_

Minor bug... When creating apple update pkginfos, makepkginfo ignores the displayname option.

A very simple fix is in: https://github.com/hjuutilainen/munki/commit/d4d43ec448e112f18d2a1e6a536a3c6b6a857be3 --
Hannes

_Original issue: http://code.google.com/p/munki/issues/detail?id=255_

**Comment by gregneagle** [comment]
This was merged a long time ago: https://github.com/munki/munki/commit/d4d43ec448e112f18d2a1e6a536a3c6b6a857be3

But the issue wasn't closed. Closing now.
