### ISSUE TITLE
custom warning

### ISSUE THREAD

**Issue by natewalck** [munki/munki#264]
_From [steve.ku...@gmail.com](https://code.google.com/u/105417981970712392096/) on October 29, 2013 03:33:59_

a custom warning, when you install a software similar to the firmware warning.

that would be useful maybe before a osx update to warn the user

_Original issue: http://code.google.com/p/munki/issues/detail?id=264_

**Comment by gregneagle** [comment]
This has been essentially implemented as the "preinstall_alert" and "preupgrade_alert", nicht war?
