### ISSUE TITLE
Error comparing bundle version for mere existence

### ISSUE THREAD

**Issue by natewalck** [munki/munki#279]
_From [jesse.c....@gmail.com](https://code.google.com/u/102871374939581767735/) on February 24, 2014 13:31:40_

Here: https://code.google.com/p/munki/source/browse/code/client/munkilib/updatecheck.py#517 It checks for the version on a bundle unconditionally even if there is no bundle version in the pkginfo installs key to compare.

E.g.:

path = /System/Library/Java/JavaVirtualMachines/1.6.0.jdk
type = bundle

(And no other key).

Everything works right except: https://code.google.com/p/munki/source/browse/code/client/munkilib/updatecheck.py#539 Throws an error when it can't compare version keys. And it wouldn't - because there are none in the pkginfo, even though the correct behaviour of yes/no on the bundle.

I think the right thing to do may be to first check if there is a version_comparison_key OR a CFBundleShortVersionString (at least) in the installs item before calling comparePlistVersion.

_Original issue: http://code.google.com/p/munki/issues/detail?id=279_

**Comment by gregneagle** [comment]
Closing this due to lack of interest/development/discussion/progress...
