### ISSUE TITLE
Munki doesn't check for revoked server certificate

### ISSUE THREAD

**Issue by natewalck** [munki/munki#316]
_From [michael....@gmail.com](https://code.google.com/u/104090147250712813511/) on April 10, 2014 04:42:49_

After having to revoke and recreate the certificate of my Munki server due to the OpenSSL "heartbleed" bug, I noticed that curl does not check certificate revocation lists (CRLs) and Munki appears to contain no specific logic to do that itself.
curl 7.19.7 and higher support checking against a manually-downloaded CRL, so Munki should
1. download the server's certificate (e.g. using openssl s_client -connect hostname:443)
2. extract the CRL URL from it (e.g. by piping the certificate into openssl x509 -text noout and matching against a regex like "X509v3 CRL Distribution Points:\s*URI:(.*?)\s")
3. download that CRL to a file
4. pass it to curl using the --crlfile argument in every curl call
As not all certificates necessarily contain a CRL URL, steps 3 and 4 should be skipped if the regex in step 2 does not match.

To also check for revoked root and intermediate certificates, CRL files for the entire chain would have to be checked. Unfortunately curl only supports a single --crlfile argument, so that is not easily possible.

curl 7.19.7 was released in November 2009. Mac OS X 10.6.8 contains exactly that version and all newer versions of OS X contain newer ones, but I am not sure whether Apple ever included that version with an update for OS X 10.5, the earliest OS X version supported by Munki.

--- What steps will reproduce the problem? 1. Set up a web server with an SSL certificate obtained from a trusted CA or import the root certificate into System keychain.
2. Set up Munki with a repository on an SSL-encrypted web server
3. Have the CA revoke the SSL certificate
4. Run sudo managedsoftwareupdate --checkonly What is the expected output? What do you see instead? Munki checks for updates like normal. Instead, the update check should fail with an invalid (revoked) certificate error.

What version of the Munki tools tools are you using? On what version of OS X? Munki 1.0.0.1864, OS X 10.8.5

_Original issue: http://code.google.com/p/munki/issues/detail?id=316_

**Comment by gregneagle** [comment]
Closing this as the HTTP/HTTPS code has changed dramatically since this issue was opened.
