### ISSUE TITLE
Log window in Managed Software Center

### ISSUE THREAD

**Issue by natewalck** [munki/munki#328]
_From [ioto...@gmail.com](https://code.google.com/u/107247870725893978456/) on June 07, 2014 05:08:34_

A Log window implemented similar to the one in the Installer app. Command+L to open. Displays ManagedSoftwareUpdate.log.

Optional: choose current log files located in /Library/Managed Installs/Logs/ with ManagedSoftwareUpdate.log as default.

Thanks!

_Original issue: http://code.google.com/p/munki/issues/detail?id=328_

**Comment by clburlison** [comment]
This was added with https://github.com/munki/munki/commit/820718aaf02582e86bc911abbd6250b4dd851c7a & https://github.com/munki/munki/commit/655809019022497009847a725fbc801764753552 which made their way into release [v2.7.0](https://github.com/munki/munki/releases/tag/v2.7.0)

This issue can be closed.
