### ISSUE TITLE
com.googlecode.munki.munkiimport compatibility with Profile Manager

### ISSUE THREAD

**Issue by natewalck** [munki/munki#347]
_From [boneyjel...@gmail.com](https://code.google.com/u/113163839790660303759/) on July 07, 2014 11:46:43_

I would like to have the capability to better manager munkiimport and manifestutil from Profile Manager or Workgroup Manager. Right now, Munki only checks ~/Library/Preferences/com.googlecode.munki.munkiimport.plist for configuration preferences rather than looking globally for the preference information.

Alternatively, please allow me to specify the repo path from the manifestutil command line. Right now, only munkiimport and makecatalogs allow the repo path to be set from the command line.

_Original issue: http://code.google.com/p/munki/issues/detail?id=347_

**Comment by gregneagle** [comment]
As of this commit: https://github.com/munki/munki/commit/874f89ea96afcb19796a4029103daca43a5dadea, munkiimport now uses CFPreferences methods to read and write its configuration. Note that if you manage all or parts of the com.googlecode.munki.munkiimport preferences via MCX or profiles as "Forced/Always", `munkiimport --configure` will still _write_ preferences you choose, but they will be silently ignored.

**Comment by gregneagle** [comment]
`manifestutil` will take longer to update as it currently can work on non-OS X platforms (and doesn't need FoundationPlist or CFPreferences). If we add CFPrefs support, it still needs to be able to fall back to raw plist reading and writing if CFPreferences isn't available.

**Comment by erikng** [comment]
Thanks for doing this so quickly. I'll test on Monday with my cookbook.
