### ISSUE TITLE
FEATURE REQUEST: add reinstall option in MSC (Munki2)

### ISSUE THREAD

**Issue by natewalck** [munki/munki#351]
_From [david.iw...@gmail.com](https://code.google.com/u/107212327211504705270/) on July 17, 2014 10:54:26_

There are situations where having the ability to reinstall a package would be useful. This could be implemented by recognizing an option-click on "remove" to offer reinstall instead.

A scenario: A self-Install package has a payload that applies values to the currently logged in user's ByHost preferences, so they only affect the current user. Or a script which customizes the current user's Dock, Desktop, or other user-level items.

In order to apply those settings in a different/new user account, the package needs to be installed again while that user is logged in.

_Original issue: http://code.google.com/p/munki/issues/detail?id=351_

**Comment by gregneagle** [comment]
This is essentially the OnDemand functionality to be included with Munki 2.3, currently at Release Candidate 1. Closing this.
