### ISSUE TITLE
ENHANCEMENT - category key accepts string or array of string for multiple values

### ISSUE THREAD

**Issue by natewalck** [munki/munki#363]
_From [ryan.manly@gmail.com](https://code.google.com/u/ryan.manly@gmail.com/) on August 07, 2014 13:57:35_

It would be nice if the category key would accept an array of values so software could be available in multiple categories.

_Original issue: http://code.google.com/p/munki/issues/detail?id=363_

**Comment by gregneagle** [comment]
Not implementing at this time.
