### ISSUE TITLE
Better error output in manifestutil

### ISSUE THREAD

**Issue by natewalck** [munki/munki#365]
_From [ryan.manly@gmail.com](https://code.google.com/u/ryan.manly@gmail.com/) on August 12, 2014 08:37:23_

If a pkginfo is created without certain relevant keys...easily illustrated when lacking a 'name' key...manifestutil will output a traceback letting you know which key was missing but it would be nice if the exception was caught and a message telling you which specific pkginfo was causing the error was displayed.

_Original issue: http://code.google.com/p/munki/issues/detail?id=365_

**Comment by rmanly** [comment]
I don't remember why or how this was even an issue given that makecatalogs will output

```
WARNING: file path/pkginfo is missing name
```

I would just close this as I didn't provide any details about what the heck I was doing… :P
