### ISSUE TITLE
Download lang specific ASUS descriptions [Munki2 enhancement request]

### ISSUE THREAD

**Issue by natewalck** [munki/munki#369]
_From [nbalonso](https://code.google.com/u/nbalonso/) on August 20, 2014 22:40:00_

Now that looks like Munki2 will be available in many different languages, it would be interesting if it could download the language specific descriptions for the Apple updates.

_Original issue: http://code.google.com/p/munki/issues/detail?id=369_

**Comment by gregneagle** [comment]
Addressed specifically here: https://github.com/munki/munki/commit/465c60b5f8b20ce716fb32ba01fb005495ac5986

Munki admin should set the ManagedInstalls preference 'AppleSoftwareUpdateLanguages' to the desired language.
