### ISSUE TITLE
MSC Search box has no background colour on 10.10

### ISSUE THREAD

**Issue by natewalck** [munki/munki#378]
_From [gra...@grahamgilbert.com](https://code.google.com/u/108778264542551396038/) on August 26, 2014 03:56:54_

The search box in MSC Version 4.0.2187 (2187) is grey - this has only appeared in the last few days (I assume with the new toolbar).

_Original issue: http://code.google.com/p/munki/issues/detail?id=378_

**Comment by gregneagle** [comment]
Fixed here: https://github.com/munki/munki/commit/d5a0af55c77cb6ac716847a3facf2cfa71f4be59
