### ISSUE TITLE
Multiple language product descriptions / categories

### ISSUE THREAD

**Issue by natewalck** [munki/munki#384]
_From [choules@wycomco.de](https://code.google.com/u/choules@wycomco.de/) on September 03, 2014 09:37:27_

Please implement support for multi language elements in munki. Especially for sites with users who speak different languages this would be a very neat feature.

The following item should be translatable:
- display_name
- description
- category
- developer(?)

Suggestion:
The translations should be part of the pkginfo files. Right now all those fields are plain strings. It should be possible to define a string or a dictionary containing multiple strings, whereas the key for contained strings might be the ISO language code (en_GB, de_DE etc.). Perhaps a kind of "default language" should be defined.

All the munki tools then just need to check if the given item is a string or a dictionary and then use the right language.

_Original issue: http://code.google.com/p/munki/issues/detail?id=384_

**Comment by miawri** [comment]
This would be an excellent enhancement!

**Comment by gregneagle** [comment]
This was implemented ages ago in Munki 3.2: https://github.com/munki/munki/wiki/Pkginfo-Files#localized_strings

**Comment by miawri** [comment]
Amazing.

I found this ancient enhancement request before the wiki entry.
