### ISSUE TITLE
Bootstrapping enhancement

### ISSUE THREAD

**Issue by erikng** [munki/munki#422]
I'm noticing some of my clients are getting [Errno 8] nodename nor servname provided during initial bootstrapping and immediately cancel out.

Is it possible to add a longer delay for the network to initialize or have Munki look for the server more than once (maybe five times) before removing the dot file? If I immediately trigger another bootstrap seconds later, everything works.

**Comment by gregneagle** [comment]
This was pulled and merged, yes?

**Comment by erikng** [comment]
Si.

**Comment by gregneagle** [comment]
Closing.

**Comment by erikng** [comment]
Would you have any opposition to me increasing the time once again from 30 seconds to 60?

**Comment by gregneagle** [comment]
It takes a full minute after boot for your network to be available? What is this, the 1890s? No, no objections. I might have some objections for your network crew, though...
