### ISSUE TITLE
Possible Issue: update_for only targeting fullname of app

### ISSUE THREAD

**Issue by erikng** [munki/munki#433]
(this could be by design).

Packages:
Foo-1.0
Foo-1.1
Fooupdate-1.0 marked as update_for Foo.

If manifest contains Foo-1.1 rather than Foo only, the update_for will not work. The admin must specifically mark Foo-1.1 as an update_for in its pkginfo for Munki to download the product.

**Comment by gregneagle** [comment]
Closing...
