### ISSUE TITLE
tmp not being removed - Munki 2.1

### ISSUE THREAD

**Issue by erikng** [munki/munki#438]
When importing .apps, Munkiimport will create the dmg to a tmp file but they are never removed. 

In my testing I was not letting Munki rebuild the catalogs but I doubt that's the issue. I have not had a chance to look at the source code.

**Comment by gregneagle** [comment]
I don't think this is new to 2.1 -- I bet this exists all the way back to 1.0 and earlier.

**Comment by keeleysam** [comment]
I like this behavior.  Sometimes when running munkiimport I'll make an
error and control+c to quit, and then I'll run munkiimport against that DMG
in /tmp so I don't have to wait for it to be created a second time.

On Fri, Jan 9, 2015 at 4:55 PM, Greg Neagle <notifications@github.com>
wrote:

> I don't think this is new to 2.1 -- I bet this exists all the way back to
> 1.0 and earlier.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munki/munki/issues/438#issuecomment-69414744>.
>



-- 
Samuel Keeley

**Comment by gregneagle** [comment]
You might like it, but it's wrong, and over time the number (and disk usage) of /private/tmp/munki-FOO directories can grow quite large. I do plan to address this.

**Comment by erikng** [comment]
Control+C is understandable though because you are deliberately stopping the process before it has completed.

I think the best option would be to only remove the temp files at the very end, after import.

**Comment by gregneagle** [comment]
Addressed here: https://github.com/munki/munki/commit/58d8a07dece5636250655575c3a167d48d5feb4e
