### ISSUE TITLE
Copyfromdmg needs destination_path when using destination_item

### ISSUE THREAD

**Issue by bochoven** [munki/munki#440]
Contrary to what the documentation says, I need to specify the destination_path when renaming a copy item. If I don't specify the destination_path, I get the following error:

```sh
Installing ADF 2014 (1 of 1)...
    Mounting disk image adf2014.04.macintel64.openmpi-2014.04.r44409.dmg...
ERROR: Unexpected error in munkilib.installer:
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 1006, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 818, in main
    mustrestart = doInstallTasks(appleupdatesavailable)
  File "/usr/local/munki/managedsoftwareupdate", line 222, in doInstallTasks
    munki_need_to_restart = installer.run(only_unattended=only_unattended)
  File "/usr/local/munki/munkilib/installer.py", line 1223, in run
    only_unattended=only_unattended)
  File "/usr/local/munki/munkilib/installer.py", line 707, in installWithInfo
    retcode = copyFromDMG(itempath, item.get('items_to_copy'))
  File "/usr/local/munki/munkilib/installer.py", line 526, in copyFromDMG
    retcode = copyItemsFromMountpoint(mountpoint, itemlist)
  File "/usr/local/munki/munkilib/installer.py", line 404, in copyItemsFromMountpoint
    if not os.path.exists(destpath):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

Relevant xml:

```plist
	<key>items_to_copy</key>
	<array>
		<dict>
			<key>destination_item</key>
			<string>ADF2014.app</string>
			<key>source_item</key>
			<string>ADF2014.04.app</string>
		</dict>
	</array>
```

**Comment by gregneagle** [comment]
Does 
```
    <key>items_to_copy</key>
    <array>
        <dict>
            <key>destination_item</key>
            <string>/Applications/ADF2014.app</string>
            <key>source_item</key>
            <string>ADF2014.04.app</string>
        </dict>
    </array>
```

work?  If so, I think that's what's meant by not needing to specify the destination_path. I didn't write that code; will look at it later today.

**Comment by bochoven** [comment]
Hmm it looks like specifying the full path in destination_item does not resolve the issue.

**Comment by bochoven** [comment]
I think this is jus a documentation issue: looking at the code destination_path has to exist.

```python
        destpath = item.get("destination_path")
```

**Comment by gregneagle** [comment]
Even if it is, the code should handle it better and not blow up.

**Comment by gregneagle** [comment]
Try this:
https://github.com/munki/munki/commit/9c9ac8dcddce5540a987f05614ad365212723eae

If you specify a destination_item as I do above it should now work; if you specify one like you do above (with no path) you'll get an error (but not a traceback).

**Comment by bochoven** [comment]
Thanks, but now you changed the way destination_item works. Some people may rely on the previous behaviour.

**Comment by gregneagle** [comment]
No, I don't believe I did. Can you clarify what you think is different?

**Comment by bochoven** [comment]
In the previous situation you had to define destination_path _and_ destination_item (relative path to destination_path)

Now if you specify destination_path, destination_item is skipped.
If you only specify destination_item, it is an absolute path.

**Comment by gregneagle** [comment]
No, the behavior should be the same.

You can still define destination_item as a relative path to destination_path; but you can also now (as I think was originally intended) just define the full path in destination_item and not define destination_path at all.

**Comment by bochoven** [comment]
Yes, you're right.

**Comment by gregneagle** [comment]
<sigh of relief>

**Comment by bochoven** [comment]
Sorry about that, I should have read the whole script, not only the part you changed. There's still the need to document this though.

**Comment by gregneagle** [comment]
You can edit the wiki if you'd like...
