### ISSUE TITLE
munkiimport should copy 'supported_architectures' key from existing pkginfo

### ISSUE THREAD

**Issue by uroehm** [munki/munki#446]
I still need to support a few PPC machines in my domain. For this, I keep old Universal-versions of applications around, which get distinguished from the newer versions available to Intel-Macs via the 'supported_architectures' key.
At the moment, one has to manually copy these 'supported_architectures' entries with each newly imported application version. This is error prone. Instead, that key should be added to the list of automatically copied pkginfo keys in munkiimport.

My suggested fix: In the current version of munkiimport, extend the array of copied pkginfo keys with the following string (eg. behind line 964):
                            'supported_architectures',

**Comment by keeleysam** [comment]
I don't think this is a good strategy, as if I import Firefox 35 it
supports different architectures than Firefox 3.6.

If this is an issue, it's probably better to enhance munkiimport by telling
it how to get supported architectures from the installer or application
bundle.

On Friday, January 23, 2015, uroehm <notifications@github.com> wrote:

> I still need to support a few PPC machines in my domain. For this, I keep
> old Universal-versions of applications around, which get distinguished from
> the newer versions available to Intel-Macs via the
> 'supported_architectures' key.
> At the moment, one has to manually copy these 'supported_architectures'
> entries with each newly imported application version. This is error prone.
> Instead, that key should be added to the list of automatically copied
> pkginfo keys in munkiimport.
>
> My suggested fix: In the current version of munkiimport, extend the array
> of copied pkginfo keys with the following string (eg. behind line 964):
> 'supported_architectures',
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munki/munki/issues/446>.
>


-- 
Samuel Keeley

**Comment by gregneagle** [comment]
Agree with Sam about the danger of assuming that version X+1 of an application/software package supports the same architectures as version X; VLC is another example that comes to mind. At some point a version was released that was 64-bit Intel-only.

Several years ago, supported_architectures seemed very important to pay attention to; today, not so much.

Might I suggest an alternate approach?

Create a "ppc-production" catalog, and put all the ppc or universal versions of your software in that catalog.

For your few PPC machines, make sure their applicable manifest has the "ppc-production" catalog as the first catalog in their catalog list.

When checking for software, Munki will check the ppc-production catalog first and use the highest version of, say, Firefox found in that catalog.

Intel machines should not have the ppc-catalog in their manifests, and so they'll find and install more recent versions of the software.

**Comment by uroehm** [comment]
@ keeleysam:
With most applications I encountered, the supported architectures are actually very stable. Typically there was a pivot version where PPC support was dropped and all I am doing now is to add newer, Intel-only versions which I do want to have ignored by my old PPC machines because the supported_architectures does not include Power Macintosh anymore. So my typical use case is that I have the last PPC version of the app in my repository, which is used by the PPC Macs, plus one or two of the most recent application versions, which tend to be Intel-only and where a copy of the supported_architectures key from the most recent pkginfo file is correct.

There's only one exception of that rule in my repository, which is FileZilla which to this date produces separate PPC and Intel packages, and I actually import them by the same pkginfo name (FileZilla), but with different supported_architectures. As this is only one, I easily can edit it manually.
Thinking about it now, I might be cleaner that I would use two distinct names here - eg. FileZilla and FileZillaPPC - and the problem to have to manually edit the pkginfo would be solved.
That's actually the way how I handle Firefox versus TenFourFox...

I agree though that my suggestion is a simple quick fix which fundamentally assumes this 'pivot' version in the development cycle, and that from that side a actual analysis of the installer file with a correct determination of the supported architecture would be safer. That however is not a simple change anymore then...

**Comment by gregneagle** [comment]
"if I have an older PPC version of vlc (say 2.0.6) in ppc-production and a newer vlc version 2.1.5 in my general production catalog, and both are included in the same manifest (order: PPC, then general production) - which version of vlc would Munki pick?"

2.0.6.

"Additionally, I guess that I still would need though a distinct key per PPC-only software, in order to get those included only into the ppc-production catalog... "

No, you'd just add the PPC-only software to the ppc-production catalog (and remove it from the general production catalog). Since very little new PPC software is released, this would be mostly one-time effort.

**Comment by gregneagle** [comment]
Closing this as I've decided not to make this change to munkiimport.
