### ISSUE TITLE
MSC Fails to Trigger a Restart When pkginfo Doesn't Declare RestartAction but pkg Requires Reboot

### ISSUE THREAD

**Issue by foigus** [munki/munki#447]
Summary
Managed Software Center is not successfully triggering a restart when the pkginfo doesn't provide the info that would have caused Munki to (normally) require a logout first before installing.

Steps to Reproduce
1. munkiimport the following pkg (Ricoh Aficio SP C242SF driver):
http://support.ricoh.com/bb/pub_e/dr_ut_e/0001229/0001229240/V201/r57501L11.dmg
2. Edit the generated pkginfo to remove the RestartAction key of "RequireRestart" (the installer is just a PPD, thus I believe a restart isn't warranted)
3. makecatalogs
4. Add the Installer Item to a manifest (I added to managed_installs)
5. Initiate installation of the Installer Item via Managed Software Center on the Client

Expected Results
1) managedsoftwareupdate installs the software
2) Managed Software Center prompts for a restart
3) The computer restarts.

Actual Results
1) managedsoftwareupdate installs the software
2) Managed Software Center prompts for a restart with the message "Restart Required: Software installed or removed requires a restart. You will have a chance to save open documents."
3) The computer fails to restart, and Managed Software Center reports "Install session failed: There is a configuration problem with the managed software installer. The process ended unexpectedly. Contact your systems administrator."

ManagedSoftwareUpdate.log:
https://gist.github.com/anonymous/2ca92e9402ac59803021

Workaround
Leave the RestartAction of "RequireRestart" in the Installer Item's pkginfo.

Regression/Isolation
Per Greg's ##osx-server IRC feedback ( https://botbot.me/freenode/osx-server/2015-01-30/?msg=30846648&page=6 ):
This doesn't look promising: 
https://github.com/munki/munki/blob/master/code/apps/Managed%20Software%20Center/Managed%20Software%20Center/MSCStatusController.py#L226
Like a feature from Munki 1's MSU.app that didn't get implemented in MSC, and the condition is pretty rare (as in you have to go out of your way to trigger it).

**Comment by gregneagle** [comment]
This should be addressed in the 2.2.2 release.
