### ISSUE TITLE
Munki failed install stops subsequent installs.

### ISSUE THREAD

**Issue by dingerkingh** [munki/munki#448]
Let's say I have 6 pending installs and the first one fails or has a problem, it is just skipping over the remaining 5 installs even though they may not have a problem installing. 

Maybe this is by design and not actually a problem - but it would be cool if it would just skip over the one failed app and install the remaining installs.

**Comment by gregneagle** [comment]
This is not the expected behavior.
Let's see a log or the output of `managedsoftwareupdate -vvv`demonstrating the issue.

If the following 5 installs have a dependency on the first install, then this _is_ expected. Otherwise, Munki  proceeds down the list of installs even if one fails.

**Comment by dingerkingh** [comment]
Ok - I have removed the install that were causing the issue so I could get the others installed. I will reenable and try to get the log. The error that was showing up was HDIUTIL No Mountable Filesystem found. This was caused by me disabling access to DMGs in profile manager. (Not smart) In the mean time - the certificate expired on profile manager so none of the devices could talk to profile manager to undo the disable DMGs. I was trying to use Munki to push the new profile out but the adobe install would error out causing the subsequent profile to never get installed. 

Anyways - long story short is I will run the -vvv command.

Would it be `managedsoftwareupdate --installonly -vvv` ? or just `-vvv`

**Comment by gregneagle** [comment]
If you've borked the machine such that it cannot mount disk images, that would affect the installation of every single thing on a disk image. Were any of the pending items to install not on a disk image?

-vvv give additional verbosity during a managedsoftwareupdate run. So you'd add -vvv to a run that attempted to install the items; in your case that would probably be managedsoftwareupdate --installonly -vvv, but make sure the items are queued for install first.

All Munki admins should familiarize themselves with this:
https://github.com/munki/munki/wiki/Troubleshooting

**Comment by dingerkingh** [comment]
Yeah - when I run the -vvv I get:

Managed Software Update Tool
Copyright 2010-2014 The Munki Project
http://code.google.com/p/munki

Starting...
    Performing preflight tasks...
    preflight stdout:     Munkireport: # Executing scripts in preflight_abort.d
    Munkireport: # Executing scripts in preflight.d
    Munkireport: Running bluetooth.sh
    Munkireport: Running directoryservice.sh
    Munkireport: Running disk_info
    Munkireport: Running displays.py
    Munkireport: Running filevaultstatus
    Munkireport: filevaultstatus Error: Error: FileVault is Off.
    Munkireport: Running localadmin
    Munkireport: Running networkinfo.sh
    Munkireport: Running warranty
    Munkireport: Running submit.preflight
    **Checking for Apple Update Metadata**
    Looking for detail for: zzz031-11170, version latest...
    Not found
    Looking for detail for: 031-3227, version latest...
    Not found
    Looking for detail for: zzzz031-17330, version latest...
    Not found
    Looking for detail for: 031-10992, version latest...
    Not found
    Looking for detail for: 031-07292, version latest...
    Not found
Installing Adobe Flash Player (1 of 2)...
    suppress_bundle_relocation: False
    Mounting disk image AdobeFlashPlayer-16.0.0.235.dmg...
ERROR: Error: "hdiutil: attach failed - no mountable file systems" while mounting AdobeFlashPlayer-16.0.0.235.dmg.
ERROR: No filesystems mounted from Ado
HANGS AT THIS POINT

I am installing the profile from a package which install fine on it's own. However, if a dmg like adobe is in front of it - it never gets installed - just skips right over it to system updates.

No biggie - I can just disable all of the other dmg installs until it is reenrolled to profile manager.

**Comment by gregneagle** [comment]
That's not an issue I can easily reproduce (nor do I think I really want to try). OK to close?

**Comment by dingerkingh** [comment]
Yeah - not sure you can fix stupidity...
