### ISSUE TITLE
Setting MSU to Suppress User Notification and Auto Install conflicts with Force Install

### ISSUE THREAD

**Issue by micmil** [munki/munki#449]
We have DeepFreeze installed on our lab computers. This requires us to set MSU to not install updates automatically, and do not notify the user of new updates. We did this using two settings on the clients in /Library/Preferences/ManagedInstalls - 
SuppressUserNotification = true
SuppressAutoInstall = true

This works perfectly until a package is marked as Forced or Forced After [Date]. The Forced setting overrides the suppression on notifications and auto installs. In order to support a mixed environment, like most schools have, we would have to manage two packages for each update: one that is Forced for machines without DeepFreeze, and one that is not forced for machines with DF. This is simply not practical and is a management nightmare.

We really like the idea of Forced installs, but it is currently impractical to use. Would it be possible to change the behavior of the Forced install and abide by the settings in SuppressUserNotification and SuppressAutoInstall?

**Comment by micmil** [comment]
>But I think a better approach would be to turn off all periodic background runs on your DeepFrozen computers and only run managedsoftwareupdate during your maintenance windows.

Thanks, that would definitely be preferable. I'm having trouble finding info on that. Before I post on munki-dev, how would I go about disabling background checks entirely?

**Comment by gregneagle** [comment]
sudo launchctl unload -w /Library/LaunchDaemons/com.googlecode.munki.managedsoftwareupdate-check.plist

**Comment by gregneagle** [comment]
Closing this.
