### ISSUE TITLE
Unhandled exception in makecatalogs

### ISSUE THREAD

**Issue by gregneagle** [munki/munki#450]
The new icon_hash code in makecatalogs needs some additional error-checking. See:

https://groups.google.com/d/msg/munki-dev/7HZbyHIpJ0o/uURLDq76hzsJ

**Comment by keeleysam** [comment]
What should be the behavior here?  Should the pkginfo still be added to the catalog even though it is invalid and cannot be used under any condition by the client?

**Comment by gregneagle** [comment]
errors.append("WARNING:....") and skip the file I think would be best.
