### ISSUE TITLE
ERROR: softwareupdate error: 100

### ISSUE THREAD

**Issue by SailorMars** [munki/munki#451]
I dont know if its a bug or i missed something.

Today I updated to munki 2.2.0.2399 on my test server (10.10.2) and 2 test clients.
The server is AD bound and one client (10.10.2) is also AD bound and one client (10.10.1) not.
With munki 2.2.0.2397 all works fine, but with version 2.2.0.2399 I get a SUS update error on the unbound client.
/usr/local/munki/managedsoftwareupdate
ERROR: softwareupdate error: 100

/usr/local/munki/managedsoftwareupdate --installonly
ERROR: Missing local Software Update catalog at 
/tmp/munki_swupd_cache/content/catalogs/local_install.sucatalog

/usr/sbin/softwareupdate -l
The Apple Softwareupdateserver (localhost) is not responding

Update:
AD bound MAC
via terminal with /usr/local/munki/managedsoftwareupdate > no error 100
via managed software update > error 100
Can install Updates from SUS

unbound MAC
via terminal with /usr/local/munki/managedsoftwareupdate > error 100
via managed software update > error 100
Doesn't download MAC Updates from SUS

**Comment by gregneagle** [comment]
This is an error that many Munki admins have seen over the years; you'll find many mentions on the munki-dev list. We don't know what causes it, or what causes it to go away, but it always goes away by itself. Most times, a restart clears it up.

**Comment by SailorMars** [comment]
Thanks for the reply, I will watch it

**Comment by StrongJava** [comment]
A restart of the server may clear it? Or a restart of the client on which the error is being logged?

**Comment by erikng** [comment]
Client.

**Comment by jessepeterson** [comment]
As others have noted in [other forums](https://groups.google.com/d/msg/munki-dev/foOxg2ArEGg/UspZuBliDAAJ): if you're running reposado check and double-check your setup!

In one case we found that having bad permissions in the reposado mirrored updates (`html` folder) caused the OS X softwareupdate client to get HTTP 403 errors reading some distribution files (as noted in `/var/log/install.log`). This would manifest as the mysterious `ERROR: softwareupdate error: 100` in the munki logs. Fixing the permissions (on the reposado server side) made that go away. Do check your other reposado server setup details such as catalog URLs, port numbers, web server setup, etc., though!

**Comment by gniemetz** [comment]
Thank you @jessepeterson , this tip helped a lot
