### ISSUE TITLE
messed up my install

### ISSUE THREAD

**Issue by appleaday3k** [munki/munki#453]
I somehow managed to mess up my install,  i have attempted uninstalls, and reinstalls but cannot get munki working, any ideas?

error:
When i run sudo managedsoftwareupdate, i get a bunch of the following error
WARNING: Manifest /Library/Managed Installs/manifests/client_manifest.plist has no catalogs

my client_manifest.plist

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>managed_installs</key>
	<array>
		<string>Install Adobe Flash Player</string>
	</array>
</dict>
</plist>

**Comment by natewalck** [comment]
Please email the munki-dev mailing list: https://groups.google.com/forum/#!forum/munki-dev

This is a change request system, not a support system.

Thanks!

Nate
