### ISSUE TITLE
certificated package passed to untrust ?

### ISSUE THREAD

**Issue by sebizare** [munki/munki#455]
Hi everybody,
Since one week or two i don't know, some packages don't want to install on a 10.10. (i'm sure it work 15 days ago).
 When i look in Managedsoftwareupdate.log the log says:

Mar 09 2015 10:13:32 +0100     Install of Logiciels d’imprimantes Hewlett-Packard failed with return code 1
Mar 09 2015 10:13:32 +0100 ERROR: ------------------------------------------------------------------------------
Mar 09 2015 10:13:32 +0100 ERROR: installer: Package name is Logiciels d’imprimantes Hewlett-Packard
Mar 09 2015 10:13:32 +0100 ERROR: installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.
Mar 09 2015 10:13:32 +0100 ERROR: ------------------------------------------------------------------------------

It seem that the certificate for my package is not valid :-o
Is someone have the same problems  ?
Is someone knows how i can use the "-allowUntrusted" option in the .plist  to force the package ?
 The client munki version is 4.0.2348
It's specific driver that i take from apple and import in munki and since 15 days it works.
sebastien

**Comment by keeleysam** [comment]
Please read https://managingosx.wordpress.com/2012/03/24/fixing-packages-with-expired-signatures/

For support with munki, please post to the munki-dev list. http://groups.google.com/group/munki-dev

**Comment by gregneagle** [comment]
See also: https://derflounder.wordpress.com/2015/02/10/certificate-authority-expiration-and-apple-software-updates/

You can download replacement pkgs (that aren't expired) from Apple, or you can remove the signatures altogether using the techniques described in the link given by keeleysam.

**Comment by sebizare** [comment]
thanks a lot i'll test it it works ;-), i can remove the cert with keeleysam link, and reimport the package
sebastien
