### ISSUE TITLE
Enhancement - Process updates for "munki" before any other items.

### ISSUE THREAD

**Issue by erikng** [munki/munki#457]
When a munki upgrade is available through the server, I would like the clients to process these packages prior to anything being layered.

Currently my workaround is to put it at the highest manifest on the first entries for "managed_installs". Given the recent issues, it would be nice during bootstrapping mode if it would process these packages first.

**Comment by gregneagle** [comment]
"When a munki upgrade is available through the server, I would like the clients to process these packages prior to anything being layered." Why? What problem would this solved? Any updated code isn't likely to be used until the _next_ Munki run, so updating the tools first isn't going to make any difference around the installing of items during that same run.

One might more convincingly argue that it would be better to install any Munki tools pkg _last_ to minimize the chance that swapping out code while Munki is running would cause the Munki tools to crash.

**Comment by keeleysam** [comment]
I don't really understand why this would be needed, but you should use the
minimum_munki_version key if you're running into issues with unsupported
pkginfos such as configuration profiles.

Or just install the most recent version of munki during your bootstrap.

On Fri, Mar 13, 2015 at 8:26 AM, Greg Neagle <notifications@github.com>
wrote:

> "When a munki upgrade is available through the server, I would like the
> clients to process these packages prior to anything being layered." Why?
> What problem would this solved? Any updated code isn't likely to be used
> until the *next* Munki run, so updating the tools first isn't going to
> make any difference around the installing of items during that same run.
>
> One might more convincingly argue that it would be better to install any
> Munki tools pkg *last* to minimize the chance that swapping out code
> while Munki is running would cause the Munki tools to crash.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munki/munki/issues/457#issuecomment-79045081>.
>



-- 
Samuel Keeley

**Comment by erikng** [comment]
Yes I'll just change my bootstrapping process.

I also didn't think about the fact that the Munki run will still run on the current version.
