### ISSUE TITLE
makepkginfo: don't fail on payload-free flat packages, warn conditionally

### ISSUE THREAD

**Issue by dayglojesus** [munki/munki#459]
The present `makepkginfo` implementation produces an fatal error when attempting to parse a payload-free flat package.

``` Bash
WARNING: No valid Distribution or PackageInfo found.
payload-free.pkg doesn't appear to be a valid installer item!
````
With regard to this [thread](https://groups.google.com/forum/#!topic/munki-dev/zPNfOTJVwlQ), allow flat payload-free packages to be parsed, but produce a warning if no criteria for successful installation is provided.

To suppress the warning, successful installation criteria can be supplied using:
- installs items: `-f PATH` or  `--file=PATH`
- install check script: `--installcheck_script=SCRIPT_PATH` or `--installcheck-script=SCRIPT_PATH`

**Comment by gregneagle** [comment]
Addressed here: https://github.com/munki/munki/commit/8d12a04e59853f9518900b68b249d9e6c8470b15
