### ISSUE TITLE
Updates do not appear in MSC GUI

### ISSUE THREAD

**Issue by arubdesu** [munki/munki#467]
As discussed on the dev list, broken down into two issues:
1. updates from this catalog do not appear in MSC GUI
2. by performing any optional install in the meantime, updates which require a reboot also get installed, which the user is only notified about AFTER completion of install - not sure if connected to updates from beta track.
![screen shot 2015-03-31 at 11 31 52 am](https://cloud.githubusercontent.com/assets/388808/6922543/f106f4fc-d799-11e4-89ce-0a21c0d259bc.png)

**Comment by gregneagle** [comment]
There is not enough info here to begin to guess what is going on. You are the only person who has reported anything like this. So it's all on you to figure it out, or to uncover enough context/details so that others (or I!) can either reproduce it or otherwise figure out what is going on.

First step: does this occur only when softwareupdate is configured to get the beta channel updates?

**Comment by gregneagle** [comment]
Additional things to investigate:

1) com.apple.SoftwareUpdate CatalogURL vs ManagedInstalls
2) Contents (and owner, group, mode) of /Library/Managed Installs/AppleUpdates.plist
3) Investigation into the contents of /Library/Managed Installs/swupd
4) Investigation into the contents of /Library/Updates

**Comment by erikng** [comment]
I haven't seen this on any of the seeds. This includes with optional installs.

**Comment by natewalck** [comment]
I've definitely seen seeds show up in MSC. I am getting them directly from
Apple, no Caching server or Reposado.

Nate

**Comment by arubdesu** [comment]
Will re-open if I can reliably replicate issue

**Comment by arubdesu** [comment]
This is also occurring on a machine not running 10.10.3/beta's, I've clarified the title, pardon me muddying my symptom with a possible cause. Other background info:
- using client certs
- InstallAppleSoftwareUpdates is turned on
- newest MSC/munkitools release(2.2.4.2431)
- com.apple.SoftwareUpdate CatalogURL is not set

Everything else requested is here: https://gist.github.com/arubdesu/4f4f8f497d835d593dff
I'll make another gist with the same info on a 10.10.2 machines experiencing the same symptom

**Comment by erikng** [comment]
Where are the logs showing the install?

**Comment by arubdesu** [comment]
added, as you can see I optionally updated Atom and Bartender, which 'silently' triggered the OS updates without me realizing again

**Comment by gregneagle** [comment]
Does /Library/Managed\ Installs/AppleUpdates.list exist? If so, what is its mode?

This is where available Apple updates are recorded.  If somehow this file can't be read by the current user, MSC.app won't know these updates exist (but the root managedsoftwareupdate process will). If MSC.app doesn't know about those updates, it won't have the information it would need to decide to tell the user they must logout before proceeding with the updates.

**Comment by arubdesu** [comment]
https://gist.github.com/arubdesu/4f4f8f497d835d593dff#file-com-apple-softwareupdate-related-txt-L45
```-rw-r--r--  1 root  admin  1486 Apr  9 15:21 /Library/Managed Installs/AppleUpdates.plist```
What might be smacking the perms...

**Comment by gregneagle** [comment]
That's OK -- that's readable by everyone. But that's the way it was at the time you captured it, which may or may not be as it was when MSC.app was reading it. But if you can reproduce the state, you can check the state of /Library/Managed Installs/AppleUpdates.plist while in that state.

**Comment by arubdesu** [comment]
https://gist.github.com/arubdesu/fbd46790871e51a72775

**Comment by gregneagle** [comment]
Allister:

Does this issue persist for other users on the same machine, or is it limited to your user account?

Also: can I see output of these:

`defaults read ManagedInstalls`  (intention here is to read the copy in your user's preferences)
`defaults read /Library/Preferences/ManagedInstalls`

**Comment by arubdesu** [comment]
It does persist on other users, and at least one other machine. Running defaults as my users domain doesn't return, we use root's domain for our prefs but /L/P/managedInstalls has the following:
```{
    AppleSoftwareUpdatesOnly = 0;

    ClientIdentifier = odmit21;

    DaysBetweenNotifications = 1;

    InstallAppleSoftwareUpdates = 0;

    InstalledApplePackagesChecksum = 1567e942810486c3b7af666f8587b584d39da793c125020f38321d113aa5c076;

    LastAppleSoftwareUpdateCheck = "2015-04-09 22:59:25 +0000";

    LastCheckDate = "2015-04-09 22:58:42 +0000";

    LastCheckResult = 0;

    LastNotifiedDate = "2015-04-09 18:42:46 +0000";

    LogFile = "/Library/Managed Installs/Logs/ManagedSoftwareUpdate.log";

    LogToSyslog = 0;

    LoggingLevel = 1;

    ManagedInstallDir = "/Library/Managed Installs";

    PackageVerificationMode = hash;

    SoftwareRepoURL = "http://10.97.22.150/repo";

    SoftwareUpdateServerURL = "";

    SuppressAutoInstall = 0;

    SuppressStopButtonOnInstall = 0;

    SuppressUserNotification = 0;

    UseClientCertificate = 0;
}```

**Comment by gregneagle** [comment]
More to the above:

I can reproduce your issue by doing this:

`defaults write ManagedInstalls InstallAppleSoftwareUpdates -bool NO`

(Writing the preference to my user preferences -- not /Library/Preferences/ManagedInstalls)

When MSC.app (running as the user) reads the value of InstallAppleSoftwareUpdates from the "ManagedInstalls" domain, the user preference has highest precedence.

When it sees this preference as "NO" is decides it should not look at any available Apple Updates. (This was an enhancement request from someone; I can't find it right now; basically they flipped the preference _after_ Munki had downloaded/cached Apple updates and were surprised that MSU/MSC displayed them still)

But managedsoftwareupdate (running as root) doesn't see that same pref. So it caches (and displays) Apple Updates, but MSC thinks it's not supposed to display them (and erroneously, that managedsoftwareupdate will not be installing them)

**Comment by gregneagle** [comment]
> InstallAppleSoftwareUpdates = 0;

And there is the source of the problem.

MSC.app can't see the root preferences. It can only see the /Library/Preferences/ManagedInstalls preferences.

See here: https://github.com/munki/munki/wiki/Preferences#secure-config

Specifically:

>Note: the following configs are required in /Library/Preferences/ManagedInstalls.plist (or set via MCX), as the GUI portion of Munki runs as the logged in user, not root. Do not place them in the secure plist, or you may encounter unexpected behavior from Managed Software Update.app:

>ManagedInstallDir
>InstallAppleSoftwareUpdates
>AppleUpdatesOnly
>ShowRemovalDetail
>InstallRequiresLogout
>HelpURL

I'd say you are encountering unexpected behavior from Managed Software Center.app.
I'll make this warning bigger.

**Comment by gregneagle** [comment]
Had you noticed that MSC was never showing any Apple Software Updates ever -- that this was not MSC failing to show OS updates or software updates requiring a restart, but something much wider -- that Apple updates were _never_ showing up?

The key for me was when you posted the `opensnoop` output I could see that MSC.app was never even trying to read the AppleUpdates.plist.

**Comment by erikng** [comment]
Allister,

Perhaps instead of setting this via root preferences, use /L/P/ManagedInstalls and on top of this have a profile that is installed to ensure settings are maintained.

**Comment by arubdesu** [comment]
Thanks for leading me by the nose to this, sorry I needed to lean heavily on you for assistance.
That new wording is indeed instructive of the supported way to get reliable settings.The correct behavior consistently and immediately appears when the setting is added to /L/P/ManagedInstalls, even though the other machine experiencing the symptom did not have that pref set anywhere else besides root's domain.
I'll modify our deployments configuration steps accordingly, thanks again.

**Comment by erikng** [comment]
Might want to post on munki dev for the benefits of other admins.

**Comment by gregneagle** [comment]
>".The correct behavior consistently and immediately appears when the setting is added to /L/P/ManagedInstalls, even though the other machine experiencing the symptom did not have that pref set anywhere else besides root's domain."

InstallAppleSoftwareUpdates defaults to false, so if it can't read a value for that key, it assumes it is false.

https://github.com/munki/munki/blob/master/code/apps/Managed%20Software%20Center/Managed%20Software%20Center/munki.py#L92
