### ISSUE TITLE
Munki wiki points to a file on Google Code

### ISSUE THREAD

**Issue by flammable** [munki/munki#468]
I was reading about [securing the Munki repo with client certificates](https://github.com/munki/munki/wiki/Using%20Munki%20With%20SSL%20Client%20Certificates), and saw the wiki page links to a file still hosted on Google Code:

http://munki.googlecode.com/files/UsingMunkiWithSSLClientCertificates-demo.zip

I searched the GitHub issues and didn't see anything about the Google Code transition, so forgive me if you're tracking this elsewhere.

**Comment by gregneagle** [comment]
Thanks. Fixed. File now at
https://github.com/munki/contrib/raw/master/UsingMunkiWithSSLClientCertificates-demo.zip

**Comment by gregneagle** [comment]
(no idea if the info and files are currently applicable/useful, however)

**Comment by flammable** [comment]
Thanks, Greg!
