### ISSUE TITLE
Tag me i'm famous

### ISSUE THREAD

**Issue by AlroneRhyn** [munki/munki#472]
Hello!
It would be awesome to have a tag field or a compagny/entity field that could be grep by munkireport-php. 

GREAT job guys, keep going.

**Comment by arubdesu** [comment]
Hey @AlroneRhyn, it sounds like you want to know if munki supports adding arbitrary key/values to e.g. manifests, which it does. MWA uses name fields to identify the user of a computer, for example, but munki doesn't need nor document that.
You can ask the MR-PHP folks what keys they expect, I don't believe they support the feature you're hinting at, which is to say multi-tenancy. Good luck

**Comment by gregneagle** [comment]
Closing this is is not a Munki issue or an enhancement request for Munki, and Allister's reply covers it!
