### ISSUE TITLE
managedsoftwareupdate crashes on 10.6.8, when profile pkginfo autoremoval set to true

### ISSUE THREAD

**Issue by schwifty** [munki/munki#475]
Slightly doctored pkginfo:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>PayloadIdentifier</key>
	<string>com.blah</string>
	<key>_metadata</key>
	<dict>
		<key>munki_version</key>
		<string>2.2.0.2399</string>
		<key>os_version</key>
		<string>10.6.8</string>
	</dict>
	<key>autoremove</key>
	<false/>
	<key>catalogs</key>
	<array>
		<string>development</string>
		<string>testing</string>
		<string>production</string>
	</array>
	<key>display_name</key>
	<string>Settings for 802.1x</string>
	<key>installer_item_location</key>
	<string>Settings_for_8021x-1.5.mobileconfig</string>
	<key>installer_item_size</key>
	<integer>20</integer>
	<key>installer_type</key>
	<string>profile</string>
	<key>minimum_munki_version</key>
	<string>2.2</string>
	<key>minimum_os_version</key>
	<string>10.7</string>
	<key>name</key>
	<string>Settings_for_8021x</string>
	<key>preinstall_script</key>
	<string>#!/bin/sh

echo "hello world"

exit 0
	</string>
	<key>unattended_install</key>
	<true/>
	<key>unattended_uninstall</key>
	<true/>
	<key>uninstall_method</key>
	<string>remove_profile</string>
	<key>uninstallable</key>
	<true/>
	<key>version</key>
	<string>1.5</string>
</dict>
</plist>
```

10.6.8 clients running munkitools 2.2.4.2431 and 2.2.4.2466 run successfully when autoremove is set to false, but when set to true this happens:

admin$ sudo /usr/local/munki/managedsoftwareupdate -vvvvv -a
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 1038, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 734, in main
    updatecheckresult = updatecheck.check(client_id=options.id)
  File "/usr/local/munki/munkilib/updatecheck.py", line 2975, in check
    dummy_result = processRemoval(item, cataloglist, installinfo)
  File "/usr/local/munki/munkilib/updatecheck.py", line 2227, in processRemoval
    if evidenceThisIsInstalled(item):
  File "/usr/local/munki/munkilib/updatecheck.py", line 1395, in evidenceThisIsInstalled
    if profiles.profile_is_installed(identifier):
  File "/usr/local/munki/munkilib/profiles.py", line 254, in profile_is_installed
    if identifier_in_config_profile_info(identifier):
  File "/usr/local/munki/munkilib/profiles.py", line 75, in identifier_in_config_profile_info
    for profile in config_profile_info().get('_computerlevel', []):
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by gregneagle** [comment]
I think this https://github.com/munki/munki/commit/e988ba19934529533e22d22bfd1effca31873f25 fixes that issue.

**Comment by schwifty** [comment]
Fix confirmed! Thanks as always, for everything.
