### ISSUE TITLE
Total Disk Space

### ISSUE THREAD

**Issue by computeronix** [munki/munki#478]
Looking in the database there is available disk space of clients but not total disk space.  Could you also pull total disk space and put it in the report table next to available disk space?

**Comment by gregneagle** [comment]
Munich doesn't do any of this (maintaining any sort of database or tables). Are you thinking of/referring to MunkiRepot-PHP or MunkiWebAdmin or Sal or one of the other reporting/management add-ons for Munki?

**Comment by computeronix** [comment]
Ohh dang yes Munkiwebadmin  sorry mentioned the wrong github from here


disregard :)


by the way, amazing product!!  Love it!!


Bill
________________________________

**Comment by computeronix** [comment]
https://github.com/munki/munkiwebadmin/issues/21
