### ISSUE TITLE
Applications in Munki that contain an Apostrophe in the Name will not install or uninstall (optional_installs key)

### ISSUE THREAD

**Issue by joshua-d-miller** [munki/munki#481]
Spoke with Greg on chat today and went through some troubleshooting steps as I am currently testing an application for one of our faculty members called TNEF's Enough (http://www.joshjacob.com/mac-development/tnef.php).  After importing this item into my Munki repository I attempted to install it using the optional_installs key which will allow a user to install it on their own.  When clicking the install button, nothing happens.  Per Greg's advice I examined both the Managed Software Center debugging log located at (/Users/Shared/.com.googlecode.munki.ManagedSoftwareUpdate.logs) and the system.log on the OS X system and NO log entries were written to either logs when clicking install.  If I remove the apostrophe from the Name in Munki then I am able to install the software no problem.  It is also worth noting that a piece of software with an apostrophe CAN be installed if it is in managed_installs.  For now, I'm just removing the apostrophe from the Name as it is ok if it is in the display_name but I thought I would submit this as an issue just in case anyone else might run into this issue.

**Comment by gregneagle** [comment]
Should be addressed by this commit: https://github.com/munki/munki/commit/73a1a33e801815f26d813a0313156514a3be43fc

**Comment by gregneagle** [comment]
Assuming this is fixed; will reopen if needed
