### ISSUE TITLE
Question - Munki 2.2.4 - Enrollment Profile

### ISSUE THREAD

**Issue by computeronix** [munki/munki#489]
Is it possible to push a replacement enrollment profile through munki using the new 2.2.4 update?

The current way I can think of doing this is via a self-created App and pushing it with Munki

**Comment by gregneagle** [comment]
I'd wrap it in a package and install it that way.

**Comment by gregneagle** [comment]
This type of question will get better exposure and better responses on the muni-dev and/or munch-discuss mailing lists/Google Groups.

**Comment by jessepeterson** [comment]
That is to say: [munki-discuss](https://groups.google.com/forum/#!forum/munki-discuss) and [munki-dev](https://groups.google.com/forum/#!forum/munki-dev).

**Comment by gregneagle** [comment]
Autocorrect is fun.
