### ISSUE TITLE
Move paths.d from Admin pkg to Core pkg

### ISSUE THREAD

**Issue by erikng** [munki/munki#491]
I'm not sure why I never noticed this until now, but it would be really nice if the munki paths.d file was installed from the core package and not the admin package.

As many people are using AutoPKG which splits the packages, your fleet will not receive this unless the admin package is also installed.

**Comment by gregneagle** [comment]
Would probably accept a pull request.

(Of course if you aren't installing the admin pkg, it implies you aren't using the CLI tools, and therefore do you really need the munki paths.d file?)

**Comment by erikng** [comment]
Great I'll actually look into it. 

As for the argument, if I SSH into a machine I get a different experience. It would make things faster for me to have the paths working in a shell.

**Comment by gregneagle** [comment]
And now the other argument: there's not much of a reason to _not_ install the Munki admin tools on client machines. They are no more "dangerous" than having defaults/PlistBuddy/ssh/scp/vi/etc on machines.

**Comment by erikng** [comment]
Up to you. PR sent.

**Comment by erikng** [comment]
Resolved.
