### ISSUE TITLE
Demonstration setup should include info about Server.app

### ISSUE THREAD

**Issue by ftiff** [munki/munki#497]
https://github.com/munki/munki/wiki/Demonstration-Setup

This is not too fancy, but it breaks the flow of the Demonstration setup as Server.app introduces some changes from the client version. I believe it's important enough to put some notes about it, even if the workflow clearly states it's for a client machine. 

1) sudo ln -s /Users/Shared/munki_repo /Library/WebServer/Documents/
-> need to specify `/Library/Server/Web/Data/Sites/Default` instead.

2) By default OS X with Server.app uses a redirect from HTTP to HTTPS, which might make the next command fail. You can disable that by doing this: Server.App > Websites, double-click on "Server Website" > Redirects > Edit… and delete the entry "https://{SERVER_NAME}".

**Comment by gregneagle** [comment]
I disagree that it "should" include info about Server.app. 

The introduction clearly states that the instructions here are NOT applicable for OS X Server. Nor are they applicable for RHEL7 or Debian or IIS or ngnix, etc, etc. The supported parameters are narrow.

If you want to write a new document that demonstrates a setup using OS X Server as the server, feel free. I no longer use OS X Server and cannot write nor vouch for the accuracy of any documentation around the use of OS X Server. (Nor do I care to setup OS X Server each year to test and verify Apple hasn't made any changes that affect the setup.) 

A Getting Started document should be simple and accurate and so I must be able to test and verify. I do not plan to include OS X Server instructions in the Getting Started document.

**Comment by nmcspadden** [comment]
For the record, I've got a blog post [here](https://osxdominion.wordpress.com/2015/02/26/setting-up-munki-with-os-x-yosemite-server/) that goes through this process.

**Comment by jaknz** [comment]
Would it be worth updating the Demo Setup page with a disclaimer and link to Nick's blog entry?

**Comment by gregneagle** [comment]
Done.
