### ISSUE TITLE
El Capitan style CSS

### ISSUE THREAD

**Issue by keeleysam** [munki/munki#504]
Managed Software Center currently uses modified CSS from the Mac App Store as it existed in 2013, so its visual style is that of 10.6.

This should be updated to the modern Yosemite style.

Here is the CSS which the Mac App Store currently uses:
https://s.mzstatic.com/htmlResources/BE06/da-storefront-base.css

It would be much easier to accomplish this if someone has the MAS CSS that it was originally based on so it is easy to tell what the changes were. Simply adding the additional Munki styles to the current CSS mostly works, but leaves non-functional buttons.

**Comment by keeleysam** [comment]
Here's an updated link for current CSS
https://s.mzstatic.com/htmlResources/7574/da-storefront-base.css

Help would be very much appreciated from someone with a strong understanding of CSS.

**Comment by weswhet** [comment]
@riscfuture here is most of the info regarding what we discussed. We would really appreciate the help :)

**Comment by RISCfuture** [comment]
Per @weswhet's request I have a 95%-finished branch: https://github.com/RISCfuture/munki/tree/el-capitan-css

The last page (Download) still has some display tweaks that are proving hard to fix. The rest of it should be close, if not a perfect match.

**Comment by gregneagle** [comment]
Perfect match isn't really a goal. This looks quite good.
What are the outstanding issues?

**Comment by gregneagle** [comment]
![screenshot 2016-03-09 15 10 20](https://cloud.githubusercontent.com/assets/700560/13653896/1e58437e-e609-11e5-84b5-17efcbad7765.png)

Is this one of the issues? Note how "No pending updates" is too far left and not aligned with "Other available updates"

**Comment by RISCfuture** [comment]
Yes, left-aligning things was one of the issues.

**Comment by gregneagle** [comment]
Here's my fix for that:

```
diff --git a/code/apps/Managed Software Center/Managed Software Center/WebResources/updates.css b/code/apps/Managed Software Center/Managed Software Center/WebResources/updates.css
index 0f38282..42c19f1 100644
--- a/code/apps/Managed Software Center/Managed Software Center/WebResources/updates.css        
+++ b/code/apps/Managed Software Center/Managed Software Center/WebResources/updates.css        
@@ -59,7 +59,11 @@ div.installations th {
 }
 
 #update-count-string {
-    margin-left: -10px
+    /*margin-left: -10px*/
+}
+
+#updates-progress-spinner {
+    margin-right: -10px;
 }
 
 div.installations th:first-child {
```

**Comment by gregneagle** [comment]
BTW, when originally working on MSC.app, I found it very useful to run MSC.app, then load the html files from here ~/Library/Caches/com.googlecode.munki.ManagedSoftwareCenter/html/ into Safari and use its web inspector to debug HTML and CSS.

**Comment by RISCfuture** [comment]
… That would have been very helpful …

**Comment by gregneagle** [comment]
Tim: I've merged your work into an el-capitan-css branch in this repo. Hopefully we can get some more eyes on it and resolve any remaining issues.

https://github.com/munki/munki/tree/el-capitan-css

**Comment by bruienne** [comment]
Tested here with our minor customizations (banner image) and everything looks great. It's going out to a larger test channel now for further review and verification nothing else breaks.

Tentative 👍 LGTM

**Comment by gregneagle** [comment]
@RISCfuture several minor CSS tweaks in my branch (https://github.com/munki/munki/tree/el-capitan-css) fixing all the display issues I've noticed so far...

**Comment by weswhet** [comment]
<img width="87" alt="screen shot 2016-03-14 at 1 46 27 pm" src="https://cloud.githubusercontent.com/assets/6865785/13759445/7782d82a-e9eb-11e5-9ebe-da3a563a3d89.png">

Has anyone noticed the bottom of the navigation buttons looks off?

**Comment by gregneagle** [comment]
Sure. Not at all related to webview CSS. You'll see the same thing with the "current" MSC.app There are other odd behaviors with the tool bar controls:

- Retaining "disabled" visual status (as in your image)
- Updates icon sometimes draws the incorrect size (usually/always? when badged).

Neither of these behaviors are new. It would be nice to fix them, but again, they are not connected to changes in html+css in the web views.

**Comment by gregneagle** [comment]
BTW, I've fixed some of these issues in the latest revision.

**Comment by gregneagle** [comment]
Merged to master here: https://github.com/munki/munki/commit/aa10492d5c96606a38068ec21e0f9fc8362da59e
