### ISSUE TITLE
App Transport Security has blocked a cleartext HTTP

### ISSUE THREAD

**Issue by RicknTx** [munki/munki#505]
Has anyone run into this before?

I'm seeing this while running managedsoftwareupdate from Terminal.

Managed Software Update Tool
Copyright 2010-2014 The Munki Project
https://github.com/munki/munki

Starting...
    Performing preflight tasks...
Checking for available updates...
2015-08-08 14:38:07.804 Python[10212:411439] App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.
ERROR: Could not retrieve manifest test_munki_client from the server: Error -1022: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.
ERROR: Could not retrieve managed install primary manifest.

I've found a few discussions and adding an entry to the Info.plist will address it, but I haven't figured out where to drop that in at yet.

**Comment by gregneagle** [comment]
I'd think mentioning that you are running this on a beta of OS X 10.11 El Capitan might be important as well.

I'll point you here: https://github.com/munki/munki/releases/tag/v2.3.0-RC1

And also suggest you should follow here: http://groups.google.com/group/munki-dev

**Comment by RicknTx** [comment]
Sorry Greg... 

I didn't think about that ..  My apologies for causing any troubles...  

Respectfully... Rick
