### ISSUE TITLE
OS X 10.11 policy banner obscures Munki progress bar at login window

### ISSUE THREAD

**Issue by jimrt** [munki/munki#508]
I'm not sure if this is an Apple bug or a Munki bug. 

-OS X 10.11 (latest beta)
-Munki tools (2.3.0.2520)

We have user agreement text saved in /Library/Security/PolicyBanner.txt . When Munki is performing an install at the login window, the progress bar is obscured by the policy banner window. OS X 10.10 and below do not have this issue. I do not see any errors in the logs (at least not with logging set to the default level). It's not a huge deal, but it is nice to see that Munki is doing something without having to dismiss the banner every few seconds.

**Comment by natewalck** [comment]
If you could grab a screenshot or picture of this, that may be helpful as well.

**Comment by gregneagle** [comment]
"I'm not sure if this is an Apple bug or a Munki bug." or none of the above!

Something behaving differently in a new OS is not necessarily a _bug_.

I'm guessing Apple has changed the NSWindowLevel of the Policy Banner in order to guarantee its visibility.

If someone wants to look at this and can find a fix/workaround, I'll accept a PR. It's not likely to be high on my list in the near future.

**Comment by jimrt** [comment]
Bug may be the wrong term, but it's definitely an unwanted (at least for my organization) change in behavior. If I can figure something out in the code, I will submit a PR.

**Comment by bruienne** [comment]
We ran into the same issue. To work around it (of sorts) we decided to delay the policy banner until after the user successfully logs in but before the Desktop appears by modifying the `mechanisms` section of `system.login.console` in the authorization DB. We use a Python script to perform the check and modification as part of the Munki preflight but the same process can be accomplished with a shell script, or possibly using ObjC or Swift and system frameworks. Script is as follows:

```
import subprocess
import plistlib
import sys

# Our read and write commands to the authorizationdb
readcmd = ['/usr/bin/security', 'authorizationdb', 'read', 'system.login.console']
writecmd = ['/usr/bin/security', 'authorizationdb', 'write', 'system.login.console']

# Run the read task, get the contents of system.login.console
task = subprocess.Popen(readcmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
(out, err) = task.communicate()
pl = plistlib.readPlistFromString(out)

# Pop the first item in the list, this should be builtin:policy-banner
banner = pl['mechanisms'].pop(0)

# If the popped item is not the policy-banner we bail, something is not right
if 'builtin:policy-banner' in banner:
    print "NOTICE: Changing policy-banner to be last item in system-login-console."
    pl['mechanisms'].append(banner)
    input_plist = plistlib.writePlistToString(pl)

    # Write the plist back to the authorizationdb
    task = subprocess.Popen(writecmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    (out, err) = task.communicate(input=input_plist)
else:
    print "WARNING: Policy banner was not first item, not making changes."
    sys.exit(-1)
```

**Comment by gregneagle** [comment]
Addressed here: https://github.com/munki/munki/commit/67c2a3f52dfa0ef33c239b6ea25d80bed8f90868
