### ISSUE TITLE
OS X 10.10 Policy Banner

### ISSUE THREAD

**Issue by josephbeck17** [munki/munki#509]
In 10.10 if you click the Accept button on the policy banner while an install is taking place it will automatically place the curser in the username box, allowing you to login and interrupt the install. Not sure if there's anything that can be done about this from your end, just wanted to make sure it was reported.

**Comment by gregneagle** [comment]
Addressed here: https://github.com/munki/munki/commit/67c2a3f52dfa0ef33c239b6ea25d80bed8f90868
