### ISSUE TITLE
silent upgrades of munki while MSC is open leads to unexpected results.

### ISSUE THREAD

**Issue by erikng** [munki/munki#514]
After sending out the latest munki version silently, I noticed a few test VMs displayed oddities with items in MSC.app. A few users also reported the issue.

When managedsoftwareupdate --auto runs while MSC.app is already open, this happens.

![screen shot 2015-09-02 at 9 06 22 pm](https://cloud.githubusercontent.com/assets/5685016/9649190/152961d4-51b7-11e5-9bbb-152cad3ecf69.jpg)

**Comment by gregneagle** [comment]
Almost certainly related to this commit: https://github.com/munki/munki/commit/73a1a33e801815f26d813a0313156514a3be43fc

I'm not likely to have the time to dig into this in the near future, so if other people want to dig in, feel free.

**Comment by erikng** [comment]
Sounds like a one time issue though right? If so, it's not a big deal. I will test silently updating munki tomorrow and report what happens.

**Comment by gregneagle** [comment]
A note: this might be considered "expected" if MSC.app is open and Munki is upgrading from a version before the above referenced commit to one after it. The templates stored on-disk get changed, but the new code that knows how to use the new templates isn't (usually) active until the next time MSC.app is launched. This type of thing has the potential to occur any time MSC.app is updated, but is almost always a temporary cosmetic issue.

**Comment by erikng** [comment]
After testing this again this morning I definitely agree with that statement. Subsequent upgrades through --auto are fine. I don't think there's any fix needed. You can close it if you would like. 

If needed I can make a post on munki-dev to inform other admins about this potential "issue".

**Comment by gregneagle** [comment]
Closing.
