### ISSUE TITLE
Log Window

### ISSUE THREAD

**Issue by ryness** [munki/munki#515]
Feature request: show an optional log window when running MSC via the GUI and/or the option to display values like manifest, repo URL, etc.

**Comment by arubdesu** [comment]
Hey there. Pardon, but there already are two log windows GUI's you could use: Console.app and Terminal.app when running with `/usr/local/munki/managedsoftwareupdate -vv`. If this really should be in the core product, could you mockup what it would look like?

**Comment by jessepeterson** [comment]
I've thought about this issue before — it's been requested by people I work with. I think something subtle would be all that's required. Perhaps some small text in the About window of MSC. Or make the variables for URL, Catalog, etc. available to the HTML templating system and leave it up to the admins to show the URL somewhere if they desire, where they desire in the main window. Perhaps a discussion for the mailing lists.

However, @ryness, if your intent is to have quick access to know which clients are on which manifests I'd suggest something like [MunkiWebAdmin](https://github.com/munki/munkiwebadmin) or [MunkiReport-PHP](https://github.com/munkireport/munkireport-php). Setup is pretty straight forward and once you get used to using a "dashboard" type app to view/review/manage Munki at least I found the concern at the client-side is just not much of an issue.

**Comment by gregneagle** [comment]
See also #586. My inclination is still not to add this functionality.

**Comment by weswhet** [comment]
I agree with not having a logging window on MSC, however one for munki status at the logout window would be useful. Similar to the one with OS X Installer. CMD+L gives you a log view. Right now to view live logs during the logout window you would need to ssh in, but that can be difficult(impossible) if a client is on wifi and disconnects at the logout window.

**Comment by gregneagle** [comment]
@weswhet See https://github.com/munki/munki/tree/munkistatus-logwindow

**Comment by weswhet** [comment]
Beautiful. 

<img width="1146" alt="screen shot 2016-04-19 at 6 32 59 pm" src="https://cloud.githubusercontent.com/assets/6865785/14661166/5aeedfec-0660-11e6-8ab8-c319ed2cf5e0.png">

**Comment by gregneagle** [comment]
I see you even have a custom location for the log and the code handled it correctly.
I added the path view just to have something in that space, but I think it also aids in log location discoverability for people new to Munki.

**Comment by weswhet** [comment]
Agree completely. One thing I noticed in testing was if you take focus from the log window back to MunkiStatus you can't just reclick the log window to take focus back. You have to (CMD+L) again in order to bring focus back. Not a show stopper by any means but I figured I would bring it up.

**Comment by gregneagle** [comment]
This is related to the translucent "masking" windows (one per display) that keep you from activating the login window. They are child windows of the status window, which prevents them from becoming active when you click on them. But when you bring the status window frontmost, it brings its child windows (the masking windows) with it, moving them in front of the log window.

Since the masking windows are now in front of the log window, you cannot click on the log window to bring it frontmost.

I can't think of any way to really address this without causing other issues.

**Comment by gregneagle** [comment]
I have some code locally that addresses the log window activation issues, but at the expense of bringing back some of the issues that present themselves when a loginwindow banner is present.

If I'd known how complex this was going to end up being, I would have just said "no" to the log window for MunkiStatus. The upside is that adding a log window to Managed Software Center.app will now be extremely simple...

**Comment by gregneagle** [comment]
(In actuality, it's just the stupid loginwindow banner behavior that increases the complexity here -- perhaps we just make the UX slightly worse for sites that have a loginwindow banner and call it a day)

**Comment by weswhet** [comment]
Sounds like a reasonable sacrifice. Add a wiki note for that use case and call it a day. :)

**Comment by poundbangbash** [comment]
Define worse.  We have a mandated acceptable use policy banner on our systems. The munki 2.6.1 changes make the experience nicer in 10.11 with the transparency layering on top of the banner.

**Comment by gregneagle** [comment]
Try the current munkistatus-logwindow code for worse.

**Comment by gregneagle** [comment]
Updated munkistatus-loginwindow here: https://github.com/munki/munki/commit/d9ef976d4c1116290e163fba628c39b28c354902

Brief testing on 10.6.8, 10.8.5 and 10.11.4 so far. If there is a loginwindow PolicyBanner on 10.11+, and you:

1) open the log window with Command-L
2) Move it aside an click the status window, bringing it to the front
3) The log window moves _behind_ the translucent masking windows and cannot be brought forward by clicking. 
4) Workaround: hit Command-L again.

**Comment by gregneagle** [comment]
A few subsequent commits, so please test with the latest commit to munkistatus-loginwindow.
(I also successfully tested on 10.9.5)

**Comment by poundbangbash** [comment]
I just built and tested against 10.11.4.  It works as described.  If the "worse" is the fact that to bring the log back to focus is issuing command-L I think that's acceptable.  One would hope that understanding the content of said log requires enough skill set to not be burdened by another key command.

**Comment by gregneagle** [comment]
Question for you, @weswhet : you've customized the location of the main Munki log. Is that file readable by unprivileged users? If I were to add a log window to Managed Software Center, sound like I need to account for the possibility I can't actually read the log file...

**Comment by weswhet** [comment]
my custom log file is readable by everyone. I would image you are looking at a 1% scenario where the log file isn't readable.

**Comment by gregneagle** [comment]
As of this commit https://github.com/munki/munki/commit/820718aaf02582e86bc911abbd6250b4dd851c7a both MunkiStatus and Managed Software Center have log windows.
