### ISSUE TITLE
 Amazon S3 REST API

### ISSUE THREAD

**Issue by erikaulin** [munki/munki#516]
Hi, would really love if Munki Client would support AWS REST API header authentication.
Use case would be deploying munki repos on Cloud Front to get them distributed across the globe.

From my understanding it's a need to extend the munki client to handle the following parameters.
Your AWS access key ID, The time when the signature expires (in seconds since 00:00:00 UTC 1970) and The URL encoding of the Base64 encoding of the HMAC-SHA1 of StringToSign.

Found a php and bash script that does this at this website:
http://docs.unified-streaming.com/tutorials/cloud/s3-authorization.html#using-query-parameters

Cheers!

**Comment by gregneagle** [comment]
This sounds interesting, but not something I would plan to implement or support in the near future. (Largely because I d not need this feature and don't want to do all the setup needed to get to the point where I could implement and test.) I think it would make the most sense for you and/or other interested parties to work on adding this yourself -- you are in the best position to test and iterate.

**Comment by bruienne** [comment]
This sounds interesting. To get started, there's a decent Python example using standard modules here: http://mashupguide.net/1.0/html/ch16s05.xhtml I'd say the idea would be to run all S3-bound calls for payloads through an S3 URL-prepper if so configured via global Munki config, with some additional plist keys to store AWS Access ID and key.

Modified from the above URL to calculate a hypothetical Authorization signature for an Adobe Flash pkg:
```
import sha, hmac, base64, urllib
    AWSAccessKeyId = "0PN5J17HBGZHT7JJ3X82"
    AWSSecretAccessKey = "uV3F3YluFJax1cknvbcGwgjvx4QpvB+leU8dUj2o"
    Expires = 1175139620
    HTTPVerb = "GET"
    ContentMD5 = ""
    ContentType = ""
    CanonicalizedAmzHeaders = ""
    CanonicalizedResource = "/mymunkirepo/pkgs/AdobeFlashPlayer-99.99.pkg"
    string_to_sign = HTTPVerb + "\n" +  ContentMD5 + "\n" +  ContentType + "\n" + \
        str(Expires) + "\n" + CanonicalizedAmzHeaders + CanonicalizedResource
    sig = base64.b64encode(hmac.new(AWSSecretAccessKey, string_to_sign, sha).digest())
    print urllib.urlencode({'Signature':sig})
```
```
$ python S3-signature.py
Signature=x29Ul0geMk%2FPY9FdSJ2TwEPFGcY%3D
```
The request could then be made for `http://mymunkirepo.s3.amazonaws.com/pkgs/AdobeFlashPlayer-99.99.pkg?AWSAccessKeyId=0PN5J17HBGZHT7JJ3X82&Signature=x29Ul0geMk%2FPY9FdSJ2TwEPFGcY%3D&Expires=1175139620` and appease the S3 API gods enough to retrieve the file.

**Comment by gregneagle** [comment]
This would be addressed if/when pull request #580 is merged -- you'd then provide a middleware module that either modified the URLs (adding the query parameters) or set the appropriate headers.

**Comment by gregneagle** [comment]
#580 was merged a little over a week ago. There's some documentation that needs to be written, and sample middleware that needs to be posted, but the functionality is there. @waderobson: please get some basic documentation up!

**Comment by waderobson** [comment]
I haven't forgotten about this. @gregneagle Have a look here https://github.com/waderobson/middleware_docs
I'm not sure if that's enough or too much. And I wasn't sure on the wiki etiquette, do I just drop this page in?

**Comment by gregneagle** [comment]
I copied it (with minor edits) here: https://github.com/munki/munki/wiki/Middleware. Munki wiki is open to anyone, so you can tweak or add as you find things to clarify/expand upon.
