### ISSUE TITLE
pkginfo pre_action alerts with scrollbars causing MSC.app to exhibit odd issues and occasional crashes

### ISSUE THREAD

**Issue by erikng** [munki/munki#517]
This seems to impact Munki 2.0.1 official release all the way through the current commit.

Prereq
- Item with pre_install/uninstall/upgrade action.
- MSC.app is small enough/has enough items available via Self Service that the scrollbar appears.

If a user attempts to install the software via the Software or Categories tab, MSC.app will show odd graphical issues and may even crash. You can replicate this with the following steps:
1. Make sure testing vm/machine has 4+ self service packages
2. Add a pre_install alert to one of the items.
3. Open MSC and make it as small as possible.
4. Go to the Updates tab, making the scrollbar appear on the right side.
5. Go back to Software tab and select software with alert. Accept alert.
6. Immediately cancel software after seeing cog wheel
7. Select software again and accept alert.
8. Immediately cancel software

**Comment by keeleysam** [comment]
Can you do a screen recording/take some screenshots so we can be sure that we are seeing the same issues?

Can you also give us your OS version and if the display is Retina or not?  Some other graphical issues tie into that.

**Comment by erikng** [comment]
https://www.dropbox.com/s/p55heuyha5ul4nm/MSC_Alert_Crash.mov?dl=0

This video is from a VM, however I experience it on an iMac 21" Non Retina.

OS X 10.10.5

**Comment by natewalck** [comment]
Do you have the stack trace for this? I saw the error window, not sure how useful that stack trace would be.

Post the stack trace and maybe check logs, try launching it via command line (/Applications/Managed\ Software\ Center.app/Contents/MacOS/Managed\ Software\ Center) and see if it yields any good info, etc.

**Comment by erikng** [comment]
I didn't save it but I'll try and spin up a VM sometime this week to grab one.

**Comment by erikng** [comment]
Little late to the party, but here is the crash itself, recreated with the changes Greg made last week.

[Managed Software Center_2015-11-30-104704_D25GM0DEDHJR.txt](https://github.com/munki/munki/files/47529/Managed.Software.Center_2015-11-30-104704_D25GM0DEDHJR.txt)

**Comment by erikng** [comment]
It appears this issue may be limited to Yosemite machines, with Scrollbars set to "Automatic" when using a _wired_ mouse. It may be even more limited to a specific graphics driver.

I have not tested pre-Yosemite, but El Capitan does not have this issue on the same machine type/conditions.

**Comment by gregneagle** [comment]
Closing this old issue  -- wasn't reproducable a year ago and have had no reports in a long time.

**Comment by erikng** [comment]
Fine with me. It's no longer my issue anyway. :P
