### ISSUE TITLE
Optional installs fail when /Users/Shared is not present

### ISSUE THREAD

**Issue by arubdesu** [munki/munki#519]
Ran into this issue due to lack of `/Users/Shared` folder: when clicking 'Install' button for an optional install, the spinner rotates for about 5 seconds while the red 'Downloading' text displays, then resets the button text to 'Install'. Once I restored the `/Users/Shared` folder installs once again worked, but some sort of failure feedback would be good.

**Comment by aysiu** [comment]
Would it make more sense to give failure feedback "Your /Users/Shared folder is missing and is necessary" or to just correct it (Munki checks if /Users/Shared is missing and, if so, creates it)?

**Comment by natewalck** [comment]
/Users/Shared exists on all new systems, so it was deleted somewhere along the way (stating the obvious here).

I'd think it is fairly safe to create the directory with the default permissions if it is missing, but that is approaching config management territory.

**Comment by gregneagle** [comment]
Managed Software Center is running as the current user. We probably cannot create the /Users/Shared directory.

**Comment by natewalck** [comment]
Just tested that, a normal user cannot created Shared. So a warning is the best bet.

**Comment by arubdesu** [comment]
Nope, wants to be root:wheel 777. And for the curious as to how we ended up without one, we backed up the `/Users/specificuser` path to an external drive with CarbonCopyCloner, wiped the disk, and then on restore didn't point to the subfolder inside /Users as the source, instead bulldozing /Users with the contents ending up as only the one home folder being restored.

**Comment by gregneagle** [comment]
Please test to see if this commit https://github.com/munki/munki/commit/4ad7237f23b716a814d3f7a1d6a5164a72323447 adequately addresses the issue.

**Comment by gregneagle** [comment]
I believe this issue has been addressed for a while.
