### ISSUE TITLE
Rename munki manifest

### ISSUE THREAD

**Issue by islamadel** [munki/munki#521]
Hello,
I would like to be able to rename my manifests, without losing any further dependencies with other included manifests.
can u recommend a safe method to do that, so that all dependencies get automatically renamed?

example:
manifest name package_1
has included_manifests: pack_2
I would like to rename pack_2 to pack_x

and the included_manifest pack_2 in package_1 should be rename also to pack_x

**Comment by erikng** [comment]
There isn't an automatic way to do this. The best approach would probably be a script.

**Comment by islamadel** [comment]
can anyone here donate that script? :)

**Comment by arubdesu** [comment]
'Here' is not a mailing list, nor is this code-specific. Feel free to ask on https://groups.google.com/forum/#!forum/munki-discuss or whichever you feel is appropriate here: https://github.com/munki/munki/wiki/Discussion-Group

**Comment by natewalck** [comment]
As Allister mentioned, please post this to munki-discuss. Issues are reserved for specific problems with Munki and feature requests.

**Comment by islamadel** [comment]
Ok, Thanks. If possible please consider it as a feature request

**Comment by natewalck** [comment]
I think this is something that would be best left up to the admin. You know exactly what you need and it would be hard for someone else to write that functionality and give you exactly what you are looking for.

If you end up writing a script for this, definitely share it. I am sure others could adapt it to their own environments.

**Comment by arubdesu** [comment]
The closest/most currently applicable place one could look for inspiration for such a script, within this project, is probably https://github.com/munki/munki/blob/master/code/client/manifestutil
