### ISSUE TITLE
def profile_needs_to_be_installed() should check if a higher version is already installed

### ISSUE THREAD

**Issue by maverickagm** [munki/munki#527]
Use Case: I have hundreds of systems all configured with a configuration profile (.mobileconfig file) that activates the screensaver after 20 minutes. I created an updated mobileconfig file that sets screensaver activation after 2 hours. The 2 hour screensaver config gets installed only on a select few hosts and the mobileconfig file is written so that the 2 hour config is an upgrade to the 20 minute config. 

Both configuration profiles have the same PayloadIdentifier and PayloadUUID.
Both configuration profiles have the same PayloadIdentifier and PayloadUUID within the PayloadContent array section.
The PayloadVersion is set to 1 within the 20 minute screensaver mobileconfig file, and 2 within the 2 hour screensaver mobileconfig file (the same is done in the PayloadContent array section as well). 

When both the mobileconfig files are installed via the profiles command line, everything works fine. The 2 hour config deprecates the 20 minute config. 

When the mobileconfig files are installed via munki, munki continually wants to reinstall the deprecated 20 minute mobileconfig file. The reason is that "/Library/Managed Installs/ConfigProfileData.plist" stores a file hash of one of the mobileconfig files. Bacause both mobileconfig files have the same PayloadIdentifier, one of the two will always want to reinstall. The file hash should be associated with the version of the PayloadIdentifier. Perhaps the keys of ConfigProfileData.plist should be in the format of "{PayloadIdentifier}-{PayloadVersion}" instead of just "{PayloadIdentifier}". This way munki can be capable of deprecating configuration profiles with other configuration profiles.

**Comment by gregneagle** [comment]
Configuration profiles do not have internal version numbers.

The "PayloadVersion" key is not for your use to version a configuration profile; it is for Apple's use to indicate the version of the configuration profile _format_.

The pkginfo file for a configuration profile can and _should_ be given a useful version number . The pkginfo file for your "2 hour screensaver mobileconfig file" should have a higher version number than the one you do not want to use any longer.

If you version the pkginfo files for your config profiles, Munki will behave as you expect.

**Comment by maverickagm** [comment]
Ah. Thanks Greg. That clarifies a few things. Perhaps I'll go about it with an installcheck_script so that not every host gets the update.

**Comment by erikng** [comment]
There is no need to do that. Simply up the version on the pkginfo file.
