### ISSUE TITLE
Installs Array does not appear to be working

### ISSUE THREAD

**Issue by ltinker** [munki/munki#535]
Hey All,

So maybe im doing something wrong here,
but for what ever reason it appears the Installs Array is not working in my environment,

I am using OS X 10.10 clients with managed software update version 2.2.0.2376

I'll start backwards as to where things are at the moment,
due to using installs type as bundle and it not working i changed to using just the file type
```
	<key>Installs</key>
	<array>
		<dict>
			<key>path</key>
			<string>/Applications/Microsoft Office 2011/Office/Startup/Word/EndNote CWYW Word 2011.bundle/Contents/info.plist</string>
			<key>type</key>
			<string>file</string>
		</dict>
	</array>
```

prior to that i was actually using the bundle details provided by makepkginfo.

```
	<key>Installs</key>
	<array>
		<dict>
			<key>CFBundleShortVersionString</key>
			<string>17.4.0.10646</string>
			<key>CFBundleVersion</key>
			<string>2015.17.4.0.10646</string>
			<key>path</key>
			<string>/Applications/Microsoft Office 2011/Office/Startup/Word/EndNote CWYW Word 2011.bundle</string>
			<key>type</key>
			<string>bundle</string>
			<key>version_comparison_key</key>
			<string>CFBundleShortVersionString</string>
		</dict>
	</array>
```

after installation and removing the bundle files
`managedsoftwareupdate --checkonly -vvv` returns  

```
* Processing manifest item EndNoteX7CWYW for install
    Looking for detail for: EndNoteX7CWYW, version latest...
    Considering 1 items with name EndNoteX7CWYW from catalog dev
    Considering item EndNoteX7CWYW, version 17.4 with minimum os version required 10.9.0
    Our OS version is 10.10.3
    Found EndNoteX7CWYW, version 17.4 in catalog dev
    EndNoteX7CWYW version 17.4 (or newer) is already installed.
    Looking for updates for: EndNoteX7CWYW
    Looking for updates for: EndNoteX7CWYW-17.4
    Looking for updates for: EndNoteX7CWYW--17.4
```
showing it thinks its still installed.

updating the manifest so the pkg name is in the 'Managed Uninstalls' array after having manually removed the files and then rerunning `managedsoftwareupdate --checkonly -vvv` returns   
```
 * Processing manifest item EndNoteX7CWYW for removal
    Looking for all items matching: EndNoteX7CWYW...
    Adding item EndNoteX7CWYW, version 17.4 from catalog dev...
    Considering item EndNoteX7CWYW-17.4 for removal info
    EndNoteX7CWYW-17.4 not installed.
    EndNoteX7CWYW doesn't appear to be installed.
```

showing it already recognises it as removed,
so I'm really quite confused as to whats going on here,
there are no recipe details in the pkginfo as it was the first thing i removed even though i know the installs array is used if it exists so the receipt details should not be getting used.

has any one got a better idea as to where to look to troubleshoot this better or can see anything glaringly obvious as to what i have missed?

**Comment by gregneagle** [comment]
Keys are case-sensitive. "Installs" != "installs".

**Comment by ltinker** [comment]
I felt it was something glaringly obvious.

 thanks Greg,
