### ISSUE TITLE
munkiimport arbitrary files

### ISSUE THREAD

**Issue by keeleysam** [munki/munki#541]
(opening this for myself)

I would like for munkiimport to be able to import any file, not just application bundles, packages, and profiles.

For example, you may want to place the Adobe Flash mms.cfg with Munki using a copyfromdmg and ensure its contents match the hash you expect, but this currently requires manually making a dmg and using makepkginfo along with importing it manually.

**Comment by gregneagle** [comment]
Be careful that you don't start reinventing Apple packages.

**Comment by gregneagle** [comment]
No plans to do this.
