### ISSUE TITLE
Bootstrap issues with setting SoftwareRepoURL 10.11

### ISSUE THREAD

**Issue by xEnt22** [munki/munki#544]
Hi all,

My workflow is not bootstrapping after leaving deploy studio when using 10.11, if i use the exact same workflow with 10.10 it bootstraps fine. i checked the munki logs and it seems it tries to bootstrap, but has the error 'the url is the default munki and is insecure' bla bla, basically saying the SoftwareRepoURL has not been set and pointing to our munki repository. whats even stranger is, once i create an account and manually run a managedsoftwareupdate, it is all of a sudden set and working.

Here is my DS script to set the repository and bootstrap. (i have a separate script after to set the ClientIdentifier) . both scripts are launched on first boot.

#!/bin/sh

defaults write /Library/Preferences/ManagedInstalls SoftwareRepoURL "http://svr-munki/repo"
defaults write /Library/Preferences/ManagedInstalls SuppressStopButtonOnInstall -bool true
touch /Users/Shared/.com.googlecode.munki.checkandinstallatstartup

exit 0

**Comment by gregneagle** [comment]
This is not an issue with Munki itself. This is possibly an issue with Deploy Studio, your workflow, your script, or your configuration. Please consider posting for help on the munki-discuss Google Group: https://groups.google.com/forum/#!forum/munki-discuss

(You might consider creating a CNAME of "munki" pointing to "svr-munki", and have a package on your Munki server set the "correct" defaults...)
