### ISSUE TITLE
preuninstall_alert dialog not shown when removal started on "My Items"

### ISSUE THREAD

**Issue by rmanly** [munki/munki#545]
A preuninstall_alert is not shown to the user when the software removal is initiated on the "My Items" tab of the MSC gui.

**Comment by gregneagle** [comment]
Ping @erikng @bartreardon

**Comment by gregneagle** [comment]
Please test https://github.com/munki/munki/commit/8fc18792c846bd45f72547192a8de53030234c04

**Comment by rmanly** [comment]
This issue appears resolved.
