### ISSUE TITLE
software removal cancellation removes item from "My Items"

### ISSUE THREAD

**Issue by rmanly** [munki/munki#546]
If a software removal is cancelled the item in question will no longer be listed in "My Items"

**Comment by gregneagle** [comment]
'My Items" is really the list of items in the SelfServeManifest's managed_installs section.

Using MSC.app, one can uninstall both items listed in managed_installs, and those installed some other way (and therefore not listed in managed_installs). Clicking "Remove" on an item adds the item to managed_uninstalls of the SelfServeManifest, (and removes it from managed_installs of the same manifest).

If a user then cancels the uninstall, we remove the item from the managed_uninstalls, but we've lost the any information on whether or not that item was previously in managed_installs.

To address this issue we'll need to track the state of items that were moved from managed_installs to managed_uninstalls differently than items that are only added to managed_uninstalls.

**Comment by gregneagle** [comment]
Please try https://github.com/munki/munki/commit/a96d55ca49562df730ed1c4314f5d195ee4f5c41

**Comment by rmanly** [comment]
Tested with a "regular" optional pkg (no alerts) and clicking both the Cancel button on the Software tab and the Cancel Removal button on My Items. Both functioned as expected, the item remained in My Items.

I also tested a pkg with a with a preuninstall_alert. Cancelling from the alert, the cancel removal, and the cancel button all stopped the uninstall while keeping the item in the My Items list.
