### ISSUE TITLE
Issue when checking managed installs config and entering sudo command

### ISSUE THREAD

**Issue by avasquez3593** [munki/munki#550]
When entering the following sudo command to check for updates and see if my configuration has worked. This happens..

sudo /usr/local/munki/managedsoftwareupdate -vv
Managed Software Update Tool
Copyright 2010-2014 The Munki Project
https://github.com/munki/munki

Starting...
    No client cert info provided, so no client keychain will be created.
Checking for available updates...
    Getting manifest bootstrap...
    Retrieving list of software for this machine...
    Bytes received: 291
    Status: 404
    Headers: {u'Content-Length': u'291', u'Keep-Alive': u'timeout=5, max=100', u'Server': u'Apache', u'Connection': u'Keep-Alive', u'Date': u'Mon, 07 Dec 2015 20:02:32 GMT', u'Content-Type': u'text/html; charset=iso-8859-1'}
ERROR: Could not retrieve manifest bootstrap from the server: HTTP result 404: not found
ERROR: Could not retrieve managed install primary manifest.
Checking Apple Software Update catalog...
    Caching CatalogURL https://swscan.apple.com/content/catalogs/others/index-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
    Status: 304
    Headers: {u'Expires': u'Tue, 08 Dec 2015 00:02:33 GMT', u'Keep-Alive': u'timeout=15, max=306', u'Server': u'Apache', u'Connection': u'Keep-Alive', u'Etag': u'"448359-5261a5fb11800"', u'Cache-Control': u'max-age=14400', u'Date': u'Mon, 07 Dec 2015 20:02:33 GMT'}
    Item is unchanged on the server.
    /tmp/munki_swupd_cache/mirror/apple.sucatalog already exists and is up-to-date.
    Skipping Apple Software Update check because sucatalog is unchanged, installed Apple packages are unchanged and we recently did a full check.
ERROR: Could not read plist: /Library/Managed Installs/manifests/client_manifest.plist
ERROR: plist does not exist.
    The following Apple Software Updates are available to install:
        + Security Update 2015-004-1.0
           *Restart required

Run managedsoftwareupdate --installonly to install the downloaded updates.
Finishing...
    Getting info on currently installed applications...
Done.

Can someone please help and tell me why these two error are coming up:
ERROR: Could not retrieve manifest bootstrap from the server: HTTP result 404: not found
ERROR: Could not retrieve managed install primary manifest.

When entering the following sudo command: sudo defaults write /Library/Preferences/ManagedInstalls SoftwareRepoURL "http://IP ADDRESS/munki_repo"

Is that format correct for the software repo URL?

**Comment by gregneagle** [comment]
GitHub issues are for reporting code issues with the Munki code, and not a general support mechanism. Please ask for help on the munki-discuss Google Group: https://groups.google.com/forum/#!forum/munki-discuss

See also: https://github.com/munki/munki/wiki/Troubleshooting

**Comment by gregneagle** [comment]
Closing since discussion is now on munki-discuss.
