### ISSUE TITLE
Components using gurl.py are vulnerable to POODLE

### ISSUE THREAD

**Issue by vineyard** [munki/munki#551]
I noticed this issue in `managedsoftwareupdate`, however any component that uses `gurl.py` for network communication is affected. While testing for man-in-the-middle vulnerabilities, I discovered that `gurl.py` enables SSLv3 with TLS_FALLBACK_SCSV. Enabling TLS_FALLBACK_SCSV with SSLv3 support allows a man-in-the-middle attacker to downgrade the protocol and cipher suite to one that is vulnerable to the [POODLE attack](https://www.openssl.org/~bodo/ssl-poodle.pdf).

Unfortunately, I don't believe Apple has offered support for setting custom SSL/TLS connection parameters (i.e. cipher suite, protocol version, etc.) until very recently. It looks like it should be possible to use [NSURLSession with NSURLSessionConfiguration](https://developer.apple.com/library/mac/documentation/Foundation/Reference/NSURLSessionConfiguration_class/#//apple_ref/occ/instp/NSURLSessionConfiguration/TLSMaximumSupportedProtocol) on Mac OS X 10.9+ to disable SSLv3 though.

**Comment by arubdesu** [comment]
pinging @pudquick

**Comment by gregneagle** [comment]
But if the _server_ is not supporting SSLv3 connections, is there an issue?

**Comment by vineyard** [comment]
Yes, it's still an issue. During my testing, the server I was connecting do did not support SSLv3. However, I was able to manipulate the TLS handshake as a man-in-the-middle and force the client to downgrade to SSLv3 anyway.

**Comment by gregneagle** [comment]
From the linked document: "The attack described above requires an SSL 3.0 connection to be established, so disabling the SSL 3.0 protocol in the client or in the server (or both) will completely avoid it."

**Comment by gregneagle** [comment]
There's little-to-no-hope of addressing this client-side for 10.6-10.8 clients.

**Comment by vineyard** [comment]
@gregneagle unfortunately that's the conclusion we came to as well. Google considers this significant enough that we are patching our internal implementation even if this won't be fixed upstream. I was advised to open this bug, as the issue affects more than just our fleet.

**Comment by gregneagle** [comment]
Patching it how?

Why would Google not share?

**Comment by vineyard** [comment]
I don't believe there'd be any reason for us not to share. I'm just not the one who'd be doing the work. The "fix" would most likely be reimplementing portions of `gurl.py` to replace `NSURLConnection` with `NSURLSession` and `NSURLSessionConfiguration`. Unfortunately I'm not a Mac developer myself - I'm a security engineer, so the specifics on remediating this particular issue are somewhat outside my area of expertise.

**Comment by vineyard** [comment]
If you're interested in performing your own testing, I found the issue using the open-source [nogotofail framework](https://github.com/google/nogotofail).

**Comment by vineyard** [comment]
To be clear, it would be our strong preference for the issue to be fixed upstream in the munki codebase, whether the patch comes from Google or from somewhere else. Unfortunately I don't have the expertise to offer any further guidance at this time beyond the links I've already provided.

**Comment by gregneagle** [comment]
That is likelier to happen sooner if the Google MacOps folk share their internal efforts.

**Comment by vineyard** [comment]
I've pinged them to see if we have any more information we can share.

**Comment by vineyard** [comment]
How critical is preserving support for systems older than 10.9? We're having some more internal discussions around this issue.

**Comment by gregneagle** [comment]
You'd have to ask all the people using Munki in the entire world. Since there are lots of EDU orgs using it,  I'd venture to guess that there are lots and lots of systems all the way back to 10.6.x.

Obviously, what you do internally can be different, as you have control over your Mac fleet.

**Comment by vineyard** [comment]
In that case, we'd probably have to do a conditional import and then branch based on the OS version. Does that sound reasonable?

**Comment by gregneagle** [comment]
Yes.

**Comment by gregneagle** [comment]
https://gist.github.com/gregneagle/1267c85cb235adbc642b

**Comment by vineyard** [comment]
This version ^^^ of gurl.py appears to resolve the vulnerability. After 24 hours of continuous man-in-the-middle testing, I was unable to reproduce the issue using your new code.

**Comment by gregneagle** [comment]
Closing this since it is fixed here: https://github.com/munki/munki/commit/b9944e95453530c20478b7326cf0db7637b754bd 
This change will be in the 2.6 official release, but people who want the fix sooner can run a version built from any GitHub revision on or after this one.
