### ISSUE TITLE
Please list component versions with Release

### ISSUE THREAD

**Issue by arubdesu** [munki/munki#558]
Please add this to the notes for the 2.4 release, like on https://munkibuilds.org/2.4.0.2561/:
```
core: 2.4.0.2561
admin: 2.4.0.2561
app: 4.1.2531
launchd: 2.0.0.1969
```

**Comment by gregneagle** [comment]
I'm not likely to be motivated to do the extra work, sorry.

**Comment by arubdesu** [comment]
In the time you replied and closed the issue, you could have hit the 'Edit release' button and appended this information... 
¯\_(ツ)_/¯

**Comment by gregneagle** [comment]
Not really. And then you'd expect me to do it for all releases always. That's what I'm not motivated to do. It's extra work that I don't want to commit to. The information _is_ available for those people who need it for some reason; it's just not part of the release notes. Lots of information potentially useful to some is not in the release notes -- that's unavoidable.
