### ISSUE TITLE
Dropped connection during updatecheck can lead to unexpected removals

### ISSUE THREAD

**Issue by gregneagle** [munki/munki#560]
Hi,

Using Munki with both included manifests and autoremove packages, I've encountered some unexpected (unintended?) behaviour when network connection is lost during a munki run.

If network connection is lost after the run has started, but before munki has downloaded the included manifests, it will automatically delete/uninstall all packages contained in those included manifests (that are marked autoremove).

I have usually seen this when there is a big package or update contained in one of these included manifests. The reason for this, I think, is because munki progresses like this:
- check main manifest
- check if pacakges are missing
- download packages
- check first included manifest
- check if pacakges are missing
- download packages
- check second incldued manifest
- check if pacakges are missing
- download packages

and so on. This means that the more included manifests, and the bigger the packages are, the greater the odds of packages being unexpectedly uninstalled.

I've reproduced this consistently by creating a small repository with dummy packages about 1GB of size set to autoremove, and assigned these to their own separate manifests. I've then included these in the manifest of the machine.
I then first do a complete run where munki downloads and installs all these packages.
Then I remove the package from the first included manifest, do another run, and see munki properly autoremoving it.
Next, I re-add the package to the first included manifest and do a new run of munki. See that it starts downloading the package, then unplug the network cable. Munki loses connection, and starts to autoremove all the packages in the remaining included manifests.

Not quite sure what the best way to completely fix this, but if munki always downloaded all (managed) manifests before doing anything else (e.g. before downloading packages or checking if they are already installed), it would probably prevent 99% of all cases where I've seen this happen.

cheers,
Nikolai Vincent Vaags

**Comment by kujeger** [comment]
I've made a "small" test-case repository here:
http://kumini.kujeger.net/munkirepo_autoremove_testcase.zip
It contains manifests and packages that should make it pretty easy to reproduce and test.

**Comment by gregneagle** [comment]
@nmcspadden See https://github.com/munki/munki/commit/74aed49f2247ef3833bb286d3d1b32651fecd0e0

**Comment by gregneagle** [comment]
Closing: addressed in Munki 3.
