### ISSUE TITLE
No "Update" icon if language is different than english

### ISSUE THREAD

**Issue by pexner** [munki/munki#565]
Switch to a different language than english in System Preferences, restart Managed Software Center and the "Update" icon is gone!
(tested with German and French)

**Comment by RichardLafontaine** [comment]
I have the same problem with French on 10.11.3 system with Munki 2.5.0.2626
It's our only install so far...

**Comment by gregneagle** [comment]
Redownload the installer pkg and reinstall. Fixed?

**Comment by RichardLafontaine** [comment]
Yes, fixed using https://munkibuilds.org/munkitools2-latest.pkg

**Comment by gregneagle** [comment]
Which is not what I asked to have verified, so hoping the release pkgs on GitHub are good now...
