### ISSUE TITLE
munkitools-2.5.1.2630.pkg reporting as 2.5.1.2627 when installed

### ISSUE THREAD

**Issue by fseesink** [munki/munki#566]
Not sure how this interplays, but use AutoPkgr.  Had just downloaded 2.5.0 earlier today.  Then, when I went to run AutoPkgr, it said there was a new release, 2.5.1.2630.  To be honest, I totally missed that version change.  But when I tried to let AutoPkgr do the update by clicking [Update Munki tools], it downloaded the pkg, then came back with same yellow ball and indicating a new version was out.

I went and decided to manually install munkittools.  Installed 2.5.0 (again, missed newer version notification in AutoPkgr), and then ran AutoPkgr and got yellow ball.  THAT's when I noticed a newer version, and sure enough, back here I found the 2.5.1 package had dropped just 3 hours ago.

However, after downloading and installing that, I STILL get a yellow ball and indication in AutokPkgr that a newer version exists of Munki tools.  Doing a simple

**munkiimport --version**

The output says
**2.5.1.2627**

So not sure if this is a bug in AutoPkgr, or if this is because the installer filename version doesn't match what the binary outputs, if that makes sense.  Anyway, there's a mismatch here.  Thought you might want to know.

**Comment by gregneagle** [comment]
See https://github.com/lindegroup/autopkgr/issues/493.
