### ISSUE TITLE
Feature request: start or stop install after date

### ISSUE THREAD

**Issue by gdarm** [munki/munki#568]
This week I rolled out Office 2016 to 150 clients and found an issue I had with multiple munki sites.

Once I added the package name to the manifests the clients began downloading the package. And I got many error messages from sites the package was not already synced to.
Of course I can wait for the sync and then add the package name to the manifests, but wouldn't it be fine to automate these process?

We could use those new pkginfo keys:
"start_install_after_date" which also means "do not cache before date" and
"stop_install_after_date" which stop the install of a package after the defined local time.

And of course we could start an uninstall after date, because the software is only licensed until date x:
"start_uninstall_after_date" which uninstalls a package after the defined local time.

Don't know if it's to complex to implement, but it would be fine if somebody can. :)

**Comment by gregneagle** [comment]
You import a pkg to the Munki repo -- it's now available for clients to download and install. There is no separate "caching" step -- Munki downloads a package if it determines it needs to install it; it's stored in a local "Cache" folder until that install is completed.

It sounds like maybe you've implemented some sort of multi-site multi-repo setup with some sort of script that syncs repos, and updated manifests are getting to the downstream repos before the new packages are getting there. Munki doesn't know anything about any of that, and I don't think I want to add code to support specific implementations of that.

You can use conditional items to make an item available in a manifest based on the date.
See this discussion: https://groups.google.com/d/topic/munki-dev/csU8UBd4aFA/discussion

An example:

```xml
 <key>conditional_items</key>
  <array>
    <dict>
      <key>condition</key>
      <string>date > CAST("2016-03-02T00:00:00Z", "NSDate")</string>
      <key>managed_installs</key>
      <array>
        <string>AdobePhotoshopCC2015</string>
      </array>
      <key>managed_uninstalls</key>
      <array>
        <string>AdobePhotoshopCS6</string>
      </array<
    </dict>
  </array>
```

This would cause Photoshop CS6 to be removed, and Photoshop CC 2015 to be installed starting at midnight local time on 02 March 2016.
