### ISSUE TITLE
apple (beta) updates which require reboot not logging out from MSC GUI

### ISSUE THREAD

**Issue by arubdesu** [munki/munki#569]
Steps to reproduce:
Through the install of two 10.11.4 beta revisions, running master munkitools(the most current versions of the whole suite), I get prompted to install the apple update in the Managed Software Center GUI
Expected results:
Clicking install should logout the GUI by telling all other apps to close
Actual:
No apps quit, and only after manually logging out does the install occur

I'm assuming debugging/logging can be added for the interaction with the MSC GUI, and I know that logout_helper has been bumped recently. Could I get some guidance before I install this most recent update?

**Comment by gregneagle** [comment]
logout_helper is not involved here; that's only for force_install_after_date.

Have you enabled MSC/MSU logging, and if so, have you reviewed those logs?

**Comment by gregneagle** [comment]
Are you seeing an alert sheet prompting you that you must logout after you click "Update?

**Comment by gregneagle** [comment]
See https://github.com/munki/munki/blob/master/code/apps/Managed%20Software%20Center/Managed%20Software%20Center/AlertController.py#L195-L196

There's MSC logging there.

**Comment by gregneagle** [comment]
This is called:
https://github.com/munki/munki/blob/master/code/apps/Managed%20Software%20Center/Managed%20Software%20Center/munki.py#L392

which in turn, calls:
https://github.com/munki/munki/blob/master/code/apps/Managed%20Software%20Center/Managed%20Software%20Center/munki.py#L376

If that fails to trigger a logout, then that would imply that Apple has broken this bit of AppleScript:

```
ignoring application responses
    tell application "loginwindow"
        «event aevtrlgo»
    end tell
end ignoring
```

(and are you seeing this _only_ with these specific beta updates (and how are you getting these -- is softwareupdate pointing at a special sucatalog?))

**Comment by gregneagle** [comment]
Does Console.app or system.log have anything interesting at the point MSC would be attempting to trigger a logout?

**Comment by arubdesu** [comment]
```
$ defaults read /Library/Preferences/ManagedInstalls | grep MSU
    MSUDebugLogEnabled = 1;
    MSULogEnabled = 1;
```
<img width="1173" alt="screenshot 2016-03-01 14 19 21" src="https://cloud.githubusercontent.com/assets/388808/13438812/a4a41d88-dfb8-11e5-906a-6a03903a181d.png">

**Comment by arubdesu** [comment]
And the resulting log: https://gist.github.com/arubdesu/01bf1fac01f5180bd62a

**Comment by arubdesu** [comment]
I've seen this consistently with the last three updates, managedsoftwareupdate `2.5.0.2626`, Managed Software Center `4.1.2616`. I'm pointed at Apple's seed catalog.

**Comment by arubdesu** [comment]
I'm seeing nothing in syslog that correlates to that timestamp, just the normal box/Dropbox/buletooth chatter.

**Comment by gregneagle** [comment]
"I've seen this consistently with the last three updates, managedsoftwareupdate 2.5.0.2626, Managed Software Center 4.1.2616. I'm pointed at Apple's seed catalog." What about with _other_ updates that require a logout or restart?

**Comment by gregneagle** [comment]
From your log:
`1456860001.747508 INFO abanks : @@user:install_with_logout@@`

Which proves it got here: https://github.com/munki/munki/blob/master/code/apps/Managed%20Software%20Center/Managed%20Software%20Center/AlertController.py#L195-L196

Which then implies the code to trigger a logout _is_ running, and further implies the OS is simply ignoring it. You could run the code manually:

```
% cd /Applications/Managed\ Software\ Center.app/Contents/Resources/
% python
Python 2.7.10 (default, Oct 23 2015, 18:05:06) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import munki
>>> munki.logoutAndUpdate()
```

**Comment by arubdesu** [comment]
My bad, local issue where applescript/osascript libraries are hosed. Pardon.
