### ISSUE TITLE
HFS compression is not preserved in copy_from_dmg installer type

### ISSUE THREAD

**Issue by VitosX** [munki/munki#570]
Hello,

I noticed software installed using munkitools often uses more disk space than manually copied from downloaded images, which may be important in space constrained situations.
I see **copyItemsFromMountpoint** function in **installer.py** uses _/bin/cp_, which explains app bundles size expansion. Using _/usr/bin/ditto_ instead would be more effective, preserving filesystem-level compression. Gains in size for some software are really substantial (ie. LibreOffice is 242 MiB compressed vs 765 MiB uncompressed, Xcode - 4,5 GiB vs 9,7 GiB). There is no noticeable launch time impact - and in many cases apps are actually launching faster thanks to lower I/O load (especially on older HDDs).

All I did was this change (2.4.0.2561, not current version):
```
470,471c470,471
<         retcode = subprocess.call(["/bin/cp", "-pR",
<                                    source_itempath, full_destpath])
---
>         retcode = subprocess.call(["/usr/bin/ditto",
> 					source_itempath, full_destpath])
```

Is there any reason why cp is being used?

PS. Adding `"--hfsCompression", "--noqtn"` as options even allows to enforce the compression (a lot of software is not distributed in this useful form, I know apps from App Store use it) and get rid of useless com.apple.quarantine extended attributes in case disk image was downloaded manually using internet browser.

**Comment by gregneagle** [comment]
This seems like a good enhancement to make. I think hfsCompression was just being introduced when Munki was first written and I at least did not know much about it.

Before implementing, I'd like to compare the results with a Finder drag copy -- if that preserves hfsCompression, then I'd be even more in favor of this change.

I don't think I'd be in favor of _forcing_ hfsCompression, unless a Finder drag copy applies hfsCompression even if the source isn't compressed.

Munki already strips the com.apple.quarantine attribute, so no changes needed there.

**Comment by keeleysam** [comment]
I'd also be interested to know if this makes installs faster for bundles which contain a large amount of files.  Copying 4.5 or 9.7 GB for Xcode shouldn't take too long, but since the Xcode 7.2.1 bundle contains 465790 files it takes a very long time to copy from the dmg.

**Comment by gregneagle** [comment]
Is the --noqtn option for ditto available in 10.6?

**Comment by gregneagle** [comment]
Answering my own question: yes, the --noqtn flag is supported on 10.6's version of ditto.

**Comment by VitosX** [comment]
Finder drag copy preserves the compression. You can verify the size used on disk using _du_.
I made a timed copy of current LibreOffice from munki-created dmg image on my MacBook Pro (using _purge_ to flush disk cache before each test).
_Ditto_ took 8.086s, while _cp_ took 9.415s.

I also made a test on Mac Pro running older HDD, but couldn't get consistent results. Both tools took similar time though.

I agree forcing compression should not be a default solution (it is preferable for app bundles, but someone might use _copy_from_dmg_ for some other data files, which may lead to undesirable outcome in specific scenarios). It would be great in my opinion to have such option in pkginfo files, but I leave it up to you if it is worth the trouble.

**Comment by gregneagle** [comment]
Change committed here: https://github.com/munki/munki/commit/c6ec424be1944c738fc219fdaf24661434a04d62
