### ISSUE TITLE
MSC displays blank "Updates" tab

### ISSUE THREAD

**Issue by childrss** [munki/munki#573]
Similar to issue https://github.com/munki/munki/issues/552 I HAD several machines with blank updates tabs in MSC.  The other tabs (software, categories, my items) were populating just fine.

I had a force-update-by (with reboot) with Firefox 38.7.0 and Adobe AIR pending install.  Normal behavior resumes after the force-install-update-by occurs (and the force occurs normally, absent the red text and description :-(

How would I go about troubleshooting this for future (or in case I still have a machine back at work in this state)?  I peered into the log files in /Library/Managed Installs/Logs but didn't see anything interesting.

Thanks much as always!

Force-install set by MunkiAdmin 1.4.1
managedsoftwareupdate -V = 2.5.1.2627
client_resources/custom.zip set, removed (just deleted from client) but didn't seem to make a difference
MSC v. 4.1.2627

**Comment by gregneagle** [comment]
MSC.app uses the contents of /Library/Managed Installs/InstallInfo.plist to determine what to display in each of its views, so I'd capture that and see if you can use it to replicate the issue. (MSC.app also uses the contents of /Library/Managed Installs/icons and /Library/Managed Installs/client_resources, so it might not hurt to capture those)

**Comment by childrss** [comment]
Sweet -- I'll give it a go and report back.  I messed around a bit with the icons, but got nailed by that nasty sysadmin who put a 'force-install-by-date' on adobe AIR... was time for a break anyway ;-)

**Comment by gregneagle** [comment]
Any updates here? Without a reproducible case this issue may sit here for eternity...

**Comment by childrss** [comment]
My apologies -- I've not seen it again lately I think we can close it and I'll re-address it in the case that it reappears.

**Comment by gregneagle** [comment]
Closing. Please re-open if you find a reproducible case.
