### ISSUE TITLE
Apple updates fail when not able to connect to Apple update server

### ISSUE THREAD

**Issue by jessepeterson** [munki/munki#579]
As reported in slack yesterday:

```
    Getting client resources...
Checking Apple Software Update catalog...
WARNING: Could not download Apple SUS catalog:
ERROR: Unexpected error in appleupdates:
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 1048, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 798, in main
    forcecatalogrefresh=force_catalog_refresh)
  File "/usr/local/munki/munkilib/appleupdates.py", line 1743, in appleSoftwareUpdatesAvailable
    force_check=forcecheck, suppress_check=suppresscheck)
  File "/usr/local/munki/munkilib/appleupdates.py", line 1557, in AppleSoftwareUpdatesAvailable
    dummy_success = self.CheckForSoftwareUpdates(force_check=True)
  File "/usr/local/munki/munkilib/appleupdates.py", line 810, in CheckForSoftwareUpdates
    print err
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 33: ordinal not in range(128)
```

> ah, I see. the error message has a fancy quote in it: "Error -1003: The operation couldn’t be completed. (NSURLErrorDomain error -1003.)"

A note here: the Munki host legitimately was not able to access the apple update URL - the error is accurate.

> [10:43] 
> if I [change line 810](https://github.com/munki/munki/blob/master/code/client/munkilib/appleupdates.py#L810) from `munkicommon.display_warning('\t%s', str(err))` to `munkicommon.display_warning(u'\t%s', err)` it seems to work and display fine

When this error hits the Munki UI doesn't update and `managedsoftwareupdate` doesn't seem to finish correctly.

**Comment by gregneagle** [comment]
Please see if this addresses the issue: https://github.com/munki/munki/commit/7f27114fcb75f9d35a74bb95974e0f1818bd108d

**Comment by gregneagle** [comment]
Closing this; can reopen if needed.

**Comment by jessepeterson** [comment]
Sorry for delay. Was able to test latest build just now. Error was properly shown and Munki run finished despite inaccessibility of software update feed. Thanks!
