### ISSUE TITLE
Logging Error with Large Conditional Statements. 

### ISSUE THREAD

**Issue by weswhet** [munki/munki#583]
I get the following error output when (LogToSyslog = True) and (LoggingLevel > 1) when a manifest contains very large conditional statement.. 100+ OR statements. You can have LoggingLevel at 2 with no SysLog and everything is normal. 

<img width="617" alt="screen shot 2016-03-23 at 6 47 19 pm" src="https://cloud.githubusercontent.com/assets/6865785/14006167/bee92ec4-f127-11e5-8d79-bc8c2ef06065.png">

**Comment by gregneagle** [comment]
Can you also provide a sample manifest that triggers this? Looks like Python's logging module dislikes the length/size of the text that its been asked to log...

**Comment by gregneagle** [comment]
(would have been nice for that output from the command-line to have been _text_ and not a picture so I could copy-n-paste; just saying')

**Comment by gregneagle** [comment]
Some possibly related issues:
http://bugs.python.org/issue11907
https://github.com/unbit/uwsgi/issues/75
http://comments.gmane.org/gmane.comp.python.bugs/240656

**Comment by weswhet** [comment]
The error is thrown when retrieving the Optional manifest. 
`Getting manifest Optional...
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 863, in emit
    self.socket.send(msg)
error: [Errno 40] Message too long
Logged from file munkicommon.py, line 522
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 863, in emit
    self.socket.send(msg)
error: [Errno 40] Message too long
Logged from file munkicommon.py, line 522`

That manifest is here. https://gist.github.com/weswhet/95d38dd9cd7f5975ffd6#file-optionalmanifest

**Comment by gregneagle** [comment]
Addressed here: https://github.com/munki/munki/commit/d0df8379c9578641104bf065bdf352b0a5b0e4a0

Will merge that into master after 2.6.0 official release.

**Comment by gregneagle** [comment]
That attempted fix has been merged to master. If you don't want to build from source, a pre-built pkg is available here: https://munkibuilds.org/2.6.1.2693/munkitools-2.6.1.2693.pkg

**Comment by weswhet** [comment]
Verified on latest build!

Thanks!
