### ISSUE TITLE
ERROR: Unexpected error in updatecheck

### ISSUE THREAD

**Issue by BaddMann** [munki/munki#584]
Finding an issue on first "forced" run of Munki on freshly imaged Macs. 
Not see this behavior on earlier imaged macs, but will have to do more digging in their logs.

Here's the error: 
```
Mar 30 2016 09:24:52 -0700     XQuartz-2.7.8-2.7.86.dmg downloaded at 74168 KB/s
Mar 30 2016 09:24:52 -0700     **Checking for removals**
Mar 30 2016 09:24:52 -0700     Dropbox doesn't appear to be installed.
Mar 30 2016 09:24:52 -0700     Quicktime7 doesn't appear to be installed.
Mar 30 2016 09:24:52 -0700     **Checking for managed updates**
Mar 30 2016 09:24:52 -0700 ERROR: Unexpected error in update check
Mar 30 2016 09:24:52 -0700 Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 742, in main
    updatecheckresult = updatecheck.check(client_id=options.id)
  File "/usr/local/munki/munkilib/updatecheck.py", line 3027, in check
    installinfo)
  File "/usr/local/munki/munkilib/updatecheck.py", line 2149, in processManifestForKey
    processManagedUpdate(item, cataloglist, installinfo)
  File "/usr/local/munki/munkilib/updatecheck.py", line 1563, in processManagedUpdate
    if someVersionInstalled(item_pl):
  File "/usr/local/munki/munkilib/updatecheck.py", line 1330, in someVersionInstalled
    munkicommon.display_error(errmsg)
  File "/usr/local/munki/munkilib/munkicommon.py", line 485, in display_error
    msg = concat_log_message(msg, *args)
  File "/usr/local/munki/munkilib/munkicommon.py", line 350, in concat_log_message
    return msg.rstrip()
AttributeError: 'Error' object has no attribute ‘rstrip'

```

Tried all builds created by Tim Sutton's brilliant MunkiBuild.org site in reverse order.
Found that the issue was introduced in app version 4.2.2667 and was not there in 4.2.2665

Specific builds: 
Bad: 
https://munkibuilds.org/2.6.0.2668/ and up
Good:
https://munkibuilds.org/2.6.0.2665/ and down

portion of my manifest performing updates checks:
```
	<key>managed_updates</key>
	<array>
		<string>Camtasia2</string>
		<string>flip4macwmv</string>
		<string>Keynote</string>
		<string>MunkiAdmin</string>
		<string>munkitools</string>
		<string>Numbers</string>
		<string>Pages</string>
		<string>VMFusion</string>
	</array>
```

Hope this helps.
Oliver

**Comment by gregneagle** [comment]
Thank you for the report.

The version of the Managed Software Center.app would not have a bearing, as it does not contain /usr/local/munki/munkilib/munkicommon.py. The version of the munki tools in /usr/local/munki is relevant here, and it looks like this was probably caused by https://github.com/munki/munki/commit/2abb90bba81c1f114b49f818f046040d6060f340 or https://github.com/munki/munki/commit/7f27114fcb75f9d35a74bb95974e0f1818bd108d.

While I appreciate you finding this issue, I do want to point out that pkgs available on munkibuilds.org are often testing builds. The last "official" release build of Munki 2.5.1 doesn't have this issue -- you might want to limit your installation of testing builds onto testing machines...  your call, of course, but it's far more likely to encounter broken things in testing builds.

**Comment by gregneagle** [comment]
I would also be interested in what error is successfully returned at this stage on an unaffected version of the munki tools.

**Comment by gregneagle** [comment]
@BaddMann Please see if this build addresses your issue: https://munkibuilds.org/2.6.0.2681

**Comment by BaddMann** [comment]
Oh wow. 
It appears to be working!
The log file is completely devoid of any errors and the Mac is waiting to install.
That was fast i only just managed to finish the re-image process!

**Comment by BaddMann** [comment]
On the pre-production code subject.
I only add the latest code to freshly imaged Macs so that I can dip my toe in the deep end of Munki troubleshooting. 
The main workflows run the regular builds and are of course maintained by my munki repo.
I appreciate the heads up though.
Will definitely avoid when we do a mass image of the campus.
Thanks for your help.

**Comment by BaddMann** [comment]
Wait do i close the issue or you?
What's the etiquette?

**Comment by gregneagle** [comment]
It's fine.
