### ISSUE TITLE
Request: Show client ID and catalogues in MSC app

### ISSUE THREAD

**Issue by llauren** [munki/munki#586]
One way to improve the debugging usability of the Managed Software Center app would be to show the ClientIdentifier and SoftwareRepoURL from `defaults read /Library/Preferences/ManagedInstalls`, and what catalogues munki offered to the app.

**Comment by gregneagle** [comment]
There's lots of admin-useful stuff that could be displayed in Managed Software Center. But that's an end-user focussed application, and could not possibly display the wide range of info without looking scary and intimidating to end-users.
The Munki admin is expected to use the command-line and examine the preferences, logs,  and the various files in /Library/Managed Installs. There's lots of useful debugging info in those locations.

**Comment by llauren** [comment]
OK, i guess that'll have to suffice.

**Comment by ryan8382** [comment]
I have wanted to submit this one also. Could we have it be some sort of key combination or something? It would save a bit of time.

**Comment by erikng** [comment]
FWIW, I and Clayton added most of this information to MR-PHP.

**Comment by gregneagle** [comment]
No, I'm not really interested in implementing this.

**Comment by gregneagle** [comment]
(I think using a reporting console like MunkiReport-PHP or Sal is the better approach as well. I don't walk around to hundreds of machines and open Managed Software Center and click on GUI elements to get information. I either SSH in and use the command-line, or rely on my reporting console.)

**Comment by llauren** [comment]
Aargh! I've awoken a monster! So sorry D:
