### ISSUE TITLE
Managed Software Center loops when uninstalling an application with missing uninstall method

### ISSUE THREAD

**Issue by erikng** [munki/munki#590]
If the uninstallmethod key is missing in the pkginfo file and a user attempts to uninstall an optional item via MSC, the update tab will loop indefinitely until MSC is killed. Managedsoftwareupdate properly logs the event as an error.

**Comment by gregneagle** [comment]
This sounds like it could be the same as #389.

**Comment by erikng** [comment]
Yep. Go ahead and close.

**Comment by gregneagle** [comment]
We'll track this in #389.
