### ISSUE TITLE
Update check failed

### ISSUE THREAD

**Issue by Meflou** [munki/munki#592]
When I installed the app I got this error:
<img width="1143" alt="screen shot 2016-04-12 at 09 56 14" src="https://cloud.githubusercontent.com/assets/10213346/14452100/dc8e8452-0094-11e6-9459-e42926dd4095.png">

Is it no longer working?

**Comment by gregneagle** [comment]
You didn't restart after install and the required launchd jobs needed for the GUI to be able to start a managedsoftwareupdate run are not currently active. 

If you need further help/support, please post on the munki-discuss group: https://groups.google.com/group/munki-discuss
