### ISSUE TITLE
MSC 4.2.2673 Install issue

### ISSUE THREAD

**Issue by nescom-it** [munki/munki#593]
I selected an install on an application and it began the installation, however, the list of available installs and the update screen overlaid each other. No matter which tab I select (Software, Categories, My Items, Updates) the category stays frozen and the content from each category shows up beneath it. Also when I quit MSC it gave me an error. (See files below)

![mscenterbug](https://cloud.githubusercontent.com/assets/14878032/14469844/8c0cea58-00b4-11e6-8c48-e25a55032788.jpg)
![mscenterbug2](https://cloud.githubusercontent.com/assets/14878032/14469847/8c17ceaa-00b4-11e6-9267-5cddb4a31692.jpg)
![mscenterbug3](https://cloud.githubusercontent.com/assets/14878032/14469845/8c15887a-00b4-11e6-8cf6-0bf16949080f.jpg)
![mscenterbug4](https://cloud.githubusercontent.com/assets/14878032/14469846/8c1705e2-00b4-11e6-9db7-b4a46e5e6f2e.jpg)
[MSCerrorLog.txt](https://github.com/munki/munki/files/215606/MSCerrorLog.txt)

**Comment by gregneagle** [comment]
Have see no other reports of this. Suggest posting on munki-dev and/or munki-discuss to get more eyes/feedback. 
Have you customized anything in the client (ala https://github.com/munki/munki/wiki/Client-Customization) and if so, what happens when you test with your customizations removed?

**Comment by nescom-it** [comment]
This is the first time I have seen it as well. I have some basic client customizations (Banners and Help Link). I have not tried without the customizations yet

**Comment by erikng** [comment]
By any chance do you have any pop ups on your packages, prior to installation?

**Comment by nescom-it** [comment]
No there are no Pop ups

**Comment by erikng** [comment]
Is the machine an iMac?

**Comment by nescom-it** [comment]
iMac 21.5" Late 2012 running 10.10.5

**Comment by erikng** [comment]
I've seen something similar (but with pre_install/upgrade alerts) on 2011 and 2012 iMacs, but I could never figure out the exact cause.

If you close Managed Software Center after it exhibits this behavior, does it eventually crash with a corresponding dump?

**Comment by nescom-it** [comment]
Yes I have included the report: [https://github.com/munki/munki/files/215606/MSCerrorLog.txt](url)

**Comment by gregneagle** [comment]
Closing this old issue.
