### ISSUE TITLE
Nothing showing on the Frontpage 

### ISSUE THREAD

**Issue by zesa111** [munki/munki#595]
Hi use munki at the first time.
I use the Introduction and put Firefox.

Under Updates, I take an message for Firefox to update.

But I take nothing on the Frontpage (Software) or on Catergory.
Also, i couldn't click on "Installed".

What is the reason?!

And knows anyone a good guide to manage munki?
f.e. to deploy MSC on Clients with configs or a better way to put DMGs or PKGs on munki.

Thanks.

![bildschirmfoto 2016-04-14 um 21 25 16](https://cloud.githubusercontent.com/assets/15154678/14541400/21787c70-028a-11e6-9b99-85fc3d9b9029.png)
![bildschirmfoto 2016-04-14 um 21 15 04](https://cloud.githubusercontent.com/assets/15154678/14541407/2585e7e4-028a-11e6-9961-c38ef0e7ed7b.png)

**Comment by gregneagle** [comment]
I'll bet this will be relevant:
https://github.com/munki/munki/wiki/FAQ#q--i-just-set-up-munki-2-and-theres-nothing-available-under-software-or-categories-and-the-icons-are-greyed-out-how-do-i-make-things-available-there

For additional help/advice on working with Munki, consider posting on munki-discuss: https://groups.google.com/group/munki-discuss

And there are more resources:
https://github.com/munki/munki/wiki/More-Links-And-Tools

**Comment by zesa111** [comment]
I add:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>catalogs</key>
	<array>
		<string>testing</string>
	</array>
	<key>optional_installs</key>
	<array>
	</array>
	<key>optional_installs</key>
	<array>
		<string>Firefox</string>
		<string>Adobe</string>
		<string>Acobat</string>
	</array>
</dict>
</plist>

```

but it dosn't work ?

**Comment by gregneagle** [comment]
You now have _two_ optional_installs arrays. One is empty. Which one is used is undefined.

Please use munki-discuss for general support. GitHub issues should be for reporting reproducible bugs, not for general usage support.
