### ISSUE TITLE
munkiimport fails when copying funky characters from a previous pkginfo

### ISSUE THREAD

**Issue by miikkali** [munki/munki#596]
I am attempting to `munkiimport` a new version of an existing pkg. `munkiimport` suggests using the previous pkginfo as a template. Unfortunately the previous pkginfo has a curly quote in it. `munkiimport` hangs.

I can reproduce the following with Munki build 2.6.1.2723:

1. Import a pkg with `munkiimport`
2. Open the imported pkg’s pkginfo and insert a curly quote in the description key. (I can't tell if any other key would produce the error too. I've tested only with the description key.)
```
	<key>description</key>
	<string>Naughty character: ‘</string>
```
3. Import a new version of the package —> munkiimport will suggest using the previous pkginfo as template —> answer yes and accept all suggestions. This happens:

```
$ munkiimport test-package.pkg 
This item is similar to an existing item in the repo:
            Item name: test-package
         Display name: test-package
          Description: Naughty character: ‘
              Version: 1.0
  Installer item path: test-package-1.0.pkg

Use existing item as a template? [y/n] y
Copying unattended_install: False
Copying unattended_uninstall: False
Copying category: 
Copying developer: 
           Item name: test
        Display name: test
         Description: Naughty character: ´  
```
Then it hangs. Nothing happens. I escape with ctrl-c and I get this traceback:
```
Traceback (most recent call last):
  File "/usr/local/munki/munkiimport", line 1139, in <module>
    main()
  File "/usr/local/munki/munkiimport", line 1009, in main
    pkginfo[key] = raw_input_with_default(prompt, default)
  File "/usr/local/munki/munkiimport", line 64, in raw_input_with_default
    return unicode(raw_input(), encoding=sys.stdin.encoding)
KeyboardInterrupt
```

Character encoding in my setup is UTF-8.

**Comment by gregneagle** [comment]
While I could reproduce this issue on earlier builds, I can't reproduce this with the current master/HEAD:

```
% /Users/Shared/munki-git/munki/code/client/munkiimport ../EasyFind.dmg 
This item is similar to an existing item in the repo:
            Item name: EasyFind
         Display name: EasyFind
          Description: Naughty character: ‘
• EasyFind finds files and folders by name or content using advanced Boolean operators.
              Version: 4.9.3
  Installer item path: apps/EasyFind-4.9.3.dmg

Use existing item as a template? [y/n] y
Copying unattended_install: True
Copying unattended_uninstall: False
Copying category: Utilities
Copying developer: DEVONtechnologies
           Item name: EasyFind
        Display name: EasyFind
         Description: Naughty character: ‘                                                                                   
• EasyFind finds files and folders by name or content using advanced Boolean operators.                                      
```

..and the cursor is at the end of the description, ready for editing.

I'm running under 10.11.4, Python 2.7.10.

**Comment by gregneagle** [comment]
Oh, and locally, and using Apple's Terminal.app... (in case that turns out to be relevant)

**Comment by miikkali** [comment]
I’m running OS X 10.11.5 Beta (15F18b) and Python 2.7.10.
Locally, with Terminal.app.
I'll try to see if I made a mistake in my testing, or something, but I did try it two or three times with similar results. I'll come back to this later.

**Comment by gregneagle** [comment]
Perhaps a post on munki-dev, referencing this issue, to get more eyes on it?

**Comment by miikkali** [comment]
Yes, I can do that, tomorrow, as it's already getting late in the evening around here.  Thanks for your quick response!

-
Miikkali


Greg Neagle <notifications@github.com<mailto:notifications@github.com>> kirjoitti 18.4.2016 kello 19.49:


Perhaps a post on munki-dev, referencing this issue, to get more eyes on it?

-

**Comment by gregneagle** [comment]
I posted it.

**Comment by clburlison** [comment]
On 10.11.4, Python 2.7.10:

(Not sure if this is relevant) With munkiimport version 2.6.1.2696, I didn't get a hang like @miikkali  I got the following error. Which resulted in the description key not being set.

```bash
Unhandled exception in thread started by <function insert_default_text at 0x1054a65f0>
Traceback (most recent call last):
  File "/usr/local/munki/munkiimport", line 55, in insert_default_text
    readline.insert_text(text.encode(sys.stdout.encoding))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 19: ordinal not in range(128)
```

With munkiimport version 2.6.1.2723, it's properly encoding/decoding the `‘` character. So no errors over here.

**Comment by gregneagle** [comment]
It was definitely broken in older builds. What's important is trying to determine its status in the _current_ code. I think it is fixed. @miikkali does not.

**Comment by aysiu** [comment]
I just did a test with the latest stable Munki release using _munkiimport_ on El Capitan (again, stable—not beta), and it imports just fine using the previous template (even tried exactly that apostrophe at the end of the description field.

**Comment by gregneagle** [comment]
We're not testing the behavior for "latest stable Munki release". We're interested in the behavior for the CURRENT master/HEAD code.

**Comment by aysiu** [comment]
Doh! I can test that, too. Hang on...

**Comment by aysiu** [comment]
Just tested on 2.6.1.2723, and I'm not getting any errors when importing using the template that has the "naughty" character.

**Comment by miikkali** [comment]
Hi! I tested some more and got deeper. This is probably not a Munki issue after all, but it depends on how you see it. Apologies for not including _complete_ testing information in my original post. What was missing was exactly _how_ and _with what_ I inserted and saved the problematic characters to the pkginfo. I typed them in Notes.app and copy&pasted to MunkiAdmin, then saved the pkginfo. I can reproduce this. If I edit the pkginfo and insert the characters with f.ex. TextWrangler, there's no problem. So MunkiAdmin saves the characters in some way that puzzles munkiimport. Maybe I should take the issue to @hjuutilainen and we could close it here?

**Comment by aysiu** [comment]
As far as I know, Notes is plain text, but just so you know for sure that it's MunkiAdmin, can you type the special characters into MunkiAdmin directly instead of copying and pasting from Notes.app?

**Comment by miikkali** [comment]
I sure can and will test it. Could take some hours though, as the evening is already closing around here. Whatever the result, people will be copy&pasting text from various sources into MunkiAdmin and managing their pkginfos that way. That's why I suggested calling Hannes for input and started to think that maybe this is not a Munki issue but a MunkiAdmin issue. I don't know. I'll come back later after I've tested. In any case, I'll notify @hjuutilainen.

**Comment by hjuutilainen** [comment]
This is most certainly a case with the smart quotes: https://derflounder.wordpress.com/2014/02/01/disabling-smart-quotes-in-mavericks/

MunkiAdmin already does multiple overrides to try to avoid the expansion but I guess I'm not doing enough to stop these. @miikkali, could you open a separate issue for this in MunkiAdmin so we'll get this properly fixed?

**Comment by gregneagle** [comment]
I think this misses the point. Unicode characters should be allowed in display names and descriptions. The tools around Munki should handle those properly.

**Comment by hjuutilainen** [comment]
Technically you're right, and in fact it seems that MunkiAdmin already reads and writes these correctly:

![screen shot 2016-04-19 at 21 18 48](https://cloud.githubusercontent.com/assets/19357/14650402/5b8c0646-0674-11e6-943c-3d7ccb40e5fc.png)

I just really don't agree with the behavior of OS X which replaces the regular ones with smart ones by default. User should be allowed to use them if desired but it should be a conscious decision.

**Comment by miikkali** [comment]
I cannot reproduce the issue by typing curly quotes directly into MunkiAdmin. It only appears when I've copy&pasted these characters from somewhere else, namely Notes.app. What do you think, should I close this issue here and open a new one in MunkiAdmin?
