### ISSUE TITLE
managed installs ClientResourceURL or ClientResourcesFilename

### ISSUE THREAD

**Issue by jimmybaeyens** [munki/munki#597]
Hi All,

on my web server i've created a directory 'client_resources' (in the same directory where catalogs,manifests,pkgs and pkgsinfo is) 
This directory includes a 'site_default.zip' with modified banners and is zipped from the terminal as advised.
Now my question... i can't get my app to use fetch these banners? 
here is the output of Managed Installs.plist

defaults read /Library/Preferences/ManagedInstalls
{
    AppleSoftwareUpdatesOnly = 0;
    ClientIdentifier = "testing_manifest";
    ClientResourceURL = "https://***.****.com/client_resources/site_default.zip";
    ClientResourcesFilename = "https://****.****.com/client_resources/site_default.zip";
    FollowHTTPRedirects = none;
    InstallAppleSoftwareUpdates = 0;
    LastCheckDate = "2016-04-19 12:45:41 +0000";
    LastCheckResult = 0;
    LogFile = "/Library/Managed Installs/Logs/ManagedSoftwareUpdate.log";
    LogToSyslog = 0;
    LoggingLevel = 1;
    ManagedInstallDir = "/Library/Managed Installs";
    PendingUpdateCount = 0;
    SoftwareRepoURL = "https://****.****.com/";
    UseClientCertificate = 0;
 
stars have been replaced ofcourse...   i'm not sure which i need to use the ClientResourceURL or ClientResourcesFilename 

anyone can help me out here?

best regards,
Jimmy

**Comment by gregneagle** [comment]
General support questions should go to the munki-discuss mailing list. (But briefly: delete both ClientResourceURL and ClientResourcesFilename from your ManagedInstalls.plist, and test again, looking at the output of `managedsoftwareupdate -vvv`.) If you need further assistance, please post on munki-discuss.

**Comment by jimmybaeyens** [comment]
ah ok thanks man rather new here! will test :-)

**Comment by jimmybaeyens** [comment]
works like charm!
