### ISSUE TITLE
with munkiimport imported app (microsoft remote desktop) does not sho in munkiclient

### ISSUE THREAD

**Issue by himbeere** [munki/munki#600]
Hello Devs.

I imported the Microsoft Remote Desktop app with munkiimport. Everything went well. The Package is shown in munkiadmin and it is in the right catalog. But it's not shown when i ran the munki client on my Macbook. What could be causing this?

thanks in advance and best regards
t.

**Comment by bochoven** [comment]
Please use munki-discuss for general support. GitHub issues should be for reporting reproducible bugs, not for general usage support.

**Comment by himbeere** [comment]
Ok. Thanks.
