### ISSUE TITLE
Multiple Installer Items that "require" the same Installer Item Cause Dependency Check Errors

### ISSUE THREAD

**Issue by foigus** [munki/munki#603]
I encountered an issue due to my error (not synchronizing a remote copy of our Munki repo with the master) and found interesting behavior.  Three Installer Items:

- IllustratorCC2014StandardColorSettings
- InDesignCC2014StandardColorSettings
- PhotoshopCC2014StandardColorSettings

"require" the same Installer Item:

- AdobeStandardColorSettingsSupport

When managedsoftwareupdate evaluates the first Installer Item of the three (in this case IllustratorCC2014StandardColorSettings):

```
    * Processing manifest item IllustratorCC2014StandardColorSettings for install
    Looking for detail for: IllustratorCC2014StandardColorSettings, version latest...
    Considering 1 items with name IllustratorCC2014StandardColorSettings from catalog production
    Considering item IllustratorCC2014StandardColorSettings, version 2016.1.14 with minimum os version required 10.5.0
    Our OS version is 10.11.1
    Found IllustratorCC2014StandardColorSettings, version 2016.1.14 in catalog production
    IllustratorCC2014StandardColorSettings-2016.1.14 requires AdobeStandardColorSettingsSupport. Getting info on AdobeStandardColorSettingsSupport...
    * Processing manifest item AdobeStandardColorSettingsSupport for install
...
    Need to install AdobeStandardColorSettingsSupport
...
WARNING: Download of AdobeStandardColorSettingsSupport failed: HTTP result 404: not found
WARNING: Didn't attempt to install IllustratorCC2014StandardColorSettings because could not resolve all dependencies.
```

But the following two Installer Items have the following result:

```
    * Processing manifest item InDesignCC2014StandardColorSettings for install
    Looking for detail for: InDesignCC2014StandardColorSettings, version latest...
    Considering 1 items with name InDesignCC2014StandardColorSettings from catalog production
    Considering item InDesignCC2014StandardColorSettings, version 2016.1.14 with minimum os version required 10.5.0
    Our OS version is 10.11.1
    Found InDesignCC2014StandardColorSettings, version 2016.1.14 in catalog production
    InDesignCC2014StandardColorSettings-2016.1.14 requires AdobeStandardColorSettingsSupport. Getting info on AdobeStandardColorSettingsSupport...
    * Processing manifest item AdobeStandardColorSettingsSupport for install
    AdobeStandardColorSettingsSupport has already been processed for install.
    Looking for package com.meredith.InDesignCC2014StandardColorSettings, version 2016.1.14
    	This package is not currently installed.
    Need to install InDesignCC2014StandardColorSettings
...
    Downloading InDesign CC 2014 Standard Color Settings-2016.1.14.pkg...

	0..20..40..60..80..100
...
    * Processing manifest item PhotoshopCC2014StandardColorSettings for install
    Looking for detail for: PhotoshopCC2014StandardColorSettings, version latest...
    Considering 1 items with name PhotoshopCC2014StandardColorSettings from catalog production
    Considering item PhotoshopCC2014StandardColorSettings, version 2016.1.14 with minimum os version required 10.5.0
    Our OS version is 10.11.1
    Found PhotoshopCC2014StandardColorSettings, version 2016.1.14 in catalog production
    PhotoshopCC2014StandardColorSettings-2016.1.14 requires AdobeStandardColorSettingsSupport. Getting info on AdobeStandardColorSettingsSupport...
    * Processing manifest item AdobeStandardColorSettingsSupport for install
    AdobeStandardColorSettingsSupport has already been processed for install.
    Looking for package com.meredith.PhotoshopCC2014StandardColorSettings, version 2016.1.14
    	This package is not currently installed.
    Need to install PhotoshopCC2014StandardColorSettings
...
    Downloading Photoshop CC 2014 Standard Color Settings-2016.1.14.pkg...

	0..20..40..60..80..100
...
    The following items will be installed or upgraded:
        + InDesignCC2014StandardColorSettings-2016.1.14
            Script to set standard color settings for InDesign CC 2014
        + PhotoshopCC2014StandardColorSettings-2016.1.14
            Script to set standard color settings for Photoshop CC 2014
```

Running `managedsoftwareupdate --installonly` installs InDesignCC2014StandardColorSettings  and PhotoshopCC2014StandardColorSettings.  Running `managedsoftwareupdate -vvvvv` again skips IllustratorCC2014StandardColorSettings due to the failed AdobeStandardColorSettingsSupport `require`ment.

**Comment by gregneagle** [comment]
Please see if this addresses your issue:

https://github.com/munki/munki/commit/5a3e130449ab8630073552094ba9d05a51c545f9

Pre-built pkg for your convenience:

[munkitools-2.7.0.2753.pkg.zip](https://github.com/munki/munki/files/243215/munkitools-2.7.0.2753.pkg.zip)

**Comment by foigus** [comment]
Yes--that worked.  Note I tested this on my home Munki repo, so the software titles have changed but the problematic arrangement is still the same:

- Edited pkginfo files for OutputFactoryCS6, OutputFactoryCC2014, and OutputFactoryCC2015 to solely `require` Wireshark
- Ran makecatalogs
- Created a manifest `dependencytest`
- Added OutputFactoryCS6, OutputFactoryCC2014, and OutputFactoryCC2015 Installer Items to the manifest `dependencytest`
- Renamed the "pkg" `Wireshark-2.0.3.dmg` to `Wireshark-2.0.3a.dmg` in the repo
- Created a VM, set ManagedInstall preferences properly
- Installed munkitools-2.6.1.2684, restarted
- Ran `sudo managedsoftwareupdate -vvvvv`
- Observed the first `managed_install` listed in the `dependencytest` manifest (OutputFactoryCS6) was skipped due to the HTTP 404 error for `Wireshark-2.0.3.dmg`
- Observed the remaining two `managed_install`s (OutputFactoryCC2014 and OutputFactoryCC2015) were downloaded and pending installation
- Installed munkitools-2.7.0.2753
- Ran `sudo managedsoftwareupdate -vvvvv`
- Observed all three `managed_install`s listed in the `dependencytest` manifest were skipped due to the HTTP 404 error for `Wireshark-2.0.3.dmg` and the cached packages for OutputFactoryCC2014 and OutputFactoryCC2015 were removed

**Comment by gregneagle** [comment]
Fixed here: https://github.com/munki/munki/commit/5a3e130449ab8630073552094ba9d05a51c545f9
