### ISSUE TITLE
Update available after date/time

### ISSUE THREAD

**Issue by Benni1012** [munki/munki#604]
Hi it would be a big help for me if its a possible that an update available after a specified time. Like the force install option. 

Maybe something for Munki 2.8.0

**Comment by gregneagle** [comment]
You can use conditional_items in manifests to make items available after a certain date/time:

https://groups.google.com/d/topic/munki-dev/csU8UBd4aFA/discussion

This could be used to, say,  make Office2016 a managed_install after June 1st at noon (and also making Office2011 a managed_uninstall at the same time)

This isn't as helpful for doing something like holding back Google Chrome 50 until May 15th at noon (where both Google Chrome 49 and Google Chrome 50 have the same name in Munki) -- but no-one has asked for that functionality, and I expect its need to be incredibly rare. If you needed that, just don't add Google Chrome 50 to your "production" (or equivalent) catalog until May 15th at noon.

**Comment by gregneagle** [comment]
If you think this needs further discussion, please post to the munki-dev mailing list.

**Comment by Benni1012** [comment]
Thank you :)
