### ISSUE TITLE
Pending updates should not block new optional installs

### ISSUE THREAD

**Issue by keeleysam** [munki/munki#605]
If a user has pending updates, they are currently not able to install new optional items without installing those pending items.  This may be desired behavior for some, but it creates user frustration when they cannot install something small like a printer while waiting to install something large like a new version of an Office application or OS X.

To make this behave better, after a user clicked 'Install' on an item in MSC, perhaps the logic could change here:
https://github.com/munki/munki/blob/d12e481d7b58882e3dd9833bc17b359228353300/code/apps/Managed%20Software%20Center/Managed%20Software%20Center/MSCMainWindowController.py#L422-L453

I think changing this could also lead to a better experience with OnDemand items, which are usually scripts that you'd expect to run immediately.

**Comment by gregneagle** [comment]
Sorry - this is a carrot-and-stick design decision. To get the things they want, the users must accept the installation of the things the admin says are needed. I do not plan to make any changes to Munki's core logic around this.

**Comment by gregneagle** [comment]
Closing this; any further discussion (including workarounds) can happen on munki-dev.
