### ISSUE TITLE
managedsoftwareupdate fails if manifest name contains umlaut characters

### ISSUE THREAD

**Issue by workflowsguy** [munki/munki#608]
If the name of a manifest contains "special" characters like umlauts, managedsoftwareupdate will fail with an error message like this:

`Starting...`
`Checking for available updates...`
`    Retrieving list of software for this machine...`
`	0..20..40..60..80..100`
`    Retrieving catalog "Produktion"...`
`	0..20..40..60..80..100`
`ERROR: Unexpected error in updatecheck:`
`Traceback (most recent call last):`
`  File "/usr/local/munki/managedsoftwareupdate", line 1048, in <module>`
`    main()`
`  File "/usr/local/munki/managedsoftwareupdate", line 742, in main`
`    updatecheckresult = updatecheck.check(client_id=options.id)`
`  File "/usr/local/munki/munkilib/updatecheck.py", line 2998, in check`
`    installinfo)`
`  File "/usr/local/munki/munkilib/updatecheck.py", line 2107, in processManifestForKey`
`    nestedmanifestpath = getmanifest(item)`
`  File "/usr/local/munki/munkilib/updatecheck.py", line 2580, in getmanifest`
`    manifesturl = manifestbaseurl + urllib2.quote(partialurl)`
`  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 1282, ``in quote`
`    return ''.join(map(quoter, s))`
`KeyError: u'\u0308'`

The version is 2.6.1.2684

Thanks.

**Comment by gregneagle** [comment]
This is due to an underlying issue in the Python libraries:
http://stackoverflow.com/questions/15115588/urllib-quote-throws-keyerror

manifest names are used in URLs. What is the standard way to encode unicode characters in a URL?

IOW, Can I visit `http://someserver/manifests/günter` without error?

**Comment by gregneagle** [comment]
Addressed here: https://github.com/munki/munki/commit/28cb5f7c664b29bddc5d5d95db4afac0b86e34da
