### ISSUE TITLE
com.apple.quarantine xattr Not Being Stripped

### ISSUE THREAD

**Issue by foigus** [munki/munki#612]
I’m having difficulty, possibly surrounding this commit (proposed by @VitosX ):

https://github.com/munki/munki/commit/c6ec424be1944c738fc219fdaf24661434a04d62

The comment for that commit is that "This preserves hfsCompression and filters out com.apple.quarantine xattrs while copying.” In my case the quarantine xattr isn’t being stripped when `copy_from_dmg`ing something with Munki 2.6.1 release.

```
$ xattr -l /Applications/Thing.app
com.apple.FinderInfo:
00000000  50 4C 41 50 6C 74 64 70 00 10 00 00 00 00 00 00  |PLAPltdp........|
00000010  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  |................|
00000020
com.apple.metadata:kMDItemLastUsedDate:
00000000  62 70 6C 69 73 74 30 30 33 41 BC 81 0C 4B 1B 2F  |bplist003A...K./|
00000010  34 08 00 00 00 00 00 00 01 01 00 00 00 00 00 00  |4...............|
00000020  00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00  |................|
00000030  00 11                                            |..|
00000032
com.apple.quarantine: 0002;00000000;Safari;307970D4-C4DC-4ADE-9994-D54705EB80EE
com.dropbox.attributes:
00000000  78 9C AB 56 4A 29 CA 2F 48 CA AF 88 4F CB CC 49  |x..VJ)./H...O..I|
00000010  CD 4C 89 CF C9 4F 4E CC 51 B2 52 A8 56 CA 4D 4C  |.L...ON.Q.R.V.ML|
00000020  CE C8 CC 03 89 25 96 94 14 81 85 52 12 4B 12 81  |.....%.....R.K..|
00000030  0C 25 A3 AC C8 64 C3 E0 80 24 17 17 83 FC C8 80  |.%...d...$......|
00000040  48 D7 4A 93 52 83 CA 74 5B 5B A5 DA DA 5A 00 C0  |H.J.R..t[[...Z..|
00000050  69 1C 39                                         |i.9|
00000053
```

Client is OS X 10.10.5 and Munki 2.6.1.2684.  Tested against OS X 10.11 and Munki 2.6.1.2684 and quarantine xattr is preserved there as well.

**Comment by gregneagle** [comment]
Test this, please: https://github.com/munki/munki/commit/827113f3d5953ba8f88207ac7b39a2e3dc97e7a0

**Comment by clburlison** [comment]
That commit has resolved my test case. Thinks ditto!

**Comment by foigus** [comment]
Resolved my issue as well (I did need to bump to the Munki 2.7 release in order to allow `powermgr` to be imported).

Thanks!
