### ISSUE TITLE
Please Digitally Sign Munki

### ISSUE THREAD

**Issue by delize** [munki/munki#613]
Our InfoSec team has raised concerns that the package on the release page is not digitally signed.

I was wondering what it would take (apart from creating our own internal version of Munki) to have the package digitally signed by the author?

Thanks,

**Comment by gregneagle** [comment]
If this is important to you, build it yourself from source (after auditing the source) and sign it yourself.

I have no plans to offer a signed package.

**Comment by gregneagle** [comment]
That might have come of more brusque than intended -- I don't want to add to my time and expense; I'd need to register a AppleID and Developer account for the Munki Project to get access to a Developer signing cert which I'd then have to keep secure and renew at regular intervals yet also consistently use to sign all releases. It's just work I personally do not need and am not interested in adding to my plate.

**Comment by bochoven** [comment]
Here's our (redacted)  munkitools signing one-liner:

```sh
productsign --sign "Developer ID Installer: Our Company (XXXXX99XX)" munkitools-2.3.0.2520.pkg munkitools-2.3.0.2520-signed.pkg
```

**Comment by delize** [comment]
@gregneagle Yeah, just a bit. But it is alright, I understood the reasoning as to why you would have no plans to sign it yourself. It's all good. :)

@bochoven I will be sure to use that depending on the outcome internally. :)
