### ISSUE TITLE
MSC/Munki Download Path

### ISSUE THREAD

**Issue by MIOResNet** [munki/munki#614]
Hello,

So we are wondering if it is possible to change the default download path for apps to install. We are in a frozen environment using Deep Freeze and are trying to see if we can change the download directory to a "Thawspace" so we don't hammer the server every day with 500+ machines all at once. 

The goal is to have them intermittently  check in and only download the updates into a specific folder, then at a specified time a script runs to update from that folder. 

We tried looking at the Munki2 build but that seemed inefficient, any help would be appreciated.

**Comment by gregneagle** [comment]
See: https://github.com/munki/munki/wiki/Preferences

Set ManagedInstallDir to a directory in your "Thawspace".

Alternately, use a symlink to point to your "Thawspace" for the Cache folder

Let's keep the Issues for actual bugs/code issues -- if you want to discuss this further use the munki-discuss or munki-dev mailing lists, please.
