### ISSUE TITLE
how to use munki to deploy installer package

### ISSUE THREAD

**Issue by risingsun6** [munki/munki#618]
Hi, thanks for reading my issue. I am now having a problem with munki. Only Drag-and-Drop applications are displayed in Managed Software Center. I have added the latest version of OS X El Capitan and java, but they do not show in Managed Software Center. 

Regards,

**Comment by gregneagle** [comment]
This is a place to report bugs with the code, not a general support forum.

https://github.com/munki/munki#get-help

Please post on munki-discuss.
