### ISSUE TITLE
softwareupdate options change in 10.12 causing issues with munki. 

### ISSUE THREAD

**Issue by weswhet** [munki/munki#619]
More or less a tracker for now but it seems that the `-v` and `-f` are no longer valid options for `softwareupdate` on 10.12..

`Checking for available Apple Software Updates...
    softwareupdate cmd: ['/usr/local/munki/ptyexec', '/usr/sbin/softwareupdate', '-v', '-l', '-f', '/tmp/munki_swupd_cache/ApplicableUpdates.plist']
    softwareupdate: invalid option -- v...
    softwareupdate: invalid option -- f...
    usage: softwareupdate <cmd> [<args> ...]...
    ** Catalog Management:...
    --set-catalog <URL>	Set the new catalog URL (requires privileges)...
    --clear-catalog		Clear the catalog URL back to defaults (requires privileges)...
    ** Manage Updates:...
    -l | --list		List all appropriate update labels (options:  --no-scan)...
    -d | --download		Download Only...
    -e | --cancel-download		Cancel a download...
    -i | --install		Install...
    <label> ...	specific updates...
    -a | --all		All appropriate updates...
    -r | --recommended	Only recommended updates...
    --background		Trigger a background scan and update operation...
    --ignore <label> ...	Ignore specific updates...
    --reset-ignored		Clear all ignored updates...
    ** Other Tools:...
    --suspend-background 	Suspend background operations from occurring temporarily (use --duration to specify duration to suspend in seconds)...
    --duration <duration>)		Optional duration in seconds to suspend background operations (defaults to 5*60 seconds)...
    --dump-state		Log the internal state of the SU daemon to /var/log/install.log...
    --evaluate-products		Evaluate a list of product keys specified by the --products option...
    ** Options:...
    --no-scan		Do not scan when listing or installing updates (use available updates previously scanned)...
    --products		A comma-separated (no spaces) list of product keys to operate on.
    --force			Force an operation to complete.  Use with --background to trigger a background scan regardless of "Automatically check" pref...
    --verbose	Enable verbose output...
    --help	Print this help...
Finishing...
    Performing postflight tasks...
`

**Comment by gregneagle** [comment]
See https://github.com/munki/munki/commit/811a22fd37d112ded403e9ef1d3cda2f85caa2f2

**Comment by gregneagle** [comment]
Pre-built for you here: https://munkibuilds.org/_branches/localized-apple-updates/2.7.0.2771/

**Comment by gregneagle** [comment]
Looks like I was prescient in wanting to remove the use of the undocumented `-f` flag as well.

**Comment by weswhet** [comment]
@gregneagle missing a comma between 10.11 and 10.12 in /usr/local/munki/munkilib/appleupdates.py

**Comment by weswhet** [comment]
`Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 59, in <module>
    from munkilib import updatecheck
  File "/usr/local/munki/munkilib/updatecheck.py", line 35, in <module>
    import appleupdates
  File "/usr/local/munki/munkilib/appleupdates.py", line 82
    '10.12': ('https://swscan.apple.com/content/catalogs/others/'`

**Comment by gregneagle** [comment]
So you should be able to fix that for your own testing.

https://github.com/munki/munki/commit/9b174ff7302ad7c49b9fa604998033298878e608 for everyone else.

**Comment by weswhet** [comment]
Looks good! Thanks

**Comment by gregneagle** [comment]
I'm closing this, as the localized-apple-updates branch will soon be merged into master.
