### ISSUE TITLE
Conditional Hostname "Like" with multiple "*" Fails

### ISSUE THREAD

**Issue by BaddMann** [munki/munki#620]
I'm trying to make a conditional manifest based on my hostnames.

If I have more then one * wildcard the manifest errors out munki on the computers that fall within the condition.
I've tried this with OS version and don't see any problems with multiple * wildcards there.

Error I Got for my absolute worse LIKE string:
`ValueError: NSInvalidArgumentException - Can't do regex matching, reason: (Can't open pattern U_REGEX_RULE_SYNTAX (string bld1-200-t373538-m.domain.com, pattern *-*-T*-M, case 0, canon 0))`

I've managed to make a reasonable LIKE check, but I thought you might like to know about this.

**Comment by BaddMann** [comment]
Sorry, stable release.....

**Comment by gregneagle** [comment]
Munki is just using OS X/Cocoa's NSPredicates. You need to follow the rules of those.

https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/Predicates/Articles/pSyntax.html

If you create a predicate string that NSPredicate doesn't like, all Munki can do is tell you, which is what it did. So I'd say it's functioning as designed.

**Comment by gregneagle** [comment]
You originally wrote "If I have more then one * wildcard the manifest crashes munki" and then you changed it to "If I have more then one * wildcard the manifest errors out munki".

Could you please post a transcript showing the actual behavior, perhaps with a `managedsoftwareupdate -vvv` run?

**Comment by gregneagle** [comment]
```python
#!/usr/bin/python

import sys
import os
from Foundation import NSDate

from Foundation import NSPredicate

def doComparison(comp_string, obj):
    print 'Comparison: %s' % comp_string
    try:
        p = NSPredicate.predicateWithFormat_(comp_string)
    except Exception, e:
        print >> sys.stderr, "WARNING: %s" % e
        print False
        print
        return
        
    print p.evaluateWithObject_(obj)
    print

info = {}
info['hostname'] = 'bld1-200-t373538-m.domain.com'

print info
print

predicate = 'hostname LIKE "*-*-t*-m.*"'
doComparison(predicate, info)

predicate = 'hostname LIKE "*-*-T*-M.*"'
doComparison(predicate, info)

predicate = 'hostname LIKE[c] "*-*-T*-M.*"'
doComparison(predicate, info)

predicate = 'hostname MATCHES ".*-.*-t.*-m.*"'
doComparison(predicate, info)

predicate = 'hostname MATCHES ".*-.*-T.*-M.*"'
doComparison(predicate, info)

predicate = 'hostname MATCHES[c] ".*-.*-T.*-M.*"'
doComparison(predicate, info)
```

output:

```
{'hostname': 'bld1-200-t373538-m.domain.com'}

Comparison: hostname LIKE "*-*-t*-m.*"
True

Comparison: hostname LIKE "*-*-T*-M.*"
False

Comparison: hostname LIKE[c] "*-*-T*-M.*"
True

Comparison: hostname MATCHES ".*-.*-t.*-m.*"
True

Comparison: hostname MATCHES ".*-.*-T.*-M.*"
False

Comparison: hostname MATCHES[c] ".*-.*-T.*-M.*"
True
```

**Comment by gregneagle** [comment]
```
predicate = 'hostname LIKE *-*-T*-M'
doComparison(predicate, info)
```

results in `WARNING: NSInvalidArgumentException - Unable to parse the format string "hostname LIKE *-*-T*-M"`

But since I don't know your exact comparison predicate, I'm just guessing here.

**Comment by BaddMann** [comment]
Yeah i realized Crash was to strong a phrase when it just fail to load the manifest.
Sometime had an Error 100.

You included another * for domain!!!
Oh no I feel dumb.

**Comment by gregneagle** [comment]
I'd still like to see a transcript of a session demonstrating what you are seeing. I don't really know if there is an issue here to address -- there's not enough information in your description.

**Comment by BaddMann** [comment]
Email?

**Comment by gregneagle** [comment]
No -- you can attach files here. Or copy and paste text.

**Comment by BaddMann** [comment]
I can't, in good conscience just upload the log from a production machine to a very public Github. 
I'm sorry. 

I did perform a ton of tests though and then filtered the results with this command.

All my host names are capitalized on my Macs. How Munki receives the hostname is beyond me. 
Why I sometimes get hostnames on some macs and then FQDN on others is a problem I'm thinking is unrelated, but I think that's related to my techs not doing certain tasks. Though I had to rule this out so I included multiple checks. 
Two looking for the FQDN (in multiple cases), two with the hostname only (in multiple cases) and the third just gets both cause it's not looking for the period between host and domain al in multiple cases.

What I've found is that it definitely appears to be case sensitive search even though this article says the search is suppose to be case-insensitive: https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/Predicates/Articles/pSyntax.html

What's weird is it all has to be lowercase.

This output is all from the same host: BLD1-200-T50-M.domain.edu

`managedsoftwareupdate -vvv | grep "Predicate hostname" | sort | uniq`

```
    Predicate hostname LIKE "*-*-T*-M" is False
    Predicate hostname LIKE "*-*-T*-M*" is False
    Predicate hostname LIKE "*-*-T*-M.*" is False
    Predicate hostname LIKE "*-*-T*-M.*EDU" is False
    Predicate hostname LIKE "*-*-t*-m" is False
    Predicate hostname LIKE "*-*-t*-m*" is True
    Predicate hostname LIKE "*-*-t*-m.*edu" is True
    Predicate hostname LIKE "fa-*-m.*edu" is False
```

Again sorry for not giving the full log.
I was about to setup a test environment, so I could provide full logs, but my day ran out.

**Comment by BaddMann** [comment]
Nope I'm just rather dyslexic and totally mis-read something.

> String comparisons are, by default, case and diacritic sensitive. You can modify an operator using the key characters c and d within square braces to specify case and diacritic insensitivity respectively, for example firstName BEGINSWITH[cd] $FIRST_NAME.


I'm going to stop trying to be helpful and assume I'm an idiot.

**Comment by gregneagle** [comment]
I really wanted to see the output to understand if there was an issue to fix there. Oh well. :-(

I did suggest you sanitize the log files -- all I really cared about was the logging around evaluating your problematic comparison.
