### ISSUE TITLE
Problems with InstallCheck_Script

### ISSUE THREAD

**Issue by Benni1012** [munki/munki#626]
Hi,
I have this little script as a part of my pkgsinfo.

`>#/bin/sh

OUTPUT=$(sudo /usr/local/bin/RemoteUpdateManager --action=list)
STRING="Following Updates are applicable on the system"

#Adobe Updates Verfuegbar
if [[ "$OUTPUT" =~ "$STRING" ]]; then exit 0; fi

#Keine Adobe Updates Verfuegbar
exit 1`

When I run this on my clients by hand its working. 
I got the following error: 
`        0..20..40..60..80..100
ERROR: Error executing script installcheck_script: [Errno 8] Exec format error
    Getting icon Install Wacom Tablet.png for Wacom Tablett...
    Getting client resources...
    Getting client resources...
Checking Apple Software Update catalog...`

Has anyone an Idea?

And I got another problem. When I am piped somthing from stderr to stdout in an InstallCheck_Script.
`something 2>&1`
I get the following error when I am run "makecatalogs"

`Unexpected error for /Library/Server/Web/Data/Sites/munki_repo/pkgsinfo/configs/adobeupdater/adobeupdaterrun.pkginfo: Encountered unknown ampersand-escape sequence at line 24 in file /Library/Server/Web/Data/Sites/munki_repo/pkgsinfo/configs/adobeupdater/adobeupdaterrun.pkginfo
`
Best regards
Benni

**Comment by gregneagle** [comment]
This issue tracker is for tracking code issues (bugs) and feature requests. It's not a general support forum. Please post to [munki-discuss](https://groups.google.com/group/munki-discuss).

https://github.com/munki/munki#get-help

**Comment by Benni1012** [comment]
The script is still fine. So Munki or Python give me an error.

**Comment by arubdesu** [comment]
@Benni1012 if you make an invalid launchd job that doesn't run do you file an issue with Apple? Please use the provided resources to continue this conversation.

**Comment by Benni1012** [comment]
@arubdesu the problem with the pipe is a bug in makecatalogs.

**Comment by natewalck** [comment]
@Benni1012 please post this to munki-discuss. This is not a support
channel.

Also, it may not be work if your script isn't encoded properly to be inside
a plist. There is more to it then copy and pasting a bash script into a
plist. See the wiki for details on scripts within your pkginfo.

Nate
