### ISSUE TITLE
munki import doesn't use CFPreferences

### ISSUE THREAD

**Issue by erikng** [munki/munki#638]
Tracking this so I don't forget but munki import and all the other admin tools have a hard coded path to the user library. This makes automating a munki setup with mobile configuration files impossible.

**Comment by gregneagle** [comment]
Not _impossible_... You could use mobile configuration files created with mcxToProfile with Set-Once (Once or Often) frequency if you need something to work today.

**Comment by gregneagle** [comment]
Upon investigation, Munki Enterprise Support has determined this is a duplicate of issue #347.

**Comment by erikng** [comment]
Okay good idea. And that's hilarious.
