### ISSUE TITLE
Munki 2.8.0 RC 1 trouble importing output from CreateOSXinstallPkg

### ISSUE THREAD

**Issue by aysiu** [munki/munki#640]
This doesn't seem to be a universal problem, but at least I and one other person have experienced it:
https://groups.google.com/d/msg/munki-dev/yq-fb8p4Vyk/1IKWT-rtCAAJ

Steps to reproduce:
1. Create install pkg for OS X El Capitan 10.11.6.
2. use `munkiimport` to get it into Munki repo.

Just to make sure `munkiimport` itself is working in RC1, I tried it (same machine) with TextWrangler.app and outset.pkg, and both imported just fine.

```
munkiimport Downloads/InstallOSX_10.11.6_15G31.pkg
Making disk image containing InstallOSX_10.11.6_15G31.pkg...
created: /tmp/munki-ML6ZL7/InstallOSX_10.11.6_15G31.dmg
Disk image created at: /tmp/munki-ML6ZL7/InstallOSX_10.11.6_15G31.dmg
Traceback (most recent call last):
  File "/usr/local/munki/munkiimport", line 1152, in <module>
    main()
  File "/usr/local/munki/munkiimport", line 946, in main
    pkginfo = make_pkginfo(arguments)
  File "/usr/local/munki/munkiimport", line 665, in make_pkginfo
    return FoundationPlist.readPlistFromString(stdout)
  File "/usr/local/munki/munkilib/FoundationPlist.py", line 105, in readPlistFromString
    raise NSPropertyListSerializationException(error)
munkilib.FoundationPlist.NSPropertyListSerializationException: Unknown character 'L' (0x4c) in <integer> on line 25
```

**Comment by aysiu** [comment]
I think I found the culprit. From the output of `makepkginfo`:
```
<key>installed_size</key>
	<integer>8388608L</integer>
```
There's an `L` inside what should be an integer

If I run the same `makepkginfo` on the same .pkg with 2.7, I get this output:
```
<key>installed_size</key>
	<integer>8388608</integer>
```
No `L` in there.

**Comment by arubdesu** [comment]
Looking through commit history, `makepkginfo` code hasn't changed between 2.7 and current, so it seems there's some other environmental issue at play.

**Comment by gregneagle** [comment]
The relevant change is in munkicommon I believe.

**Comment by aysiu** [comment]
Thanks! Let me know if there's any other info you need from me.

**Comment by gregneagle** [comment]
This commit: https://github.com/munki/munki/commit/5cf1d4f6a0747cb556dca104489b4531a00085b7

and even more specifically, the removal of the code around here:
https://github.com/munki/munki/commit/5cf1d4f6a0747cb556dca104489b4531a00085b7#diff-bf5dfb5469914317f1f44fd61822ae90L1271

**Comment by aysiu** [comment]
I can confirm the new RC fixed this issue. Thanks, Greg!
