### ISSUE TITLE
fixed time interval for update check

### ISSUE THREAD

**Issue by islamadel** [munki/munki#642]
Hello,
How can I fix the time interval for munki update check to be every 2 hours (and not less)?
Thanks

**Comment by arubdesu** [comment]
Yes. 
https://github.com/munki/munki/wiki/Launchd-Jobs-and-Changing-When-Munki-Runs

**Comment by gregneagle** [comment]
GitHub issues are for reporting bugs and requesting new features. Please use the Google Groups/mailing lists for general support questions.

(Thank you, Allister, for responding)  

https://github.com/munki/munki#get-help
