### ISSUE TITLE
Pkg installs crash on munki 2.8.0.2809

### ISSUE THREAD

**Issue by MiqViq** [munki/munki#645]
For some reason 2.8.0.2809 cannot install some of my installer packages (generated by autopkg or manually using pkgbuild).
Munki version 2.7.1.2774 works just fine.
When manually installing those pkgs it works, also with using /usr/sbin/installer -pkg.
Tested with cli and MSC-app.

OS X 10.11.6.

2.8.0.2809 crash log on installing a problematic pkg:

ERROR: Unexpected error in munkilib.installer:
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 1052, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 844, in main
    mustrestart = doInstallTasks(appleupdatesavailable)
  File "/usr/local/munki/managedsoftwareupdate", line 232, in doInstallTasks
    only_unattended=only_unattended)
  File "/usr/local/munki/munkilib/installer.py", line 1222, in run
    only_unattended=only_unattended)
  File "/usr/local/munki/munkilib/installer.py", line 768, in installWithInfo
    installer_environment)
  File "/usr/local/munki/munkilib/installer.py", line 120, in install
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings

**Comment by MiqViq** [comment]
Munki 2.8.0.2809 can install some pkgs, like when downgrading to munki_core-2.7.1.2774.pkg.
So there must be an issue with a certrain kind of pkg that  2.8.0.2809 cannot handle?
Maybe 10.11.6 has some additional security settings regarding pkg signing?

**Comment by gregneagle** [comment]
It would be incredibly helpful in diagnosing this issue to have a way to reproduce it. Can you provide an example package that triggers this crash? I have not yet seen _any_ package trigger a problem like this.

**Comment by gregneagle** [comment]
Updating issue here since it's getting sprayed across multiple channels...

@MiqViq sent me a couple of packages that are crashing for him. I imported them into a test Munki repo and was able to install them without any issues using Munki 2.8.0.2809.

**Comment by gregneagle** [comment]
I can reproduce the exact exception traceback in a different context:

```
import subprocess
>>> proc = subprocess.Popen(['/usr/sbin/pkgutil', '-pkgs', 2])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
```

In your report, Munki's code raises an unhandled exception here:
```
File "/usr/local/munki/munkilib/installer.py", line 120, in install
stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```
Context:

https://github.com/munki/munki/blob/master/code/client/munkilib/installer.py#L115-L120

This would seem to imply that either `pkgpath` or `choicesXMLpath` is not a string. Again this leads us back to your pkginfo...

**Comment by MiqViq** [comment]
Did some more testing on a 10.11 VM that has nothing but the base OS.

If I remove "suppress_bundle_relocation" or set it to false in pkginfo for Cyberduck it will not fail.

So it seems that later munki version 2809 stumbles on that?


-MiqViq

**Comment by gregneagle** [comment]
Seems unlikely to be the trigger:

https://github.com/munki/munki/blob/master/code/client/munkilib/installer.py#L63

It should do absolutely nothing on your flat packages since they are not directories.

**Comment by gregneagle** [comment]
...and I think I found the issue. Please try your items against https://github.com/munki/munki/commit/97957434d5487b477d069499035d0fd9f4e25280

Pre-built for your convenience here: https://munkibuilds.org/2.8.0.2810/

**Comment by MiqViq** [comment]
Fix worked, CyberDuck with suppress_bundle_relocation=true installs fine with 2.8.2810.

Thanks!

-MiqViq

**Comment by MiqViq** [comment]
...and also works with Monotype SkyFonts with suppress_bundle_relocation=true.

-MiqViq

**Comment by gregneagle** [comment]
Was now also able to reproduce the crash and verify that latest commit fixes it.
