### ISSUE TITLE
Add preference to bypass system proxy

### ISSUE THREAD

**Issue by verycarefully** [munki/munki#646]
I'd like for my Munki clients to ignore system proxy settings and connect directly to my Simian server.

This should be a straightforward change since [gurl.py](https://github.com/munki/munki/blob/master/code/client/munkilib/gurl.py) is using NSURLSession:

```
from CFNetwork import kCFNetworkProxiesHTTPSEnable
[...]
configuration.setConnectionProxyDictionary_({ kCFNetworkProxiesHTTPSEnable: False })
```

I suspect many (most?) people won't want this configuration though, and would prefer their munki connections go through the (managed) proxy, so I propose exposing a default-off flag ("NoProxy", perhaps?) in [ManagedInstalls.plist](https://github.com/munki/munki/blob/master/Preferences/ManagedInstalls.plist). 

Let me know if this change sounds good and I'll send a PR.

**Comment by gregneagle** [comment]
Admins should opt-in to this behavior by setting IgnoreSystemProxies to True in the ManagedInstalls preferences domain. I think you should also turn off proxies for HTTP as well as HTTPS if you are going to do this.

**Comment by gregneagle** [comment]
Note also that gurl.py never reads Munki's preferences directly --  the preference reading would happen in fetch.py, which would pass the option to Gurl.initWithOptions_()
