### ISSUE TITLE
munkicommon.get_ipv4_addresses() missing

### ISSUE THREAD

**Issue by fuzzycheck** [munki/munki#648]
Hi,
  I have a preflight script that relies on munkicommon.get_ipv4_addresses(), but it seems to have disappeared in this version. Could you please re-include it?

$ munkiimport --version
2.8.0.2810

>>> from munkilib import fetch, munkicommon
>>> munkicommon.get_ipv4_addresses()
>>> dir (munkicommon)
['ADDITIONAL_HTTP_HEADERS_KEY', 'APPDATA', 'APP_DISCOVERY_EXCLUSION_DIRS', 'BUNDLE_ID', 'CFPreferencesAppSynchronize', 'CFPreferencesCopyAppValue', 'CFPreferencesCopyKeyList', 'CFPreferencesSetValue', 'CONDITIONS', 'DMGhasSLA', 'DMGisWritable', 'EXIT_STATUS_INVALID_PARAMETERS', 'EXIT_STATUS_MUNKI_DIRS_FAILURE', 'EXIT_STATUS_OBJC_MISSING', 'EXIT_STATUS_PREFLIGHT_FAILURE', 'EXIT_STATUS_ROOT_REQUIRED', 'EXIT_STATUS_SERVER_UNAVAILABLE', 'Error', 'FILESYSTEMS', 'FoundationPlist', 'LOGINWINDOW', 'LaunchServices', 'MACHINE', 'MANAGED_INSTALLS_PLIST_PATH', 'ManagedInstallsPreferences', 'MunkiLooseVersion', 'NSDate', 'NSMetadataQuery', 'NSPredicate', 'NSRunLoop', 'Popen', 'Preferences', 'PreferencesError', 'SCDynamicStoreCopyConsoleUser', 'SECURE_MANAGED_INSTALLS_PLIST_PATH', 'SP_APPCACHE', 'SecureManagedInstallsPreferences', 'StringType', 'TimeoutError', '_TMPDIR', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '_asciizToStr', '_fFlagsToSet', '_stop_requested', '_unsigned', 'archive_report', 'blockingApplicationsRunning', 'cleanUpTmpDir', 'concat_log_message', 'configure_syslog', 'ctypes', 'currentGUIusers', 'diskImageForMountPoint', 'diskImageIsMounted', 'display_debug1', 'display_debug2', 'display_detail', 'display_error', 'display_info', 'display_percent_done', 'display_status_major', 'display_status_minor', 'display_warning', 'fcntl', 'findAppsInDirs', 'findProcesses', 'forceLogoutNow', 'format_time', 'getAppBundleExecutable', 'getAppData', 'getAvailableDiskSpace', 'getBomList', 'getBundlePackageInfo', 'getBundleVersion', 'getChoiceChangesXML', 'getConditions', 'getFilesystems', 'getFirstPlist', 'getFlatPackageInfo', 'getInstalledPackageVersion', 'getIntel64Support', 'getLSInstalledApplications', 'getMachineFacts', 'getOnePackageInfo', 'getOsVersion', 'getPackageMetaData', 'getPkgRestartInfo', 'getReceiptInfo', 'getRunningProcesses', 'getSPApplicationData', 'getSpotlightInstalledApplications', 'getVersionString', 'get_hardware_info', 'get_ip_addresses', 'get_version', 'getconsoleuser', 'gethash', 'getmd5hash', 'getsha256hash', 'getsteps', 'hasValidConfigProfileExt', 'hasValidDiskImageExt', 'hasValidInstallerItemExt', 'hasValidPackageExt', 'hashlib', 'hdiutilInfo', 'isAppRunning', 'isApplication', 'isExcludedFilesystem', 'kCFPreferencesAnyUser', 'kCFPreferencesCurrentHost', 'kCFPreferencesCurrentUser', 'listdir', 'log', 'logging', 'main', 'minidom', 'mountPointsForDiskImage', 'mountdmg', 'munkistatus', 'munkistatusoutput', 'nameAndVersion', 'os', 'osascript', 'padVersionString', 'parsePkgRefs', 'pathIsVolumeMountPoint', 'platform', 'pref', 'printreport', 'printreportitem', 'pythonScriptRunning', 're', 'readreport', 'reload_prefs', 'report', 'reset_errors', 'reset_warnings', 'rotate_main_log', 'rotatelog', 'runEmbeddedScript', 'runScript', 'saveappdata', 'savereport', 'select', 'set_file_nonblock', 'set_pref', 'shutil', 'signal', 'stopRequested', 'str_to_ascii', 'struct', 'subprocess', 'sys', 'tempfile', 'time', 'tmpdir', 'to_unicode', 'unmountdmg', 'urllib2', 'validPlist', 'validateDateFormat', 'verbose', 'version', 'warnings', 'writefile']

**Comment by gregneagle** [comment]
I think you should modify your script. The functions inside the various munkilib files are for Munki's use and they aren't a stable, documented API.

```
try:
    foo = munkicommon.get_ipv4_addresses()
except AttributeError:
    foo = munkicommon.get_ip_addresses('IPv4')
```

or similar.

**Comment by fuzzycheck** [comment]
Thanks Greg. I'll try that.
