### ISSUE TITLE
Relative vs. hardcoded paths to munki components

### ISSUE THREAD

**Issue by arubdesu** [munki/munki#656]
I was looking at #563's focus on moving the component tools around and currently only see `munkiimport` and `appleupdates.py` as targeting `/usr/local/munki`. Would a PR to make those relative be accepted? Would it be ok to target the master branch with those modifications? (Just for future reference, repoclean, paths.d and the build scripts like make_munki_mpkg.sh would need to eventually be updated as well, but all of those can be on hold for now.)

**Comment by gregneagle** [comment]
We certainly can reduce the use of/need for hard-coded paths, but we cannot eliminate them completely. Launchd jobs need absolute hard-coded paths to the executables they launch and the files they watch.

In munkimport, the code _already_ checks the relative path before falling back to absolute if unsuccessful:

https://github.com/munki/munki/blob/master/code/client/munkiimport#L625-L630
https://github.com/munki/munki/blob/master/code/client/munkiimport#L670-L675

Same with repoclean:
https://github.com/munki/munki/blob/master/code/client/repoclean#L129-L134

Same with appleupdates.py:
https://github.com/munki/munki/blob/master/code/client/munkilib/appleupdates.py#L1343-L1351

I don't see anything at all that needs to be/can be done currently.

**Comment by arubdesu** [comment]
Agreed, pardon the bother. Closing.
