### ISSUE TITLE
Are there new instructions for making munki with client certs work on El Capitan? 

### ISSUE THREAD

**Issue by rangaa** [munki/munki#659]
Followed these instructions but not able to make it work under El Capitan/ Apache 2.4.18. Sounds like several changes to apache from earlier version of OS X to El Capitan. 
SSLMutex seems is dropped in 2.4
Getting errors for custom logs with rotatelogs as well. Guessing something related to changes there as well.
Mostly, not able to start the munki web server on port 443 using munki.conf. Please point to the right repository.

Thanks
rangaa

**Comment by gregneagle** [comment]
There is no new documentation, and none planned by me at least -- I don't even recommend the use of OS X Server as a Munki server. User-contributed documentation is always welcome.

**Comment by rangaa** [comment]
Thanks!
