### ISSUE TITLE
JAMF Self Service Dock icon badge shows same count as Managed Software Center

### ISSUE THREAD

**Issue by fuzzylogiq** [munki/munki#660]
Hi,

Being one of the few users who use the JSS in combination with munki, we noticed that the badge count on JAMF's Self Service application was showing the same count as Managed Software Center, regardless of the number of items requiring attention in Self Service.

I tracked this down to the following error in system.log:

`com.apple.dock.extra[26734]: objc[26734]: Class DockTilePlugIn is implemented in both /Applications/Self Service.app/Contents/PlugIns/SSDockTilePlugin.docktileplugin/Contents/MacOS/SSDockTilePlugin and /Applications/Managed Software Center.app/Contents/PlugIns/MSCDockTilePlugin.docktileplugin/Contents/MacOS/MSCDockTilePlugin. One of the two will be used. Which one is undefined.`

So it looks like there is a namespace collision in the naming of the DockTilePlugIn classes used by both Self Service and the MSC. A PR is forthcoming for MSC, we've also filed a bug report with JAMF to get them to rename theirs.

**Comment by gregneagle** [comment]
Addressed in #661
