### ISSUE TITLE
Feature request: manifestutil display-manifest return all included manifests & packages

### ISSUE THREAD

**Issue by cwindus** [munki/munki#663]
One of the things that I find myself doing from time to time is checking the complete "inherited" state of a particular manifest, to which I wrote a simple python tool (https://github.com/cwindus/munki_utils/blob/master/inherited_packages.py) that would do this for me.

Ideally, `manifestutil display-manifest` would also look at a given manifest, and recurse through any included manifests to output what a given manifest actually "inherits".
This is particularly useful for inspecting machine level manifests before deployment, or for instances where running `managedsoftwareupdate` on a client is not practical.

**Comment by gregneagle** [comment]
While I'm not opposed to the idea of a new verb that does what you suggest here, I think `display-manifest` should continue to simply display the contents of the manifest.

**Comment by gregneagle** [comment]
at least `display-manifest` should continue its current behavior by default; perhaps a new flag could cause it to recursively display included manifests.

**Comment by cwindus** [comment]
A new verb would certainly make sense, as I understand the reasoning behind `display-manifest` being used for a specific manifest.

**Comment by gregneagle** [comment]
Of course now that I think about it more, since `manifestutil` is usually used interactively, a new verb would be more useful than an additional option flag to the existing `display-manifest` verb.

I don't actually use `manifestutil` much, but would probably accept a PR adding this functionality.

**Comment by cwindus** [comment]
Cool, I'll have a play around wrangling my code into something submittable for a PR.

**Comment by cwindus** [comment]
I'm curious as to people's thoughts on the best output format?
Currently testing output like this:

![image](https://cloud.githubusercontent.com/assets/17076873/18935373/ec31a3f8-8622-11e6-85eb-2a14e3a66af3.png)

**Comment by gregneagle** [comment]
You'll probably want to post on munki-dev and/or munki-discuss and point people at this FR issue.

**Comment by cwindus** [comment]
Thanks Greg, will do. I may have jumped the gun a bit with the PR.

**Comment by poundbangbash** [comment]
Interesting idea.  manifestutil is my primary method of managing munki and I use the tab auto-complete constantly.  Instead of duplicating the beginning of the verb can I suggest it be something more unique like `expanded-manifest-display`?  That way it won't conflict with `disp<tab>`.

Also, if possible, having the displayed included-manifest info cascade at the point of the included-manifest would be easier to read and see the relation to the manifests in my opinion.

Something like:

```
$ manifestutil expanded-manifest-display VMH49bwaLxlK

catalogs:
	 testing
	 production
included_manifests:
	 au.edu.qld.redlands.staff.desktop.exec-assistants
		 catalogs:
			 production
		 included_manifests:
			 au.edu.qld.redlands.staff.desktop.common
				 catalogs:
					 production
				 included_manifests:
					 au.edu.qld.redlands.apps-collection.office.mandatory-install
					 au.edu.qld.redlands.apps-collection.iwork.mandatory-install
					 au.edu.qld.redlands.all.common
					 au.edu.qld.redlands.apps-collection.teachers.mandatory-install
					 au.edu.qld.redlands.lpt-collection.staff.mandatory-install
				 managed_installs:
					 au.edu.qld.redlands.pol.common.clear-nvram
					 au.edu.qld.redlands.pol.common.computer-sleep
					 au.edu.qld.redlands.pol.common.device-aup
					 au.edu.qld.redlands.pol.common.efi-passwd
					 au.edu.qld.redlands.pol.common.partitions
					 au.edu.qld.redlands.pol.common.shared-user-fix
					 au.edu.qld.redlands.pol.common.user-mask
					 au.edu.qld.redlands.pol.profile.common.disable-siri
					 au.edu.qld.redlands.pol.profile.common.screensaver-lock
					 au.edu.qld.redlands.pol.profile.staff.common.app-restrictions
				 optional_installs:
					 au.edu.qld.redlands.app.virtualbox
		 optional_installs:
			 au.edu.qld.redlands.app.handbrake
			 au.edu.qld.redlands.app.ibooks-author
managed_installs:
managed_uninstalls:
optional_installs:
```

Though I don't know how unruly it would get with multiple nested included-manifests.  In our environment we rarely have more than one nested included-manifest.  A manifest will have an included-manifest but that included-manifest won't have one.

-Eric

**Comment by cwindus** [comment]
Hmmm. The additional indenting of manifests is an interesting thought, and yes, certainly makes the included manifest hierarchy clearer.

The environment here is configured to use multiple manifests that get included in various manifests, so I can avoid putting packages in machine specific manifests, rather assigning the package to a manifest for a particular 'role'; it helps me keep the number of manifests a single package touches to a minimum - I don't want to keep updating five different manifests when I add a new package, etc.

At present I'm simply calling `printplist()` for the output, I'll look at ways I can indent the hierarchy.

**Comment by erikng** [comment]
Good work Carl. I don't use manifestutil either, but I like it!

Sent from my iPhone

On Sep 28, 2016, at 7:27 PM, Carl <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmmm. The additional indenting of manifests is an interesting thought, and yes, certainly makes the included manifest hierarchy clearer.

The environment here is configured to use multiple manifests that get included in various manifests, so I can avoid putting packages in machine specific manifests, rather assigning the package to a manifest for a particular 'role'; it helps me keep the number of manifests a single package touches to a minimum - I don't want to keep updating five different manifests when I add a new package, etc.

At present I'm simply calling printplist() for the output, I'll look at ways I can indent the hierarchy.

-

**Comment by cwindus** [comment]
@poundbangbash - I may just pass on that particular indentation process for the time being! I'm struggling to wrap my head around the process of doing that 😑  💀 

I have however taken the recommendation re tab completing, and changed the method and verb to `expand-included-manifests`.

**Comment by gregneagle** [comment]
Closing as this has been merged.
