### ISSUE TITLE
FEATURE REQUEST - Add a new value for installer_type for installer apps like webex

### ISSUE THREAD

**Issue by antoinemonnier** [munki/munki#668]
Hi

I don't found any way to import correctly into munki an app that is the installer of the final app. WebEx doesn't give us the standalone app but only an installer for the cisco add on webex

Could it be possible to add a new value for installer_type where we tell to munki that the app is an installer and it must run it to install. (and not just copying it).

**Comment by gregneagle** [comment]
Not in a generic way, no. Munki runs as root -- it can't run and control an arbitrary GUI app to install things.
