### ISSUE TITLE
Add external Script for Notifications

### ISSUE THREAD

**Issue by aschwanb** [munki/munki#671]
This is an idea for a feature request inspired by Grahams excellent poste [here](https://grahamgilbert.com/blog/2016/08/29/more-notifications-with-yo-the-yo-strikes-back/):
It seems like there are some good tools that handle custom user notifications. [yo](https://github.com/sheagcraig/yo/releases) comes to mind to name just one. Maybe munki could let them handle the daily task of reminding users about their updates.

This could be implemented using a new ManagedInstalls Key: `RunScriptForNotification` If the key is set, munki will execute the script every time it reminds user to update. If it is not set, it will return to it's default logic.

**Comment by gregneagle** [comment]
Please see https://github.com/munki/munki/wiki/FAQ#q--how-is-a-user-notified-of-available-updates and https://github.com/munki/munki/wiki/FAQ#q-does-munki-support-notification-center-notifications. While not directly addressing your proposal, it does reflect my thinking about Munki update notifications. I'm not interested in supporting alternatives and the additional logic complexity at the current time.

You could certainly implement something for yourself along the lines you suggest with no code changes in Munki. Set SuppressUserNotification to true to prevent MSC.app from launching to notify about updates, then implement a Munki postflight script that does your alternative notification. You'd read the PendingUpdateCount from /Library/Preferences/ManagedInstalls to see if there are available updates, and perhaps use your own logic for how _often_ to notify, and then use Yo.app or similar to display your notifications.

**Comment by aschwanb** [comment]
Thank you for your detailed reply. I agree with you that postflight scripts have more flexibility at this point. Thanks gain.

I'll close this issue.
