### ISSUE TITLE
Show managed_installs and managed_updates in "My items"

### ISSUE THREAD

**Issue by nathanperkins** [munki/munki#680]
Hello,

I think it'd be an improvement if users could see the packages that are being automatically installed on their system. It can be confusing for the user if they delete an application and Munki keeps replacing it. Adding managed_installs and managed_updates to the "My Items" tab in Managed Software Center would allow users to understand which packages are being managed by Munki.

For UX changes, I think you could add a dropdown to filter for all items, optional_installs, managed_installs, and managed_updates. Another field could be added to show that a package is mandatory, update, or optional.

This feature could be added along with a pkginfo tag that allows you to hide packages from My Items if IT wants to keep them hidden from users, for scripts and such.

Best,
Nathan

**Comment by erikng** [comment]
As a best practice, you should not add items to both managed_installs and optional. If you fix that architectural decision, your users will not be confused.

On Nov 1, 2016, at 6:17 PM, Greg Neagle <notifications@github.com<mailto:notifications@github.com>> wrote:


"My Items" are just that: Items I have chosen and have control over.

You might be arguing for the addition of a new tab, "Managed Items" or similar.

While I am not opposed to the idea, I have no plans to spend any time implementing it, especially with your additional complication/refinement of "a pkginfo tag that allows you to hide packages from [Managed Items] if IT wants to keep them hidden from users, for scripts and such" (which is probably needed, but complicates implementation as it requires admins to do something)

(Without that -- a proposed "Managed Items" would contain over 250 items here, many with such boring names as "libgsf" and "Perl-DBD-mysql" and "SOAPpy" and completely irrelevant to most users)

You might consider bringing up your idea on munki-dev for discussion.

-

**Comment by erikng** [comment]
Apologies, you stated if a user deletes an application.

Alternatively you could have a URL on your sidebar with a title "What We Manage" and you could display all items from managed_installs. This would require zero changes to munki.

Allister has an interesting tool that could work for this, but I can't remember the name.

On Nov 1, 2016, at 6:17 PM, Greg Neagle <notifications@github.com<mailto:notifications@github.com>> wrote:


"My Items" are just that: Items I have chosen and have control over.

You might be arguing for the addition of a new tab, "Managed Items" or similar.

While I am not opposed to the idea, I have no plans to spend any time implementing it, especially with your additional complication/refinement of "a pkginfo tag that allows you to hide packages from [Managed Items] if IT wants to keep them hidden from users, for scripts and such" (which is probably needed, but complicates implementation as it requires admins to do something)

(Without that -- a proposed "Managed Items" would contain over 250 items here, many with such boring names as "libgsf" and "Perl-DBD-mysql" and "SOAPpy" and completely irrelevant to most users)

You might consider bringing up your idea on munki-dev for discussion.

-

**Comment by aysiu** [comment]
I don't know if this is the same request, but I could see it being useful (instead of in My Items) for users to see managed_installs in the Software tab but just with no option to be removed. Again, that way they know Munki is managing things... just that they don't have an option for that particular item.

Totally agree with _I have no immediate plans to spend any time implementing it_, though. It isn't necessary functionality. More just a user experience nice touch enhancement.

**Comment by nathanperkins** [comment]
I wouldnt be opposed to adding the feature with a key for whitelisting items that you do want to show up in managed software update. I mostly want this for our standard deployment, which wouldnt be hard to whitelist.

**Comment by gregneagle** [comment]
Closing as there are no plans to change the implementation of "My Items".
