### ISSUE TITLE
Issue importing office 2016 into munki

### ISSUE THREAD

**Issue by Daleee** [munki/munki#683]
I'm having an issue importing my office 2016 pkg into munki so that it is accesible via MSC.

Before i explain, I've imported multiple new apps into our repo before with no issues.

Process:

Running munkiimport through terminal with path to installer.
Have gone through the details such as item, display name, catalogue etc
asks to import the item - hit Y
asks to find an icon - Hit Y (doesn't find one)

Anyway, it imports the pkg and pkginfo into the correct directories.

I rebuild the catalogues and refresh MSC and cannot get it to appear.

FYI i've put it in the testing catalogue and i do have access to to that catalogue.

I apologise if this isn't easy to read, i'm quite new to munki - any help would be appreciated

**Comment by arubdesu** [comment]
Hey Mr. Bobermien,
This is not an issue with the code itself, which is what GitHub issues are best used for. I would suggest either using the [munki-discuss](https://groups.google.com/group/munki-discuss) mailing list or the [MacAdmins Slack](http://macadmins.org) #munki channel to ask usage questions in the future. As a side point, even though this is yet another thing to become familiar with, the [autopkg](https://github.com/autopkg/autopkg) tool can automatically import non-volume license Office 2016 installers.

**Comment by Daleee** [comment]
Thankyou, i will try that!
