### ISSUE TITLE
Official Support for loading launchd's without reboot

### ISSUE THREAD

**Issue by erikng** [munki/munki#687]
Given the likelihood of imaging being deprecated in leu of DEP provisioning, I am wondering if we should have official support for the launchdaemons/agents to be loaded during installation.

Pros: 
- DEP bootstrap with munki can immediately function without additional packages/postinstall scripts that are custom to every company.
- Other traditional workflows can reduce a reboot.
- Reboot no longer needed through GUI installs
- Less need for autopkg recipes to deploy each sub munki pkg as the entire package can be deployed without issue. 

Cons:
- Will require a new launchd package
- Will more than likely require pre/post install for launchctl scripts and account for potential race conditions.
- This could be a breaking change for people who touch munki's trigger file during provisioning and expect a restart.
- Further documentation

**Comment by gregneagle** [comment]
This is far trickier than you might think: a postinstall script that unloaded/loaded the Munki launchdaemons would kill a Munki session that was trying to install an updated set of Munki launchdaemons...

Feel free to think about it and experiment, but it's incredibly low on my list of priorities.

**Comment by nmcspadden** [comment]
At an initial first pass, I'd be happy if this was limited just to "first time installs" - i.e. no Munki launchds are already loaded (and therefore wouldn't have any potential problems killing existing Munki processes by loading them).

**Comment by erikng** [comment]
Perhaps we only handle it for the first installation then and leave it alone.

**Comment by gregneagle** [comment]
Also, you note "Reboot no longer needed through GUI installs" -- rebooting also makes sure the updated launch _agents_ get loaded; without a reboot (or logout of all sessions) you'll need to handle the unload/load of the launch agents in all GUI sessions, again being careful to not kill anything in use by Munki...

**Comment by gregneagle** [comment]
"At an initial first pass, I'd be happy if this was limited just to "first time installs" --

We can detect if there are any Munki launch daemons running or loaded, but if there are, then we need to restart instead. You can't decide you need to restart in a package postinstall script, you have to decide _before_ the install starts -- indeed, even before a preinstall script runs. It would have to be done in a distribution script. Not impossible (I think), but not trivial...

**Comment by gregneagle** [comment]
FWIW, I have several non-imaging workflows that install the Munki tools as part of building or deploying a machine. If we get limited to only using MDM+DEP we have a lot more problems to deal with, one major one being the likelihood that Munki's primary developer stops working on Munki :-)

**Comment by gregneagle** [comment]
(not trying to shut this down -- just make sure you've really thought it through before committing to the work. It's not likely to be easy, and very likely to have some unpleasant failure modes)

**Comment by erikng** [comment]
So I've toyed with the following:

1. A fifth package that contains the launchdaemons and a secondary script to enable them.

2. A javascript function that calls an external script (which can be called using `productbuild --scripts /path/to/scripts --distribution --/path/to/distribution.xml`) to check if the launchdaemons/launchagents exist.

2a - If they exist, load the normal launchd package and install.
`<choice id "launchd" selected="true" enabled="true" visible="true" </choice>`
`<choice id "launchdnew" selected="false" enabled="false" visible="false" </choice>`
2b - If they do not, load the secondary launchd package
`<choice id "launchd" selected="false" enabled="false" visible="false" </choice>`
`<choice id "launchdnew" selected="true" enabled="true" visible="true" </choice>`

This is done via two javascript functions which call the same script, but return different values. For the example above I'm just using the boolean values vs the function call.

If this sounds like an appropriate method, I can finish the work on that and then we can discuss what the script should do. For now I have a simple shell script that runs launchctl.

**Comment by erikng** [comment]
For clarity, the javascript function/script is in the root level package and not the new package.

**Comment by gregneagle** [comment]
I'm not clear on why there is a "fifth" package with launchdaemons. What happened/happens to the current launchd pkg?

**Comment by erikng** [comment]
Correct. My thought process being that we don't have to create additional logic on how to handle upgrades - the files would just be replaced (we can remove the required restart from the current package as well). For new installations, the launchd with the postinstall script will be invoked.

If the javascript file detects a previous installation, the normal launchd package will load, otherwise the "new installation" launchd package will install.

**Comment by erikng** [comment]
After speaking with Greg, an alternative approach would be to do the following:

1. Add a postinstall script to the launchd pkg that detects if there are any GUI sessions or existing launchd receipts - if there are none, run the script.
2. Change the `onConclusion` property in the launchd pkg to also detect GUI sessions/existing launchd and only trigger a restart if they _exist_.

The only issue with part 2 is I have discovered that `onConclusion` does not accept javascript functions/external scripts. There is `onConclusionScript` which does, but this would break compatibility with [OS X 10.6](https://developer.apple.com/library/content/documentation/DeveloperTools/Reference/DistributionDefinitionRef/Chapters/Distribution_XML_Ref.html#//apple_ref/doc/uid/TP40005370-CH100-SW11).

Given that this would now be a breaking change, I would love input before I move further along with this.

**Comment by gregneagle** [comment]
The way to move forward is to build a new script to live alongside `make_munki_mpkg.sh` (or add more options to the existing package-building script) -- in either case what would be output is a new "DEP-friendly" package for use with DEP enrollments. Such a package would not replace the current official "mainstream/general-use" package, at least not in the near term.

**Comment by macmule** [comment]
I like the sound of that @gregneagle.

Would it be much more than removing the post install from the PackageInfo?
https://github.com/munki/munki/blob/master/code/tools/make_munki_mpkg.sh#L236

**Comment by erikng** [comment]
No. I will try and finish the work today.

Sent from my iPad

On Jan 10, 2017, at 2:04 AM, macmule <notifications@github.com<mailto:notifications@github.com>> wrote:


I like the sound of that @gregneagle<https://github.com/gregneagle>.

Would it be much more than removing the post install from the PackageInfo?
https://github.com/munki/munki/blob/master/code/tools/make_munki_mpkg.sh#L236

-

**Comment by erikng** [comment]
Merged as of https://github.com/munki/munki/commit/0de8f061a8d678b96fba8ef224aa66fd5df1179b
