### ISSUE TITLE
Munki launch daemons not installing 

### ISSUE THREAD

**Issue by Sinequanonh** [munki/munki#692]
Hi, I'm having trouble deploying a netinstall image which contains the latest munki tools package and this simple script:

```sh
#!/bin/bash

/usr/bin/defaults write "$3/Library/Preferences/ManagedInstalls.plist" SoftwareRepoURL -string "https://munki.company.org"
/usr/bin/defaults write "$3/Library/Preferences/ManagedInstalls.plist" AdditionalHttpHeaders '("Authorization: Basic XXXXXX")'
/usr/bin/defaults write "$3/Library/Preferences/ManagedInstalls.plist" ClientIdentifier -string "agent"
/usr/bin/defaults write "$3/Library/Preferences/ManagedInstalls.plist" InstallAppleSoftwareUpdates -bool true
/usr/bin/touch "$3/Users/Shared/.com.googlecode.munki.checkandinstallatstartup"
```
I've deployed this image several times, and for some reason sometimes the launch daemons and launch agents are not present on the client machine.
Any ideas?

**Comment by gregneagle** [comment]
It's not clear that this is related to any code issue with Munki -- you've introduced a lot of variables, since we don't know what's in your netinstall image. Consider asking for help on the munki-discuss mailing list. If an actual code issue is identified we can reopen this issue.
