### ISSUE TITLE
Product Keys on 10.12

### ISSUE THREAD

**Issue by digitalhealer** [munki/munki#694]
In order to find the product key for apple updates i usually run this command "softwareupdate -l -f /tmp/updatelist.plist".  On 10.12 it no longer works.  Does anyone have another way of getting the product keys on 10.12?

**Comment by gregneagle** [comment]
There are alternative methods listed here: https://github.com/munki/munki/wiki/Pkginfo-For-Apple-Software-Updates#identifying-updates

Look also here: https://github.com/hjuutilainen/sus-inspector

Please in the future use the munki-discuss list for general questions.
