### ISSUE TITLE
enhancements to repoclean

### ISSUE THREAD

**Issue by apettinen** [munki/munki#696]
I made a few enhancements to repoclean utility, see https://github.com/apettinen/munki/blob/master/code/client/repoclean

In a nutshell, the new features/enchancements are:
- converted from `optparse` to `argparse`
- option to exclude specific items
- delete items not in manifests, taking into account Apple Update Metadata (these are never deleted)
- do a dryrun, printing out what would be deleted (no printing to file yet)

Obviously this is a delicate matter as we are talking about a powerful tool. So far this is "works for me", therefore no pull request. However, I thought somebody might be interested and/or find these enhancements useful. I'm happy to work this further and correct any mistakes/stupidities I've made.

**Comment by gregneagle** [comment]
All the other Munki command line tools use optparse -- in addition, Munki still supports OS X 10.6, which comes with Python 2.6, which does not include argparse. So I would not at present accept a PR that converted repoclean to use argparse.

A dryrun option is nice, but since you are prompted before deleting now, what is gained?

Finally, if you do decide to create a PR, you need to sign a CLA: https://github.com/munki/munki/wiki/Contributing-to-Munki#contributor-license-agreement

**Comment by apettinen** [comment]
I understand the issue with optparse vs argparse - in fact, first I tried to comply with the 2.6 support. However, to best of my knowledge, optparse does not support `parser.add_argument('z', nargs='*')` style input. Therefore, to be able to specify multiple packages to be excluded I converted to argparse.

Obviously, this could be avoided by accepting a file (plist) which includes the excluded files.

I agree that the dryrun is a bit unnecessary, although you can now redirect the output to a file. This could also be an option to directly to write to file and print nothing to the command line?

I'll be happy to work on these features.

**Comment by fuzzylogiq** [comment]
`optparse` still allows the `action="append"` argument which appends to a list in the options dict if you specify it multiple times. e.g.:
```
from optparse import OptionParser

parser = OptionParser()
parser.add_option("-x", "--exclude", action="append",
                  help="exclude pkg (can be specified multiple times)",
                  metavar="PKG")

(options, args) = parser.parse_args()

print options
```

`repoclean -x pkg1.pkg -x pkg2.pkg` would output:

`{ 'exclude': [ 'pkg1.pkg', 'pkg2.pkg]' }`

**Comment by apettinen** [comment]
Thanks for the tip. I've converted to optparse, but there's another issue I have to figure out before commiting.

**Comment by gregneagle** [comment]
And now in the Munki3 branch, repoclean has changed rather dramatically...

**Comment by apettinen** [comment]
Yeah, I've been thinking whether there's any point of developing this further now that Munki3 is coming. I might as well contribute to that, if found necessary/beneficial.

**Comment by apettinen** [comment]
Heh, bumbed into this, and this is very old and outdated now on so many fronts, that I will close it. 😄
