### ISSUE TITLE
problems with checking subpackages during running managedsoftwareupdate

### ISSUE THREAD

**Issue by tm-dd** [munki/munki#697]
AT FIRST. I like Munki. It's the best deployment software which I ever used in the last 7 years as an system administrator of Apple Macs. I can using bash scripts to create and fill the munki software repository automaticly.

**Short Description of my current problem:**

I have an problem by deploying "GPG Suite 2017.1b2" (with https://gpgtools.org/) with Munki 2.8.2.2855.

The package has 13 subpackages, but two of then are created for different MacOS (X) versions. 
So only 12 of the 13 subpackages are allowed to install on the same system.

I defined the options with "installer_choices_xml" and the Munki installed the 12 packages correctly.
But on the next run of "managedsoftwareupdate" Munki means that all 13 packages must be installed and a loop of installations begins.

It looks like a mistake by checking of the packages on "managedsoftwareupdate".
This check should also analyse the "choices.xml" file.

**Long Description:**

* Software versions:
    
        sh-3.2$ sudo /usr/local/munki/managedsoftwareupdate --version
        2.8.2.2855
        sh-3.2$
        
        sh-3.2$ system_profiler -detailLevel mini | grep 'System Version'
              System Version: macOS 10.12.3 (16D32)
        sh-3.2$
    
        # But the problem exists on the older Mac OS X 10.11. (El Capitain) also.

* Manually installation - this packages will be needed:

    sh-3.2# pkgutil --pkgs | grep gpg
    sh-3.2#
    
    sh-3.2# installer -pkg /Volumes/GPG\ Suite/Install.pkg -target /
    installer: Package name is GPG Suite
    installer: Installing at base path /
    installer: The install was successful.
    sh-3.2#
    
    sh-3.2# pkgutil --pkgs | grep gpg
    org.gpgtools.checkprivatekey.pkg
    org.gpgtools.gpgkeychain.pkg
    org.gpgtools.gpgmail12.pkg
    org.gpgtools.gpgpreferences.pkg
    org.gpgtools.gpgservices.pkg
    org.gpgtools.key
    org.gpgtools.libmacgpg.xpc.pkg
    org.gpgtools.libmacgpgB.pkg
    org.gpgtools.macgpg2.pkg
    org.gpgtools.pinentry.pkg
    org.gpgtools.pkg.preinstall
    org.gpgtools.updater.pkg
    sh-3.2#
    
* Package analysis:

The subpackage "GPGMail_Core.pkg" is designed from OS X 10.9 to 10.11 and the sub package "GPGMail_12_Core.pkg" for macOS 10.12.

        sh-3.2$ installer -showChoicesXML -pkg /Volumes/GPG\ Suite/Install.pkg -target /
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <array>
                <dict>
                        <key>childItems</key>
                        <array>
                                ...
                                <dict>
                                        <key>childItems</key>
                                        <array/>
                                        <key>choiceDescription</key>
                                        <string>Installs to: /Library/Mail/Bundles
        Description: OpenPGP for Apple Mail.
        OS X: 10.9 – 10.11</string>
                                        <key>choiceIdentifier</key>
                                        <string>installer_choice_4</string>
                                        <key>choiceIsEnabled</key>
                                        <false/>
                                        <key>choiceIsSelected</key>
                                        <integer>0</integer>
                                        <key>choiceIsVisible</key>
                                        <false/>
                                        <key>choiceSizeInKilobytes</key>
                                        <integer>8090</integer>
                                        <key>choiceTitle</key>
                                        <string>GPGMail</string>
                                        <key>pathsOfActivePackagesInChoice</key>
                                        <array>
                                                <string>file://localhost/Volumes/GPG%20Suite/Install.pkg#GPGMail_Core.pkg</string>
                                        </array>
                                </dict>
                                <dict>
                                        <key>childItems</key>
                                        <array/>
                                        <key>choiceDescription</key>
                                        <string>Installs to: /Library/Mail/Bundles
        Description: OpenPGP for Apple Mail.
        macOS: 10.12</string>
                                        <key>choiceIdentifier</key>
                                        <string>installer_choice_5</string>
                                        <key>choiceIsEnabled</key>
                                        <true/>
                                        <key>choiceIsSelected</key>
                                        <integer>1</integer>
                                        <key>choiceIsVisible</key>
                                        <true/>
                                        <key>choiceSizeInKilobytes</key>
                                        <integer>10768</integer>
                                        <key>choiceTitle</key>
                                        <string>GPGMail</string>
                                        <key>pathsOfActivePackagesInChoice</key>
                                        <array>
                                                <string>file://localhost/Volumes/GPG%20Suite/Install.pkg#GPGMail_12_Core.pkg</string>
                                        </array>
                                </dict>
                                ...
                                <dict>
                                        <key>childItems</key>
                                        <array/>
                                        <key>choiceDescription</key>
                                        <string></string>
                                        <key>choiceIdentifier</key>
                                        <string>installer_choice_13</string>
                                        <key>choiceIsEnabled</key>
                                        <true/>
                                        <key>choiceIsSelected</key>
                                        <integer>1</integer>
                                        <key>choiceIsVisible</key>
                                        <false/>
                                        <key>choiceSizeInKilobytes</key>
                                        <integer>0</integer>
                                        <key>choiceTitle</key>
                                        <string>CheckPrivateKey</string>
                                        <key>pathsOfActivePackagesInChoice</key>
                                        <array>
                                                <string>file://localhost/Volumes/GPG%20Suite/Install.pkg#CheckPrivateKey.pkg</string>
                                        </array>
                                </dict>
                        </array>
                        <key>choiceIdentifier</key>
                        <string>__ROOT_CHOICE_IDENT_DISTRIBUTION_TITLE</string>
                        ...
                        <array/>
                </dict>
        </array>
        </plist>
        sh-3.2$

* Installation Loop:

After installing the GPG Suite, Munki check all 13 subpackages:

        sh-3.2$ sudo /usr/local/munki/managedsoftwareupdate -vvv
        Password:
        Managed Software Update Tool
        Copyright 2010-2016 The Munki Project
        https://github.com/munki/munki
        
        Starting...
        ...
            * Processing manifest item standard_10_12_pkgs_GPG_Suite for optional install
            Looking for detail for: standard_10_12_pkgs_GPG_Suite, version latest...
            Considering 1 items with name standard_10_12_pkgs_GPG_Suite from catalog standard_10_12_pkgs
            Considering item standard_10_12_pkgs_GPG_Suite, version 2 with minimum os version required 10.12
            Our OS version is 10.12.3
            Considering item standard_10_12_pkgs_GPG_Suite, version 2 with maximum os version supported 10.12.12
            Our OS version is 10.12.3
            Found standard_10_12_pkgs_GPG_Suite, version 2 in catalog standard_10_12_pkgs
            Looking for package org.gpgtools.checkprivatekey.pkg, version 1.1
            Looking for package org.gpgtools.gpgkeychain.pkg, version 1249b (cda0ef2)
            Looking for package org.gpgtools.gpgmail12.pkg, version 1192b (25351e4)
            Looking for package org.gpgtools.gpgmail.pkg, version 1169 (16bcb99)
                This package is not currently installed.
            Adding standard_10_12_pkgs_GPG_Suite to the optional install list
            ** Processing manifest standard_en_apps for optional_installs
        ...
            
            The following items will be installed or upgraded:
                + standard_10_12_pkgs_GPG_Suite-2
                    Tools to using GPG on Apple Mail (and other programs).
        
        Run managedsoftwareupdate --installonly to install the downloaded updates.
        Finishing...
            Getting info on currently installed applications...
        Done.
        sh-3.2$
        
So Munki is missing the sub package "org.gpgtools.gpgmail.pkg", which was designed for other OS X versions.

* Log file during the installation:

The option "installer_choice_4" will not be installed. Same like in the manually installation process.
    
        sh-3.2# ls -l /tmp/munki-*/; set -x; cat /tmp/munki-*/choices.xml; cat /tmp/munki-*/com.googlecode.munki.*.plist; cat /tmp/munki-*/com.googlecode.munki.*.stderr; cat /tmp/munki-*/com.googlecode.munki.*.stdout; set +x
        total 24
        -rw-r--r--  1 root  wheel  2729 Feb  3 10:03 choices.xml
        -rw-r--r--  1 root  wheel  2013 Feb  3 10:03 com.googlecode.munki.a6077e4f-e9ef-11e6-a4dd-10ddb1f390af.plist
        -rw-r--r--  1 root  wheel     0 Feb  3 10:03 com.googlecode.munki.a6077e4f-e9ef-11e6-a4dd-10ddb1f390af.stderr
        -rw-r--r--  1 root  wheel  1054 Feb  3 10:03 com.googlecode.munki.a6077e4f-e9ef-11e6-a4dd-10ddb1f390af.stdout
        + cat /tmp/munki-sBJ9RM/choices.xml
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <array>
                <dict>
                        <key>attributeSetting</key>
                        <integer>1</integer>
                        <key>choiceAttribute</key>
                        <string>selected</string>
                        <key>choiceIdentifier</key>
                        <string>installer_choice_1</string>
                </dict>
                <dict>
                        <key>attributeSetting</key>
                        <integer>1</integer>
                        <key>choiceAttribute</key>
                        <string>selected</string>
                        <key>choiceIdentifier</key>
                        <string>installer_choice_2</string>
                </dict>
                <dict>
                        <key>attributeSetting</key>
                        <integer>1</integer>
                        <key>choiceAttribute</key>
                        <string>selected</string>
                        <key>choiceIdentifier</key>
                        <string>installer_choice_3</string>
                </dict>
                <dict>
                        <key>attributeSetting</key>
                        <integer>0</integer>
                        <key>choiceAttribute</key>
                        <string>selected</string>
                        <key>choiceIdentifier</key>
                        <string>installer_choice_4</string>
                </dict>
                <dict>
                        <key>attributeSetting</key>
                        <integer>1</integer>
                        <key>choiceAttribute</key>
                        <string>selected</string>
                        <key>choiceIdentifier</key>
                        <string>installer_choice_5</string>
                </dict>
                <dict>
                        <key>attributeSetting</key>
                        <integer>1</integer>
                        <key>choiceAttribute</key>
                        <string>selected</string>
                        <key>choiceIdentifier</key>
                        <string>installer_choice_6</string>
                </dict>
                <dict>
                        <key>attributeSetting</key>
                        <integer>1</integer>
                        <key>choiceAttribute</key>
                        <string>selected</string>
                        <key>choiceIdentifier</key>
                        <string>installer_choice_7</string>
                </dict>
                <dict>
                        <key>attributeSetting</key>
                        <integer>1</integer>
                        <key>choiceAttribute</key>
                        <string>selected</string>
                        <key>choiceIdentifier</key>
                        <string>installer_choice_8</string>
                </dict>
                <dict>
                        <key>attributeSetting</key>
                        <integer>1</integer>
                        <key>choiceAttribute</key>
                        <string>selected</string>
                        <key>choiceIdentifier</key>
                        <string>installer_choice_9</string>
                </dict>
                <dict>
                        <key>attributeSetting</key>
                        <integer>1</integer>
                        <key>choiceAttribute</key>
                        <string>selected</string>
                        <key>choiceIdentifier</key>
                        <string>installer_choice_10</string>
                </dict>
                <dict>
                        <key>attributeSetting</key>
                        <integer>1</integer>
                        <key>choiceAttribute</key>
                        <string>selected</string>
                        <key>choiceIdentifier</key>
                        <string>installer_choice_11</string>
                </dict>
                <dict>
                        <key>attributeSetting</key>
                        <integer>1</integer>
                        <key>choiceAttribute</key>
                        <string>selected</string>
                        <key>choiceIdentifier</key>
                        <string>installer_choice_12</string>
                </dict>
                <dict>
                        <key>attributeSetting</key>
                        <integer>1</integer>
                        <key>choiceAttribute</key>
                        <string>selected</string>
                        <key>choiceIdentifier</key>
                        <string>installer_choice_13</string>
                </dict>
        </array>
        </plist>
        + cat /tmp/munki-sBJ9RM/com.googlecode.munki.a6077e4f-e9ef-11e6-a4dd-10ddb1f390af.plist
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
                <key>EnvironmentVariables</key>
                <dict>
                        <key>HOME</key>
                        <string>/var/root</string>
                        <key>LC_CTYPE</key>
                        <string>UTF-8</string>
                        <key>LOGNAME</key>
                        <string>root</string>
                        <key>MAIL</key>
                        <string>/var/mail/root</string>
                        <key>MUNKI_VERBOSITY_LEVEL</key>
                        <string>1</string>
                        <key>PATH</key>
                        <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki</string>
                        <key>SHELL</key>
                        <string>/bin/sh</string>
                        <key>SSH_AUTH_SOCK</key>
                        <string>/private/tmp/com.apple.launchd.ixF04YTAfK/Listeners</string>
                        <key>SUDO_COMMAND</key>
                        <string>/usr/local/munki/managedsoftwareupdate --installonly</string>
                        <key>SUDO_GID</key>
                        <string>20</string>
                        <key>SUDO_UID</key>
                        <string>501</string>
                        <key>SUDO_USER</key>
                        <string>admin</string>
                        <key>TERM</key>
                        <string>xterm-256color</string>
                        <key>USER</key>
                        <string>root</string>
                        <key>USERNAME</key>
                        <string>root</string>
                        <key>VERSIONER_PYTHON_PREFER_32_BIT</key>
                        <string>no</string>
                        <key>VERSIONER_PYTHON_VERSION</key>
                        <string>2.7</string>
                        <key>__CF_USER_TEXT_ENCODING</key>
                        <string>0x0:0:0</string>
                </dict>
                <key>Label</key>
                <string>com.googlecode.munki.a6077e4f-e9ef-11e6-a4dd-10ddb1f390af</string>
                <key>ProgramArguments</key>
                <array>
                        <string>/usr/sbin/installer</string>
                        <string>-verboseR</string>
                        <string>-pkg</string>
                        <string>/Library/Managed Installs/Cache/GPG_Suite-2017.1_beta2__2.pkg</string>
                        <string>-target</string>
                        <string>/</string>
                        <string>-applyChoiceChangesXML</string>
                        <string>/tmp/munki-sBJ9RM/choices.xml</string>
                </array>
                <key>StandardErrorPath</key>
                <string>/tmp/munki-sBJ9RM/com.googlecode.munki.a6077e4f-e9ef-11e6-a4dd-10ddb1f390af.stderr</string>
                <key>StandardOutPath</key>
                <string>/tmp/munki-sBJ9RM/com.googlecode.munki.a6077e4f-e9ef-11e6-a4dd-10ddb1f390af.stdout</string>
        </dict>
        </plist>
        + cat /tmp/munki-sBJ9RM/com.googlecode.munki.a6077e4f-e9ef-11e6-a4dd-10ddb1f390af.stderr
        + cat /tmp/munki-sBJ9RM/com.googlecode.munki.a6077e4f-e9ef-11e6-a4dd-10ddb1f390af.stdout
        installer: Package name is GPG Suite
        installer: choices changes file '/tmp/munki-sBJ9RM/choices.xml' applied
        installer: Upgrading at base path /
        installer:PHASE:Preparing for installation…
        installer:PHASE:Preparing the disk…
        installer:PHASE:Preparing GPG Suite…
        installer:PHASE:Waiting for other installations to complete…
        installer:PHASE:Configuring the installation…
        installer:STATUS:
        installer:%8.786930
        installer:PHASE:Writing files…
        installer:%10.924142
        installer:PHASE:Writing files…
        installer:%66.528024
        installer:PHASE:Running package scripts…
        installer:%67.596463
        installer:PHASE:Running package scripts…
        installer:%68.665178
        installer:PHASE:Running package scripts…
        installer:%95.676485
        installer:PHASE:Cleaning up…
        installer:PHASE:Validating packages…
        installer:%97.750000
        installer:STATUS:Running installer actions…
        installer:STATUS:
        installer:PHASE:Finishing the Installation…
        installer:STATUS:
        installer:%100.000000
        installer:PHASE:The software was successfully installed.
        installer: The upgrade was successful.
        + set +x
        sh-3.2#
        
        sh-3.2# pkgutil --pkgs | grep gpg
        org.gpgtools.checkprivatekey.pkg
        org.gpgtools.gpgkeychain.pkg
        org.gpgtools.gpgmail12.pkg
        org.gpgtools.gpgpreferences.pkg
        org.gpgtools.gpgservices.pkg
        org.gpgtools.key
        org.gpgtools.libmacgpg.xpc.pkg
        org.gpgtools.libmacgpgB.pkg
        org.gpgtools.macgpg2.pkg
        org.gpgtools.pinentry.pkg
        org.gpgtools.pkg.preinstall
        org.gpgtools.updater.pkg
        sh-3.2#

Best regards and MANY MANY thanks to all developer of the Munki projekt,

Thomas

**Comment by vmiller** [comment]
Hi Thomas,  questions like this regarding how to deploy specific packages would be better directed to the [munki-discuss](https://groups.google.com/forum/#!forum/munki-discuss) Google group.  You will get more eyes on your question there.

**Comment by tm-dd** [comment]
OK, I will also write the post on the munki-discuss Google group, but it look like an software problem. So, I have noted this here.
Thanks, however, for the answer and the link. This group was new for me.

**Comment by gregneagle** [comment]
May I also point you to:

https://github.com/munki/munki#get-help
https://github.com/munki/munki/wiki/FAQ#q-munki-successfully-installed-some-software-but-now-each-time-munki-runs-it-wants-to-install-the-software-again-why-is-this
https://github.com/munki/munki/wiki/How-Munki-Decides-What-Needs-To-Be-Installed
and https://github.com/munki/munki/wiki/Troubleshooting, which lists the munki-discuss group as a troubleshooting resource.

Since you've asked your question on munki-discuss now, and gotten at least one useful/accurate response, I'm going to close this issue here.
