### ISSUE TITLE
GUI Application not working but Terminal Application is working

### ISSUE THREAD

**Issue by Robin38219733** [munki/munki#704]
Hello,
The GUI Application "Managed Software Update" say it can't connect to my Server but when i open a terminal an type "managedsoftwareupdate" it works.
I have also installed Munki Report.
I can also see the Files when i navigate to http://serverip/munki_repo
Can anyone help me?

**Comment by bochoven** [comment]
Please ask questions in the newsgroups for munki or munkireport. Github issues are for bugs or enhancement requests.

**Comment by gregneagle** [comment]
https://github.com/munki/munki#get-help

https://github.com/munki/munki/wiki/Troubleshooting

http://groups.google.com/group/munki-discuss
