### ISSUE TITLE
How to best calculate installed_size of Adobe CCP packages 

### ISSUE THREAD

**Issue by timsutton** [munki/munki#705]
I did a [quick pass](https://github.com/timsutton/munki/commit/7d57c383139a2e0afd873b72854fcd8d4af001f3) at tallying up the sizes of the HD payloads as a means to calculate `installed_size` for Adobe CCP packages, which currently aren't being calculated. I figured its calculation would add 1-2% more in accounting for the language packages or regional default content, most of which aren't installed.

But then @foigus did some tests by attempting an install on a system with a very low amount of free space, and looked at the reported values calculated by Adobe's installers, i.e.:

`02/12/17 17:28:32:880 | [FATAL] |  | HDSetup | HDPIM | ApplicationManager |  | HDPIM | 34479 | Total size required for installation is '3918635328' bytes, but only '353124352' bytes are available on the installation directory`

..and compiled this spreadsheet, which shows my tallying of HD package payloads as being quite off the mark, in both directions depending on the app:

<img width="737" alt="screen shot 2017-02-13 at 12 23 56 am" src="https://cloud.githubusercontent.com/assets/119358/23185126/44a0aed6-f850-11e6-8315-42179897d52f.png">

Column B is what Adobe's installer reports as minimum required space (and ostensibly what would make sense to have in an `installed_size`) and column C is what the updated `adobeinfo.py` code would calculate.

I can't make sense of much of this - it's also not clear to me what of this is also taking into effect the CC installer libraries which are sort of part of the installation. In @foigus's case he had those libraries already on the system.

I'm finding that if I simply take my compressed DMG size containing the CCP package and multiply it by around ~2.2x, I get pretty close to Adobe's value (with Illustrator being an odd exception, where it's actually _less_ than the compressed DMG).

My instinct is to simply take `installer_item_size` and multiply it by some best guess like the above to arrive at `installed_size` and call it a day, unless someone's willing to spend (possibly a lot of) time to figure out why the numbers are so off when just summing package payloads, and if I haven't missed something easy in my calculating of the `ExtractSize` values.

I see that normally when Munki attempts a download, it will [fall back](https://github.com/munki/munki/blob/4053a0dbe77d900308260ba8a39ca1df4814d33c/code/client/munkilib/updatecheck/download.py#L49) to `installer_item_size` if `installed_size` isn't set. Since these installers are so large, though, and we often have a case where we want to add a bunch at once, the 10-15GB of difference can be significant for those who are running very low on free space.

**Comment by erikng** [comment]
As I was reading this my first thought was "multiply it". I don't think it's worth the effort because who knows when Adobe will make another change.
________________________________

**Comment by gregneagle** [comment]
@timsutton Close this?

**Comment by timsutton** [comment]
Thanks!
