### ISSUE TITLE
Enhancement: Allow user to install selected updates by force (munki_do.py in MSC.app GUI)

### ISSUE THREAD

**Issue by MiqViq** [munki/munki#708]
It would be easier for user if user can install only selected updates by force.
This could also bypass logout or restart requirements of a certain update.
The functionality of "munki_do.py" but with better impelementation, now it seems that "munki_do.py" temporarily messes up some file permissions in munki client.

**Comment by gregneagle** [comment]
It's not completely clear what you are proposing -- but I have no interest/intention of changing Managed Software Center to allow for picking individual updates to install.

**Comment by gregneagle** [comment]
No plans to implement this at this time.
