### ISSUE TITLE
munkiimport issue with --uninstallpkg switch and trailing slashes

### ISSUE THREAD

**Issue by kevinmcox** [munki/munki#710]
It looks like I've stumbled across an issue with including uninstaller packages when a trailing slash is left behind the package name. I got the slashes by using tab to autocomplete the filename in Terminal. I've tested it against multiple packages, but all Adobe CCP ones in this case.

This command works just fine:

`munkiimport Illustrator\ CC\ 2017_Install.pkg --uninstallpkg Illustrator\ CC\ 2017_Uninstall.pkg`

However this one (notice the two trailing slashes behind .pkg) doesn't:

`munkiimport Illustrator\ CC\ 2017_Install.pkg/ --uninstallpkg Illustrator\ CC\ 2017_Uninstall.pkg/`

The installer shows up as expected, but it creates the uninstaller as a hidden file with the name:
**.dmg-21.0.2.242**

Terminal output:

```
Copying Illustrator CC 2017_Install.dmg to /path/to/repo/pkgs/adobe/Illustrator CC 2017_Install-21.0.2.242.dmg...
Copying .dmg to /path/to/repo/pkgs/adobe/.dmg-21.0.2.242...
Saving pkginfo to /path/to/repo/pkgsinfo/adobe/Adobe Illustrator CC (2017)-21.0.2.242...
```

The uninstaller item location key does point to the hidden file, so the uninstall does work properly.

```
<key>uninstaller_item_location</key>
<string>adobe/.dmg-21.0.2.242</string>
```

But it could definitely cause problems for someone trying to clean up old packages in their repo.

Apologies if this is already a known issue, I didn't find it in a search.

**Comment by nathanperkins** [comment]
I've also run into this. When using tab autocomplete, the Terminal adds a slash for .pkgs, so it happens every time I go back to package new Adobe products after a few months :)

I assumed the file was just not being created. Good to know that it's just hidden but still works.

**Comment by gregneagle** [comment]
> On Mar 7, 2017, at 8:42 AM, Nathan Perkins <notifications@github.com> wrote:
> 
> I've also run into this. When using tab autocomplete, the Terminal adds a slash for .pkgs,
> 
Only for bundle-style packages, which are actually directories. (and all AAMEE/CCP packages are bundle-style packages, even in 2017)

> so it happens every time I go back to package new Adobe products after a few months :)
> 
> I assumed the file was just not being created. Good to know that it's just hidden but still works.
>

**Comment by rmanly** [comment]
should I create a pull request for the Munki3 branch as well?
