### ISSUE TITLE
Invalid values for RestartAction result in blank Updates window in MSC

### ISSUE THREAD

**Issue by poundbangbash** [munki/munki#713]
If a pkginfo file has a value for `RestartAction` that doesn't match one of the supported values for that key, the Updates window in Managed Software Center.app (MSC) displays a blank window.

Steps to reproduce:

1. Edit a pkginfo to include an invalid value for RestartAction (e.g. `asdf`)
2. Add the pkg to a manifest
3. On the client machine, manually run managedsoftwareupdate.
4. When complete, launch MSC.

Alternately, if MSC is running while munki is running its check for installs, upon managedsoftwareupdate finishing, MSC's Updates window gets stuck showing "Update in progress." and an infinite scrolling progress bar even though the process has ended according to /Library/Managed Installs/Logs/MangedSoftwareUpdate.log

-Eric

**Comment by gregneagle** [comment]
I would imagine this bug has been present in MSC.app for a long time!
