### ISSUE TITLE
[v3] Please add some documentation/examples on the wiki for implementing Repo

### ISSUE THREAD

**Issue by groob** [munki/munki#714]
I'm trying to write my own `Repo` Plugin based on the FileRepo. 

I replaced the `put` method with my own binary here
```
    def put(self, src, dest):
        '''Copies a local file to the repo.'''
        cmd = ['/usr/local/bin/munkiapiimport', src, os.path.join(self.path, dest)]
        return subprocess.call(cmd)
```
which right now is just a binary that exits `0` 

Running munkiimport with my plugin, I noticed that the `put` is invoked when the `pkg` is copied, but not the `pkginfo`.

@gregneagle was able to show me how to add a `__del__` method, but it's not something I would've been able to implement on my own. 

@ryanyu91 since you're the author behind the FileRepo plugin, would you mind adding additional documentation for writing a complete Repo implementation?

**Comment by ryanyu91** [comment]
Hi @groob @gregneagle ,
Yes, I can add some documentation. The idea is if you want a new plugin, you can inherit from FileRepo and override any methods thats different.

**Comment by ryanyu91** [comment]
Forgot to add __init__ to plugins directory so users can import FileRepo if they wish, created another pull request for Munki3:
https://github.com/munki/munki/pull/721

**Comment by gregneagle** [comment]
@ryanyu91 : I'm in the middle of a major refactor/rethink of the repo plugins; give me a few days and then I'll want you to take a look to see if you can make your things work within the refactor.

I found many potential issues with the current code and decided it needed a refactor/rethink. I'm doing it in a separate branch for now, which I have not yet published. It's pretty extensive, though, so it may take me a few more days to get it to a state where people can try it and give feedback. I think it will greatly simplify the creation and use of plugins when complete, however.

**Comment by gregneagle** [comment]
@groob ^^

**Comment by gregneagle** [comment]
@groob, @ryanyu91 : https://github.com/munki/munki/blob/new_repo_abstraction/notes_about_this_branch.md

Ryan: please take a look and see if Centrify can work with this style of repo plugin. We can add features if there are things missing,  but it seems a more flexible starting point.

**Comment by ryanyu91** [comment]
Hi @gregneagle @groob 
Sorry for the delay, had to rework some things in Centrify's Repo, but it works with the new munki now. Thanks. 
I agree its a much more flexible starting point.

**Comment by gregneagle** [comment]
This is really good news. I'm going to merge the new_repo_abstraction branch into the Munki3 branch and document this as the format for repo plugins.

**Comment by gregneagle** [comment]
I'm closing this issue since there are now three example Repo plugins and a wiki page, complete with developer notes.
