### ISSUE TITLE
error on importing to remote file share url

### ISSUE THREAD

**Issue by circleplus** [munki/munki#716]
```
munkiimport -v --repo_url=ftp://myuser@192.168.0.110 --repo_path=munki someapp.dmg
````

this would fail all the time, even though the remote file system was mounted successfully. I think there's a bug inside munkiimport (for both master and latest release). See below code pieces from master version:

```python
    if not os.path.exists(REPO_PATH) and REPO_URL:
        mount_repo_cli()
    if not os.path.exists(REPO_PATH):
        return False
````
it would return False irrespective of the result of "mount_repo_cli".  returning "True"/"False" based on "WE_MOUNTED_THE_REPO" global variable might be an approach.

**Comment by gregneagle** [comment]
1) There's no official support for mounting FTP shares
2) repo_path is always tested as an absolute path where the share gets mounted.
3) You haven't really described the failure! What exactly fails?

**Comment by circleplus** [comment]
Okay!  I think I've figured out --repo_path has to be /Volumes/<mount point>.  It might be good to document a little bit on how to specific repo_url together with repo_path ... My original understanding is repo_url is the server url without path components, and repo_path is the path components..

**Comment by circleplus** [comment]
Sorry, I've just started to play with munki today, and hasn't figured out how to specify those two parameters properly ... the error I saw was "Could not connect to munki repo. Check the configuration and try again." after mounting ftp successfully.

**Comment by gregneagle** [comment]
https://github.com/munki/munki/wiki/munkiimport#details

If you have ideas on how to better word this stuff here:

```
Path to munki repo (example: /Volumes/repo): 
Repo URL (example: afp://munki.pretendco.com/repo):
```

Feel free to suggest improved wording. Perhaps:

```
Local filesystem path to munki repo (example: /Volumes/repo): 
Repo file share URL (example: afp://munki.pretendco.com/repo):
```

**Comment by circleplus** [comment]
how do you think of removing the necessity of --repo_path when trying to use "--repo_url" to mount the repo directly. So any naming issues/conflicts would be resolved internally.  For example, I was just running into issue that "/Volume/munki" folder was persisted and not removed upon manual unmount, thus "--repo_url" wouldn't mount the remote unless I've removed manually that folder. 

so to mount a remote repo, command like below would simple enough to be understood as well as documented easily:
```
 munkiimport --repo_url=ftp://myuser@192.168.0.100/munki someapp.dmg
```

then munkiimport implementation would handle all mounting/transferring/unmounting steps.  Or even simpler, to support both local and remote within one parameter and add option to list supported transfer protocol.

this is just some thought.  I'll see what I can help contribute to get  this great project better!

thanks for your very quick response!

**Comment by gregneagle** [comment]
It's a very common workflow to mount the repo and leave it mounted.

So a later run of munkiimport, we can just check to see if the Munki repo is available at the repo_path. If it is, we skip the mounting.

Most people using `munkiimport` configure it once using `--configure`. Then after that it's just:

`munkiimport /path/to/foo.dmg`
`munkiimport /path/to/bar.pkg`

**Comment by gregneagle** [comment]
Also, please consider joining the munki-discuss and/or munki-dev Google Groups, as GitHub issues are not a great place for general discussion. If you want to discuss code changes further, munki-dev is the right place.

https://groups.google.com/group/munki-discuss
https://groups.google.com/group/munki-dev

**Comment by circleplus** [comment]
Sure! Thanks for pointing out!
