### ISSUE TITLE
[v3] crash on installinfo.save_pending_update_times()

### ISSUE THREAD

**Issue by timsutton** [munki/munki#720]
I'm seeing this towards the end of a `managedsoftwareupdate` run, using the current-as-of-today `3.0.0.3086` version build of `Munki3`:

```
Traceback (most recent call last):
  File "./managedsoftwareupdate", line 1039, in <module>
    main()
  File "./managedsoftwareupdate", line 961, in main
    installinfo.save_pending_update_times()
  File "/Users/test/munki/code/client/munkilib/installinfo.py", line 155, in save_pending_update_times
    for name in pending_updates[category]:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_convenience.py", line 589, in enumeratorGenerator
    yield container_unwrap(anEnumerator.nextObject(), StopIteration)
objc.error: NSGenericException - *** Collection <__NSCFDictionary: 0x7f840475fb70> was mutated while being enumerated.
```

..which seems to be due to the deletion happening during the nested iteration [here](https://github.com/munki/munki/blob/90d457b082a77048dd540a9f8b55c0b9e3e19f24/code/client/munkilib/installinfo.py#L157).

I briefly tested doing what AutoPkg did, which was to switch `FoundationPlist` to use `NSPropertyListMutableContainersAndLeaves` instead of `NSPropertyListMutableContainers` and to first call `mutableCopy()` on the NSDict, but I still get the error. Unless I did something wrong, and might be showing my lack of experience with Objective-C here, but I would guess that the obj-c runtime simply doesn't allow mutation in this enumeration construct, or at least in the way PyObjC provides it.

I don't have a quick answer to solve this, wanted to at least raise the issue. I'd think maybe doing a list comprehension and copying all the values we want to _keep_ into a temporary copy and then writing that back out could be a safer way to do this.

In terms of how I raised the error, I'd only just put the 3.0.0.x code on this test VM for the first time today, and changed the client manifest to one which had a series of `managed_installs`, all of which I applied successfully. My guess is that since they all installed successfully and are no longer pending, Munki was determining that it was safe to remove these items from `UpdateNotificationTracking.plist` and that's where this code block was hit.

**Comment by gregneagle** [comment]
How does this look?
```python
    try:
        prior_pending_updates = FoundationPlist.readPlist(pendingupdatespath)
    except FoundationPlist.NSPropertyListSerializationException:
        prior_pending_updates = {}
    current_pending_updates = {}

    for category in update_names:
        if category not in current_pending_updates:
            current_pending_updates[category] = {}
        for name in update_names[category]:
            if (category in prior_pending_updates and
                    name in prior_pending_updates[category]):
                # copy the prior datetime from matching item
                current_pending_updates[category][name] = prior_pending_updates[
                    category][name]
            else:
                # record new item with current datetime
                current_pending_updates[category][name] = now

    FoundationPlist.writePlist(current_pending_updates, pendingupdatespath)
```

This entirely avoids trying to modify the NSDictionary in-place.

**Comment by timsutton** [comment]
Just tested my same reproducible failure and then changed to use your code above, and it works as expected. Thanks, ship it!
