### ISSUE TITLE
installing a certain app using Munki

### ISSUE THREAD

**Issue by araan** [munki/munki#726]
Hello, i'm new here.
First of all i'm sorry for my bad english and for this stupid question but i cannot find a solution on my own...

i need to use munki in order to install a .dmg on several imac
i've already made this a lot of times with both .dmg / .pkg and .app without any issue.

Today i need to import a new .dmg , but when i try to import and install it using munki, the app does not work.
the app appears in the "Application folder" with an incorrect icon, and when i try to open it, the app quits automatically.

The .Dmg is not damaged, since i've tried to install it without using munki, and it worked fine.

i've tried to : 
- import the .app instead of the .dmg file (same issue)
- create an installer .pkg (same issue)

Do you have any idea on how to solve this issue ?

Thank you 
Daniele

**Comment by gregneagle** [comment]
Hi!

The code issues section is not a general help forum.

https://github.com/munki/munki/wiki#where-to-go-for-more-info-and-help
https://github.com/munki/munki/wiki/Troubleshooting#still-stuck

You should post your problem on the munki-discuss list: http://groups.google.com/group/munki-discuss
...where many experienced Munki admins will read your question and offer advice.
