### ISSUE TITLE
Munki error with Acrobat XI Pro pkg removal

### ISSUE THREAD

**Issue by MiqViq** [munki/munki#732]
managedsoftwareupdate --version
2.8.3.3016

managedsoftwareupdate --installonly:

Removing Adobe Acrobat XI Pro (latest) (3 of 5)...
    Gathering information on installed packages...
	0ERROR: Unexpected error in munkilib.installer:
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 1033, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 837, in main
    mustrestart = doInstallTasks(appleupdatesavailable)
  File "/usr/local/munki/managedsoftwareupdate", line 234, in doInstallTasks
    only_unattended=only_unattended)
  File "/usr/local/munki/munkilib/installer/core.py", line 723, in run
    removallist, only_unattended=only_unattended)
  File "/usr/local/munki/munkilib/installer/core.py", line 526, in process_removals
    forcedeletebundles=True)
  File "/usr/local/munki/munkilib/installer/rmpkgs.py", line 802, in removepackages
    if not init_database(forcerebuild=rebuildpkgdb):
  File "/usr/local/munki/munkilib/installer/rmpkgs.py", line 437, in init_database
    import_package(receiptpath, curs)
  File "/usr/local/munki/munkilib/installer/rmpkgs.py", line 242, in import_package
    plist.get('Bundle versions string, short'), '1.0')
TypeError: get_objectForKey_() takes at most 3 arguments (4 given)

Pkginfo for Adobe Acrobat XI Pro:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>autoremove</key>
	<false/>
	<key>catalogs</key>
	<array>
		<string>testing</string>
	</array>
	<key>description</key>
	<string>Adobe Acrobat XI Pro (11.0.0)</string>
	<key>developer</key>
	<string>Adobe</string>
	<key>display_name</key>
	<string>Adobe Acrobat XI Pro</string>
	<key>installed_size</key>
	<integer>1483468</integer>
	<key>installer_choices_xml</key>
	<array>
		<dict>
			<key>attributeSetting</key>
			<integer>1</integer>
			<key>choiceAttribute</key>
			<string>selected</string>
			<key>choiceIdentifier</key>
			<string>browserplugin</string>
		</dict>
	</array>
	<key>installer_item_hash</key>
	<string>34b195e37468f58b8fc49fb274078294fe15d03c772401438eb98649d3f1cb5d</string>
	<key>installer_item_location</key>
	<string>PRIVATE/Adobe/AdobeAcrobatPro_XI/AdobeAcrobatPro_XI-11.0.0.pkg</string>
	<key>installer_item_size</key>
	<integer>596880</integer>
	<key>installs</key>
	<array>
		<dict>
			<key>CFBundleIdentifier</key>
			<string>com.adobe.Acrobat.Pro</string>
			<key>CFBundleName</key>
			<string>Acrobat</string>
			<key>CFBundleShortVersionString</key>
			<string>11.0.0</string>
			<key>path</key>
			<string>/Applications/Adobe Acrobat XI Pro/Adobe Acrobat Pro.app</string>
			<key>type</key>
			<string>bundle</string>
			<key>version_comparison_key</key>
			<string>CFBundleShortVersionString</string>
		</dict>
		<dict>
			<key>CFBundleIdentifier</key>
			<string>com.adobe.distiller</string>
			<key>CFBundleName</key>
			<string>Distiller</string>
			<key>CFBundleShortVersionString</key>
			<string>11.0.0</string>
			<key>path</key>
			<string>/Applications/Adobe Acrobat XI Pro/Acrobat Distiller.app</string>
			<key>type</key>
			<string>bundle</string>
			<key>version_comparison_key</key>
			<string>CFBundleShortVersionString</string>
		</dict>
	</array>
	<key>minimum_os_version</key>
	<string>10.6.8</string>
	<key>name</key>
	<string>AdobeAcrobatPro_XI</string>
	<key>postuninstall_script</key>
	<string>#!/bin/bash
rm -rf "/Applications/Adobe Acrobat XI Pro" 2&gt;/dev/null
exit 0</string>
	<key>receipts</key>
	<array>
		<dict>
			<key>optional</key>
			<true/>
			<key>installed_size</key>
			<integer>1072</integer>
			<key>packageid</key>
			<string>com.adobe.acrobat.11.viewer.browser.pkg.MUI</string>
			<key>version</key>
			<string>11.0.0</string>
		</dict>
		<dict>
			<key>optional</key>
			<true/>
			<key>installed_size</key>
			<integer>416</integer>
			<key>packageid</key>
			<string>com.adobe.acrobat.11.viewer.print_pdf_services.pkg.MUI</string>
			<key>version</key>
			<string>11.0.0</string>
		</dict>
		<dict>
			<key>optional</key>
			<true/>
			<key>installed_size</key>
			<integer>1083792</integer>
			<key>packageid</key>
			<string>com.adobe.acrobat.11.viewer.app.pkg.MUI</string>
			<key>version</key>
			<string>11.0.0</string>
		</dict>
		<dict>
			<key>optional</key>
			<true/>
			<key>installed_size</key>
			<integer>1216</integer>
			<key>packageid</key>
			<string>com.adobe.acrobat.11.viewer.print_automator.pkg.MUI</string>
			<key>version</key>
			<string>11.0.0</string>
		</dict>
		<dict>
			<key>optional</key>
			<true/>
			<key>installed_size</key>
			<integer>251000</integer>
			<key>packageid</key>
			<string>com.adobe.PDApp.AdobeApplicationManager.installer.pkg</string>
			<key>version</key>
			<string>1</string>
		</dict>
		<dict>
			<key>optional</key>
			<true/>
			<key>installed_size</key>
			<integer>0</integer>
			<key>packageid</key>
			<string>com.adobe.acrobat.11.viewer.preinstall.pkg.MUI</string>
			<key>version</key>
			<string>11.0.0</string>
		</dict>
		<dict>
			<key>installed_size</key>
			<integer>145972</integer>
			<key>packageid</key>
			<string>com.adobe.acrobat.11.viewer.appsupport.pkg.MUI</string>
			<key>version</key>
			<string>11.0.0</string>
		</dict>
	</array>
	<key>uninstall_method</key>
	<string>removepackages</string>
	<key>uninstallable</key>
	<true/>
	<key>version</key>
	<string>11.0.0</string>
</dict>
</plist>

**Comment by MiqViq** [comment]
Hmmm.

On another Mac the pkg removal was successful.
Seems like the issue is not in Munki but with the problematic client.

**Comment by gregneagle** [comment]
That looks the same as this issue: https://github.com/munki/munki/issues/706, which was resolved with a later commit.

The version you are running is a (older) build of non-released work-in-progress software. It's fine (and appreciated) to test and file issues on development code -- but if you find an issue, try to test and replicate it with the _latest_ development code. It's time-consuming to have to look at old code and see if the issue might still be present in the current code.

**Comment by MiqViq** [comment]
Sorry about jumping to a conclusion too hastily.

Will do update my clients.

br,

MiqViq

**Comment by gregneagle** [comment]
I hope you aren't pushing the development code to all your managed clients. 2.8.2 is the current supported release: https://github.com/munki/munki/releases/tag/v2.8.2

**Comment by MiqViq** [comment]
Not yet, waiting for a more robust release with v3.
