### ISSUE TITLE
Printer not adding to system pref>Printers

### ISSUE THREAD

**Issue by Daleee** [munki/munki#737]
I currently use the CSV import method for printers into my munki repo.

I've managed to get the new printer into the managed software centre repo but when i install it, it doesn't come through the system prefs/printers.

Any idea why this might be?

The code issues section is not a general help and troubleshooting forum.

https://github.com/munki/munki#get-help  
https://github.com/munki/munki/wiki#where-to-go-for-more-info-and-help  
https://github.com/munki/munki/wiki/Troubleshooting#still-stuck  

Please use the code issues section for reporting reproducable issues with the code or to propose/request new features.
But before you do, consider bringing up the topic for discussion on the munki-dev list: http://groups.google.com/group/munki-dev

**Comment by rickheil** [comment]
This is almost certainly not a code issue with munki - there is no "csv import method" built directly in, but you may be using one of the myriad of tools. So this isn't the best place to get help. 

I would suggest you post your question to the munki-discuss list - https://groups.google.com/forum/#!forum/munki-discuss as that is where you can post the output of something like managedsoftwareupdate -vvvv and managedsoftwareupdate --installonly -vvvv and get expert help!

**Comment by gregneagle** [comment]
The code issues section is not a general help and troubleshooting forum.

https://github.com/munki/munki#get-help
https://github.com/munki/munki/wiki#where-to-go-for-more-info-and-help
https://github.com/munki/munki/wiki/Troubleshooting#still-stuck

Please use the code issues section for reporting reproducable issues with the code or to propose/request new features.
