### ISSUE TITLE
[v3] Managed Software Center incorrectly displays "Additional Pending Updates" dialog

### ISSUE THREAD

**Issue by vmiller** [munki/munki#738]
I have been seeing the "Additional Pending Updates" dialog even when there is no additional updates.  

I did some testing, and can reproduce this consistently.  With an install that is not unattended and with no other updates pending, this behavior happens consistently with an auto check.  It does not happen with a manualcheck.

**Comment by gregneagle** [comment]
Can you provide steps to reproduce this?

**Comment by vmiller** [comment]
Machine running build 3197, with DaysBetweenNotifications set to 0.

- Add a test package that has unattended_install set to False to its managed_installs
- run sudo managedsoftwareupdate --auto
- when notified click the notification to bring up managed software center
- Click UPDATE
- "Additional Pending Updates" message is presented (even though no other updates are listed).
- Click OK and then click UPDATE again and the installation runs

I can delete the package receipt and repeat the above.  My statement about auto vs manualcheck is not entirely correct, rather the difference seems to be if MSC is open with the run is done.  Repeating the above steps with MSC left open results in no "Additional Pending Updates" message.

**Comment by gregneagle** [comment]
See if the code as of this commit: https://github.com/munki/munki/commit/de288f6460becd1435ae39c70212bff9d24745ea

Behaves more like you'd expect.

**Comment by vmiller** [comment]
I'll confirm when I get a chance, might not be till the morning.

**Comment by vmiller** [comment]
Confirmed that this issue is fixed.
