### ISSUE TITLE
FR: url key for pkginfo 

### ISSUE THREAD

**Issue by nathanperkins** [munki/munki#740]
Any interest in adding a `url` key to the pkginfo that could be used in the Managed Software Center in the information side bar?

Feel free to pick a different name if `url` doesn't feel right.

Example for Adobe Muse:
`<key>url</key>`
`<string>https://www.adobe.com/products/muse.html</string>`

![screen shot 2017-04-04 at 9 33 53 am](https://cloud.githubusercontent.com/assets/10337495/24668095/81815626-191a-11e7-84d0-2ab5286b7743.png)

**Comment by gregneagle** [comment]
Not enough interest to _implement_ it! If someone else wants to...

I'd suggest "vendor_info_url" or "item_info_url" or "developer_url" --something less generic than "url".

**Comment by gregneagle** [comment]
(You can already add such links to item _descriptions_...)

**Comment by nathanperkins** [comment]
I'll take a look at implementing.

What about adding both `developer_info_url` and `item_info_url`? Then, I could link the developer name if present.

**Comment by gregneagle** [comment]
Experiment!

**Comment by gmarnin** [comment]
Adding a link to the release notes as part of the description is what I do. 1Password for example:

`For more information about this update visit the &lt;a href="https://app-updates.agilebits.com/product_history/OPM4" target="_blank"&gt;Release Notes`

**Comment by gregneagle** [comment]
Closing since I have no desire to work on this myself. I'll happily review a PR that adds this functionality.
