### ISSUE TITLE
Missing de localizations

### ISSUE THREAD

**Issue by gregneagle** [munki/munki#741]
@fridomac @mschwieger 
While preparing for an eventual Munki 3 release, I'm going through the localizations. I noticed two strings that must have been added to Managed Software Center at some point since the last localization pass that were never localized into most of the supported languages, including German:

/* System configuration problem alert title */
"System configuration problem" = "System configuration problem";

/* System configuration problem alert detail */
"A systems configuration issue is preventing Managed Software Center from operating correctly. The reported issue is: " = "A systems configuration issue is preventing Managed Software Center from operating correctly. The reported issue is: ";

If you could help me out with German translations here, it would be appreciated.

**Comment by fridomac** [comment]
Hello Greg,

Happy to help!
I´m currently not on a machine with a correct git install, so I can only send you the translations via eMail. If you need a pull request, I can do that tomorrow.

> /* System configuration problem alert title */
> "System configuration problem" = "System configuration problem";
> 
Translation: „Problem mit der Systemkonfiguration“

> /* System configuration problem alert detail */
> "A systems configuration issue is preventing Managed Software Center from operating correctly. The reported issue is: " = "A systems configuration issue is preventing Managed Software Center from operating correctly. The reported issue is: ";
> 
Translation: „ Ein Problem mit der Systemkonfiguration verhindert das korrekte funktionieren der Geführten Softwareaktualisierung. Das aufgetretene Problem ist:  „

**Comment by gregneagle** [comment]
Danke!
