### ISSUE TITLE
Missing es localizations

### ISSUE THREAD

**Issue by gregneagle** [munki/munki#742]
@LcTrKiD @nbalonso 
While preparing for an eventual Munki 3 release, I'm going through the localizations. I noticed two strings that must have been added to Managed Software Center at some point since the last localization pass that were never localized into most of the supported languages, including Spanish:

/* System configuration problem alert title */
"System configuration problem" = "System configuration problem";

/* System configuration problem alert detail */
"A systems configuration issue is preventing Managed Software Center from operating correctly. The reported issue is: " = "A systems configuration issue is preventing Managed Software Center from operating correctly. The reported issue is: ";

If you could help me out with Spanish translations here, it would be appreciated.

**Comment by LcTrKiD** [comment]
I will do it tomorrow 

Enviado desde mi iPhone

**Comment by gregneagle** [comment]
See https://github.com/munki/munki/wiki/Munki-3-Localization-needs for the current list.

**Comment by gregneagle** [comment]
@LcTrKiD I hope you can still find some time to look at this.

**Comment by LcTrKiD** [comment]
Sorry Greg, tons of extra work :(

I will find some time for the translation in the next weekend.

Enviado desde mi iPhone

**Comment by gregneagle** [comment]
Gracias, @LcTrKiD!
