### ISSUE TITLE
Missing fi localizations

### ISSUE THREAD

**Issue by gregneagle** [munki/munki#743]
@hjuutilainen 
While preparing for an eventual Munki 3 release, I'm going through the localizations. I noticed two strings that must have been added to Managed Software Center at some point since the last localization pass that were never localized into most of the supported languages, including Finnish:

/* System configuration problem alert title */
"System configuration problem" = "System configuration problem";

/* System configuration problem alert detail */
"A systems configuration issue is preventing Managed Software Center from operating correctly. The reported issue is: " = "A systems configuration issue is preventing Managed Software Center from operating correctly. The reported issue is: ";

If you could help me out with Finnish translations here, it would be appreciated.

**Comment by MiqViq** [comment]
So 'System configuration problem' means that there is a possible problem with macOS itself?

**Comment by gregneagle** [comment]
Neither. The specific situation in which this error alert occurs is when MSC.app cannot write the updated SelfServeManifest to /Users/Shared/.SelfServeManifest. This might be because /Users/Shared doesn't exist, or has the wrong permissions, or there's a pre-exisiting file owned by another user at /Users/Shared/.SelfServeManifest, etc.

It's a configuration problem with the "System", where "System" means the same thing as it does when we say "System(s) Administrator".

**Comment by MiqViq** [comment]
So it is kinda vague.
I can do vague. 
I will post a suggestion and we will discuss this with Hannes.

**Comment by gregneagle** [comment]
It is general to give me the option of using that error alert for other issues. Almost by definition there is not much the end-user can do about these issues if they don't have admin rights, so it's more about helping the user report the problem to their local support.

**Comment by MiqViq** [comment]
We discussed about this with Hannes.
This is our translation in Finnish:

/* System configuration problem alert title */
"System configuration problem" = "Järjestelmän määritysvirhe";

/* System configuration problem alert detail */
"A systems configuration issue is preventing Managed Software Center from operating correctly. The reported issue is: " = "Järjestelmän määritysvirhe estää Managed Software Center -ohjelman toiminnan. Raportoitu ongelma on: ";

**Comment by gregneagle** [comment]
Added here: https://github.com/munki/munki/commit/cf909398dcd90bc0bbd2cdd0fd99c9e1659c9084
