### ISSUE TITLE
Missing fr localizations

### ISSUE THREAD

**Issue by gregneagle** [munki/munki#744]
@RichardLafontaine 
While preparing for an eventual Munki 3 release, I'm going through the localizations. I noticed two strings that must have been added to Managed Software Center at some point since the last localization pass that were never localized into most of the supported languages, including French:

/* System configuration problem alert title */
"System configuration problem" = "System configuration problem";

/* System configuration problem alert detail */
"A systems configuration issue is preventing Managed Software Center from operating correctly. The reported issue is: " = "A systems configuration issue is preventing Managed Software Center from operating correctly. The reported issue is: ";

If you could help me out with French translations here, it would be appreciated.

**Comment by RichardLafontaine** [comment]
Sorry for the delay, I was on vacation last week.
