### ISSUE TITLE
Missing Russian localizations

### ISSUE THREAD

**Issue by gregneagle** [munki/munki#749]
/* System configuration problem alert title */
"System configuration problem" = "System configuration problem";

/* System configuration problem alert detail */
"A systems configuration issue is preventing Managed Software Center from operating correctly. The reported issue is: " = "A systems configuration issue is preventing Managed Software Center from operating correctly. The reported issue is: ";

There are also new "Featured" and "Featured items" labels:

/* FeaturedLabel */
"Featured" = "Featured";

/* FeaturedItemsHeaderText */
"Featured items" = "Featured items";

Finally, there is some Notification Center notification text which probably needs a native speaker's eyes:

/* Multiple Update message */
"%@ pending updates" = "%@ отложенных обновлений";

/* One Update message */
"1 pending update" = "1 отложенное обновление";

/* Details label */
"Details" = "Подробнее";

/* Forced Install Date summary */
"One or more items must be installed by %@" = "Один или несколько элементов должны быть установлены до %@";

/* Software updates available message */
"Software updates available" = "Обновления программного обеспечения, доступные";

**Comment by timsutton** [comment]
I should be able to find someone who can take a look at this..

**Comment by gregneagle** [comment]
Doesn't @groob speak Russian?

**Comment by groob** [comment]
He speaks it, but didn't have computers growing up so he only learned computer interface details in English. 

...I'll try to send a PR for this.

**Comment by gregneagle** [comment]
See https://github.com/munki/munki/wiki/Munki-3-Localization-needs for the current list.

**Comment by timsutton** [comment]
I've also asked a couple people if they can take a look. If they don't, I'll ask a couple more :)

**Comment by timsutton** [comment]
Looks like this one can now be closed (via #759 and #760).
