### ISSUE TITLE
local only manifests interact badly with optional installs

### ISSUE THREAD

**Issue by MagerValp** [munki/munki#761]
When an item is added as both a managed install and an optional install in a regular manifest, managed trumps optional and the item is hidden from Managed Software Center's software list. However if an item is added as a managed install in a local only manifest, as well as an optional install in the regular manifest, it's still visible as an optional install in Managed Software Center. Installing it works, but if you then try to uninstall the package, it throws managedsoftwareupdate into a loop.

As discussed on Slack, this is due to local manifests being processed after regular manifests, with no handling of optional vs managed installs.

**Comment by gregneagle** [comment]
Why wouldn't we just move the processing of the local only manifest earlier?

**Comment by gregneagle** [comment]
@natewalck @nmcspadden FYI

**Comment by natewalck** [comment]
So long as LocalIOnlyManifest entries are still enforced (Meaning if it
exists in LocalOnlyManifest as a ManagedInstall, it should have the same
behavior as if it were a ManagedInstall pulled from the server). If moving
it slightly earlier doesn't break this functionality, then it should be
good.

**Comment by MagerValp** [comment]
@gregneagle I was unsure if changing the order in which they're processed would have any nasty side effects, but since that adds 0 lines of code it's obviously preferable. I'll give it a whirl.

**Comment by MagerValp** [comment]
Whirl given, and it works in our testing. @natewalck and @nmcspadden I'd appreciate if you tested it in your deployments. To test dump [this version of `core.py`](https://github.com/MagerValp/munki/blob/757b5f191bad27eea36a24568ed68fa0edf03cab/code/client/munkilib/updatecheck/core.py) into `/usr/local/munki/munkilib/updatecheck` (and remove the `.pyc`).

**Comment by gregneagle** [comment]
I await the results of @natewalck/@nmcspadden's testing.

**Comment by gregneagle** [comment]
Closing since the PR has been merged and @MagerValp says it addresses his issue.
