### ISSUE TITLE
"." is not a valid munki repo url when running makecatalogs from within the munki repo (munki3)

### ISSUE THREAD

**Issue by bdemetris** [munki/munki#767]
managedsoftwareupdate --version
3.0.0.3283

makecatalogs .
Could not connect to munki repo:  does not exist

when running makecatalogs from within the munki repo "." is not recognized as a valid repo url.
supplying the full path to the repo as an argument to makecatalogs works as expected.

**Comment by gregneagle** [comment]
Addressed with https://github.com/munki/munki/commit/ee9fa49a16093d0304bfa87dbb3f4e44070a9d23
