### ISSUE TITLE
munki file in /etc/paths.d has executable bit set

### ISSUE THREAD

**Issue by scriptingosx** [munki/munki#769]
While this is probably cosmetic rather than troublesome, I noticed the munki file put in /etc/paths.d/ has the executable bit set, which is not necessary.

This comes from setting the parent folders' mode to 755 here

https://github.com/munki/munki/blob/Munki3/code/tools/make_munki_mpkg.sh#L345

Add a line

```
chmod 644 "$COREROOT/private/etc/paths.d/munki"
```

after line 345 above.

**Comment by gregneagle** [comment]
And similar modification to the *_DEP.sh script.

Those scripts need a rethink and a merge. They are a nightmare to maintain.

**Comment by gregneagle** [comment]
Addressed here: https://github.com/munki/munki/commit/b65b506b656c520113d291e2dd899dd7e37af558. Untested.
