### ISSUE TITLE
munkiimport (3.0.0.3320) doesn't prompt for Path to munki repo

### ISSUE THREAD

**Issue by aysiu** [munki/munki#773]
Previous versions of `munkiimport` would prompt for the `repo_path`:
https://github.com/munki/munki/blob/master/code/client/munkiimport#L845-L856

In the latest Munki 3 version, that part of configure is commented out:
https://github.com/munki/munki/blob/Munki3/code/client/munkiimport#L692-L702

Not sure if that's deliberate or if that was meant to be a temporary comment that never got removed.

**Comment by gregneagle** [comment]
100% deliberate. Repo path is no longer needed.

Local repos should be configured with a repo URL of file:///path/to/repo

See: https://github.com/munki/munki/wiki/Repo-Plugins#command-line-tools
