### ISSUE TITLE
FR: Munki3: Add support for preinstall_script/postinstall_script for macOS installs

### ISSUE THREAD

**Issue by fuzzylogiq** [munki/munki#775]
As per @gregneagle's comments below, this is currently intended behaviour. It would be nice to have this functionality back for OS upgrade installs, so I'm converting this to a feature request.

Original issue:

> Hi there,
> 
> I have a preinstall_script that is supposed to run before a macOS 10.12.4 upgrade install (which tars up the munki logs and restores them on next boot because Apple annoyingly blow away folders in /var/log/ on upgrade.*) However this never seems to run using Munki3 beta 6 (managedsoftwareupdate 3.0.0.3316)
> 
> This worked previously in Munki2 using a COSXIP package for the 10.11 upgrade. Noticed this on my own machine, confirmed testing in a VM this morning. 
> 
> from managedsoftwareupdate.log:
> ```May 15 2017 12:07:22 +0100 ### Beginning os installer session ###
> May 15 2017 12:07:22 +0100 Starting macOS upgrade...
> May 15 2017 12:07:22 +0100     Mounting disk image Install macOS Sierra-10.12.4.dmg
> May 15 2017 12:07:47 +0100     Preparing to run macOS Installer...
> May 15 2017 12:12:41 +0100 Saving application inventory...
> May 15 2017 12:12:46 +0100     Performing postflight tasks...
> ```
> 
> pkginfo at https://gist.github.com/fuzzylogiq/360bf52224c6f6e79ed4c43afbf0627c
> 
> *yes, I know, we probably shouldn't be putting them there in that case. But that's secondary, requires work to fix, and I'm really more interested in why it's not running at all.

**Comment by gregneagle** [comment]
The code that starts a macOS upgrade is run completely separately from all other installs. Preinstall and postinstall scripts are currently not supported -- so that's a documentation failure. Suggest (at least for now) using requires to specify another item, perhaps a nopkg, that performs your preupgrade tasks.

**Comment by fuzzylogiq** [comment]
Updated the wiki...do you want to leave this open for now to circle back to?

**Comment by gregneagle** [comment]
Perhaps you should turn it into a feature request?

**Comment by gregneagle** [comment]
This commit adds support for preinstall_script: https://github.com/munki/munki/commit/9d1223a2b4e2c5574f112a7ad7781a2d525a7175

Adding support for postinstall_script would be possible, but given that `startosinstall` _really_ wants to handle the restart immediately after setting up the install, I'm leaning towards _not_ supporting postinstall_scripts for startosinstall items.

**Comment by fuzzylogiq** [comment]
I agree. The only thing that postinstall_script could do is to run after the next boot, but that's hacky from a munki point of view so I think I can just handle this with a script/outset.

**Comment by gregneagle** [comment]
If Munki _did_ support postinstall_script for startosinstall items, it would run after the os upgrade was set up, but before the os upgrade was actually _installed_. (This is actually not any different than a postinstall_script for a createOSXinstallPkg item)

**Comment by gregneagle** [comment]
postinstall_script support added here:
https://github.com/munki/munki/commit/1bfe546e9139e02b8a314da0251819cfcd3effc7

Neither preinstall nor postinstall_script support has been actually _tested_ by me, though.
