### ISSUE TITLE
make_munki_mpkg_dep.sh line 317

### ISSUE THREAD

**Issue by erikng** [munki/munki#777]
I don't have time to send a PR right now, but before I forget, there is a difference between the DEP and non-DEP package script currently on line 317

DEP
`for TOOL in authrestart launchapp logouthelper managedsoftwareupdate supervisor ptyexec removepackages`

Non-DEP
`for TOOL in authrestartd launchapp logouthelper managedsoftwareupdate supervisor ptyexec removepackages`

I assume this is an error. I'm trying to work on the re-write but can't guarantee when it will be ready.

**Comment by gregneagle** [comment]
It's absolutely an error and another example of why these scripts need to be replaced with a single tool.

**Comment by erikng** [comment]
working on it, but I don't have time to spend on re-writing. I'm about 50% done in rewriting it in Python.

**Comment by gregneagle** [comment]
Understood -- but know that I don't use the make_munki_mpkg_DEP.sh script and so do not test it, and therefore am more likely to forget or make mistakes with it.
