### ISSUE TITLE
Munki 3 Ignoring CFBundleVersion and CFBundleShortVersion for version tracking

### ISSUE THREAD

**Issue by fkick** [munki/munki#779]
I use the CFBundleVersion and CFBundleShortVersion to manage Avid Media Composer updates in Munki 2, and the managed software center properly identifies when the current version of Avid MC is installed. After updating to Munki 3, managed software center continually prompts the user to install an Avid MC update, even though the current version is already installed.

**Comment by gregneagle** [comment]
We're going to need a _lot_ more detail. To start:
1) The pkginfo for the Avid MC update, and
2) Output of `managedsoftwareupdate -vvv` showing the part where Munki decides to (re)install the update.
3) Optional, but useful -- output of Munki 2's `managedsoftwareupdate -vvv` showing the part where Munki decides not to (re)install the update.

**Comment by fkick** [comment]
I've included the info you requested below. Please note I've changed our URL to example.com for this upload. Thank you for your help!

1. Pkginfo Contents:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>RestartAction</key>
	<string>RequireRestart</string>
	<key>_metadata</key>
	<dict>
		<key>created_by</key>
		<string>tgroupadmin</string>
		<key>creation_date</key>
		<date>2017-04-12T03:48:22Z</date>
		<key>munki_version</key>
		<string>2.8.2.2855</string>
		<key>os_version</key>
		<string>10.12.4</string>
	</dict>
	<key>autoremove</key>
	<false/>
	<key>catalogs</key>
	<array>
		<string>testing</string>
		<string>dev_team</string>
		<string>DIT</string>
		<string>Edit_Bays</string>
		<string>Producer_Laptops</string>
	</array>
	<key>category</key>
	<string>Edit Bay</string>
	<key>description</key>
	<string>Avid Media Composer 7.0.6.4</string>
	<key>developer</key>
	<string>Avid</string>
	<key>display_name</key>
	<string>Avid Media Composer 7</string>
	<key>icon_hash</key>
	<string>c273f361dd7cdabb8e42ff4cb0bad6b69294298897564ee64c7c541709d3a926</string>
	<key>icon_name</key>
	<string>Avid Media Composer.png</string>
	<key>installed_size</key>
	<integer>6817716</integer>
	<key>installer_item_hash</key>
	<string>ae954ca8effa681bf4404404e3907affda25b2dbfd9f278d64100ca3f3ca992e</string>
	<key>installer_item_location</key>
	<string>apps/Avid/Media_Composer_7.0.6.4_Mac-7.0.6.4.6210.dmg</string>
	<key>installer_item_size</key>
	<integer>2926544</integer>
	<key>installs</key>
	<array>
		<dict>
			<key>CFBundleIdentifier</key>
			<string>com.avid.mediacomposer</string>
			<key>CFBundleName</key>
			<string>Avid Media Composer</string>
			<key>CFBundleShortVersionString</key>
			<string>7.0.6.4.6210</string>
			<key>CFBundleVersion</key>
			<string>7.0.6.4</string>
			<key>path</key>
			<string>/Applications/Avid\ Media\ Composer/AvidMediaComposer.app</string>
			<key>type</key>
			<string>application</string>
			<key>version_comparison_key</key>
			<string>CFBundleShortVersionString</string>
		</dict>
	</array>
	<key>minimum_os_version</key>
	<string>10.5.0</string>
	<key>name</key>
	<string>Avid Media Composer</string>
	<key>postinstall_script</key>
	<string>#!/bin/sh

chmod -R 777 /Applications/Avid\ Media\ Composer/SupportingFiles/Avid_MediaFiles 

exit 0</string>
	<key>receipts</key>
	<array>
		<dict>
			<key>installed_size</key>
			<integer>244852</integer>
			<key>packageid</key>
			<string>com.avid.licensecontrol.pkg</string>
			<key>version</key>
			<string>3.0.1.6105</string>
		</dict>
		<dict>
			<key>installed_size</key>
			<integer>125376</integer>
			<key>packageid</key>
			<string>com.avid.sharedcomponents.pkg</string>
			<key>version</key>
			<string>1.0.0.6210</string>
		</dict>
		<dict>
			<key>installed_size</key>
			<integer>2102207</integer>
			<key>packageid</key>
			<string>com.avid.MediaComposerapplications.pkg</string>
			<key>version</key>
			<string>7.0.6.4.6210</string>
		</dict>
		<dict>
			<key>installed_size</key>
			<integer>1400472</integer>
			<key>packageid</key>
			<string>com.avid.MediaComposerlibrary.pkg</string>
			<key>version</key>
			<string>7.0.6.4.6210</string>
		</dict>
		<dict>
			<key>installed_size</key>
			<integer>234</integer>
			<key>packageid</key>
			<string>com.avid.MediaComposersystem.pkg</string>
			<key>version</key>
			<string>7.0.6.4.6210</string>
		</dict>
		<dict>
			<key>installed_size</key>
			<integer>2378</integer>
			<key>packageid</key>
			<string>com.avid.DXDriver.pkg</string>
			<key>version</key>
			<string>5.9.0.6210</string>
		</dict>
		<dict>
			<key>installed_size</key>
			<integer>1137388</integer>
			<key>packageid</key>
			<string>com.avid.Interplay.EditorTranscode.pkg</string>
			<key>version</key>
			<string>3.0.7.40400</string>
		</dict>
		<dict>
			<key>installed_size</key>
			<integer>467065</integer>
			<key>packageid</key>
			<string>com.avid.dmfservice.pkg</string>
			<key>version</key>
			<string>1.0.5.40400</string>
		</dict>
		<dict>
			<key>installed_size</key>
			<integer>828</integer>
			<key>packageid</key>
			<string>com.avid.MediaComposerUninstaller</string>
			<key>version</key>
			<string>7.0.6.4.6210</string>
		</dict>
		<dict>
			<key>installed_size</key>
			<integer>64264</integer>
			<key>packageid</key>
			<string>com.avid.tmp.PACE.pkg</string>
			<key>version</key>
			<string>1.0.0.6210</string>
		</dict>
		<dict>
			<key>installed_size</key>
			<integer>156943</integer>
			<key>packageid</key>
			<string>com.avid.avidlogexchange.pkg</string>
			<key>version</key>
			<string>29.0.6.4.6210</string>
		</dict>
		<dict>
			<key>installed_size</key>
			<integer>422425</integer>
			<key>packageid</key>
			<string>com.avid.edlmanager.pkg</string>
			<key>version</key>
			<string>29.0.6.4.6210</string>
		</dict>
		<dict>
			<key>installed_size</key>
			<integer>423814</integer>
			<key>packageid</key>
			<string>com.avid.filmscribe.pkg</string>
			<key>version</key>
			<string>29.0.6.4.6210</string>
		</dict>
		<dict>
			<key>installed_size</key>
			<integer>48711</integer>
			<key>packageid</key>
			<string>com.avid.medialog.pkg</string>
			<key>version</key>
			<string>29.0.6.4.6210</string>
		</dict>
		<dict>
			<key>installed_size</key>
			<integer>24127</integer>
			<key>packageid</key>
			<string>com.avid.avidcodecspe.pkg</string>
			<key>version</key>
			<string>2.5.0.38485</string>
		</dict>
		<dict>
			<key>installed_size</key>
			<integer>93725</integer>
			<key>packageid</key>
			<string>com.avid.osx.utilities.pkg</string>
			<key>version</key>
			<string>7.0.4.6210</string>
		</dict>
		<dict>
			<key>installed_size</key>
			<integer>102907</integer>
			<key>packageid</key>
			<string>com.avid.tmp.thirdparty.pkg</string>
			<key>version</key>
			<string>1.0.0.6210</string>
		</dict>
	</array>
	<key>unattended_install</key>
	<false/>
	<key>unattended_uninstall</key>
	<false/>
	<key>uninstall_method</key>
	<string>removepackages</string>
	<key>uninstallable</key>
	<false/>
	<key>version</key>
	<string>7.0.6.4.6210</string>
</dict>
</plist>
```

2. Output of managedsoftwareupdate -vvv on Munki 3

> * Processing manifest item Avid Media Composer for install
>     Looking for detail for: Avid Media Composer, version latest...
>     Considering 1 items with name Avid Media Composer from catalog Producer_Laptops
>     Considering item Avid Media Composer, version 7.0.6.4.6210 with minimum os version required 10.5.0
>     Our OS version is 10.10.5
>     Found Avid Media Composer, version 7.0.6.4.6210 in catalog Producer_Laptops
>     Adding Avid Media Composer to list of processed installs
>     /Applications/Avid\ Media\ Composer/AvidMediaComposer.app/Contents/Info.plist doesn't exist.
>     Need to install Avid Media Composer
>     Download base URL is: https://example.com/munki_repo/pkgs/
>     Package name is: Media_Composer_7.0.6.4_Mac-7.0.6.4.6210.dmg
>     Download URL is: https://example.com/munki_repo/pkgs/apps/Avid/Media_Composer_7.0.6.4_Mac-7.0.6.4.6210.dmg
>     Downloading to: /Library/Managed Installs/Cache/Media_Composer_7.0.6.4_Mac-7.0.6.4.6210.dmg
>     Downloading Media_Composer_7.0.6.4_Mac-7.0.6.4.6210.dmg from apps/Avid/Media_Composer_7.0.6.4_Mac-7.0.6.4.6210.dmg
>     Downloading Media_Composer_7.0.6.4_Mac-7.0.6.4.6210.dmg from apps/Avid/Media_Composer_7.0.6.4_Mac-7.0.6.4.6210.dmg
>     Options: {'logging_function': <function display_debug2 at 0x111e8c230>, 'ignore_system_proxy': None, 'additional_headers': {'User-Agent': u'managedsoftwareupdate/3.0.0.3333 Darwin/14.5.0'}, 'file': u'/Library/Managed Installs/Cache/Media_Composer_7.0.6.4_Mac-7.0.6.4.6210.dmg.download', 'cache_data': None, 'url': u'https://example.com/munki_repo/pkgs/apps/Avid/Media_Composer_7.0.6.4_Mac-7.0.6.4.6210.dmg', 'follow_redirects': u'none', 'download_only_if_changed': False, 'can_resume': True}
>     Downloading Media_Composer_7.0.6.4_Mac-7.0.6.4.6210.dmg...
> 	0..20..40..60..80..100
>     Status: 200
>     Headers: {u'Content-Length': u'2996781122', u'Accept-Ranges': u'bytes', u'Keep-Alive': u'timeout=5, max=100', u'MS-Author-Via': u'DAV', u'Server': u'Apache', u'Last-Modified': u'Wed, 12 Apr 2017 03:49:39 GMT', u'Connection': u'Keep-Alive', u'Etag': u'"b29f4042-54cf019025ac0"', u'Date': u'Tue, 06 Jun 2017 22:38:49 GMT', u'Content-Type': u'application/x-apple-diskimage'}
>     Verifying package integrity...
>     Media_Composer_7.0.6.4_Mac-7.0.6.4.6210.dmg downloaded at 18522 KB/s
>     /Applications/Avid\ Media\ Composer/AvidMediaComposer.app/Contents/Info.plist doesn't exist.
>     Looking for updates for: Avid Media Composer
>     Looking for updates for: Avid Media Composer-7.0.6.4.6210
>     Looking for updates for: Avid Media Composer--7.0.6.4.6210

It looks like for some reason Munki isn't able to read the Info.plist file based on the line  **/Applications/Avid\ Media\ Composer/AvidMediaComposer.app/Contents/Info.plist doesn't exist.**

3. Munki 2 output:

>  * Processing manifest item Avid Media Composer for install
>     Looking for detail for: Avid Media Composer, version latest...
>     Considering 1 items with name Avid Media Composer from catalog Producer_Laptops
>     Considering item Avid Media Composer, version 7.0.6.4.6210 with minimum os version required 10.5.0
>     Our OS version is 10.10.5
>     Found Avid Media Composer, version 7.0.6.4.6210 in catalog Producer_Laptops
>     Adding Avid Media Composer to list of processed installs
>     Looking for application Avid Media Composer with bundleid: com.avid.mediacomposer, version 7.0.6.4.6210...
>     Skipped app Default blpcfgokakmgnkcojhhkbfbldkacnbeo with path /Users/edit16/Library/Application Support/Google/Chrome/Default/Web Applications/_crx_blpcfgokakmgnkcojhhkbfbldkacnbeo/Default blpcfgokakmgnkcojhhkbfbldkacnbeo.app
>     Skipped app Aspera Crypt with path /Users/edit16/Applications/Aspera Crypt.app
>     Skipped app PrinterProxy with path /Users/edit16/Library/Printers/TG-CR2-BW-COPIER @ TGROUPSL.app
>     Skipped app Default coobgpohoikkiipiblmjeljniedjpjpf with path /Users/edit16/Applications/Chrome Apps.localized/Default coobgpohoikkiipiblmjeljniedjpjpf.app
>     Skipped app Default blpcfgokakmgnkcojhhkbfbldkacnbeo with path /Users/edit16/Applications/Chrome Apps.localized/Default blpcfgokakmgnkcojhhkbfbldkacnbeo.app
>     Skipped app Aspera Connect with path /Users/edit16/Applications/Aspera Connect.app
>     Skipped app PrinterProxy with path /Users/edit16/Library/Printers/TG-CR2-COLOR @ TGROUPSL.app
>     Skipped app PrinterProxy with path /Users/edit16/Library/Printers/TG-CR1-COLOR @ TGROUPSL.app
>     Skipped app PrinterProxy with path /Users/edit16/Library/Printers/TG-CR1-BW @ TGROUPSL.app
>     	Name: 	 Avid Media Composer
>     	Path: 	 /Applications/Avid Media Composer/AvidMediaComposer.app
>     	CFBundleIdentifier: 	 com.avid.mediacomposer
>     	Version: 	 7.0.6.4.6210
>     Avid Media Composer version 7.0.6.4.6210 (or newer) is already installed.
>     Looking for updates for: Avid Media Composer
>     Looking for updates for: Avid Media Composer-7.0.6.4.6210
>     Looking for updates for: Avid Media Composer--7.0.6.4.6210
>     Icon base URL is: https://example.com/munki_repo/icons/
>     Client resources base URL is: https://example.com/munki_repo/client_resources/

**Comment by gregneagle** [comment]
```
			<key>path</key>
			<string>/Applications/Avid\ Media\ Composer/AvidMediaComposer.app</string>
```

Is almost certainly an invalid/incorrect path.
Get rid of the backslashes and I bet things start working as you would expect.

This error on the admin's part was masked by a Munki (2) behavior that's changed in Munki 3: in Munki 2 if the application does not exist at the given path, Munki searches for it. In Munki 3, it does not. So since there is an incorrect/invalid path, in Munki 3, the item is considered not installed and so Munki wants to install it.

**Comment by gregneagle** [comment]
@fkick Any update here? Can this be closed?

**Comment by fkick** [comment]
Sorry was out of the office today, but yes that's seems to have cleared the issue. Thanks!
