### ISSUE TITLE
Munki 3 - Repo URL went AWOL after update

### ISSUE THREAD

**Issue by shoopdawoop** [munki/munki#780]
After updating from v2.8.3.3014 to v3.0.0.3333 on my server I had to set the Repo URL (which was empty) via `munkiimport --configure`, but setting it to `file:///myrepopath/munki_repo` would no longer work, it only worked after adding a trailing slash to the path (`file:///myrepopath/munki_repo/`).

Not sure if this is expected behavior or considered a minor bug.

I should add that I did hit the "Update Munki Tools" button in AutoPkgr prior to manually installing the munkitools-3.0.0.3333.pkg, so maybe that messed things up.

**Comment by gregneagle** [comment]
`file:///path/to/repo` works here without a trailing slash, and I've had no other reports of any issues along these lines. There must be something unique about your environment that we're missing.

**Comment by shoopdawoop** [comment]
Seems to work fine now without the trailing slash (I copy & pasted the path before, so that might have been it, see reference), so I consider this one solved. Sorry for the buzz.
