### ISSUE TITLE
Munkiimport does not remove trailing whitespace from Repo URL, makecatalogs does

### ISSUE THREAD

**Issue by aschwanb** [munki/munki#781]
Steps to reproduce:
Running `munkiimport --configure` and leave a trailing whitespace after the repo url.

`makecatalogs` will run without issue, but `munkiimport <someSoftware>` will return the following error:
`Could not connect to munki repo: <your Repo >  does not exist`

What I don't understand is why the trailing whitespace is causing an issue with one tool but not the other. Is the Repo URL retrieved differently?

Tested with Munki Verison 3.0.0.3333 after updating from Munki Version 2.8.2

**Comment by shoopdawoop** [comment]
Could be the same issue that I had (#780), I will test this later today.

**Comment by aschwanb** [comment]
Possible. Let me know how it turns out.

**Comment by gregneagle** [comment]
There's definitely a difference in behavior between the two tools (not shocking, `makecatalogs` predates `munkiimport` by quite a bit; but if a remote repo is not mounted, `makecatalogs` still fails:

```
$ makecatalogs
Could not connect to munki repo: /Volumes/repo does not exist
```

I'll fix this so the behavior and error messages are consistent.

**Comment by aschwanb** [comment]
Thank you very much!

**Comment by gregneagle** [comment]
OK, behavior is now (as of latest master commit):
```
$ ./makecatalogs 
Attempting to mount fileshare https://munki.foo.com/repo :
Could not connect to munki repo: Error mounting url "https://munki.foo.com/repo ": Unknown error: -50, error -50
g$ ./munkiimport /Applications/Managed\ Software\ Center.app
Attempting to mount fileshare https://munki.foo.com/repo :
Could not connect to munki repo: Error mounting url "https://munki.foo.com/repo ": Unknown error: -50, error -50
```
