### ISSUE TITLE
Munki 3 Install macOS Sierra bootlock with FileVault

### ISSUE THREAD

**Issue by tcinbis** [munki/munki#788]
You end up in a bootlock if you recently enabled FileVault and the disk is still encrypting or optimizing and then munki starts an OS update with the new `startosinstall` feature.
The user will logout as expected, but once you boot into the installer the setup stops and says something like "The disk is still encrypting, please restart". But after a restart it boots into the setup again and again...

I wrote a little Pre-install script to check this state (Improvement suggestions appreciated):
```bash
#!/bin/bash
result=`diskutil cs list | grep "Conversion Progress"`
if [[ $result == "" ]]; then
  #There is no FileVault, we can install
  exit 0
elif [[ $result ==  *"Complete"* ]]; then
  #FileVault is enabled and complete,we can install
  exit 0
else
  #FileVault is enabled but incomplete, WAIT!
  exit 1
fi
```

**Comment by gregneagle** [comment]
Sounds like a bug that should also be filed with Apple -- `startosinstall` should not get a machine into this state.

**Comment by gregneagle** [comment]
This commit:

https://github.com/munki/munki/commit/065044afc62c691ef0fbcc623c91f001daf69987

should address this Apple bug. Testing appreciated.

**Comment by tcinbis** [comment]
I will test it next week!

**Comment by tcinbis** [comment]
So I tested it, but unfortunately it would just do the update even if the disk was currently encrypting.
I started logging a little bit more in your code change and think I found the problem:
`csinfo_plist = FoundationPlist.readPlist(output)`
It worked for me once I changed `FoundationPlist.readPlist(output)` to `FoundationPlist.readPlistFromString(output)`.

Everything else worked perfect!

**Comment by gregneagle** [comment]
Thanks for the testing. Your fix incorporated here:
https://github.com/munki/munki/commit/ebbbd3a1f88eae18a3f814b8de1a9032566191d5

If that's identical to your change or you can test and verify, let's close this as fixed.

**Comment by tcinbis** [comment]
I can confirm that it is identical

**Comment by gregneagle** [comment]
Closing!
