### ISSUE TITLE
Feature Request: Add a refresh button to Managed Software Center

### ISSUE THREAD

**Issue by lashomb** [munki/munki#792]
We have several mechanisms to reload the content within Managed Software Center from what I can tell. We can choose Navigate -> Reload Page from the menubar; we can click "Check Again" under the Updates tab, we can use the keyboard shortcut ⌘ R or finally we can right-click the content of the "page" and choose Reload.

Given that user input for this application is most likely via mouse-clicks though, my request is that a Refresh/Reload button be added. It could be one of the smaller Apple UI elements next to the back and forward buttons perhaps. Or maybe an auto-reload is kicked off when clicking into the Updates tab.

**Comment by gregneagle** [comment]
It's not clear to me what this button would _do_. The "Check again" button triggers a very different thing than does reloading a web view (which would rarely accomplish anything particularly useful). What were you hoping would happen when someone clicked a refresh button; and what do you think a "normal" user would expect such a button to do?

More simply: what problem are you attempting to solve?

**Comment by lashomb** [comment]
The idea being customizing local manifest content based on entitlements. We use alot of directory services groups for entitlements, where you request access to something like Tableau for example and if approved you are added to that group. Typically if you wanted to install that, you were likely already in Managed Software Center, but then realize you don't have the access to that software. So user would gain that entitlement, then click refresh, preflight runs the directory check, and items show up that you didn't have access to before.

**Comment by lashomb** [comment]
So to your point, I'm looking for "Check again" not reload perse, I wasn't aware of the distinction there.

**Comment by gregneagle** [comment]
I still don't think I understand many things here, like how the user would request an "entitlement"; how they'd know it has been granted to them, and how they'd know they need to click some button to see changes in MSC.app based on a change in entitlements.

**Comment by lashomb** [comment]
Entitlements are all external to Munki, or whatever you manage machines with. How users get entitlements is going to be org specific, but all that matters is that logic gets taken care of before `managedsoftwareupdate` is run. In our current "vendor provided solution", an "Update Inventory" policy is run by the user, Recon is run, and whatever Extension Attribute manages whether that entitlement is present scopes that item to them or not. So if a user knows they got approved for "AdobeAllTheThings" group, they run Update Inventory, so they can see the software scoped to them.

Clicking "Check Again" in Munki does ultimately work for the user, but its on the Updates tab, which is counterintuitive if you're looking for what has changed back on the Applications tab.

**Comment by lashomb** [comment]
The whole idea with entitlements probably doesn't make sense in some environments. For ours, a license for Tableau for example can cost thousands of dollars. Others have recurring fees, and if you let everyone who thinks making memes is cool install Photoshop, your Creative Cloud bill gets pretty steep. So we use directory service groups for gating those requests. It allows a managerial approval step, and they also fall into the quarterly access review we use for security groups. And we then use logic to detect membership, and allow install.

In a past job I used to run Munki (v1) alongside Puppet... it was a much smaller shop, so I just got away with Puppet doing a lookup on department from directory services and then writing the manifest name to the plist. So Creatives didn't think IntelliJ sounds cool and install it using up a license. Now I have a much bigger environment, and I'd like to get away from a server being a middleman for "facts" and just process them on endpoints. If its not a favorable design change to Munki, I understand, just explaining where I'm headed with this.

**Comment by erikng** [comment]
I think in the end you'd like the refresh button to trigger a managedsoftwareupdate run, but I would actually think you'd need some kind of progress UI for the user to understand the run hasn't finished (which is why it's in the updates tab now).

A run could take a decent amount of time and if the user expects a refresh to instantly show content with a second or two, they are going to get confused/frustrated.

Casper, which is what I think you are comparing to, does this pretty quickly in their self service - I think munki would need a giant refactoring in order to do this.

Thanks,
Erik Gomez
________________________________

**Comment by gregneagle** [comment]
Closing this. We won't do a button, but Command-R or Navigate->Reload Page does essentially what was requested.
