### ISSUE TITLE
Microsoft Office Installer 14.0.0 (followed by updates) installing under wrong owner [root] instead of local user after deployment

### ISSUE THREAD

**Issue by smokin-a-bsig** [munki/munki#796]
Running Munki 3.0.3 and Deploystudio 1.7.6 with a workflow which installs fresh OS, creates 2 new users (admin and local), reboots, and installs munkitools followed by managedsoftwareupdate and managedsoftwareupdate --installonly.

I am consistently encountering this problem with the office apps where "There is a problem with the Office database" only to find ~/Library/Group\ Containers and ~\Library/Application\ Support/Microsoft are owned by root, rather than the local user. When imaging dozens of computers, it is tiresome to manually change ownership. I can set line to change this ownership issue, but what is causing the discrepancy with only Microsoft Office in the first place?

Any help would be greatly appreciated as we have several new employees coming in soon.

**Comment by gregneagle** [comment]
This is not a Munki code issue, but rather an issue with third-party software you are deploying with Munki. I'd recommend bringing this up for discussion on the munki-discuss list: https://groups.google.com/group/munki-discuss

We deploy Office + updates via Munki as well and do not see issues like those you describe.
