### ISSUE TITLE
Munki 3 Auth Restart issue

### ISSUE THREAD

**Issue by clburlison** [munki/munki#799]
### The issue
When doing an auth restart munki reads the `RecoveryKeyFile` which I had set as (yes this was an admin error and is now corrected):

```bash
            <key>RecoveryKeyFile</key>
            <data>
BAgw
            </data>
```
FoundationPlist is unable to process this data properly because it shouldn't exist and causes a exception in `authrestart/__init__.py`. This then halts the munki run.

### The fix?
Untested, fix is to add to include `NSInvalidArgumentException` in the exception located:

https://github.com/munki/munki/blob/98a489298536e24048244ca51d72f4c8c0fdb084/code/client/munkilib/authrestart/__init__.py#L124

This should cause munki to return a empty string and continue the run.

### Error log
[AuthRestartErr.txt](https://github.com/munki/munki/files/1265153/AuthRestartErr.txt)

(I'll test this tomorrow just ran out of time for today)

**Comment by gregneagle** [comment]
I'm skeptical that will address the issue, as that's a perfectly valid key/value pair for a plist. So is

```xml
<key>RecoveryKeyFile</key>
<true/>
```
and
```xml
<key>RecoveryKeyFile</key>
<array>
     <string>foo</string>
</array>
```
etc...

**Comment by clburlison** [comment]
You are correct in that it is a valid key/value pair but FoundationPlist errors when attempting to do `NSPropertyListSerialization` since the data I'm passing isn't valid.

https://github.com/munki/munki/blob/4053a0dbe77d900308260ba8a39ca1df4814d33c/code/client/munkilib/FoundationPlist.py#L74-L77

**Comment by gregneagle** [comment]
@clburlison Can you create a PR so we can get this fix into Munki 3.1?

**Comment by clburlison** [comment]
@gregneagle #800 was the PR that fixes this. You've already merged the fix.

**Comment by gregneagle** [comment]
Well then lets get this noise removed from the signal...
