### ISSUE TITLE
managedsoftwareupdate restart flag is overridden by nopkg script.

### ISSUE THREAD

**Issue by chymb** [munki/munki#802]
Hi,
I noticed that our deployment bootstrapping (which makes heavy use of nopkg scripts) was skipping a reboot and tracked it down to the following line. The "=" overrides a previous True value if the nopkg script requires no restart.

https://github.com/munki/munki/blob/91b43fdbe84b661c6d08bcb581186cc600f6b7b0/code/client/munkilib/installer/core.py#L306

Cheers,
Chris

**Comment by gregneagle** [comment]
Wanted this fix to go into tomorrow's RC, so I did my own version of the fix:
https://github.com/munki/munki/commit/eb17f853fb7083d50c6ce778fe57bcb36bd9e86b

Thanks for finding this!
