### ISSUE TITLE
munkiimport of OSX Sierra Installer fails with UnicodeEncodeError

### ISSUE THREAD

**Issue by hugo4711** [munki/munki#805]
my-mac-server:Downloads admin$ munkiimport --version
3.0.3.3352
my-mac-server:Downloads admin$ munkiimport /Applications/Install\ macOS\ Sierra.app/
Making disk image containing Install macOS Sierra.app...
Traceback (most recent call last):
  File "/usr/local/munki/munkiimport", line 1100, in <module>
    main()
  File "/usr/local/munki/munkiimport", line 839, in main
    dmg_path = make_dmg(installer_item)
  File "/usr/local/munki/munkiimport", line 88, in make_dmg
    print line
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 123: ordinal not in range(128)

**Comment by gregneagle** [comment]
I've not encountered this behavior and I've had no other reports of it. Without being able to reproduce it, it's impossible to address.

**Comment by hugo4711** [comment]
Thanks for getting back to me!

I can also add that this happens on an Yosemite based OSX server:

Darwin my-mac-server.velian.net 14.5.0 Darwin Kernel Version 14.5.0: Sun Jun  4 21:40:08 PDT 2017; root:xnu-2782.70.3~1/RELEASE_X86_64 x86_64

**Comment by gregneagle** [comment]
I think you should bring this up on munki-discuss and see if you can find anyone else seeing this, or perhaps work with others to determine how to reproduce it/figure out what triggers it.

**Comment by gregneagle** [comment]
Just as a potential data point: what is the output of `printenv LANG` for you?

**Comment by gregneagle** [comment]
or, perhaps even more helpful, the output of `locale`?

**Comment by hugo4711** [comment]
my-mac-server:~ admin$ locale
LANG="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_CTYPE="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_ALL=
my-mac-server:~ admin$

**Comment by hugo4711** [comment]
my-mac-server:~ admin$ printenv LANG
de_DE.UTF-8

**Comment by jannheider** [comment]
@hugo4711 
I this still happening ?

Are you connected over ssh to the server (my-mac-server) ?
I had a similar issue recently

**Comment by hugo4711** [comment]
@jannheider yes I was connected via ssh - I've just tried it directly on the machine and it works...

**Comment by jannheider** [comment]
@hugo4711 
Ok, then check your locale on your ssh client site, there is the problem. SSH Client will forward the locale settings from your client.
On your server everything looks fine with locale

@gregneagle 
Think this issue could be closed, as this is not a munki issue.

**Comment by hugo4711** [comment]
Thanks a lot @jannheider !

**Comment by gregneagle** [comment]
Closing.
