### ISSUE TITLE
Xcode 9 and make_munki_mpkg.sh

### ISSUE THREAD

**Issue by pnerum** [munki/munki#807]
When using munki-rebrand script I ran in to an error. It seems the error comes from make_munki_mpkg.sh. Last week I installed Xcode 9. I’ve downgraded to Xcode 8 and I can create a munki package again.

I’ve tested this behaviour on a second Mac and could reproduce the error.

This is the output of the Munki rebrand script:

Building customized Munki...
** BUILD FAILED **

The following build commands failed:
    PhaseScriptExecution Localize build/Managed\ Software\ Center.build/Release/Managed\ Software\ Center.build/Script-C09CE1D918BEA41000B9724A.sh
(1 failure)

Cleaning up...
Done.

**Comment by fuzzylogiq** [comment]
This appears to be due to trying to run make_munki_mpkg.sh before the additional components have been installed in an updated Xcode, so not really a munki issue at all. I'll update the readme for munki-rebrand to highlight this.

**Comment by pnerum** [comment]
I can confirm after installing the additional components it all works again.
