### ISSUE TITLE
RestartAction RequireRestart not working when installing a profile

### ISSUE THREAD

**Issue by ntrogers** [munki/munki#808]
When installing a profile with `RestartAction` set to `RequireRestart`, the user is logged out and the installation occurs, but the computer does not restart afterwords. So far I've tested in OSX 10.9.5 and macOS 10.12.6. Am using munkitools v3.1.

**Comment by gregneagle** [comment]
https://github.com/munki/munki/blob/master/code/client/munkilib/installer/core.py#L297-L303

Looks like the value of RestartAction is ignored for config profiles installs, and you are the first to notice.

**Comment by ntrogers** [comment]
Ah ok thanks for pointing that out. After adding in the restart flag it performs as you would expect. 

```
# configuration profile install
elif installer_type == 'profile':
    # profiles.install_profile returns True/False
    retcode = 0
    identifier = item.get('PayloadIdentifier')
    if not profiles.install_profile(itempath, identifier):
        retcode = -1
    if retcode == 0 and requires_restart(item):
        restartflag = True
```
I've got a work around for the time being but what is the process for requesting this feature in future builds? Edit the thread title to include "Feature Request"?

**Comment by gregneagle** [comment]
I'd say making a Pull Request with your change/fix would be the best way forward. 

See https://github.com/munki/munki/wiki/Contributing-to-Munki
