### ISSUE TITLE
No pkgsinfo description, no note

### ISSUE THREAD

**Issue by bochoven** [munki/munki#811]
This maybe by design: if the pkgsinfo file has no description, the long note is not displayed.

e.g. "You must upgrade to macOS version %s to be able to install this item." is not displayed unless there is ad description tag.

**Comment by gregneagle** [comment]
I don’t think that’s by design and it should be fixed.

**Comment by gregneagle** [comment]
Relevant code is here: https://github.com/munki/munki/blob/master/code/apps/Managed%20Software%20Center/Managed%20Software%20Center/MunkiItems.py#L1047-L1081

I'm not seeing anything obvious jump out; this should display the long note even if the raw description is empty...

**Comment by gregneagle** [comment]
Depending on the exact view, this code might be relevant as well:
https://github.com/munki/munki/blob/master/code/apps/Managed%20Software%20Center/Managed%20Software%20Center/MunkiItems.py#L1157-L1207

**Comment by gregneagle** [comment]
@bochoven Can you confirm this fixes your issue?

**Comment by bochoven** [comment]
Confirmed
