### ISSUE TITLE
Clicking on the 'currently unavailable' button shows raw html in status message

### ISSUE THREAD

**Issue by bochoven** [munki/munki#812]
Strange bug as the button does not appear clickable. On a detail page, clicking the button turns the status into:

```<span class="warning">some note</span>```

On the My Items listing, the status disappears when clicking 'currently unavailable'

On the homepage clicking 'currently unavailable' turns the status also into raw html

**Comment by gregneagle** [comment]
@bochoven Can you confirm this fixes your issue?

**Comment by bochoven** [comment]
Confirmed! Nice job
