### ISSUE TITLE
iconimporter doesn't necessarily include a ColorSync Profile in .png

### ISSUE THREAD

**Issue by aysiu** [munki/munki#813]
Hat tip to @bochoven for discovering what was missing.

The ColorSync Profile that High Sierra is looking for is what appears to be missing when generated using `iconimporter`, depending on the .icns in question.

**Comment by erikng** [comment]
Is this why some icons look gray on High Sierra?

**Comment by gregneagle** [comment]
Is it that `iconimporter` (and equivalent code in Managed Software Center) is failing to copy/transfer ColorSync info, or is the issue that the original icon is missing ColorSync info?

**Comment by aysiu** [comment]
Just wanted to update this based on further testing reported on Slack:

It appears the ColorSync info is in the original .icns file and is also "in" the resulting .png (if viewed through ColorSync Utility), but it doesn't necessarily show in the Get Info dialogue for the file.

And apparently there may not need to be code changes. If you use `iconimporter` from a 10.13 machine.

**Comment by aysiu** [comment]
I'm going to close the issue, because I don't think it's an issue with Munki or even the code, and there's a very simple fix for it now that we sort of know what's going on:
Delete the offending icons
Mount the Munki repo using a 10.13 machine
run `/usr/local/munki/iconimporter /PATH/TO/MOUNTED/REPO`

**Comment by erikng** [comment]
I think this issue comes from icns -> png icons created with Apple's Preview.app.

**Comment by gregneagle** [comment]
"If you try to do this on 10.13" Do what, exactly? I can't address random ways of creating pngs. I can only address Munki's methods of converting icns files to pngs.

**Comment by gregneagle** [comment]
With the _exact same icon_ (use the one in Managed Software Center.app as a demo) `iconimporter` under 10.12.6 generates a png that is missing the embedded ColorSync profile. `iconimporter` under 10.13 generates a png that contains an embedded ColorSync profile.

**Comment by erikng** [comment]
I don't think there is anything to fix. `iconimporter` does the right thing. The admin should fix their icons.

**Comment by gregneagle** [comment]
...and yet this code https://github.com/munki/munki/commit/3d7021af8f0718f6e79dba96110b1c4af2cbd356 addresses the issue anyway.

**Comment by gregneagle** [comment]
(to test/verify, identify an icon that shows this issue. Delete it from your repo, then (under 10.12.x) use this code's `iconimporter -i item_name` to regenerate it. Rebuild catalogs, refresh a 10.13 client, and you'll see the icon looking "normal" once again.)
