### ISSUE TITLE
munki-notifier does not show force install date

### ISSUE THREAD

**Issue by erikng** [munki/munki#822]
While testing some force install dates today, we noticed that munki-notifier is truncated.

<img width="355" alt="screen shot 2017-12-07 at 4 47 20 pm" src="https://user-images.githubusercontent.com/5685016/33746677-87e7f634-db73-11e7-85b8-86f78f611213.png">

two ideas on resolving this:

Remove line two and change line 1 to `Software updates available (%int)`
<img width="354" alt="screen shot 2017-12-07 at 4 55 23 pm" src="https://user-images.githubusercontent.com/5685016/33746675-87bf3b22-db73-11e7-99a4-1a7c009e94ed.png">

Remove line two
<img width="365" alt="screen shot 2017-12-07 at 4 53 42 pm" src="https://user-images.githubusercontent.com/5685016/33746676-87d3617e-db73-11e7-9839-8ba3f559fa93.png">

**Comment by gregneagle** [comment]
This was a design decision on my part.
Your change is doable, but still might not display everything in every supported language, though German and Finnish seem to work OK:

<img width="352" alt="screen shot 2017-12-08 at 9 39 30 am" src="https://user-images.githubusercontent.com/700560/33778044-e6c5d3aa-dbfb-11e7-8308-a602338617d1.png">

<img width="351" alt="screen shot 2017-12-08 at 9 43 36 am" src="https://user-images.githubusercontent.com/700560/33778162-5d151386-dbfc-11e7-8bc3-c82c8d048ff3.png">

<img width="350" alt="screen shot 2017-12-08 at 9 46 32 ap" src="https://user-images.githubusercontent.com/700560/33778248-c44e27d6-dbfc-11e7-825d-2a39ab93b360.png">

**Comment by erikng** [comment]
Ah yes, I didn't think about the "Details" button expanding. Would you be comfortable with this change at the potential expense of other languages potentially getting truncated?

Having the date in our notifications gives us more ammunition when a user claims they had no information as to when the cutoff date was.

**Comment by gregneagle** [comment]
Addressed here: https://github.com/munki/munki/commit/3762b823751045bc9c109b3a854c815b58a77d49
