### ISSUE TITLE
makecatalogs enhancement: warning for same item with same version

### ISSUE THREAD

**Issue by erikng** [munki/munki#823]
If an admin makes a stupid mistake and has two exact items with the exact same version, it would be great if makecatalogs could find see this and give a warning.

**Comment by gregneagle** [comment]
Detecting this properly might be harder than you think. Two items with the same version, but with different OS or hardware requirements would be perfectly OK...

**Comment by gregneagle** [comment]
Also: same version, but different catalogs. Or installcheck_scripts. There might be others...

**Comment by erikng** [comment]
Hm. Perhaps I shouldn't be stupid then. You can close if it will require more effort than it's worth.

**Comment by gregneagle** [comment]
Closing this as no plans to implement.
