### ISSUE TITLE
device profile -> chrome -> bookmarks -> not getting updated 

### ISSUE THREAD

**Issue by vikaskedia** [munki/munki#825]
I am pushing the corporate bookmarks to the desktops/laptops using mobileconfig.

The first time it works flawlessly.

When there is an update to the bookmarks:
 
1. Managed software center shows there is an update 
2. System preferences -> Profiles shows that the new profile has been installed and the content shows the new URLs in it.

But chrome does not get the new bookmarks.

To solve:
I need to delete all the profiles (/usr/bin/profiled -D) and then install all the profiles again from the managed software center.

**Comment by gregneagle** [comment]
This issues tracker is not a general support mechanism. It is for tracking code issues with Munki. You issue does not sound like that. Consider posting a question on the munki-discuss mailing list.
