### ISSUE TITLE
Ignoring unattended_install key for Apple update because item RestartAction is RequireRestart

### ISSUE THREAD

**Issue by RAFd3v** [munki/munki#826]
If I try to force_install_after_date in MunkiAdmin, I'm getting this error

> Ignoring unattended_install key for Apple update because item RestartAction is RequireRestart

 in sudo /usr/local/munki/managedsoftwareupdate -vv

**Comment by vmiller** [comment]
That's not an error, it is expected behavior.  `unattended_install` will be ignored if `RequireRestart` or `RequireLogout` is set.

**Comment by arubdesu** [comment]
Hey @RAFd3v, this is an expected result, force_install_after_date will listen to an`--auto`, like the launchd job uses. Likewise, it is not an issue with MunkiAdmin.
In the future please post general usage questions to the munki-discuss mailing list, as listed on the [wiki](https://github.com/munki/munki/wiki#where-to-go-for-more-info-and-help).

**Comment by gregneagle** [comment]
This is not a general support forum. Please use the munki-discuss Google Group for support.
