### ISSUE TITLE
potential bug: URL's on Update tab should open with default browser

### ISSUE THREAD

**Issue by erikng** [munki/munki#827]
If a user has a pending update (perhaps a supplemental update) with a URL in the description and clicks on it, MSC will go to the URL. This has an unintended side-effect of removing the `Update Now` button from the user.

The user can use the back button inside MSC or change from one tab and back to the Update tab, but it might be beneficial to open the URL's with the user's default browser instead.

**Comment by gregneagle** [comment]
Since this currently functions as designed, consider starting a discussion on Munki-dev about whether the current behavior is acceptable.
