### ISSUE TITLE
Proposal: improvements in "default" repo URL

### ISSUE THREAD

**Issue by gregneagle** [munki/munki#833]
Currently, if a Munki client does not have SoftwareRepoURL defined, it looks for `http://munki/repo`. This is a very convenient way to avoid having to configure Munki clients but is insecure.

I propose the following changes:

If SoftwareRepoURL is undefined, Munki will attempt the following URLs, in order:

https://munki.<dns_domain_of_current_host>/repo
http://munki.<dns_domain_of_current_host>/repo

If one is "successful" (with what is considered "successful" yet to be defined), the successful URL is then stored in /Library/Preferences/ManagedInstalls.plist

This proposal addresses two issues:

1) Makes https the "preferred" scheme, and allows the use of a "default" https Munki server, and
2) once "bootstrapped", a client relying on Munki defaults is not as easily hijacked when on a foreign network.

**Comment by keeleysam** [comment]
Where would you pull `dns_domain_of_current_host` from?

Making https the preferred scheme is good, but I do think that this might still be really trivial to defeat.

With `http://munki`, it's really easy to abuse via Bonjour by just naming your computer `munki` on some public wifi, or search domains by a slightly more advanced attacker.

With http://munki.<dns_domain_of_current_host>, the second attack still works, and it also still works if the attacker controls your DNS (public wifi).  It might make it harder from someone else on the same network to hit you from the side, but an attacker that controls the network could simply deny the https connection and get you.

While I think that changing the default to `https://munki.<dns_domain_of_current_host>/repo` is good as long as the resolution of the DNS domain is well known, I think that the http option should not be present.  It will still allow you to bootstrap without configuration, but you'll need to ensure your DNS is in line and you have a trusted certificate.

**Comment by gregneagle** [comment]
"Where would you pull dns_domain_of_current_host from?"
Something like:
```python
#!/usr/bin/python

import os

print os.uname()[1].partition('.')[2]
```
...which gives the desired result here, but of course I'm open to better approaches.

"Auto-guess" of  SoftwareRepoURL would only happen if SoftwareRepoURL is undefined. Once there is a successful Munki run against an auto-detected URL, the URL gets written to SoftwareRepoURL in /Library/Preferences/ManagedInstalls.plist. The "auto-detect/auto-guess" mechanism would not be called again, since now SoftwareRepoURL is defined.

"I think that the http option should not be present."
I know you do. I think it should be present, because I am aware of all the different places that use Munki and get the support questions.

**Comment by gregneagle** [comment]
This also seems to work to get the current DNS domain:
```python
#!/usr/bin/python

import socket

def get_dns_domain():
    return socket.getfqdn().split('.', 1)[1]

print get_dns_domain()
```
I don't know which approach is "better".

**Comment by gregneagle** [comment]
Should probably special-case for a detected domain of "local" and _not_ accept that when auto-guessing; or at least _not_ record that in /Library/Preferences/ManagedInstalls.plist

**Comment by flammable** [comment]
This seems reasonable to me, especially the most recent thought about rejecting .local domains.

For now, we still use the bootstrapping URL, so this is useful to us.  We bootstrap using http://munki/repo, then set `SoftwareRepoURL` to https://munki.domain.edu/repo (with basic authentication).  If https is to be attempted first, would it be possible to consider an authentication prompt to be a failure if `SoftwareRepoURL` is not defined?

**Comment by gregneagle** [comment]
Thanks for describing that workflow. Definitely an authentication prompt would be a failure to connect (since an unconfigured client wouldn't have the credentials). More important would be make sure the code continued trying `http://munki.<dns_domain_of_current_host>/repo` next, which means success might need to be defined as "can retrieve the primary manifest".

**Comment by n8felton** [comment]
I feel that adding `https://munki/repo` to the "search order" would be a great addition. It would allow environments that use this method of bootstrapping to optionally remove the need for non-https services from the environment.

I believe that grabbing the `dns_domain_of_current_host` is going to have unintended negative side affects. This has the potential to "hard code" a FQDN with a domain name that could potentially be wrong. The benefit of it not being a FQDN today is that the OS will automatically append domain suffixes from the search domains that it receives from DHCP via options 15 (DNS domain suffix) and/or 119 (DNS domain search list). I have seen instances where `hostname` (and I'm assuming `socket.getfqdn()` or `os.uname()[1]`) have been something like `NatesMacBookPro.local` even though the DNS search domains contained the proper DNS suffix[es]. I'll see if I can do some testing on this in my environment to see if I can easily reproduce unwanted circumstances like this.

I'd like to offer another potential option to be considered in parallel to this; make use of DNS. This is how many auto-discover/auto-configure mechanisms in other application/services work today. [Puppet can be configured with DNS SRV records](https://puppet.com/docs/puppetserver/5.1/scaling_puppet_server.html#using-dns-srv-records), heck, [even Minecraft has support](https://minecraft.gamepedia.com/1.3.1#Changes) [for SRV records](https://www.noip.com/support/knowledgebase/how-to-add-a-srv-record-to-your-minecraft-server-remove-the-port-on-the-end-of-the-url).

A DNS SRV records such as
`_munki._tcp.example.com 86400 IN SRV 0 100 443 rafiki.example.com`
could point a client with `SoftwareRepoURL` undefined to `http[s]://rafiki.example.com/repo`.

This could also be combined with a DNS TXT record to point `SoftwareRepoURL` to something less default/more explicit, such as `https://rafiki.example.com/munki_repo` with a TXT record like
`rafiki.example.com 86400 IN TXT "repo=https://rafiki.example.com/munki_repo"`

Some examples/options for this:
1. Query DNS for a service record `_munki._tcp.example.com` (where `example.com` comes from DHCP options). Receive `rafiki.example.com` and insert it for the FQDN to be used, e.g. `https://munki/repo` becomes `https://rafiki.example.com/repo`

2. Query DNS for a service record `_munki._tcp.example.com` (where `example.com` comes from DHCP options). Receive `rafiki.example.com` and query DNS for a TXT record at `rafiki.example.com` and parse the record for `repo`, e.g. `https://munki/repo` becomes `https://rafiki.example.com/munki_repo`. If the TXT record doesn't exist, revert to example 1.

3. Query DNS for a service record `_munki._tcp.example.com`. If no SRV record exists, try querying DNS for a TXT record for `munki.example.com`. Parse the TXT record for `repo` and set `SoftwareRepoURL` according.

Other random notes/thoughts:
- SRV record port number could define pointing to http or https
- SRV records have the potential for load balancing without the need for setting up a load balancer
- SRV records have the potential for sites and/or fail over (see Puppet config/example)

*Disclaimer: I wrote this before bed and without any caffeine left in my system. I may have missed a few details somewhere.

**Comment by gregneagle** [comment]
"I believe that grabbing the dns_domain_of_current_host is going to have unintended negative side affects. This has the potential to "hard code" a FQDN with a domain name that could potentially be wrong."

Only if there is a server at https://munki.incorrect_domain_name. Remember we're going to _not_ use .local if that's the current domain name: https://github.com/munki/munki/issues/833#issuecomment-362377994

"The benefit of it not being a FQDN today is that the OS will automatically append domain suffixes from the search domains that it receives from DHCP via options 15 (DNS domain suffix) and/or 119 (DNS domain search list). "

That is precisely something we want to avoid. If the "saved" `SoftwareRepoURL` is `https://munki/repo` I can hijack your machine and have it talk to _my_ Munki server if you are on the same network as me by hosting an https server at "munki". This is the _same_ problem as always using `http://munki/repo` as the `SoftwareRepoURL` --  it's just a little more difficult to spin up an https server with a valid cert.

This could even be unintentional  and not malicious, but the result is still undesired.

"I'd like to offer another potential option to be considered in parallel to this; make use of [...] DNS SRV records"

Contributions welcome (I don't have the interest in coding and testing such an implementation), but again this would be used _only_ for an initially unconfigured client; once a successful Munki session occurred Munki would need to "hard-code" what it discovered, or you have yet another way to hijack clients that don't set `SoftwareRepoURL`.

**Comment by gregneagle** [comment]
I started looking at actually _implementing_ this proposal. To do it "correctly" (for my definition of "correctly") will be non-trivial. Since I personally don't actually _need_ this functionality, I can't promise it will be implemented any time soon.

**Comment by majorsl** [comment]
I like it a lot, but I'd just point out that I (and possibly others) followed the [Demonstration Setup](https://github.com/munki/munki/wiki/Demonstration-Setup) guide and as a result our default repos are actually munki.<dns_domain_of_current_host>/munki_repo

I don't know if you'd consider checking of that path as well, or if that would muddy things too much. At least give that guide a tweak.

**Comment by gregneagle** [comment]
@majorsl The Demonstration Setup is _not_ a guide to production deployment. It only covers setting up a Munki server on localhost.  Choices were made to make the Demo Setup as easy and understandable as possible but those same choices are not necessarily good for production deployment.

**Comment by gregneagle** [comment]
A stab at implementation: https://github.com/munki/munki/commit/975d2b1f362056ad66d8d998e57d8a6305041a64

**Comment by gregneagle** [comment]
If you'd like to test, please use this build from the the Munki3dev branch (or a later build): https://munkibuilds.org/_branches/Munki3dev/3.3.0.3510/

**Comment by gregneagle** [comment]
This will be part of the Munki 3.3 release.
