### ISSUE TITLE
Disable High Sierra APFS

### ISSUE THREAD

**Issue by slchd** [munki/munki#836]
Now that Munki 3 supports MacOS High Sierra import directly, would it be possible to add an option not to convert volume to APFS. I still have machine with SSD that we don’t want to convert.

Thanks

**Comment by arubdesu** [comment]
Hey there, this is already implemented and documented.
https://github.com/munki/munki/wiki/macOS-Installer-Application-support#munki-31-changes

**Comment by slchd** [comment]
Thanks for the info.
