### ISSUE TITLE
Munki trying to install package but only if checked through the UI

### ISSUE THREAD

**Issue by DP19** [munki/munki#840]
I have a package that has an install check script that looks like this:

#!/bin/bash
if [ $(yarn -version) == '1.3.2' ];
then
	exit 1
else
	exit 0
fi

This runs successfully and if the user has it installed and it's the right version it will showed as installed but only when you do a manual check with:
sudo managedsoftwareupdate -v

if you check through Managed Software Center is says it needs to be installed. I've made this install check to echo "no install" or "install" and run it with sudo, it yields the same result, it shows as installed. Not sure why it's doing something different with the ui vs the command line.

**Comment by gregneagle** [comment]
GitHub issues are not a general support channel for Munki. Please post your issue on the Munki-discuss mailing list.
