### ISSUE TITLE
try..except block in 'makecatalogs' not compatible with python >= 3.x

### ISSUE THREAD

**Issue by jsilverman-blispay** [munki/munki#841]
This probably affects all the try..catch blocks.

After installing Python3 via Homebrew, makecatalogs stops working with the following error:

      File "/usr/local/munki/makecatalogs", line 62
       except munkirepo.RepoError, err:
                              ^
      SyntaxError: invalid syntax

**Comment by gregneagle** [comment]
The Munki tools are not supported under Python 3.
