### ISSUE TITLE
Computer HostName containing Unicode characters and no ClientIdentifier error out

### ISSUE THREAD

**Issue by sphen13** [munki/munki#844]
Had a fresh 10.13.3 machine today that was set up in the way of a typical Apple laptop.  The host name ended up being: "Admin’sMacBookPro" with a curly quote in it.  If we do not specify a ClientIdentifier for munki so that it will grab the serial numbered manifest, this ends up choking on the non-standard character:

`    No client id specified. Requesting Admin’sMacBookPro...
ERROR: Unexpected error in updatecheck:
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 1129, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 853, in main
    client_id=options.id.decode('UTF-8'))
  File "/usr/local/munki/munkilib/updatecheck/core.py", line 77, in check
    mainmanifestpath = manifestutils.get_primary_manifest(client_id)
  File "/usr/local/munki/munkilib/updatecheck/manifestutils.py", line 164, in get_primary_manifest
    manifest = get_manifest(clientidentifier, suppress_errors=True)
  File "/usr/local/munki/munkilib/updatecheck/manifestutils.py", line 91, in get_manifest
    manifestbaseurl + urllib2.quote(manifest_name.encode('UTF-8')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 5: ordinal not in range(128)
`

**Comment by sphen13** [comment]
Latest 3.2.0 release of munkitools

**Comment by gregneagle** [comment]
See if this https://github.com/munki/munki/commit/332212bfcefa70b8e6c09c5a883778650c0ab28c fixes it for you.

**Comment by gregneagle** [comment]
Closing as fixed via https://github.com/munki/munki/commit/332212bfcefa70b8e6c09c5a883778650c0ab28c
