### ISSUE TITLE
category logic should be == and not in

### ISSUE THREAD

**Issue by erikng** [munki/munki#845]
As discussed on Slack, there is a bug in the logic of categories, where if category contains part of the word in another category, the item will show up.

Example:
- Xcode in `IDE` category
- VLC in `Video` category

In this case the `Video` category will be correct, but the `IDE` category will contain both Xcode and VLC. https://github.com/munki/munki/blob/master/code/apps/Managed%20Software%20Center/Managed%20Software%20Center/mschtml.py#L344-L346

**Comment by gregneagle** [comment]
Fixed by #846.
