### ISSUE TITLE
Unable to edit Package description

### ISSUE THREAD

**Issue by SinoMunki** [munki/munki#852]
How can I edit a package description ?

I tried to do so in "catalogs/production" and "pkgsinfo/packagename" under the  <key>description</key> section but nothing changed when I reloaded the Application Center.

Any suggestions ?

**Comment by SinoMunki** [comment]
I saw that I had to rebuild my package, but how can I do it ?

**Comment by gregneagle** [comment]
This is a place to report code issues with Munki and not a general support forum. To post this issue you had to delete text telling you where to get support. Where to get support is also described in the wiki.

**Comment by gregneagle** [comment]
https://github.com/munki/munki/wiki#where-to-go-for-more-info-and-help  
https://github.com/munki/munki/wiki/Troubleshooting#still-stuck  
(and a hint for your issue: https://github.com/munki/munki/wiki/Makecatalogs)
