### ISSUE TITLE
Contextual Menu 'Copy Link' command produces 'file://' URL

### ISSUE THREAD

**Issue by wildeep** [munki/munki#858]
In MSC.app, you can control-click on the title of an entry to produce a contextual menu. One of the commands in the menu is 'Copy Link'.

The current behavior is that "file:///Users/<username>/Library/Caches/com.googlecode.munki.ManagedSoftwareCenter/html/detail-<URL encoded package name>.html" is copied to the clipboard.

It might be more useful if these were 'munki://'-style links instead.

More info on munki's custom protocol links here: https://github.com/munki/munki/wiki/Munki-Links

**Comment by gregneagle** [comment]
I agree, but looks difficult to implement. I’d accept a PR (which should also fix the other issues with that contextual menu) but I’m unlikely to spend time on this any time soon

**Comment by gregneagle** [comment]
This is addressed in the new MSC.app included with the Munki 3.6 preview releases.
