### ISSUE TITLE
attempted to do a managedsoftwareupdate- got the following error "AttributeError: 'module' has no attribute 'Memoize' any suggestions please

### ISSUE THREAD

**Issue by TerryOR** [munki/munki#860]
The code issues section is not a general help and troubleshooting forum.

https://github.com/munki/munki#get-help  
https://github.com/munki/munki/wiki#where-to-go-for-more-info-and-help  
https://github.com/munki/munki/wiki/Troubleshooting#still-stuck  

Please use the code issues section for reporting reproducable issues with the code or to propose/request new features.
But before you do, consider bringing up the topic for discussion on the munki-dev list: http://groups.google.com/group/munki-dev

**Comment by gregneagle** [comment]
Suggestion:  reinstall the Munki tools and restart. If you need more assistance please post on the Munki-discuss list.

**Comment by TerryOR** [comment]
oK Ill try that many thanks for the quick response
