### ISSUE TITLE
Need to add add Mojave SUS catalog to list of default catalogs

### ISSUE THREAD

**Issue by dcoobs** [munki/munki#861]
We're seeing the following error messages on 10.14 clients:

`No default Software Update CatalogURL for: 10.14`

I believe the 10.14 SUS catalog needs to be added to the list of default catalogs.

**Comment by gregneagle** [comment]
Ah, good catch. I don't point to Apple's sucatalogs and so had not noticed this. Good thing all the people testing Munki against Mojave betas reported this...

**Comment by gregneagle** [comment]
Addressed here: https://github.com/munki/munki/commit/611050eb38b8089a17ec2450d89fabe3e6e31bd5
