### ISSUE TITLE
warning - osinstaller.py using `--applicationpath` option

### ISSUE THREAD

**Issue by pmamberti** [munki/munki#864]
While installing 10.14 using munki I noticed the following warning in the log:

```
Sep 25 2018 12:48:01 +0100     Mounting disk image Install_macOS_10.14-18A391.dmg
Sep 25 2018 12:48:07 +0100     WARNING: "--applicationpath" is deprecated in macOS 10.14 and greater. Please remove it from your invocation.
Sep 25 2018 12:48:09 +0100     Preparing to run macOS Installer...
Sep 25 2018 12:48:13 +0100     Preparing: 0.2%
```

The `--applicationpath` option is not needed and has been deprecated should be removed from the `startosinstall` command in osinstaller.py: https://github.com/munki/munki/blob/f438b5def97f750a66fd058589bdf0dad092a4c9/code/client/munkilib/osinstaller.py#L265

**Comment by gregneagle** [comment]
This was actually already addressed in the Munki3dev and swift apps branches (and I forgot this fact), will be addressed in the next release of the Munki tools. Current behavior still _works_ as the warning is just that.
