### ISSUE TITLE
makepkginfo --mode converts mode to lowercase

### ISSUE THREAD

**Issue by bochoven** [munki/munki#866]
While trying to fix the permissions on an Application bundle (Opera) by adding the `--mode go+rX` option to the `mkpkginfo` command line tool, I noticed that the permissions are lowercase in the resulting .plist file.

Looking in the sources I noticed that there is a `lowercase()` statement in the `check_mode()` function

https://github.com/munki/munki/blob/master/code/client/munkilib/admin/pkginfolib.py#L713

This prevents the uppercase `X` being recorded correctly. I would send a PR to remedy this, but I can't oversee the consequences of removing the `lowercase()` invocation.

**Comment by gregneagle** [comment]
Not at all sure I understand the original reasoning behind converting to lowercase...
