### ISSUE TITLE
Munki Pseudo dark mode logic is somewhat inaccurate

### ISSUE THREAD

**Issue by erikng** [munki/munki#868]
When testing psuedo dark mode on 10.13.6, I noticed it did not work. After playing around with the code in mschtml.py, I think I know why

```
def interfaceStyle():
    '''Returns "dark" if using Dark Mode, otherwise "light"'''
    # running under Mojave or later or undocumented pref is set
    if (int(os.uname()[2].split('.')[0]) >= 18 or
            NSUserDefaults.standardUserDefaults().boolForKey_("AllowDarkModeOnUnsupportedOSes")):
        interfaceType = NSUserDefaults.standardUserDefaults().stringForKey_("AppleInterfaceStyle")
        if interfaceType == "Dark":
            return "dark"
    return "light"
```

Since it hits the `interfaceType` check, it will never actually return dark mode as this key doesn't exist in pre-Mojave.

If we rewrite the code to this, it fixes the issue.

```
def interfaceStyle():
    '''Returns "dark" if using Dark Mode, otherwise "light"'''
    # running under Mojave or later or undocumented pref is set
    if int(os.uname()[2].split('.')[0]) >= 18:
        interfaceType = NSUserDefaults.standardUserDefaults().stringForKey_("AppleInterfaceStyle")
        if interfaceType == "Dark":
            return "dark"
    elif NSUserDefaults.standardUserDefaults().boolForKey_("AllowDarkModeOnUnsupportedOSes"):
        return "dark"
    return "light"
```

**Comment by gregneagle** [comment]
Works fine as-is here on 10.13.6. I think you misunderstand the preference: it is “Allow...” and not “Use...” or “Enforce...”. See the original email thread.

**Comment by gregneagle** [comment]
https://groups.google.com/d/msg/munki-discuss/yZkn6bEAQoc/0cL8ugqbBAAJ

"For this build at least, MSC.app will adjust the appearance inside the web view to a darker style if you select "Use dark menu bar and Dock" in System Preferences->General on those older OSes. Those older OSes don't change the standard Apple controls (window chrome, buttons, etc) so you don't get the full effect, but you can see the webview changes at least."

Setting the AllowDarkModeOnUnsupportedOSes preference to true then causes MSC.app to pay attention to  "Use dark menu bar and Dock" in System Preferences->General. It does not, by itself, cause the UI style to be Dark Mode.

**Comment by erikng** [comment]
Oh got it! Yes I guess I missed that part in the original email. I had briefly remembered you describing this key, and googled it yesterday, then hit this issue.
