### ISSUE TITLE
Managed Software Center retains initial view

### ISSUE THREAD

**Issue by anewhouse** [munki/munki#869]
If you open the Managed Software Center, click in to an application's details, then click the Back button it goes back to the initial view it showed when it was first launched. It doesn't show changes that have been made while the MSC was open such as switching from dark mode to light mode, and changing the display name or category of an application.

You can reproduce it with the following:

1. Open the Managed Software Center
2. Change the display name of an application in the repo and/or toggle macOS dark mode
3. Click on an application name to view the details
4. Click the Back arrow in the top-left
5. The MSC will not show any of the changes made during step 2 - it will show the old name of the application and/or the wrong color scheme for the display mode that macOS is in. It does show the changes if you switch to another section such as Categories and then back.

**Comment by gregneagle** [comment]
A quick test seems to indicate it (the dar mode glitch) does _not_ occur in MSC 5.x, part of the munkitools 3.6 previews

**Comment by gregneagle** [comment]
This is fixed in the 3.6.0 release (except under 10.10, where the underlying WKWebView cache is inaccessible via public APIs)
