### ISSUE TITLE
Swift MSC Log window doesn't follow LogFile Preference.

### ISSUE THREAD

**Issue by weswhet** [munki/munki#883]
I have a custom LogFile Preference set via a profile. If you hit CMD+L to view to log file in MSC it displays the default file path. 

![screen shot 2018-12-05 at 10 33 51 am](https://user-images.githubusercontent.com/6865785/49535734-b0752a80-f879-11e8-9152-df41d2188e36.png)

**Comment by gregneagle** [comment]
Is that different behavior than the PyObjC apps? (Either way it's a bug to be addressed)

**Comment by weswhet** [comment]
Yeah, PyObjC apps worked as intended. In MSC and at the login window. About to test login window for Swift.

**Comment by weswhet** [comment]
Loginwindow log file works as intended.

**Comment by gregneagle** [comment]
Ha:
https://github.com/munki/munki/blob/Munki3dev/code/apps/Managed%20Software%20Center/Managed%20Software%20Center/Controllers/LogViewController.swift#L118-L119

**Comment by weswhet** [comment]
Oh that’s hilarious.

**Comment by gregneagle** [comment]
logFilePref() was never implemented.

**Comment by gregneagle** [comment]
Fixed here: https://github.com/munki/munki/commit/b6fb9cbb7f488597f2774e5e2f4848a945d7f5c9
