### ISSUE TITLE
MSC 5.x does not sort "My Items" alphabetically

### ISSUE THREAD

**Issue by kevinmcox** [munki/munki#888]
Previous versions of Managed Software Center sort the _My Items_ tab in alphabetical order.

5.1.0.3668 from 3.6 DP2 is not applying this sort.

**Comment by gregneagle** [comment]
https://github.com/munki/munki/blob/Munki3dev/code/apps/Managed%20Software%20Center/Managed%20Software%20Center/mschtml.swift#L589

**Comment by gregneagle** [comment]
Addressed here: https://github.com/munki/munki/commit/2f8f4274ab468f7674fe8f600cc30ea5d2ac8170

**Comment by kevinmcox** [comment]
Thanks Greg.
