### ISSUE TITLE
3.6DP2: Notification results in "no application set" error

### ISSUE THREAD

**Issue by kevinmcox** [munki/munki#890]
I'm seeing the attached error under macOS 10.13.6 when clicking the notification window.

Clicking the Details button closes the notification before the error pops up, while clicking the main body area of the notification leaves it on screen while producing the error.

![munki notification](https://user-images.githubusercontent.com/25358601/49881915-0fe0b680-fdf5-11e8-9486-d93cf6376cdf.png)

**Comment by gregneagle** [comment]
Is this reproducible on more than one machine, or just a messed-up LaunchServices database on this one machine?

what happens in a Terminal when you type `open munki://updates`?

**Comment by gregneagle** [comment]
Ah, for me `open munki://updates` launches an older version of MSC.app I happen to still have somewhere...

**Comment by kevinmcox** [comment]
I've only tested it on two computers with the same results, I can bring more into the mix if needed.

Results (on both) are: `The file /Users/kevinc/Desktop/munki:/updates does not exist.`

**Comment by kevinmcox** [comment]
Based on discussion in Slack with @poundbangbash and an lsregister dump it looks like the `CFBundleURLTypes` are not getting set in the LaunchServices database.

**Comment by gregneagle** [comment]
`munki:/updates` is not `munki://updates` but that's not the ultimate issue here.

**Comment by kevinmcox** [comment]
`kevinc$ open munki://updates`
`The file /Users/kevinc/Desktop/munki:/updates does not exist.`

**Comment by gregneagle** [comment]
Seems to work as expected in current Munki3dev branch.
