### ISSUE TITLE
3.6DP2: MSC app only shows icon badge when open

### ISSUE THREAD

**Issue by kevinmcox** [munki/munki#891]
Under MSC 5.1.0.3668, the Managed Software Center application icon in the Dock is only showing the badge indicating pending updates when the application is open.

Closing the app removes the badge unlike in MSC 4 where it is displayed wether the application is open or not.

![msc badge](https://user-images.githubusercontent.com/25358601/49962840-fc5c4b00-fedb-11e8-9186-7e70b931e3f2.png)

**Comment by gregneagle** [comment]
I can confirm that the DockTile plugin does not seem to be working as expected.

**Comment by kevinmcox** [comment]
Thanks, I'm happy to test any possible fixes if needed.

**Comment by gregneagle** [comment]
Even more useful would be to find any documentation on _debugging_ DockTile plugins...

**Comment by gregneagle** [comment]
Oh crap I bet I know what's going on...

**Comment by gregneagle** [comment]
If you can build and test this version: https://github.com/munki/munki/commit/dbf1b560c8f78e4d5e0b1ba50d0742862ecf5aac that would be helpful!

**Comment by gregneagle** [comment]
Did not address it here. :-(

**Comment by gregneagle** [comment]
I take that back. It works. Once installing the new MSC.app you have to do one of: 1) log out and back in, or 2) Remove MSC.app from the Dock and re-add it.
