### ISSUE TITLE
Precache does not precache OS upgrades

### ISSUE THREAD

**Issue by aysiu** [munki/munki#896]
Precaching does not work for OS upgrades.

Discovered in this Munki-Discuss thread: https://groups.google.com/forum/#!topic/munki-discuss/WlDkz8KoyTQ

Because Munki sees it as an update for something already installed, it's not like the other optional installs. My bad for not testing it with an OS upgrade—I'd just been trying it out for some other large downloads and both with and without OnDemand.

**Comment by aysiu** [comment]
That said, I couldn't replicate the issue of precaching not working in MSC. I had a precached item, deleted it, started up MSC, checked for updates, and it re-downloaded the item to the cache.

**Comment by aysiu** [comment]
This issue may be addressed in Greg's commit: https://github.com/munki/munki/commit/0850f95a44aae5311eed0944e72ad853eab721e5

**Comment by aysiu** [comment]
Greg already did one test, but I can do a second confirmation that this error message appears if you try to use MSC to get the precache of the OS upgrade:
```
Update check failed
There is a configuration problem with the managed software installer. The process ended unexpectedly. Contact your systems administrator
```

This does not, however, happen for regular precache not-yet-installed optional installs—only for the precache OS upgrades.

**Comment by gregneagle** [comment]
Before that commit, items that were installed but needed updates were not precached. (IOW, this was not limited to OS upgrades, but did affect OS upgrades) I believe it _is_ addressed in that commit.

**Comment by aysiu** [comment]
Yes, that commit fixes optional (as opposed to managed) updates not being precached when the `precache` key is in place. But the first time it's run, the update check failed error appears in MSC, even if the download precaches successfully.

There is, however, no error in MSC for the optional items that aren't updates but are still marked as `precache`.

**Comment by gregneagle** [comment]
Seeing the error (or not) is related to the _size_ of the download (or more accurately, how long the download takes to complete. It is not related to whether or not the item is an update. The update check failed error is a _seperate_ issue from this one.

**Comment by gregneagle** [comment]
(I can replicate the error with, for example, an Xcode item set to precache. Xcode is huge and takes a long time to download; even longer than a macOS install.)

**Comment by aysiu** [comment]
So this issue is taken care of with that commit.

But perhaps there should be another issue just on extra large precache items? The precache items I've been testing have been large but still under 2 GB.

**Comment by gregneagle** [comment]
Yes. That is why I said the MSC error dialog is a _seperate_ issue.

**Comment by gregneagle** [comment]
Closing this.
