### ISSUE TITLE
Precaching doesn't have access to PackageCompleteURL key

### ISSUE THREAD

**Issue by arubdesu** [munki/munki#901]
We commonly put large items in cloud storage buckets and leverage PackageCompleteURL, which was not being added to InstallInfo.plist and therefore 404'ing when /usr/local/munki/precache_agent runs munkilib/updatecheck/download.py's cache() function. I'm waiting for the US/legal to follow up regarding the CLA, but the fix was to add that key to the array here:
https://github.com/munki/munki/blob/c2ced7cfe665aa12b9b9311efbb99e91bea1b790/code/client/munkilib/updatecheck/analyze.py#L235-L236

**Comment by gregneagle** [comment]
I want to do a RC of 3.5.2 very soon. Do you think the CLA will happen soon, or should I just recreate your fix?

**Comment by arubdesu** [comment]
Please recreate, pardon. Thanks

**Comment by gregneagle** [comment]
Looking at lines 249-257. Do your items with PackageCompleteURL _also_ have installer_item_location? And what about PackageURL? Shouldn't we fix this for all of these variations?

**Comment by gregneagle** [comment]
@arubdesu -- can you see if 
https://github.com/munki/munki/commit/c34d17604d10d4d4a35b243bb56a8b8e45f9444a addresses this issue?
