### ISSUE TITLE
Bug: Period in munki:// Links Not Handled Correctly

### ISSUE THREAD

**Issue by splemp** [munki/munki#903]
When creating munki:// links as documented in the wiki, items with periods in the name do not behave as expected. 

Scenario: 
- Open Terminal and run `open munki://detail-org.mozilla.firefox` where org.mozilla.firefox is a valid munki item

Expected Results: 
- MSC opens to appropriate page

Actual Results:
- MSC opens to the currently open page
- If the item simply isn't an available optional install, you actually get an error page

Workaround: 
- It is possible to add .html to the end of the link to get the expected behavior

Solution:
- Document this behavior, or
- Modify code

I'm not currently able to provide any help resolving this, but I'm creating this issue for general awareness.
munki-discuss discussion: https://groups.google.com/forum/#!topic/munki-discuss/vvxDp-D0K7Q

**Comment by gregneagle** [comment]
Addressed here: https://github.com/munki/munki/commit/e68ece8ec1ab467fc90f9aaca28b239b4bd495d2
will be in next 3.6 release candidate (likely early next week). (Or build it yourself to test today)

**Comment by splemp** [comment]
Looks like it works great. Thanks!
