### ISSUE TITLE
Package name can not end in a number

### ISSUE THREAD

**Issue by cfxegbert** [munki/munki#908]
`munkiimport --subdirectory=apps/maxon --icon_path="/Volumes/Installer R20.028 Web MAC/bin/MAXON-Inst.app/Contents/Resources/c4dapp.icns" -name=Cinema4D_R20 --displayname="Cinema4D R20" --description="Cinema4D R20" --autoremove --unattended_install --unattended_uninstall --developer=MAXON --category=Desktop --catalog=development --catalog=production Cinema4D_R20.pkg`

I end up with the file pkgsinfo/apps/maxon/Cinema4D_R-20.030 and I expect pkgsinfo/apps/maxon/Cinema4D_R20-20.030.  The package name within the pkginfo file is
 `       <key>name</key>
        <string>Cinema4D_R</string>`

The reason this is needed this is we install several major versions of Cinema4D on the same machine.

**Comment by gregneagle** [comment]
pkgsinfo file names don't matter at all -- clients never see them.

`-name=Cinema4D_R20` should be `--name=Cinema4D_R20`, and that change might address your immediate issue, though it feels like there are other issues hiding below that one.

**Comment by gregneagle** [comment]
`-name=Cinema4D_R20`, since it has a single hyphen, is being interpreted as the `-n/--nointeractive` option to `munkiimport`.  And then the name is being extracted/derived from the pkg. Normally, without the `-n/--nointeractive` option, you'd see it listed with an opportunity to modify it, but with that option, it just charges ahead.

So again, changing that bit to `--name=Cinema4D_R20` most likely will address your issue. You may or may not want to add `-n` as well, depending on whether or not you expect some interactivity.

**Comment by gregneagle** [comment]
A demo:
```
% munkiimport --subdirectory=apps/maxon --name=Cinema4D_R20 --displayname="Cinema4D R20" --description="Cinema4D R20" --autoremove --unattended_install --unattended_uninstall --developer=MAXON --category=Desktop --catalog=development --catalog=production ~/Downloads/some_fake_Cinema4D_R20.pkg 
           Item name: Cinema4D_R20
        Display name: Cinema4D R20
         Description: Cinema4D R20
             Version: 20
            Category: Desktop
           Developer: MAXON
  Unattended install: True
Unattended uninstall: True
            Catalogs: development, production

Import this item? [y/n] n
```
In this example it might not be correctly detecting the version number and I might have to manually override it, which could be done interactively, with the `--pkgvers` option, or afterwards by editing the generated pkginfo.

I'm going to close this; if there are additional related issues here, feel free to reopen or create a new issue.
