### ISSUE TITLE
[FR] manually set catalogs for one run of managedsoftwareupdate

### ISSUE THREAD

**Issue by nathanperkins** [munki/munki#909]
For the purposes of testing relatively new packages and preparing new machines with fresh software, I find that I'm sometimes having to switch a machine's primary manifest from our "production" catalog to "testing" for one run of managedsoftwareupdate. Once that run is done, I switch it back to production so the machine isn't continually subjected to packages that are in test.

Our munki repo is checked in through git and manually pushed to a server when ready so these little changes are a little time-consuming to put in and clutter up the repo history.

The tool already has a neat feature `--id=manifest` to set a different primary manifest for one run of munki. Is there any interest in providing a similar feature for catalogs which would overwrite the catalogs for one run of munki?

I imagine it would look something like this:

```managedsoftwareupdate --catalogs=catalog1,catalog2,etc```

**Comment by nathanperkins** [comment]
Would you mind if I implement this and submit a pull request?

This is a brief description of the changes I think would be needed from a quick scan of the code related to the `--id` feature.

`client/managedsoftwareupdate`
- Add `--catalogs` to config options with default of `''` and help of `Comma-separated list of catalogs for this run only.`
- Add `opt_catalogs=options.catalogs.decode('UTF-8').split(',')` to `updatecheck.check()` around line 860.

`client/munkilib/updatecheck/core.py`
- Add `opt_catalogs=[]` to `check()` args.
- In `check()`, wherever there is `cataloglist = manifestutils...` replace with `cataloglist = opt_catalogs or manifestutils...`

**Comment by gregneagle** [comment]
At this time, I would not be interested in adding such a feature.

**Comment by nathanperkins** [comment]
Is it something you'd reject if I put in a PR?

**Comment by gregneagle** [comment]
Yes, it not a PR I would accept at the current time.

catalogs are elements of manifests.

Why not also support `--managed-installs` and `--managed-uninstalls`, etc, etc, for all the supported manifest elements?

Additionally, included manifests can include catalogs (even if this is not generally recommended). It's not clear what the expected/desired behavior should be if you specified `--catalogs`...

**Comment by arubdesu** [comment]
I just always switch it server-side, but then again I have to deal with a lot of clients (more testers the better) and have plenty of hardware. I'm understanding the repeated toggling of this, but the value proposition does seem like a hard sell. That you know about the `--id=manifest` capability and you  can specify catalog in a manifest makes me wonder why you don't set the catalog in that 'one-off' manifest to achieve a similar result? I could be missing something...

**Comment by nathanperkins** [comment]
Thanks for your responses. I understand this might not be something that everybody finds valuable but I want to be an advocate for it because I think it could really help with testing packages without mucking up the repository with primary manifest changes that are only meant to be applicable for one munki run.

The behavior would be similar to what is found with `--id`. If you specify `--catalogs=testing`, then the only catalog would be `testing`. Munki would not check any manifests to determine what catalogs should be included, it would just be the ones specified in the argument.

As an example of a use case where this would have helped me out, I was having problems with AD binding failing to provide admin access on some machines. I was working on a prototype AD binding package adjustment to fix the issue and wanted to deploy it on freshly imaged machines and any machines where the AD bind was having issues.

Without this feature, I had to switch catalogs on these machines from "production" to "testing" and back to "production" on the backend, which only two admins have access to and requires a git commit + push + server update for each change. With this feature, I would have been able to advise our lower level techs that they can run `sudo managedsoftwareupdate --catalogs=testing` and report any issues back to me.

As another example, we've had some instances where a user has an issue with software that is supposedly fixed in a newer version, but the package isn't quite trusted enough for production. This would allow us to easily upgrade the user without the typical required backend changes.

Keep in mind that in our environment, we have an "unstable" catalog which is completely untested, "development" which is suitable for IT and very targeted testing, "testing" which is trusted enough for about 15-25% of our staff and "production" which is trusted for everything.

@arubdesu I read about that workaround in Slack and it could work, but also requires a bunch of backend changes and cluttering up the repo with a bunch of extra manifests for specific manifest + catalog combination, or catalog + package. I would love to avoid these backend changes because those fall on 1 or 2 people, where a command-line option could be used by any of the IT support staff.

**Comment by nathanperkins** [comment]
@gregneagle with regards to the `--managed_installs` and `--managed_uninstalls`, I see a lot of value in that as well.

Just like the examples above, `--managed_installs` would allow our support staff to install specific packages outside the normal manifests as needed to respond to certain requests or incidents, without requiring backend changes.

`--managed_installs` could also be used in conjunction with `--catalogs` for very targeted testing of packages that are still in development, without backend changes.

I'd be interested in exploring the idea more and even implementing it myself :)

**Comment by gregneagle** [comment]
You did not address "Additionally, included manifests can include catalogs (even if this is not generally recommended). It's not clear what the expected/desired behavior should be if you specified `--catalogs`..."

This would be an important implementation detail.

IOW, does --catalogs override the catalog list for the primary manifest only? or does it override all catalog lists in all included manifests? If the latter, this might have unexpected/undesired effects, as directly changing the catalog list in the primary manifest does _not_ affect the catalog list in included manifests.

If the former, it complicates this bit:

  `client/munkilib/updatecheck/core.py`

  * Add `opt_catalogs=[]` to `check()` args.
  * In `check()`, wherever there is `cataloglist = manifestutils...` replace with `cataloglist = opt_catalogs or manifestutils...`

**Comment by gregneagle** [comment]
Munki is designed around the idea that you declare (and document!) desired state by authoring a manifest. "on-the-fly" --managed-installs and --managed-uninstalls is counter to that design. And anyone with local root or sudo privs can now install anything at all that's in your repo.

`sudo managedsoftwareupdate --managed-installs SomeExpensiveSoftwareThatWasntApproved`

I'm unconvinced that this would be a good idea.

**Comment by gregneagle** [comment]
_You've_ chosen/designed it to make it hard to update things on the server side.
Here, anyone on the help desk can navigate to MunkiWebAdmin2, add the testing catalog to a machine, run Managed Software Center (or ssh into a machine and run managedsoftware update), or advise the user to run MSC.app. It's fast and easy, and logged as git changes.

**Comment by nathanperkins** [comment]
> You did not address "Additionally, included manifests can include catalogs (even if this is not generally recommended). It's not clear what the expected/desired behavior should be if you specified `--catalogs`..."

There would be no further searching for catalogs. It would use whatever is given in `--catalogs`  and that would be the end of it. 

If some org has a repo structure where this would cause undesired effects, they're already going against the recommendations to only have catalogs in the primary manifest, right? I don't know a lot about situations where it would be valid or recommended to have catalogs in an included manifest so I'm not sure how it would run counter to expectations or cause negative effects for `--catalogs` to override the catalogs scanning process entirely.

> Munki is designed around the idea that you declare (and document!) desired state by authoring a manifest. "on-the-fly" --managed-installs and --managed-uninstalls is counter to that design. And anyone with local root or sudo privs can now install anything at all that's in your repo.

>No audit trail except possibly local logs (which are also easy to delete)

Fair, don't all these apply to the `--id` command as well? I just thought this and `--managed_installs` would be a natural extension of that feature.

>sudo managedsoftwareupdate --managed-installs SomeExpensiveSoftwareThatWasntApproved

Also fair but `--id` allows similar stuff, right?

> _You've_ chosen/designed it to make it hard to update things on the server side.
Here, anyone on the help desk can navigate to MunkiWebAdmin2, add the testing catalog to a machine, run Managed Software Center (or ssh into a machine and run managedsoftware update), or advise the user to run MSC.app. It's fast and easy, and logged as git changes.

Still working on improving this part of our setup. It's not always easy to find the time to get perfect infrastructure in place. Ideally we're going to automate some more of this but it's going to take time that my team finds difficult to find :(

**Comment by gregneagle** [comment]
`Fair, don't all these apply to the `--id` command as well? I just thought `--catalogs` and `--managed_installs` would be a natural extension of that feature.`

Less so, because a manifest with that id must exist on the server. I guess a user could maybe discover that you were using, say, manifests named after serial numbers, find a machine that has SomeExpensiveSoftwareThatWasntApproved installed, and then use `sudo managedsoftwareupdate --id <SN of machine that has SomeExpensiveSoftwareThatWasntApproved>` in its manifest's managed installs>`.

`--id` was originally designed as a testing and troubleshooting aid. There's an argument for removing it, and you've just made it. But `sudo defaults write /Library/Preferences/ManagedInstalls ClientIdentifier <SN of machine that has SomeExpensiveSoftwareThatWasntApproved>` would also get that result unless you are using configuration profiles to manage ClientIdentifier...

**Comment by nathanperkins** [comment]
Alright, makes sense. I'll close this out.

Thanks for sharing your knowledge and answering my questions.

**Comment by nathanperkins** [comment]
Sorry just one last question. 

I think your last point makes it clear that `--managed-installs` would be a non-starter because it could give a local administrator very easy access to any software on the repo. I agree with that.

I'm not sure we have quite the same issue with `--catalogs` because it would just give the client access to a different pkg version of a pkg the client was already entitled for.

Given that, is it possible that `--catalogs` could be included as a similar testing and troubleshoot aid as `--id`?

**Comment by nathanperkins** [comment]
I see now that this doesn't really fit in the design plan for this project so I will close it out.

Thanks for providing my suggestions and comments with clear and detailed feedback, it is much appreciated :)
