### ISSUE TITLE
Software installation progress doesn't update during preinstall_script phase

### ISSUE THREAD

**Issue by anewhouse** [munki/munki#915]
When installing two pieces of software in the same managedsoftwareupdate run and the second one has a preinstall_script defined, while the preinstall script for the second package is running the Updates tab in the MSC still says "Installing Package One (1 of 2)" - this isn't noticeable in most circumstances because preinstall scripts usually execute quickly but this one had to wait for a LaunchDaemon to unload.

Reproduced in both MSC 4.x and 5.x

**Comment by gregneagle** [comment]
A preinstall script can also be used to tell Munki to skip the install of an item; a non-zero return causes the install to be skipped. I think that was the original thought behind not updating the progress until after the preinstall script completed.

On the other hand, that could lead to "Installing Foo (1 of 3)..." followed by "Installing Baz (3 of 3)..." which is in itself a little confusing, so it probably makes sense to change this behavior in the future release. I won't be slipping this change into the 3.6.0 release (Managed Software Center version isn't really relevant here as it's just displaying what the underlying Munki tools are doing and there is virtually-to-no difference in the command-line tools between 3.5.3 and 3.6.0.)

**Comment by gregneagle** [comment]
This will be addressed after the 3.6 release ships.

**Comment by gregneagle** [comment]
https://github.com/munki/munki/commit/7f0d04d2eff2d0cb662afa300e873af4506181f8 is in the Munki3dev branch.
