### ISSUE TITLE
MSC 3.6 text CSS not transitioning in dark mode

### ISSUE THREAD

**Issue by dcoobs** [munki/munki#917]
We have some list items in our MSC sidebar that are simple text and don't link to anything. They appear fine in light mode but in dark mode, they remain black while all the other text/links transition to white.

MSC 4.8.3628
3.5.3.3640
![screen shot 2019-03-08 at 12 09 17 pm](https://user-images.githubusercontent.com/12276948/54047183-09679e00-419c-11e9-938c-de0bc123b448.png)

MSC 5.1.0.3730
3.6.0.3721
![screen shot 2019-03-08 at 12 27 00 pm](https://user-images.githubusercontent.com/12276948/54047775-9101dc80-419d-11e9-917a-e1409ef54a70.png)

**Comment by gregneagle** [comment]
In order to replicate the issue and hopefully fix it it would be extremely helpful to have your customized files or at least a sanitized/simplified version that demonstrates the issue.

**Comment by dcoobs** [comment]
Let me know if you need anything else

[site_default.zip](https://github.com/munki/munki/files/2947062/site_default.zip)

**Comment by gregneagle** [comment]
Looks like the .css files for the Swift apps had not been kept in sync with those for the pyobjc apps.

I think https://github.com/munki/munki/commit/aed4b4ba1c45ab8d6a1be1d8ad315c694e7b093c addresses this.

**Comment by dcoobs** [comment]
Yes, that seems to have fixed it. Thanks, Greg!
