### ISSUE TITLE
MSC.app: clicking label in toolbar items does not result in any action

### ISSUE THREAD

**Issue by gregneagle** [munki/munki#919]
Clicking a text label for the toolbar item "buttons" (Software/Categories/My Items/Updates) does not cause any action to occur.

Clicking a toolbar item label should switch to the appropriate view, just like clicking on the image does.

I am reasonably certain I fixed this in the past by implementing custom MSCToolbarbarButton and MSCToolbarButtonCell classes, but even MSC.4.8.x shows this behavior.

**Comment by gregneagle** [comment]
Here's the old fix:
https://github.com/munki/munki/issues/381

But it seems no longer functional even in MSC 4.8, at least under Mojave.

**Comment by gregneagle** [comment]
Here's a promising mention of a similar issue, but the site seems to be down:
http://www.cocoabuilder.com/archive/cocoa/191588-non-clickable-nstoolbaritem-label.html

**Comment by tcinbis** [comment]
This may or may not be related to this problem, but the button on the Update site does not start any action. No matter whether it says `Check again`, `Update all`, etc.
Starting the corrsponding action via the command line works fine and the state of the Managed Software Centre is updated accordingly.
This behaviour appeard with the most recent version 5.1.0.3733 for me.

**Comment by gregneagle** [comment]
Almost certainly unrelated, and far more likely to be this:
https://github.com/munki/munki/wiki/Client-Customization#managed-software-center-5munki-36-notes

**Comment by aschwanb** [comment]
I had a look at our issue with @tcinbis. @gregneagle is of course 100% correct. Updating the template fixed our issue.

Thank you for your help.

**Comment by gregneagle** [comment]
closing this as msc.app is undergoing a redesign and this will no longer be relevant.
