### ISSUE TITLE
Persistent 10.14.2 update

### ISSUE THREAD

**Issue by ofirgalcon** [munki/munki#920]
https://macadmins.slack.com/archives/C04QVPFGU/p1551914069321400

**Comment by gregneagle** [comment]
AFAIK, this can affect both 3.5.x and the 3.6 release candidates.

This will not be addressed in the 3.6 release.

If you are concerned about this and want real attention, please add details to this issue and please don't rely on a link to something (especially something that requires people to request access in order to join and read).

**Comment by gregneagle** [comment]
This issue is partially (mostly?) Apple's fault; Munki could be modified to work around it. Some workarounds for now:

1) If you are using reposado or similar, remove the 10.14.2 updates from the branch catalogs offered to your clients.
2) Use `sudo softwareupdate --ignore` to ignore those problematic 10.14.2 updates.

**Comment by ofirgalcon** [comment]
Thanks

Here's what I found:

```defaults read /Library/Preferences/com.apple.SoftwareUpdate RecommendedUpdates

(
       {
       “Display Name” = “macOS 10.14.3 Update”;
       “Display Version” = ” “;
       Identifier = “macOS 10.14.3 Update”;
       “Product Key” = “041-38921”;
   },
       {
       “Display Name” = “macOS 10.14.2 Update”;
       “Display Version” = ” “;
       Identifier = “macOS 10.14.2 Update”;
       “Product Key” = “091-97092”;
   }
)

cat /Library/Updates/index.plist

<?xml version=“1.0” encoding=“UTF-8"?>
<!DOCTYPE plist PUBLIC “-//Apple//DTD PLIST 1.0//EN” “http://www.apple.com/DTDs/PropertyList-1.0.dtd“>
<plist version=“1.0”>
<dict>
    <key>InstallAtLogout</key>
    <array/>
    <key>InstallLater</key>
    <array>
        <string>041-38921</string>
    </array>
    <key>ProductPaths</key>
    <dict>
        <key>041-38921</key>
        <string>041-38921</string>
        <key>091-97092</key>
        <string>091-97092</string>
    </dict>
</dict>
</plist>```

So yes, it looks like an Apple bug.

**Comment by gregneagle** [comment]
Are you in a position to attempt either of the workarounds?

`sudo softwareupdate --ignore "macOS 10.14.2 Update"`

might be the easiest to test.

**Comment by ofirgalcon** [comment]
sudo softwareupdate --ignore "macOS 10.14.2 Update" makes no difference!

**Comment by gregneagle** [comment]
Did you run `sudo softwareupdate -da` afterwards?

**Comment by ofirgalcon** [comment]
No, trying now

**Comment by ofirgalcon** [comment]
```

Software Update Tool

Finding available software

Downloaded macOS 10.14.3 Update
Done.

```

But munki says:    The following Apple Software Updates are available to install:
        + macOS 10.14.3 Update-
           *Restart required
        + macOS 10.14.2 Update-
           *Restart required

**Comment by gregneagle** [comment]
You can view the results of `--ignore` using `defaults read /Library/Preferences/com.apple.SoftwareUpdate InactiveUpdates`

```
% sudo softwareupdate --ignore Foo
Ignored updates:
(
    Foo
)
% defaults read /Library/Preferences/com.apple.SoftwareUpdate InactiveUpdates
(
    Foo
)
```

**Comment by gregneagle** [comment]
And to clear the list:

```
% sudo softwareupdate --reset-ignored
Ignored updates:
(
)
% defaults read /Library/Preferences/com.apple.SoftwareUpdate InactiveUpdates
(
)
```

**Comment by ofirgalcon** [comment]
When using ARD (or munki) I found that the command must be 

```sudo softwareupdate --ignore 'macOS 10.14.2 Update'```

rather than 

```sudo softwareupdate --ignore "macOS 10.14.2 Update" ```

**Comment by gregneagle** [comment]
I don't use ARD, so can't speak to that, but what do you mean when you say "(or munki)"?

**Comment by ofirgalcon** [comment]
Sorry - in a nopkg script

**Comment by gregneagle** [comment]
You would not use `sudo` in a nopkg script, and 

```
#!/bin/sh
/usr/sbin/softwareupdate --ignore "macOS 10.14.2 Update"
```

would work fine.

**Comment by gregneagle** [comment]
(so would

```
#!/bin/sh
/usr/sbin/softwareupdate --ignore 'macOS 10.14.2 Update'
```

)

**Comment by ofirgalcon** [comment]
I found that using " fails and ' works

**Comment by ofirgalcon** [comment]
Now I'm wondering why the 10.14.2 update is 10GB and 10.14.3 is 6GB...

**Comment by gregneagle** [comment]
Interesting, but I am still quite skeptical. (about ' vs ")

**Comment by ofirgalcon** [comment]
This is what was stored when I used "

Ignored updates:
    (
        "10.14.2",
        "\U201cmacOS",
        "Update\U201d"
    )

**Comment by gregneagle** [comment]
You were using curly quotes.

**Comment by ofirgalcon** [comment]
LOL yes, I'm stupid and half blind...

**Comment by gregneagle** [comment]
```
% python -c 'print u"\U0000201c\U0000201d"'
“”
```

**Comment by ofirgalcon** [comment]
I'm definitely seeing a problem with RC7 (not sure when it started) - the cli tools display an OS update, but Managed Software Centre doesn't display it. If other updates are available the user can press Update Now - and then the OS update is installed without warning.

**Comment by ofirgalcon** [comment]
I'm definitely seeing a problem with RC7 (not sure when it started) - the cli tools display an OS update, but Managed Software Centre doesn't display it. If other updates are available the user can press Update Now - and then the OS update is installed without warning.

**Comment by ofirgalcon** [comment]
![image](https://user-images.githubusercontent.com/16665880/54323482-7ee6ca80-45f1-11e9-9479-faeb0ec15bc5.png)

**Comment by ofirgalcon** [comment]
Shall I open a separate issue?

**Comment by gregneagle** [comment]
Yes this would be a separate issue, though quite possibly related if `/usr/sbin/softwareupdate` is giving us unreliable info.

Nothing will likely happen with such an issue without steps to reproduce it.

**Comment by gregneagle** [comment]
Also capture logs!

**Comment by ofirgalcon** [comment]
See https://github.com/munki/munki/issues/921

**Comment by gerardkok** [comment]
Would you mind reopening this? We seem to have a similar issue (i.e. munki suggests the 10.14.2 update, but the laptop is already sunning 10.14.3). Symptoms:
* munki claims there's a 10.14.2 update, snippet from ManagedSoftwareUpdate.log:
```Mar 18 2019 08:35:44 +0100 Checking Apple Software Update catalog...
Mar 18 2019 08:35:44 +0100     Caching CatalogURL https://swscan.apple.com/content/catalogs/others/index-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
Mar 18 2019 08:35:45 +0100     Skipping Apple Software Update check because sucatalog is unchanged, installed Apple packages are unchanged and we recently did a full check.
Mar 18 2019 08:35:46 +0100     **Checking for Apple Update Metadata**
Mar 18 2019 08:35:46 +0100     The following Apple Software Updates are available to install:
Mar 18 2019 08:35:46 +0100         + macOS 10.14.2 Update-
Mar 18 2019 08:35:46 +0100            *Restart required
Mar 18 2019 08:35:46 +0100     Skipping install of macOS 10.14.2 Update because it's not unattended.
Mar 18 2019 08:35:47 +0100 Finishing...
```
(also, is the line '+ macOS 10.14.2 Update-' missing a version number at the end?)
* softwareupdate, however, says not:
```
$ sudo softwareupdate -l
Software Update Tool

Finding available software
No new software available.
```
* there is indeed a 10.14.2 update waiting in /Library/Updates:
```
$ ls -la /Library/Updates/
total 2296
drwxr-xr-x@  6 root  wheel      192 Mar 18 08:25 .
drwxr-xr-x+ 67 root  wheel     2144 Mar 12 15:21 ..
drwxr-xr-x  13 root  wheel      416 Mar  5 13:14 091-97092
-rw-r--r--@  1 root  wheel    41444 Mar 18 08:25 PPDVersions.plist
-rw-r--r--@  1 root  wheel  1124815 Mar 18 08:25 ProductMetadata.plist
-rw-r--r--   1 root  wheel      320 Mar 12 09:52 index.plist
```
Maybe this update was downloaded during MDM installation, or maybe it's part of the image that the laptop came out of the factory with?

At he moment we're only seeing this on new, DEP-enrolled laptops. Our current workaround is to remove the update from /Library/Updates, but because that's under SIP, we need to boot into the Recovery Disk, mount Macintosh HD, and then remove it. After that both softwareupdate and munki agree again that there's no update to be installed.

**Comment by gregneagle** [comment]
"Our current workaround is to remove the update from /Library/Updates, but because that's under SIP, we need to boot into the Recovery Disk, mount Macintosh HD, and then remove it."

Did you see the other two workarounds in earlier comments for this issue?

**Comment by ofirgalcon** [comment]
Or ```softwareupdate --ignore 'macOS 10.14.2 Update'```

**Comment by gregneagle** [comment]
That's one of the other two workarounds, yes.

**Comment by gerardkok** [comment]
The other workarounds did not work:
* we're not using reposado, but instead pulling the updates straight from Apple, so I couldn't remove the update on that side
* we tried ignoring with softwareupdate --ignore, but after a reboot of the laptop, munki claims again that 10.14.2 needs to be installed.

Admitted we've just a small fleet of laptops, so booting into the Recovery Disk and removing the update from there is a workable solution for us in the short term.

**Comment by ofirgalcon** [comment]
I also have one iMac that insists on getting 10.14.2 update - it's already on 10.14.3

**Comment by gregneagle** [comment]
This is an Apple bug that Munki isn't handling well. It's not going to be fixed for the 3.6 release. I have some ideas on how to make Munki handle it better, but those are not likely to be implemented in the near future, especially since I'm not being affected. (I run reposado).

**Comment by gerardkok** [comment]
Ok, I can live with that, especially since I would like to go back to using reposado again (we've recently stopped using it, but this issue shows that there are benefits to using it, so I'll suggest to put it back in again).

**Comment by rickheil** [comment]
﻿If you wish, you can file a radar about this problem duping #47633611. Mine is stuck as requiring a sysdiagnose but we resolved the issue via reposado and cleaning up our small handful of affected machines already so I can’t get one.
