### ISSUE TITLE
RC7 Managed Software Centre not displaying but still installing macOS updates

### ISSUE THREAD

**Issue by ofirgalcon** [munki/munki#921]
I'm definitely seeing a problem with RC7 (not sure when it started) - the cli tools display an OS update, but Managed Software Centre doesn't display it. If other updates are available the user can press Update Now - and then the OS update is installed without warning.

![](https://user-images.githubusercontent.com/16665880/54323482-7ee6ca80-45f1-11e9-9479-faeb0ec15bc5.png)

Logs in next post

**Comment by ofirgalcon** [comment]
```Mar 14 2019 00:31:08 +0000 ### Starting managedsoftwareupdate run: installwithnologout ###
Mar 14 2019 00:31:08 +0000 Starting...
Mar 14 2019 00:31:08 +0000     Performing preflight tasks...
Mar 14 2019 00:31:08 +0000     Munkireport: # Set custom script timeout to 60 seconds
...
Mar 14 2019 00:31:56 +0000     Munkireport: Server info: starting: reportdata
Mar 14 2019 00:31:56 +0000     The following Apple Software Updates are available to install:
Mar 14 2019 00:31:56 +0000         + macOS 10.14.3 Update-
Mar 14 2019 00:31:56 +0000            *Restart required
Mar 14 2019 00:31:56 +0000     Preventing idle sleep
Mar 14 2019 00:31:56 +0000 ### Beginning managed installer session ###
Mar 14 2019 00:31:56 +0000 Processing installs
Mar 14 2019 00:31:56 +0000 Installing Delete Malware (1 of 2)
Mar 14 2019 00:31:56 +0000 Installing Maintenance (2 of 2)
Mar 14 2019 00:31:56 +0000 ###    End managed installer session    ###
Mar 14 2019 00:31:56 +0000     Allowing idle sleep
Mar 14 2019 00:31:56 +0000 Installing available Apple Software Updates...
Mar 14 2019 00:31:57 +0000     Caching CatalogURL https://swscan.apple.com/content/catalogs/others/index-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
Mar 14 2019 00:31:59 +0000 Installing macOS 10.14.3 Update
Mar 14 2019 00:32:47 +0000     Done.
Mar 14 2019 00:32:47 +0000     You have installed one or more updates that requires that you restart your computer.
Mar 14 2019 00:32:47 +0000     Please restart immediately.
Mar 14 2019 00:32:47 +0000     To automate the restart process with softwareupdate(8), use --restart.
Mar 14 2019 00:32:47 +0000 Finishing...
Mar 14 2019 00:32:47 +0000 Saving application inventory...
Mar 14 2019 00:32:53 +0000     Performing postflight tasks...
Mar 14 2019 00:32:53 +0000     Munkireport: # Set custom script timeout to 60 seconds
Mar 14 2019 00:32:53 +0000     Munkireport: # Executing scripts in postflight.d
...
Mar 14 2019 00:32:57 +0000     Munkireport: Server info: starting: installhistory
Server info: starting: reportdata
Server info: starting: appusage
Server info: starting: munkireport
Server info: starting: fan_temps
Server info: starting: managedinstalls
Server info: starting: memory
Server info: starting: smart_stats
Server info: starting: caching
Server info: starting: softwareupdate
Server info: starting: wifi
Server info: starting: usage_stats
Mar 14 2019 00:32:57 +0000 ### Ending managedsoftwareupdate run ###
Mar 14 2019 00:32:57 +0000 Software installed or removed requires a restart.
Mar 14 2019 00:32:57 +0000     Notifying currently logged-in user to restart.```

**Comment by gregneagle** [comment]
There's not really enough info there to make any determinations. I can see that managedsoftwarecenter is installing the macOS 10.14.3 Update, and that it knows it needs to notify the "currently logged-in user to restart". But I don't know how to replicate this, unless ALWAYS when macOS 10.14.3 Update is available this happens.

**Comment by ofirgalcon** [comment]
Steps to reproduce

On a Mac with a pending macOS update and a pending munki update, open Managed Software Centre and check updates. You should see only one update. Press Update.

You should see the macOS update being installed. When finished, an error message appears as shown in pic above.

**Comment by ofirgalcon** [comment]
I saw this happen with a security update too.

**Comment by ofirgalcon** [comment]
I managed to reproduce this - Managed Software Centre screen does NOT show the OS update, but its logs DO.

**Comment by ofirgalcon** [comment]
I deleted Managed Software Centre and installed the one from 3.5.3 and it works OK again. Looks like a bug in RC7 (maybe earlier).

**Comment by ofirgalcon** [comment]
I can confirm that this problem doesn't exist in Managed Software Centre 4.8.3628 but does in 5.1.0.3729

**Comment by ofirgalcon** [comment]
Here are the 2 apps running side by side, v4 is showing an osx update, v5 isn't

![image](https://user-images.githubusercontent.com/16665880/54331009-ef044900-460f-11e9-8c20-60184f46d07d.png)

**Comment by gregneagle** [comment]
Assuming I can reproduce this, this is a blocking issue for the release of Munki 3.6.

**Comment by ofirgalcon** [comment]
I now saw this on at least 4 machines. I reverted them to v4 for now. They are running 10.13 and 10.14.

**Comment by gregneagle** [comment]
I cannot yet reproduce this. If you see it again, please make a copy of of `/Library/Managed Installs/AppleUpdates.plist` (and also `/Library/Managed Installs/InstallInfo.plist` if it does not contain anything sensitive) and send me a copy.

**Comment by ofirgalcon** [comment]
[Archive.zip](https://github.com/munki/munki/files/2964763/Archive.zip)

**Comment by ofirgalcon** [comment]
I have these keys set to TRUE if that's relevant

UnattendedAppleUpdates
InstallAppleSoftwareUpdates

**Comment by gregneagle** [comment]
If I copy those files into /Library/Managed Installs on my machine, here is the result:
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/700560/54332575-06294380-45dc-11e9-884d-d47ea051ba0b.png">

**Comment by gregneagle** [comment]
I can replicate your issue:

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/700560/54333172-b304c000-45de-11e9-8b01-cf4ad48be129.png">

I can replicate it if I do this:
`sudo defaults write /Library/Preferences/ManagedInstalls InstallAppleSoftwareUpdates TRUE`

This sets the value of InstallAppleSoftwareUpdates to the _string_ "TRUE".

I highly suspect that's what you have it set to.

It's defined to be a _boolean_. But if it's a string, Python and Swift treat it differently.

In Python, any non-empty string is treated as "true-ish".
But Swift is more strictly typed, and a string is an error here,  if there's an error, the value is treated as the default, which is false.

So now MSC.app and `managedsoftwareupdate` have conflicting ideas as to what that key is set to.

MSC.app thinks it's false, so it does not display available Apple updates. But when `managedsoftwareupdate` runs, it treats the value of the key as true, and therefore installs the available/pending Apple updates.

You can fix this issue for yourself by setting that key to the correct boolean value:
`sudo defaults write /Library/Preferences/ManagedInstalls InstallAppleSoftwareUpdates -bool TRUE`

I fear this is going to be a not-uncommon error by Munki admins, so I'll need to change the logic when Munki reads the preferences to treat any non-empty strings as boolean true.

**Comment by ofirgalcon** [comment]
Strange - I was already using -bool:

defaults read /Library/Preferences/ManagedInstalls InstallAppleSoftwareUpdates
1
defaults read /Library/Preferences/ManagedInstalls UnattendedAppleUpdates
1

**Comment by ofirgalcon** [comment]
Ah - I see what I did! My mistake - you were right. I had a script that was modifying these incorrectly.
