### ISSUE TITLE
Make divider width consistent between displayed items in MSC Updates tab in Dark Mode

### ISSUE THREAD

**Issue by homebysix** [munki/munki#922]
The horizontal dividers in Managed Software Center's "Updates" tab appear inconsistent in width, as seen below:

![Screen Shot 2019-03-15 at 11 39 14 AM](https://user-images.githubusercontent.com/7801391/54455081-2a8a3a80-4718-11e9-94bf-a325f87aac33.png)

I think it would look better to have all dividers be 1 pixel wide, and that's already how the "My Items" tab behaves:

![Screen Shot 2019-03-15 at 11 45 42 AM](https://user-images.githubusercontent.com/7801391/54455132-455caf00-4718-11e9-9b8a-0a0b2645201f.png)

This is a cosmetic issue only. Thanks for considering!

**Comment by gregneagle** [comment]
PR considered. Is this a cosmetic issue when not in Dark Mode? If not, that's a clue where to start looking in the mass of HTML and CSS...

**Comment by gregneagle** [comment]
(This will not be addressed before the 3.6 release in any case)

**Comment by homebysix** [comment]
You're right, the 2px dividers only exist in Dark Mode.

![msc_light_dark gif](https://user-images.githubusercontent.com/7801391/54456187-c9b03180-471a-11e9-8821-898333dbf72d.gif)

**Comment by gregneagle** [comment]
I have a fix for this on a non-public branch that will be merged after the 3.6 release.
You can try it yourself right now if you wish by commenting out line 80 of updates.css in the WebResources.

**Comment by gregneagle** [comment]
https://github.com/munki/munki/commit/ffb2dc92dc8fd65f84f6bd9c794a9c850b3f1bba is in the Munki3dev branch.
