### ISSUE TITLE
ShowRemovalDetail missing from "managedsoftwareupdate --show-config" output

### ISSUE THREAD

**Issue by tlcarpenter** [munki/munki#940]
Displaying the contents of /Library/Preferences/ManagedInstalls.plist with PlistBuddy
reveals that "ShowRemovalDetail = false" but "ShowRemovalDetail" is completely missing
from the output of "managedsoftwareupdate --show-config". This is true on two different
systems, one running munkitools 3.6.2.3777 the other 3.5.1.3622.

**Comment by gregneagle** [comment]
This is a preference that has no effect in recent versions of Munki. I can’t think of a good reason to display its value.

**Comment by gregneagle** [comment]
(And by recent versions of Munki I mean 2.0 and later)

**Comment by tlcarpenter** [comment]
Thanks.
