### ISSUE TITLE
MSCDockTilePlugIn not loading on macOS Catalina

### ISSUE THREAD

**Issue by guidedways** [munki/munki#947]
Just checked out the latest code. The DockTilePlugin fails to load with an error in Console.app:

Could not load Dock Extra class from the bundle ~/Library/Developer/Xcode/DerivedData/Build/Products/Debug/Managed Software Center.app//Contents/PlugIns/MSCDockTilePlugin.docktileplugin

**Comment by gregneagle** [comment]
Has Apple changed things so that docktileplugins must be signed or notarized?

**Comment by gregneagle** [comment]
I see the same behavior with this code/app: https://github.com/HelmutJ/CocoaSampleCode

So this appears to be a change in Catalina WRT NSDockTilePlugin.

**Comment by guidedways** [comment]
@gregneagle I've logged this as a 'bug' with Apple, would appreciate if you could do the same. Apple won't fix this if there isn't enough feedback received.

**Comment by gregneagle** [comment]
I don't believe we've characterized the bug yet. I just tested with a signed version of the MSC.app (and subcomponents) and the docktileplugin seems to load and work OK.

So I suspect Apple has simply changed the rules here and now the Dock will only load _signed_ .docktileplugins.

**Comment by guidedways** [comment]
The docktile now only seems to load and work if the parent app is also loaded in memory, which is what the error in the console is suggesting. It seems to fail to load if the parent app isn't running, in which case it may be that the process that spawns dock tiles does not trust our signed component (I've tested this with a signed docktileplugin).

Looks like a Catalina bug nonetheless. Due to process hardening and what not, it may be that it's mistakingly marking 3rd party docktile plugins as 'untrusted' even though we've code signed them.

**Comment by gregneagle** [comment]
???
The MSC docktileplugin _WORKS_ for me if it is signed.
It does not then require "the parent app is also loaded in memory"

**Comment by guidedways** [comment]
Weird - I'm unable to get even the most simplest of dock tiles to load outside of the main process. I'm doing nothing 'extra' to code-sign them though, I've got the "checkmark" against "Codesign" when bundling it inside of the plugins folder. How are you code signing the docktile any differently?

**Comment by gregneagle** [comment]
```codesign -s "<my developer id>" --options runtime "Managed Software Center.app/Contents/PlugIns/MSCDockTilePlugin.docktileplugin" "Managed Software Center.app/Contents/Resources/MunkiStatus.app" "Managed Software Center.app/Contents/Resources/munki-notifier.app" "Managed Software Center.app"```

**Comment by guidedways** [comment]
Right - so you've got this as an extra post build script? I can try doing that I guess. That would suggest the "Code sign on Copy" option in Xcode isn't doing what it should?

**Comment by gregneagle** [comment]
No idea. I don't use it when building the app for distribution via GitHub -- it's built unsigned. I don't have any real experience with building signed code with Xcode.

**Comment by gregneagle** [comment]
Filed feedback FB7222115

Basic Information
Please provide a descriptive title for your feedback:
Rules change for docktileplugins in Catalina?
Which area are you seeing an issue with?
Dock
What type of issue are you reporting?
Incorrect/Unexpected Behavior
Description
Please describe the issue and what steps we can take to reproduce it:
An unsigned app containing an unsigned docktileplugin correctly displays badges in the Dock even when the app itself is not running in Mojave and earlier.

The same app on Catalina 19A546d does not display Dock badges when the app is not running. It appears Dock is refusing to load the plugin.

If you sign the app and the docktileplugin, the Dock will load the docktileplugin and it functions as expected.

Is this an intended change?
If so, where is it documented?
Are there other similar/related changes of which we should be aware?

This issue can be reproduced with the simple app here:
https://github.com/HelmutJ/CocoaSampleCode/tree/master/DockTile

And also with the Managed Software Center app that is part of Munki: https://github.com/munki/munki/releases/download/v3.6.2/munkitools-3.6.2.3776.pkg — though that may be more difficult to get to the point where it has badges to display.

**Comment by gregneagle** [comment]
I need to modify my claim about it working.

If there is a badge displayed in the Dock and I quit the app with Command-Q the badge remains.
If I quit the app by clicking and holding on its Dock tile, and then choosing Quit from the popup menu, the badge is removed from the dock tile.

**Comment by gregneagle** [comment]
...and now I can't get the Dock badge to persist at all when the app is not running.

So confusing.

**Comment by guidedways** [comment]
Thanks for logging feedback with Apple! Yes, I can't get my dock tile to work properly either. I still haven't tried manually code signing it, but Xcode does this any way (even if we manually code-sign, at the time of producing an ad-hoc distribution, Xcode will re-sign everything again, so in theory everything is correctly signed by the time it reaches the end user). 

Also - apps now need to be notarized for Catalina. The fact that I'm distributing a notarized, codesigned app successfully and Catalina does not prompt the user any error of any sort, I'm assuming my app is indeed code signed by the time it's installed and this is just a Catalina quirk.

**Comment by gregneagle** [comment]
"apps now need to be notarized for Catalina" no they don't.

Managed Software Center is neither signed nor notarized and runs just fine on Catalina (minus the docktileplugin weirdness).

**Comment by guidedways** [comment]
The app will run just fine on your development machine, but try sending someone a .app (especially a .pkg) - Catalina will show numerous warnings to the user, almost making it difficult for them to run the installer / launch the app without having to go into System Preferences and overriding security. This was always the case, but they've made it even more difficult run any app that isn't notarized. 

At least we received 10 reports daily from our users until we started notarizing our deployment, after which the users reported back that they've been able to run the installer just fine.

**Comment by guidedways** [comment]
And I say this on behalf of two other mac apps that I know are distributed by 3rd parties outside of the App Store.

**Comment by guidedways** [comment]
And here we are: https://appleinsider.com/articles/19/06/03/apples-macos-catalina-is-first-to-require-app-notarization-by-default

**Comment by guidedways** [comment]
https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution

Important
Beginning in macOS 10.14.5, all new or updated kernel extensions and all software from developers new to distributing with Developer ID must be notarized in order to run. **Beginning in macOS 10.15, notarization is required by default for all software**.

**Comment by gregneagle** [comment]
I think you aren't a Munki user.

Munki can install unsigned apps and they do not trigger Gatekeeper checks and therefore signing and notarization and not needed.

I agree that if you PUBLICALLY distribute software, then signing and notarization are (virtually) required, since the act of downloading the software from a web server adds a com.apple.quarantine extended attribute that triggers Gatekeeper.

But if you have a tool to privately distribute software like  Munki or Jamf, those tools can install software without adding the com.apple.quarantine bit. Gatekeeper is not triggered; the app launches normally without any warnings or popups.

**Comment by guidedways** [comment]
That's correct, I'm not a Munki user. I was referring to the Catalina related problems in general terms and noticed Munki wasn't behaving properly on my machine either.

**Comment by gregneagle** [comment]
Yes: if you are a third party software developer making your software available on websites you'll need to sign and notarize your software or face unmanageable end-user support.

If you (like me) are an enterprise administrator, we have tools (like Munki) that allow us to install unsigned software.

This is why I say, contrary to Apple's claims, signing and notarization is NOT required in Catalina.

**Comment by gregneagle** [comment]
.docktileplugins appear to work as they did in Mojave and earlier in Catalina 19A573a.
