### ISSUE TITLE
app contains bundle version 3774 not 3776?

### ISSUE THREAD

**Issue by suschizu** [munki/munki#948]
hello!
I've noticed that the version number doesn't match with the download-version 
I'm not sure if this is intended: 
<img width="272" alt="Screenshot 2019-08-08 at 23 32 12" src="https://user-images.githubusercontent.com/16004333/62739713-d02aa700-ba35-11e9-9942-58abe5b564fe.png">

**Comment by gregneagle** [comment]
It is intended.

**Comment by gregneagle** [comment]
The final part of each component's version is related to the actual git changes/commits for that component. They will not always move in concert.

**Comment by core-code** [comment]
since the version numbers are seemingly 'intended' to be broken we cannot help anymore to keep 'Munki' up-to-date automatically over at Homebrew Cask. we would need a correlation between the version number of the app and the GitHub release versions. maybe others will take over maintenance of the Muni Cask.

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/munki.rb

**Comment by erikng** [comment]
I'm surprised people who use munki actually want munki in homebrew. The target audience (system administrators) of this tool fundamentally disagrees with how homebrew itself functions.

**Comment by gregneagle** [comment]
It’s not clear how the version numbers are “broken” or why Homebrew needs the last component of the version of the application to be anything in particular (Munki is not an application), or really what the actual issue is here. I checked out the linked Cask and nothing was clarified for me.

**Comment by core-code** [comment]
> It’s not clear how the version numbers are “broken

are you a Mac user? a Mac user expects, if he downloads version 3.6.2 of something, to see version 3.6.2 when he selects it the Finder via 'Get Info', 'Column View' or 'Quick Look'. 
however, as is now, the version number number of 'Managed Software Center' have no correlation with the download.

note, i am not affiliated with Homebrew Cask, and, as mentioned, other contributors may continue to keep that Cask up-to-date manually. what i've mentioned is a system that we (the company CoreCode) run each day to keep thousands of Casks up-to-date via dozens of checks. some of these checks require the version number of the app to match the version number of the download.  

> I'm surprised people who use munki actually want munki in homebrew. 

if you do not want to see 'Munki' distributed via Homebrew Cask, i can send a delete request on your behalf.

**Comment by erikng** [comment]
@core-code I know you aren't expected to know if he is a Mac user, but he is the inventor of this tool, which is used across the world by very large companies such as Facebook, Google, Uber, etc on literally hundreds of thousands of macs. He is acutely aware of the Apple user experience and how to deploy software. 

The tool has several components, one being the GUI. A bare install from homebrew will be borderline non-functional as it has no configuration applies to tell the tool where to receive its necessary manifests/catalogs. 

There are several other checks you could do, such as the package receipt of the package itself vs looking at the Info.plist of the application bundle. By default, that's exactly how munki itself understands if it needs to upgrade itself (if a newer package is available by its own catalogs).

**Comment by gregneagle** [comment]
" what i've mentioned is a system that we (the company CoreCode) run each day to keep thousands of Casks up-to-date via dozens of checks. some of these checks require the version number of the app to match the version number of the download."

Again, Munki is not an application.

Munki is a set of tools. _One_ of the tools is an application. That application has its own development cycle and velocity, as do many of the other tools.

**Comment by gregneagle** [comment]
I'd think if you were automating updating Cask definitions you'd be using the GitHub atom feed and comparing the version of the latest release against the version in the Cask.

**Comment by core-code** [comment]
thanks for your considerations and explanations. since the reported behaviour is considered 'intended' and the bug is closed i don't think further discussion is necessary or productive.

> I'd think if you were automating updating Cask definitions you'd be using the GitHub
> atom feed and comparing the version of the latest release against the version in the Cask.

you are correct that this makes sense, and of course we are doing this too, each day for around 1000 Casks. 'Munki' has been dropped from that our list now, but, as i've said above, i'm sure other community members will take over there.
