### ISSUE TITLE
makepkginfo --nopkg --uninstall_script unattended uninstall fails

### ISSUE THREAD

**Issue by simone-pignotti** [munki/munki#950]
Running `makepkginfo --nopkg --uninstall_script=uninstall.sh --unattended_uninstall ...` does not set `uninstallable` to true in the resulting pkginfo plist.
The result is that when the package is added to a manifest's `managed_uninstalls` section, uninstalling fails and `Library/Managed Installs/` shows:
```
**Checking for removals**
Running installcheck_script for [pkg]
WARNING: Could not find uninstall info for [pkg]
```
Manually setting the following property in the pkginfo results in a successful uninstall:
```
<key>uninstallable</key>
<true/>
```
This should probably be done automatically when the `--unattended_uninstall` option is used, or another option `--uninstallable` should be added.

**Comment by gregneagle** [comment]
Fixed here: https://github.com/munki/munki/commit/3b6aa2173da882d822ec5513db28305a3470d841
