### ISSUE TITLE
client intended to send too large body

### ISSUE THREAD

**Issue by hydroflash** [munki/munki#954]
I'm seeing a lot of this in my error logs for Nginx for my clients.  Running Munkireport 5.0.1 and Munkireport Client 5.0.1

I do have a lot of reporting options selected for my clients.  Do I need to select less?

2019/09/23 13:59:32 [error] 671#0: *13213 client intended to send too large body: 1916281 bytes, client: 10.4.0.55, server: munkireport.example.com, request: "POST /index.php?/report/check_in HTTP/1.1", host: "munkireport.example.com"

**Comment by bochoven** [comment]
Check 

upload_max_filesize
and
post_max_size

in your php configuration. You may want to increase the values

**Comment by bochoven** [comment]
Oh and you may want to open this issue on https://github.com/munkireport/munkireport-php as this is only for Munki issues

**Comment by hydroflash** [comment]
My apologies for posting in the wrong area.  I found that I needed to alter my nginx.conf and add the following to the http section: client_max_body_size 20M;

That stopped all the error messages I was receiving.

Thanks!
