### ISSUE TITLE
build_python_framework.sh showing error when Munki root directory contains blank spaces in between 

### ISSUE THREAD

**Issue by pranavshenoy** [munki/munki#956]
steps to reproduce 
1. create a directory with blank spaces in between (eg: /Users/munki software/munki)
2. clone the repository there
3. run bash /Users/pranav/munki software/munki/code/tools/build_python_framework.sh
4. outputs error "usage: dirname path"

Description: 
 This is because of MUNKIROOT=$(dirname $(dirname "${TOOLSDIR}")) . The output of the inner dirname will contain a space that should be enclosed in quotation for successful execution of outer dirname

**Comment by gregneagle** [comment]
Have I translated your description of the appropriate fix correctly?

```bash
CODEDIR=$(dirname "${TOOLSDIR}")
MUNKIROOT=$(dirname "${CODEDIR}")
```

**Comment by gregneagle** [comment]
(and in the meantime I hope you can work around the issue by removing the space in the "munki software" directory name...)

**Comment by pranavshenoy** [comment]
@gregneagle  the fix looks appropriate.. 
currently I have added the code as a workaround for my testing.
