### ISSUE TITLE
Additional modules in embedded python framework for middleware

### ISSUE THREAD

**Issue by AaronBurchfield** [munki/munki#961]
I'm updating [CloudFront Middleware](https://github.com/AaronBurchfield/CloudFront-Middleware) to support Munki's embedded python, which will require the rsa module to be installed.

I'd like to avoid shipping the rsa module in the middleware package or trying to install the module with a preinstall script.

Would it be acceptable to include the rsa module in Munki's default requirements.txt, or is there an option I'm not considering to install additional modules as needed?

Thanks!

**Comment by gregneagle** [comment]
I want to be slow, cautious, and conservative about what Python modules I include, as it puts _me_ on the hook to keep them updated and I'll get support questions for modules I may not even use.

You can build a package yourself containing any modules you want.

You can edit the py3_requirements.txt in code/tools and add your additional modules, then run code/tools/build_python_framework.sh to build that customized framework.

Or you can use https://github.com/gregneagle/relocatable-python directly to build a Python framework containing whatever modules you'd like, and save/copy that module to the root of your Munki code repo.

Once you have your custom Python framework in place, you can run code/tools/make_munki_mpkg.sh to build a munkitools distribution pkg containing your customized Python.

**Comment by erikng** [comment]
I almost wonder if there is a way to add support for a path within the Munki Python framework to import them.

What if there was a path in /usr/local/munki/python/custom that had a generic shim (coming from munkitools) that was always imported and then that shim looped through the folder for modules that were installed.

The onus would still be on the admin customizing, but it would essentially make munki's python fully extensible without any further work or changes to the requirements file.

Thanks,
Erik Gomez
________________________________

**Comment by gregneagle** [comment]
That path exists now:

/usr/local/munki/Python.framework/Versions/3.7/lib/python3.7/site-packages

You can install your extra modules there. You don't need to build the framework with all your needed modules there up-front, I only offer that as one option.

**Comment by AaronBurchfield** [comment]
Thanks @gregneagle, specifying the extra modules and building Munki seems like a reasonable solution to me and I understand the desire to keep responsibilities where they belong.

@erikng, I had a similar idea, even hacked it together to test, and for _most people_ I still think managing the extra python modules in Munki's embedded requirements.txt is going to be the better option.

Building Munki with a customized python framework as suggested is very straight forward and is what I will recommend.

**Comment by gregneagle** [comment]
Some of the ideas captured here for posterity: https://github.com/munki/munki/wiki/Customizing-Python-for-Munki-4

**Comment by gregneagle** [comment]
See also https://github.com/munki/munki/issues/958

**Comment by erikng** [comment]
Wouldn't the site packages method be overridden every new version of Munki though?

My idea was similar to the preflight/postflight methodology.

Thanks,
Erik Gomez
________________________________

**Comment by erikng** [comment]
After reading your new documentation I think I have a better idea as to what you are after. The python you include is it's own standalone package, so you wouldn't deploy that but instead your own package.

It would be on the admin to maintain and ensure it doesn't break Munki when upgrading, but that seems like a very reasonable requirement.

As always, thanks for painstakingly thinking about this and creating something modular enough for the community.

Thanks,
Erik Gomez
________________________________
