### ISSUE TITLE
Uninstall of running application

### ISSUE THREAD

**Issue by dannykorpan** [munki/munki#962]
Hi,

is it possible to force closing a running application upon an available software update instead of showing a dialog that ask me to close the application manually?

Also is it possible to force an uninstallation of a running application?

I've already tried it with an pre-uninstall script, but it would not be executed until the affected application is beeing closed.

Kind Regards

**Comment by vmiller** [comment]
For general discussion and support of Munki, you will get more eyes on your problem by posting to http://groups.google.com/group/munki-discuss

Github issues are more for bugs/issues with the munki code.

**Comment by gregneagle** [comment]
When creating this issue you had to delete text suggesting how to better handle this issue.
