### ISSUE TITLE
Progress spinner in MSC does not match native macOS progress spinner

### ISSUE THREAD

**Issue by homebysix** [munki/munki#964]
The progress spinner animation in Managed Software Center is subtly different from the native macOS spinner. Although both go in the same direction, the shading of the "spokes" is reversed in MSC.

Here's the MSC spinner:
![munki_spinner mov](https://user-images.githubusercontent.com/7801391/70571018-da7ac000-1b51-11ea-9b0e-fd2611de4e47.gif)

And here's a native macOS spinner:
![macos_spinner mov](https://user-images.githubusercontent.com/7801391/70571037-e23a6480-1b51-11ea-8a60-1cd8d28fc605.gif)

This is obviously a very minor cosmetic issue, but I wanted to make a note of it anyway.

**Comment by gregneagle** [comment]
It's not a native spinner, it's an animated gif. It's likely Apple continues to change the look of the progress spinner with releases of macOS, and that MSC's more closely matched Apple's at one point.

This is not an issue I plan to do anything about (I think MSC's progress spinner looks fine, and I don't want to worry about matching the "native" look on each and every macOS release), so I'm going to close this. If you'd like to dig in and create a replacement, you can open a Pull Request that I would consider.

**Comment by gregneagle** [comment]
(It might not even be an animated gif -- it might be a static image that is animated via CSS, in which case exactly matching Apple's native spinner will be even harder.)

**Comment by homebysix** [comment]
One more observation in case somebody later wants to tackle this issue: the non-standard shading of the spokes is only noticeable in Dark Mode, which probably means different assets for light/dark modes would be required. That complicates the fix somewhat.
