### ISSUE TITLE
Problem with Illustrator CC 2018

### ISSUE THREAD

**Issue by tm-dd** [munki/munki#974]
I get the following errors with Munki 4.0.0 and 4.0.1, only with older packages of Illustrator:

	+ /usr/local/munki/munkiimport --name=commercial_illustrator_illustrator-cc-mac-de-2017-11-13-mpg_Install --subdirectory=multimedia '--description=Adobe Illustrator (german version).<br><b>This is a commercial software only for Macs.</b>' --catalog=commercial_illustrator --category=multimedia --minimum_os_vers=10.10 --maximum_os_vers=10.14.99 '--displayname=Adobe Illustrator 2018 CC (DE)' --developer=http://www.adobe.com/products/illustrator.html --nointeractive ../illustrator-cc-mac-de-2017-11-13-mpg_Install.dmg --uninstallpkg ../illustrator-cc-mac-de-2017-11-13-mpg_Uninstall.dmg
	ERROR: hdiutil error nx_kernel_mount:1359: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1359: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1359: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1359: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1359: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1359: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1359: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1359: : checkpoint search: largest xid 8, best xid 8 @ 15
	 with image ../illustrator-cc-mac-de-2017-11-13-mpg_Install.dmg.
	ERROR: hdiutil error nx_kernel_mount:1359: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1359: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1359: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1359: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1359: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1359: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1359: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1359: : checkpoint search: largest xid 8, best xid 8 @ 15
	 with image ../illustrator-cc-mac-de-2017-11-13-mpg_Install.dmg.
	Traceback (most recent call last):
	  File "/usr/local/munki/munkiimport", line 607, in <module>
		main()
	  File "/usr/local/munki/munkiimport", line 378, in main
		pkginfo = pkginfolib.makepkginfo(installer_item, options)
	  File "/usr/local/munki/munkilib/admin/pkginfolib.py", line 425, in makepkginfo
		pkginfo = get_catalog_info_from_dmg(installeritem, options)
	  File "/usr/local/munki/munkilib/admin/pkginfolib.py", line 183, in get_catalog_info_from_dmg
		cataloginfo = get_catalog_info_from_path(itempath, options)
	  File "/usr/local/munki/munkilib/admin/pkginfolib.py", line 116, in get_catalog_info_from_path
		cataloginfo = adobeinfo.getAdobeCatalogInfo(pkgpath)
	  File "/usr/local/munki/munkilib/adobeutils/adobeinfo.py", line 497, in getAdobeCatalogInfo
		cataloginfo = get_adobe_package_info(dirpath)
	  File "/usr/local/munki/munkilib/adobeutils/adobeinfo.py", line 245, in get_adobe_package_info
		info = get_adobe_setup_info(installroot)
	  File "/usr/local/munki/munkilib/adobeutils/adobeinfo.py", line 198, in get_adobe_setup_info
		payloadinfo = get_payload_info(payloadpath)
	  File "/usr/local/munki/munkilib/adobeutils/adobeinfo.py", line 159, in get_payload_info
		payloadinfo['installed_size'] = int(installsize/1024)
	TypeError: unsupported operand type(s) for /: 'str' and 'int'

After downgrading to munkitools-3.6.4.3786.pkg, this package can be imported to the munki repository:

	+ /usr/local/munki/munkiimport --name=commercial_illustrator_2018_illustrator-cc-mac-de-2017-11-13-mpg_Install --subdirectory=multimedia '--description=Adobe Illustrator (german version).<br><b>This is a commercial software only for Macs.</b>' --catalog=commercial_illustrator_2018 --category=multimedia --minimum_os_vers=10.10 --maximum_os_vers=10.14.99 '--displayname=Adobe Illustrator 2018 CC (DE)' --developer=http://www.adobe.com/products/illustrator.html --nointeractive ../illustrator-cc-mac-de-2017-11-13-mpg_Install.dmg --uninstallpkg ../illustrator-cc-mac-de-2017-11-13-mpg_Uninstall.dmg
	ERROR: hdiutil error nx_kernel_mount:1473: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1473: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1473: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1473: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1473: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1473: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1473: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1473: : checkpoint search: largest xid 8, best xid 8 @ 15
	 with image ../illustrator-cc-mac-de-2017-11-13-mpg_Install.dmg.
	ERROR: hdiutil error nx_kernel_mount:1473: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1473: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1473: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1473: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1473: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1473: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1473: : checkpoint search: largest xid 8, best xid 8 @ 15
	nx_kernel_mount:1473: : checkpoint search: largest xid 8, best xid 8 @ 15
	 with image ../illustrator-cc-mac-de-2017-11-13-mpg_Install.dmg.
	Copying illustrator-cc-mac-de-2017-11-13-mpg_Install.dmg to repo...
	Copied illustrator-cc-mac-de-2017-11-13-mpg_Install.dmg to pkgs/multimedia/illustrator-cc-mac-de-2017-11-13-mpg_Install-7.0.dmg.
	Copying illustrator-cc-mac-de-2017-11-13-mpg_Uninstall.dmg to repo...
	Copied illustrator-cc-mac-de-2017-11-13-mpg_Uninstall.dmg to pkgs/multimedia/illustrator-cc-mac-de-2017-11-13-mpg_Uninstall-7.0.dmg.
	Saved pkginfo to pkgsinfo/multimedia/commercial_illustrator_2018_illustrator-cc-mac-de-2017-11-13-mpg_Install-7.0.plist.

Sure, the package still have some import error messages, but it works.

I tested Munki on macOS 10.13.6 and 10.14.6 with the same error.

My NEWER Packages of Illustrator (CC 2020) works fine, with Munki 4.0.0.

The problem is not urgent for me, but maybe you can tell me the reason or can fix it.

**Comment by gregneagle** [comment]
Thanks for the bug report: should be fixed in the Munki4dev branch, and that same fix will be in the next release.
