### ISSUE TITLE
Can't build Munki with Catalina & xCode 11.3

### ISSUE THREAD

**Issue by boy412** [munki/munki#978]
I'm trying to build Munki from source and the instant I run `./code/tools/make_munki_mpkg.sh` I get an error during the version check step:

```
eric@Euclid munki % code/tools/make_munki_mpkg.sh
2020-02-03 18:42:29.556 defaults[7192:480892] 
The domain/default pair of (/Users/eric/Desktop/munki/code/client/munkilib/version, CFBundleShortVersionString) does not exist
/Users/eric/Desktop/munki/code/client/munkilib/version is missing!
Perhaps /Users/eric/Desktop/munki does not contain the munki source?
```

The same code compiles fine on my Mojave system running xCode 11.2.

` ¯\_(ツ)_/¯`

**Comment by gregneagle** [comment]
You are probably running into one of the new privacy protections in Catalina. Either give “defaults” permission to access your Desktop (no idea how to do that) or move the source to /Users/Shared.

**Comment by boy412** [comment]
Moving the source to /Users/Shared seems to have done the trick. Thanks Greg!
