### ISSUE TITLE
Building v4.1.0 - version is detected as v4.0.1

### ISSUE THREAD

**Issue by carlashley** [munki/munki#980]
Have run the `make_munki_mpkg.sh` on my existing repo, and a fresh repo, but each time the version detected is `metapackage version: 4.0.1.3900`.

Seems that https://github.com/munki/munki/blob/master/code/client/munkilib/version.plist is still currently v4.0.1.

**Comment by gregneagle** [comment]
Try it now. Missed a git push.

(`make_munki_mpkg_from_git.sh -b v4.1.0` would have gotten the desired result; the code was in the repo, just not in master)

**Comment by carlashley** [comment]
Confirming resolved.
