### ISSUE TITLE
munkiimport with s3Repo Plugin

### ISSUE THREAD

**Issue by trekkim** [munki/munki#982]
Hi I have issue  with munkiimport. Munki installed latest 4.1

#munkiimport /tmp/KY-PrinterDrivers.pkg 
s3Repo Plugin platform is 'macos'

Traceback (most recent call last):
  File "/usr/local/munki/munkiimport", line 607, in <module>
    main()
  File "/usr/local/munki/munkiimport", line 387, in main
    matchingpkginfo = munkiimportlib.find_matching_pkginfo(repo, pkginfo)
  File "/usr/local/munki/munkilib/admin/munkiimportlib.py", line 234, in find_matching_pkginfo
    catdb = make_catalog_db(repo)
  File "/usr/local/munki/munkilib/admin/munkiimportlib.py", line 142, in make_catalog_db
    catalogitems = FoundationPlist.readPlistFromString(plist)
  File "/usr/local/munki/munkilib/FoundationPlist.py", line 92, in readPlistFromString
    plistData = NSData.dataWithBytes_length_(data, len(data))
TypeError: Expecting byte-buffer, got str

can someone help thx

**Comment by gregneagle** [comment]
I can't provide any support/help for the s3Repo plugin as I did not write it nor do I use it. Perhaps open an issue on the GitHub site for that plugin?

**Comment by trekkim** [comment]
will do , i thought maybe you will know what does it mean in TrackBack , maybe i need just edit some part to sorted

**Comment by gregneagle** [comment]
The "meaning" is that it's expecting a bytestring and instead got a Unicode string.

This _might_ be a bug in Munki, but since it doesn't occur with the (default) FileRepo, it's hard to say. The best place to start is with the s3Repo code.

**Comment by trekkim** [comment]
thx, will try use s3 mounted directly into system  with FileREPO plugin: file:///

**Comment by trekkim** [comment]
sorted over FileRepo thx
