### ISSUE TITLE
munki root’ returned -60005 (Error = -60005)

### ISSUE THREAD

**Issue by trekkim** [munki/munki#993]
Hi,
I need help or advise with my issue.

I have issue with installation of profiles in munki on some clients, cannot find any info about that error.

Profile XX.mobileconfig installation failed: profiles install for file:‘/Library/Managed Installs/Cache/XX.mobileconfig’ and user:‘root’ returned -60005 (Error = -60005)”

Thx for any suggestions

**Comment by gregneagle** [comment]
Install them manually how Munki would -- as root, using the `profiles -IF` command. If that fails as well, Munki has nothing to do with the problem. I'm guessing you'll get the exact same error.

As for getting more info on error codes/error messages coming from the `profiles` command, you'd need to ask Apple about that.

**Comment by trekkim** [comment]
No issue after sudo /usr/bin/profile -I -F /myprofile.mobileconfig , installation success

**Comment by trekkim** [comment]
can be this cause apple security update  2020-003 in same time require installation over MSC?

**Comment by gregneagle** [comment]
`sudo` might not result in the same behavior as installing as `root`.

In any case, I have no more suggestions for you, since I know nothing about your problematic profiles.

**Comment by gregneagle** [comment]
(I really do not think this is a Munki issue. I think this is a `profiles` issue.)

**Comment by trekkim** [comment]
ahh ok will try on other machine as root directly in terminal, sorry my fault

**Comment by trekkim** [comment]
<img width="727" alt="Screenshot 2020-05-27 at 19 37 33" src="https://user-images.githubusercontent.com/6920257/83053793-9329b280-a051-11ea-87ba-9d18ba556a7e.png">

**Comment by trekkim** [comment]
<img width="963" alt="Screenshot 2020-05-27 at 19 38 37" src="https://user-images.githubusercontent.com/6920257/83053831-ab99cd00-a051-11ea-9a26-a66f169a7929.png">

**Comment by trekkim** [comment]
we can close that find problem : looks like user has Parental mode active
