### ISSUE TITLE
Error executing script postinstall_script

### ISSUE THREAD

**Issue by SegFault42** [munki/munki#995]
Hi there !

I have an error with my post install script.

that's my script 

```
#!/bin/bash
/bin/mv /usr/local/baobab-pollen/ressources/baobab.pollen.plist /Library/LauchDaemons

launchctl load /Library/LaunchDaemons/baobab.pollen.plist
```

My pre install work. But my post install give me this error

```
Running postinstall_script for baobab-pollen_latest...
ERROR: Error executing script postinstall_script: [Errno 2] No such file or directory: '/tmp/munki-0_2xz1kq/postinstall_script': '/tmp/munki-0_2xz1kq/postinstall_script'
WARNING: Postinstall script for baobab-pollen_latest returned -1```

Someone can help ? 
Thx

**Comment by erikng** [comment]
This github is for the development of Munki, not for issues with packages being deployed by Munki. 

I would suggest asking on the "Munki-discuss" google group. 

Having said that, moving your files as a post install is not a recommended approach. Your package should install that file to the necessary location.

**Comment by SegFault42** [comment]
Ok thx i will ask on the google group.
